### ISSUE TITLE
Synonyms in Dispatch

### ISSUE THREAD

**Issue by hansmbakker** [Microsoft/botbuilder-tools#1000]
## Tool
Name: Dispatch

## Describe the problem
I'm using word alterations in QnA Maker. To keep the QnA KBs clean I type questions only containing one of these synonyms. I want Dispatch to refer to the correct QnA KB even when the user enters a synonym of the word that is used as direct question in QnA Maker

## Describe the solution you'd like
Have the QnA Maker word alterations as phrase lists in Dispatch

## Describe alternatives you've considered
Putting more different questions in QnA maker (but this defeats the purpose of uploading synonyms / word alterations

[enhancement]

**Comment by tsuwandy** [comment]
Dispatch will be pulling synonyms from QnA maker.  Thanks for reporting this issue, Hans!

**Comment by tsuwandy** [comment]
Merged with master, will be in npm end of April.  Thanks!
