### ISSUE TITLE
Dispatch CLI cannot generate dispatch app when it is based only on pattern-only app

### ISSUE THREAD

**Issue by hansmbakker** [Microsoft/botbuilder-tools#1003]
## Tool
Name: Dispatch
Version: 1.3.0
OS: Windows 10 17763

## Describe the bug
When creating a dispatch app that bases only on a LUIS app that contains only patterns, Dispatch CLI returns:
```
Value cannot be null.
Parameter name: path1
```

## To Reproduce
1. Extract [bugrepro.zip](https://github.com/Microsoft/botbuilder-tools/files/2926974/bugrepro.zip). It contains the required luis apps and `bugrepro.ps1`
2. Run `bugrepro.ps1` with the authoringKey for west-europe

## Expected behavior
Dispatch cli creates dispatch app as usual

## Screenshots
![image](https://user-images.githubusercontent.com/3463496/53743033-3f560b00-3e9a-11e9-9897-c520f72c2df5.png)

## Additional context

[bug]

**Comment by tsuwandy** [comment]
Issue understood from Dispatch CLI side.  Targeting end of March.

**Comment by tsuwandy** [comment]
Fixed and will be deployed along with other botbuilder-tools by //build.
