### ISSUE TITLE
luisgen generates incorrect class when the geographyV2 pre-built entity is used

### ISSUE THREAD

**Issue by darrenj** [microsoft/botbuilder-tools#1008]
## Tool
Name: luisgen
Version: 2.0.2.0
OS: Windows 10

## Describe the bug

When running luisgen against a LUIS file which users the geographyV2 pre-built entity

```
"prebuiltEntities": [
    {
      "name": "geographyV2",
      "roles": []
    }
  ],

```
It generates a C# file that has this entry for the entity

```
            public string[] geography;
```

However at runtime if I say "book a restaurant in london at 4pm" the geography element is always NULL despite being present in the JSON response.

Debugged further and turns out luisgen should be generating a property called `geographyV2_City`

## To Reproduce
1. Create a LUIS model that uses geographyv2 pre-built entity
2. Deploy LUIS model
3. Create luisgen class
4. Attempt to deserialize JSON response and see geography is not set.

## Expected behavior
- The generated class should work with a LUIS response that returns geographyV2intent information.
- Should also check the new person pre-built entity works too

## Additional context

[bug]

**Comment by huislaw** [comment]
Need this in my project. Any estimated date to add geographyv2 in?
Thanks.

**Comment by xieofxie** [comment]
Will the [Subtypes](https://docs.microsoft.com/en-us/azure/cognitive-services/LUIS/luis-reference-prebuilt-geographyv2) be preserved in version 3?

**Comment by cleemullins** [comment]
@chrimc62 Another LuisGen one for you.
