### ISSUE TITLE
[Ludown, Spec] Support for composite entities in LU files and ludown tool.

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#1009]
## Tool
Name: Ludown

## Describe the problem
LU files and LUDown tool do not support LUIS composite entities

## Describe the solution you'd like
Support for composite entities in LU and LUDown

### Definition of composite entity
```markdown
$<entityName> : [child entity 1, child entity 2, …]
```

### Validation rules (matches LUIS UX)
- Child entities for composites must have valid type definition. If no type definition is found an error will be spit out by the LUDown parser and parse fails.
- Child entities cannot be pattern.any or other composite entities
- Utterance labels cannot have nested composite entities

### Example usage: 
```markdown
> [Supported today] Define a list entity ‘device’ with two normalized values and list of synonyms.
$device : thermostat=
    - Thermostat
    - Heater
    - AC
    - Air conditioner

$device : refrigerator=
    - Fridge
    - Cooler

> [Supported today] Define a simple entity for a custom device type.
$customDevice : simple

> [Supported today] Add pre-built temperature entity
$PREBUILT : temperature

> [--NEW--] Define a composite entity ‘deviceTemperature’ that has device (list entity), customDevice (simple entity), temperature (pre-built entity) as children
$deviceTemperature: [device, customDevice, temperature]

# setThermostat
> This utterance labels ‘thermostat to 72’ as composite entity deviceTemperature
    - Please set {deviceTemperature = thermostat to 72}
> This is an example utterance that labels ‘owen’ as customDevice (simple entity) and wraps ‘owen to 72’ with the ‘deviceTemperature’ composite entity
    - Set {deviceTemperature = {customDevice = owen} to 72}
```

[enhancement]

**Comment by darrenj** [comment]
Perfect timing :-) I just ran into this issue with a LUIS model that we have which uses composite entities.

**Comment by johnataylor** [comment]
I think this should really be a high priority item. Most non-trivial LUIS models are going to make use of Composite Entities, in core bot we used Composites to alias Lists. They can be used in a similar manner for builtins. LUIS can be a very effective tool when you make use of Lists and builtins.

**Comment by omarsourour** [comment]
@vishwacsena 
I recommend we follow the same markdown listing pattern we have for list entities for composite entities as well. Even more, with the advent of roles, composite entities can also have roles assigned to it.

There is benefit in taxonomizing our explicit entity definition. For example:
```markdown
$entityName:List
    - Children
        - Child1
        - Child2
    - Roles
        - Role1
        - Role2
```

**Comment by vishwacsena** [comment]
@omarsourour - IMHO, this would bloat up authoring when adding roles to non-list entities as well as possibly bloats up how you specify composites. I'd recommend that start with the current proposal and expand it to include your suggestion in a future update should there be strong feedback on the current notation causing confusion/ degraded readability

**Comment by cahann** [comment]
> @omarsourour - IMHO, this would bloat up authoring when adding roles to non-list entities as well as possibly bloats up how you specify composites. I'd recommend that start with the current proposal and expand it to include your suggestion in a future update should there be strong feedback on the current notation causing confusion/ degraded readability

Don't you think that if this is the path we will pursue anyway then it might be better to do those suggestions in the first version?Or do you want to avoid breaking changes?

**Comment by vishwacsena** [comment]
@cahann - To be clear, the suggestion if taken as is would introduce a breaking change to how list entities are defined today. We can do this for composites but that wold cause inconsistencies across entity definitions in .lu file format. If we have strong feedback on the need to break down lists, composites and roles into markdown sub-lists that we should take that as an additive and separate work item. 

That said, I'm pushing back on doing that additive change now since to my point in my previous response would bloat up how lists, composites and roles are defined. So let's start with the short hand succinct notation as designed in the spec above. Does that help clarify?
