### ISSUE TITLE
LU File Should Support Prebuilt Domain

### ISSUE THREAD

**Issue by daden-ms** [Microsoft/botbuilder-tools#1010]
## Tool
Name: Ludown

## Describe the problem
We want to use LU file format in our project but just found it doesn't have syntax to support prebuilt-domain

## Describe the solution you'd like
In .LU file,  use "##[PREBUILT] Communication.Dial"
so it maps to the following in the LUIS model file in JSON format:

{
      "name": "Communication.Dial",
      "inherits": {
        "domain_name": "Communication",
        "model_name": "Dial"
      }
}

## Describe alternatives you've considered
NA
## Additional context
NA

[enhancement]

**Comment by tsuwandy** [comment]
@vishwacsena, @sgellock who should take a look at this one?  Thank you!

**Comment by cahann** [comment]
Composite entities and prebuilt domains are two features that need to be support in LUDown @omarsourour will pick this work after BUILD.

**Comment by sgellock** [comment]
@vishwacsena has a spec, if you haven't sync'ed on this, please connect with him

**Comment by omarsourour** [comment]
Sounds good! I will reach out to @vishwacsena to discuss the spec. There are some subtleties like making sure a conventions is followed, how prebuilt domain entities will be supported, ensuring prebuilt domain entities and prebuilt entities are not confused, etc.

**Comment by vishwacsena** [comment]
Support for prebuilt domains is tracked via #606. Closing this in favor of that older issue tracking this.
