### ISSUE TITLE
MSBot Azure services deployed in default region rather then specified location

### ISSUE THREAD

**Issue by toddwhitehead** [Microsoft/botbuilder-tools#1013]
## Tool
Name: Msbot
Version: 4.3.4
OS: Windows 10

## Describe the bug
Some of the services are deployed into a default region rather than the location specified in the --location parameter even though they are available in that region.

## To Reproduce
1. Deploy bot to Australia eg --australiaeast
2. Some resources are deployed to australiaeast but other eg search and appinsights are deployed to souteast asia

## Expected behavior
All resources should be deployed into the region specified in the --location parameter if the service is available there

## Additional context
it looks like the utils.ts class has out of date both in terms of region service availability and service to region mapping for example

export const regionToSearchRegionMap: { [region: string]: string } = {
    australiaeast: RegionCodes.SOUTHEASTASIA,
    australiacentral: RegionCodes.SOUTHEASTASIA,
    australiacentral2: RegionCodes.SOUTHEASTASIA,
    australiasoutheast: RegionCodes.SOUTHEASTASIA,

[bug]

**Comment by munozemilio** [comment]
Hi @stevengum , PR submitted by @toddwhitehead is a partial solution to this issue.
There are some changes needed on _**az bot create**_ to fix this issue. Otherwise this error is thrown in msbot: ERROR: az bot create: 'Australia East' is not a valid value for '--insights-location'. See 'az bot create --help'.

Can you please take a look?

**Comment by sgellock** [comment]
Since we are deprecating msbot as a provisioning and deployment option, replaced with ARM template support, I'm going to resolve this issue as "won't fix"
