### ISSUE TITLE
az bot create fails when existing storage account provided

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#1015]
## Tool
Name: az bot cli
Version: azure-cli 2.0.60, botservice 0.1.8
OS: Windows

## Describe the bug
When running az bot create command with `--storage` parameter, I get this error:
```
local variable 'site_name' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 328, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 386, in _run_jobs_serially
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 379, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 356, in _run_job
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\commands\__init__.py", line 171, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-core\azure\cli\core\__init__.py", line 452, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-botservice\azure\cli\command_modules\botservice\custom.py", line 132, in create
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-moqk8ce9\azure-cli-botservice\azure\cli\command_modules\botservice\bot_template_deployer.py", line 153, in create_app
UnboundLocalError: local variable 'site_name' referenced before assignment
```

Original command:
```
az bot create --kind webapp --name *** --resource-group *** --storage ***
```
[bug]

**Comment by yochay** [comment]
We are planning on moving all-in to ARM, as as we already know, some parts, like LUIS need special care for data (also QnA), which means using scripts. Therefore I would suggest the following:


- use  az bot create to generate AppID and Password
- use ARM template for everything (including resource group, storage, web app plan, web app , etc...) 

@stevengum @scheyal

**Comment by lauren-mills** [comment]
Since az bot creates the bot, app plan, web app, appinsights, and storage by default (and I can't provide my own) I'm using it for those services and using ARM for everything else. 

The only downside with this approach for the moment is that I don't get any response with the ids for the services created by az bot beyond the bot itself, so I can't reliably do things like using the same app plan for the qna web app, or wire up qna to the same appinsights instance.

**Comment by lauren-mills** [comment]
az bot attempts to name all the services the same name as the bot, in which case its easy to just hook up the qna app to the app plan and app insights. But if there happens to already be services of the same name in the group, az bot generated unique names and doesn't send them back in the output.

**Comment by yochay** [comment]
You should be able to use  _az bot create --kind registration_ to create just the AppID and Password and everything else with the ARM template.

**Comment by stevengum** [comment]
@lauren-mills @yochay, I spoke with @scheyal today to fill him in on my WIP.

1. `az ad app create` - This creates an AppId and Password (of the user's choosing, provided it meets criteria)
2. `az group deployment` - ARM deployment, contains BotServices schema with user decided type (e.g. webapp, registration/bot)

I have the completed the two of them **separately** and have rough instructions as well. I haven't put the two together in _one_ set of instructions, but was able to use the AppId/Password in `az bot create`

Inline is the ARM template I used to create a registration bot:

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "appId": {
            "type": "string"
        },
        "sku": {
            "defaultValue": "F0",
            "type": "string"
        },
        "botId": {
            "type": "string"
        },
        "botKind": {
            "defaultValue": "bot",
            "type": "string"
        }
    },
    "variables": {},
    "resources": [
        {
            "apiVersion": "2017-12-01",
            "type": "Microsoft.BotService/botServices",
            "name": "[parameters('botId')]",
            "location": "global",
            "kind": "[parameters('botKind')]",
            "sku": {
                "name": "[parameters('sku')]"
            },
            "properties": {
                "name": "[parameters('botId')]",
                "displayName": "[parameters('botId')]",
                "endpoint": null,
                "msaAppId": "[parameters('appId')]",
                "developerAppInsightsApplicationId": null,
                "developerAppInsightKey": null,
                "publishingCredentials": null,
                "storageResourceId": null
            }
        }
    ]
}
```

**Comment by lauren-mills** [comment]
Meaning the user needs to provide their own password to the az ad app create command, right?

**Comment by stevengum** [comment]
That's correct, I believe the password requirements are:
 - 16 characters or more
 - 1 Uppercase Char
 - 1 Lowercase Char
 - 1 Special Char

**Comment by stevengum** [comment]
@swagatmishra2007, the template I provided above worked last week, but now I get this error message:
```bash
Deployment failed. Correlation ID: de0c1ae7-2bbc-45c0-93e9-08b79f9e608c. {
  "error": {
    "code": "InvalidBotData",
    "message": "Version: Bot Version has an invalid value. "
  }
}
```

Any ideas?

**Comment by gabog** [comment]
@stevengum checked and this is resolved
