### ISSUE TITLE
az cli bot creates v3 by default (should be v4)

### ISSUE THREAD

**Issue by scheyal** [Microsoft/botbuilder-tools#1016]
## Tool
AZ CLI BOT CREATE

## Describe the bug
The default bot created using az cli bot create is v3 and should be latest v4, aligned with ABS.

## To Reproduce
az bot create --verbose --output json  -g EyalTmpRG --name EyalTmpBot --description "A cli bot" --display-name "EyalTmpBot Display Name" -k webapp

## Additional context
Snippet

az bot create --verbose --output json  -g EyalTmpRG --name EyalTmpBot --description "A cli bot" --display-name "EyalTmpBot Display Name" -k webapp
….
To publish your local changes to Azure, use the following command from your code directory:
….--proj-file-path 'EyalTmpBot.csproj'
{
…
  "type": "abs"
}

[BF]C:\workspace\botroot\TempPlay\EyalTmpBot-src>dir /b
.deployment
.gitignore
App_Start
build.cmd
Controllers
default.htm
deploy.cmd
Dialogs
Global.asax
Global.asax.cs
Microsoft.Bot.Sample.SimpleEchoBot.csproj
Microsoft.Bot.Sample.SimpleEchoBot.sln
packages.config
PostDeployScripts
Properties
publish.cmd
readme.md
Web.config
Web.Debug.config
Web.Release.config

[bug]

**Comment by stevengum** [comment]
Fixed via commit [stevengum/azure-cli#f9469d8287d8c4e32c11c7e8cbe9b4a5d0831b4e](https://github.com/stevengum/azure-cli/commit/f9469d8287d8c4e32c11c7e8cbe9b4a5d0831b4e)
