### ISSUE TITLE
MSBot clone created .bot file in wrong directory

### ISSUE THREAD

**Issue by tiagodenoronha** [Microsoft/botbuilder-tools#1017]
## Tool
Name: [Msbot]
Version: 4.3.4
OS: Windows 10

## Describe the bug
While trying to clone the Enterprise Bot Template, the bot file is created on wrong directory. If the deployment scripts are in C:\Users\myuser\EnterpriseTemplate\EnterpriseTemplate, the bot file gets created in C:\Users\myuser.

## To Reproduce
1. Navigate to DeploymentScripts folder in Enterprise Bot Template
2. Run msbot clone services on that folder
3. Locate .bot file

## Expected behavior
Bot file should be created in the same directory as the .csproj.

[bug]

**Comment by sgellock** [comment]
we are moving away from using .bot files for configuration data.  instead we will be advocating configuration data be stored in appsettings.json or .env files
