### ISSUE TITLE
Dispatch CLI: the "-h" option is not showing in "usage" for every Dispatch command

### ISSUE THREAD

**Issue by hcyang** [Microsoft/botbuilder-tools#102]
## Information:
* Tools Libraries: 
* Libraries' Versions: 
* OS: 

## Commands Example:

```bash

```

## Reproduction Steps:
1.
2.
3.

**Comment by tsuwandy** [comment]
not needed since -h is used to display usage, we don't need to show it again in usage text once user used the option -h.
