### ISSUE TITLE
az bot update --set not updating properties

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#1027]
## Tool
Name: az cli
Version: 2.0.60
OS: Windows

## Describe the bug
Running `az bot update --set properties.description="<value>" ` does not update the value in the output or the Azure portal.

## To Reproduce
1. Run `az bot update --set properties.description="<value>" `
2. Verify that the output json description is unchanged

[bug]

**Comment by swagatmishra2007** [comment]
Any updates ?

**Comment by stevengum** [comment]
Not yet, we're planning on fixing this for //Build.

**Comment by gabog** [comment]
This is tentativelly fixed and we are testing it today.

**Comment by stevengum** [comment]
Closing as bugbash was successful and the PR with the fix has been approved.

https://github.com/Azure/azure-cli/pull/9152
