### ISSUE TITLE
"msbot update generic" adding raw CLI commands to Structure

### ISSUE THREAD

**Issue by adamlash** [Microsoft/botbuilder-tools#1032]
## Tool
Name: Msbot
Version: 4.3.4
OS: Windows 10

## Describe the bug
When running the command `msbot update generic` to a generic type object in the .bot file, it seems to pipe in the Command itself into a 'Options' Key alongside other values related to the command run.

This is similar to the issue found in: https://github.com/Microsoft/botbuilder-tools/issues/943

## To Reproduce
1. Create 'Generic' Type Object in Bot File. In this case it comes from an `msbot clone`. and it is a 'BotTranslate' object.
2. Update Object using `msbot update generic` with `--keys` value. In this case the command is:
`msbot update generic --url "BotTranslate" --keys "{""subscriptionKey"":""999999999999999""}" --secret "BOTSECRET=" --bot "BOTFILE.bot"`

## Expected behavior
New Value in the 'subscriptionKey' field of the configuration. 

## Screenshots
![image](https://user-images.githubusercontent.com/16238513/54955034-90e63880-4f22-11e9-85b3-001fee1bb1be.png)

## Additional context
Seems to be very similar, if not the same as: https://github.com/Microsoft/botbuilder-tools/issues/943 . I also experienced this issue when updating my endpoint. My use case is similar to that user's (Attempting to deploy via CI/CD).

The Value DOES actually get updated, but it also comes with the baggage of the keys.

[bug]

**Comment by adamlash** [comment]
As a workaround, i am running `msbot disconnect "SERVICENAME"` and then `msbot connect generic --url "SERVICENAME"` in my CI/CD to 'update' this value.

**Comment by sgellock** [comment]
We are moving away from .bot files as a mechanism to store bot configuration data.  We are instead using existing platform mechanisms, appsettings.json and .env
