### ISSUE TITLE
LUIS Publish --Staging switch is broken

### ISSUE THREAD

**Issue by dawwa** [Microsoft/botbuilder-tools#1034]
## Tool
Name: LUIS
Version: *2.2.0*

## Describe the bug
luis publish version --in "general.luis" --appId XXX --authoringKey=XXX --versionId 0.1 --publishRegion westus --staging

The CLI only honor the iStaging property in luis json file, but not the "--staging" switch.
If the  **"isStaging":true,** is absence in the input json, it always publish to production endpoint with/without the switch.

  ],
  "luis_schema_version": "3.0.0",
  "versionId": "0.1",
  **"isStaging":true,**
  "name": "General",
  "desc": "",
  "culture": "en-us"
}

## Expected behavior
The CLI should honor the specified switch "--staging"

[bug]

**Comment by tsuwandy** [comment]
The above command should have been:
luis publish version --in "general.luis" --appId XXX --authoringKey=XXX --versionId 0.1 --publishRegion westus --staging true

**Comment by dawwa** [comment]
Current Behavior: If the --in argument is in use, --staging argument is ignored.
So two options:  Either use the --staging true OR make sure the "isStaging" : true property present in the input file supplied through --in argument.
