### ISSUE TITLE
msbot create doesn't work

### ISSUE THREAD

**Issue by ikendall** [Microsoft/botbuilder-tools#1038]
## Tool
Name: Msbot
Version: 4.3.4
OS: Windows 7 Enterprise SP1

## Describe the bug
I have a bot created locally (EnterpriseBot template created in VS), with all the required services defined and deployed in Azure, so the bot works successfully running locally using the Emulator (V4). I want to deploy into Azure as a "production" endpoint. msbot create should do this but just returns with a message saying "msbot create [options] allows you to clone all of the services a bot uses into new Azure resource group" - which is not what I want, nor what the GitHub documentation for msbot create says ("When you have a local bot that you would like to create an Azure Bot Service for you can use the msbot create command.", which is want I want to do!)

## To Reproduce
1. msbot create --name mybot --location westus --groupName mygroup --sdkVersion v4 --sdkLanguage CSharp --appId [APP_ID] appSecret [APP_SERCRET] --verbose

## Expected behavior
An instance of the locally created bot in Azure, plus modification of the .bot file to include new services ... production endpoint and abs (as msbot connect does for luis, QnA etc)

## Additional context
Also had many problems with [APP_SECRET] after creating the Azure Portal App Registrations (Preview) ... if the secret string contains any protected characters |, > or & etc, (which it more often then not does) it gets incorrectly parsed by msbot - tired escaping with \ and encapsulating in "". 

[bug]

**Comment by anusharavindrar** [comment]
Just for clarification, can you post a screenshot of the error?

**Comment by ikendall** [comment]
Sorry, I can't I deleted the whole app and started again to try to find another work around (which I just succeeded by creating a basic Bot in the Azure Portal, downloading source and copying just the abs and production endpoint services manually into my .bot file and then publishing back from Visual Studio ... messy, but works. Using the CLI tools I just couldn't move my local .bot file to Azure as per the description above. I also tried az bot create, but that created a lot of shadow services rather than connecting to my existing ones (there is already an open ticket on --storage not working with az bot create.)

**Comment by anusharavindrar** [comment]
I am glad that you found a work around for this issue. As you already have a ticket opened for the other issue, I am going ahead and closing this ticket.
