### ISSUE TITLE
luisgen errs out when using stdin

### ISSUE THREAD

**Issue by rob-derosa** [Microsoft/botbuilder-tools#1040]
## Tool
Name: luisgen
Version: 2.0.2
OS: MacOS 10.14.4

## Describe the bug
luisgen throws err when input is from stdin

## To Reproduce
1. Ran this command: 

luis export version --appId 8f4....42-e2df-49ae-a941-2527653ac841 --versionId 0.2 --authoringKey b95b75f1b7d...cb90e25ca758008cc | luisgen --stdin -cs

2. Received this error:

192-168-0-46:RocketInsurance.Bot rob$ luis export version --appId 8f4....42-e2df-49ae-a941-2527653ac841 --versionId 0.2 --authoringKey b95b75f1b7d...cb90e25ca758008cc | luisgen --stdin -cs

LUISGen <LUIS.json> [-cs [CLASS]] [-ts [INTERFACE]] [-o PATH] [-v] [--version]
From a LUIS export file generate a strongly typed class for consuming intents and entities.
If the input is -, will get the export file from stdin.
At least one of -cs or -ts must be supplied.
-cs [CLASS] : Generate C# class file including namespace.  Default is Luis.<appName> if no class name is specified.
-ts [INTERFACE] : Generate Typescript interface descriptions.  Default is <appName> if no class name is specified.
-o PATH : Where to put generated files, defaults to directory where export file is.
-v --version : Report the LUISGen version.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:868:14)

## Expected behavior
No error

## Additional context
I tried this with several LUIS apps and all failed w/ the same result

[bug]

**Comment by saurav2107** [comment]
I am facing the same issue, please help.

**Comment by chrimc62** [comment]
If you look at the documentation in your bug, you will see that it does not list --stdin as a flag, it is just "-".  Maybe we should add it, but this should work for you:
luis - -cs

**Comment by AmirGeorge** [comment]
Fix to this issue has already been committed some time ago. @cleemullins when are we expected to release a new version of luisgen?

**Comment by cleemullins** [comment]
+Chris McConnell

The Release of LuisGen is up to the LUIS team. 😊

//Chris

**Comment by AmirGeorge** [comment]
Fix already committed and will be pushed with the next release.
