### ISSUE TITLE
Make chatdown support comments like ludown

### ISSUE THREAD

**Issue by joseques** [microsoft/botbuilder-tools#1044]
## Tool
Name: Chatdown

## Describe the problem
Chatdown doesn't parse comment lines like ludown does using the <kbd>></kbd> character. Chatdown parses these lines as if they were part of the content of the chat file instead of ignoring it.

## Describe the solution you'd like
Implement built-in comments parsing as part of chatdown as is implemented in ludown

[enhancement]

**Comment by vishwacsena** [comment]
@munozemilio - giving this one to you for consideration in the new CLI work for Chatdown.

**Comment by munozemilio** [comment]
This will be supported in new CLI.
Already added
