### ISSUE TITLE
cosmosdb fails with "Bad or missing --key" when it is missing the endpoint parameter

### ISSUE THREAD

**Issue by AndreMantas** [Microsoft/botbuilder-tools#1045]
## Tool
Name: Msbot
Version: 4.3.4
OS: *Windows 10*

## Describe the bug

connect cosmosdb fails with "Bad or missing --key" when it is missing the endpoint parameter.

## To Reproduce
1. Try to run ``msbot connect cosmosdb -n Name --serviceName ServiceName -t TenantId -s SubscriptionId -r ResourceGroupName -k "AzurePrimaryKey" --database MyDb --collection MyColl``
2. See output message: Error: Bad or missing --key
3. Append parameter ``-e "https://ServiceName.documents.azure.com:443/"
4. Works as expected.

## Expected behavior
Error message should point out to the missing parameter

## Additional context
To add to the problem, the [current command documentation](https://github.com/Microsoft/botbuilder-tools/blob/master/packages/MSBot/docs/add-services.md#connecting-to-azure-cosmosdb-service) is missing the -e parameter in the options table

**Comment by sgellock** [comment]
we are de-emphasizing msbot's usage.  we are moving bot configuration data into existing platform configuration files, e.g. appsettings.json and .env
