### ISSUE TITLE
luis import throws error resource is missing

### ISSUE THREAD

**Issue by bumblebee333** [Microsoft/botbuilder-tools#1063]
## Tool
Name: [LUIS]
Version: *2.4.0*

## Describe the bug
I am trying to import a JSON file into an existing empty luis app, it keeps generating the error resource is missing.  The json file does  have entities in it. I tried upgrading the version in the command line or json file but that didn't help.
## To Reproduce
1. Export an existing luis model using luis export into a json file
2. Import that file into a different app

It should just get imported. Which resource is missing. Below is the command I am using:

luis import --appId "44d7xxxx-xxxx-xxxx-8a4b-a01173eef092" --authoringKey "ea1a280b11454b5aaf3e842cd088a477"   --versionId "0.1" -in c:\source\model.json

Any help is appreciated.
Best,
Rakesh

**Comment by dmvtech** [comment]
hi @bumblebee333 

The resource in question is either a LUIS `application`, or a `version`. You need to either specify that you are importing a new application or a new version (to an existing app). For example:

`luis import application `
OR
`luis import version`

 For you, sounds like you want the latter. Here are more full examples on what you _could_ use:

`luis import application --in c:\source\model.json --appName "NewAppNameBeingCreated" --region westus --authoringKey <YOURAUTHORINGKEY>`

`luis import version --in c:\source\model.json --appId <EXISTINGAPPID> --authoringKey <YOURAUTHORINGKEY>  --versionId "0.2"`

Please find more information in the LUIS readme:
https://github.com/Microsoft/botbuilder-tools/blob/master/packages/LUIS/readme.md

**Comment by dmvtech** [comment]
Closing this as it should be answered/resolved. Please reopen if still having the issue.
