### ISSUE TITLE
Dispatch doesn't enable the same file to be used across multiple dispatch intents

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#1064]
## Tool
Dispatch
Version: 1.3.0
OS: Windows 10

## Describe the bug
We would like to use the same calendar.luis source file across multiple dispatch intents, e.g.:

```
dispatch add -t file -n calendarSkill/createEvent -f calendar.luis --includeIntents CreateCalendarEntry,FindMeetingRoom -intentName calendarSkill/createEvent
dispatch add -t file -n calendarSkill/changeEventStatus -f calendar.luis --includeIntents AcceptEventEntry,DeleteCalendarEntry -intentName calendarSkill/changeEventStatus
```

However Dispatch reports that the source file has already beeen added to dispatch:

![image](https://user-images.githubusercontent.com/33519520/56077998-89f06e80-5dda-11e9-8fb2-c0966934d6a8.png)

## To Reproduce
1. ... Run above commands with attached calendar.luis file

[calendar.zip](https://github.com/Microsoft/botbuilder-tools/files/3076056/calendar.zip)

## Expected behavior
- Dispatch to accept the same source file for different dispatchIntents / names providing the intents don't overlap.

[bug]

**Comment by tsuwandy** [comment]
This is merger to master.  @darrenj, you should be able to get it from myget when daily build is deployed.
