### ISSUE TITLE
Update bot endpoint URL using az bot failed

### ISSUE THREAD

**Issue by compulim** [Microsoft/botbuilder-tools#1065]
## Tool
Name: azure-cli
Version: 0.1.8
OS: Windows 10 18H2

## Describe the bug
When I run `az bot show ...`, it dump a JSON of information related to my bot. So I am pretty sure my subscription ID and resource group are correct.

When I run the following command to update the endpoint for the bot, it failed.

```sh
az bot update --resource-group my-bot-rg --name my-bot --subscription 12345678-1234-5678-abcd-12345678abcd --set properties.endpoint https://a1b2c3d.ngrok.io/api/messages/ --force-string
```

## To Reproduce
1. Run the command forementioned

## Expected behavior
The endpoint URL is updated to `https://a1b2c3d.ngrok.io/api/messages/`.

## Screenshots
Instead, it showed only a line of text.

```
Unknown error during execution. Please file an issue on https://github.com/Microsoft/botbuilder-tools/issues
```

## Additional context
I also tried without `--force-string`, same result.

[bug]

**Comment by gabog** [comment]
This is tentativelly fixed and we are testing it today.

**Comment by stevengum** [comment]
Closing as bugbash was successful and the PR with the fix has been approved.

https://github.com/Azure/azure-cli/pull/9152
