### ISSUE TITLE
ludown parse does not preserve special characters

### ISSUE THREAD

**Issue by matthew-clark02** [microsoft/botbuilder-tools#1072]
## Tool
Name: Ludown
Version: 1.2.0
OS: Mac OS 10.14.3

## Describe the bug
When running `luis parse toluis --in file.lu` on a file containing special characters, the outputted JSON file contained incorrect encodings.

## To Reproduce
1. Create a `file.lu` containing the following:
```
$RadioStations:BBC Radio nan Gàidheal=
- Radio nan Gàidheal
```
2. Run `ludown parse toluis --in file.lu`
3. Inspect the file.json which will contain the following:
```
"closedLists": [
    {
      "name": "RadioStations",
      "subLists": [
        {
          "canonicalForm": "BBC Radio nan GÃ idheal",
          "list": [
            "Radio nan GÃ idheal"
          ]
        }
      ],
      "roles": []
    }
  ]
```
## Expected behavior
The character encodings in the ludown file to be preserved when converted to the JSON format.

## Additional context
A brief investigation potentially pointed at the following line being the issue:
https://github.com/Microsoft/botbuilder-tools/blob/master/packages/Ludown/lib/parser.js#L274

The read-text-file library does not seem to preserve character encodings. A quick snippit of code which points to this being the issue:
```
const txtfile = require('read-text-file');
const fs = require('fs');

const fileContent = txtfile.readSync('file.lu');
console.log(fileContent)

fs.readFile('file.lu', 'utf-8', (err, data) => {
  console.log(data);
});
```

[bug]

**Comment by sgellock** [comment]
@vishwacsena bumping this to P0 (data loss)
