### ISSUE TITLE
When creating a dispatch model, sources get published to production.

### ISSUE THREAD

**Issue by martinlarosa** [Microsoft/botbuilder-tools#1073]
## Tool
Name: [Dispatch]
Version: *1.3.0*
OS: *macOS 10.14.2 & Windows 10*

## Describe the bug
When I create a dispatch model with _dispatch create_ the LUIS sources get moves to production. This makes it hard to manage my versions and test a new change without disrupting production

## To Reproduce
1. Have 2 LUIS apps with version 0.1 in production and 0.2 as Active
2. Initialize a dispatch file and add both LUIS apps to the dispatch
3. execute _dispatch create_
4. Go to the LUIS apps and you'll see that in both LUIS apps the Production versions have been changed to 0.2

## Expected behavior
Be able to test dispatch models without disrupting the production environment.

[bug]

**Comment by martinlarosa** [comment]
If dispatch needs and endpoint that is not the authoring key/ starter key endpoint, then I think a good solution would be that instead of indicating a version number when adding a Luis resource to the dispatch we would indicate the slot (Production/Staging). That way the dispatch tool will use whatever version is in that slot.
I think that would make managing the versions more intuitive. I mean, if I have a dispatch tool pointing to the staging endpoints I assume that if the version in the staging slot changes, then it is fine for the dispatch tool to use the new version. I don't think it is intuitive that the dispatch tool would change the slots because of the versions it wants to use.

**Comment by tsuwandy** [comment]
@martinlarosa , you could use the optional parameter "--publishToStaging true" if you don't want Dispatch CLI to publish to production slot.  "dispatch create" command creates, train and publish LUIS Dispatch app to production slot by default. With the combined prediction is now enabled on LUIS (calling prediction on LUIS Dispatch app will also return prediction for the source LUIS app if the source LUIS app is connected to the intent returned at Dispatch level), the source LUIS apps need to be published to production as well.  

Please let me know/reactivate this issue if you were not able to use the "--publishToStaging" option on the "create"/"refresh" commands.

**Comment by martinlarosa** [comment]
Oh I completely missed that one. Thanks.
Would that also work with the refresh command? I don't see it in the documentation.

**Comment by tsuwandy** [comment]
It should, please reactivate this if it doesn’t work with refresh.  😃

**Comment by martinlarosa** [comment]
Ok, it works!
The only weird thing is that it seems to recreate the version, at least if I don't put a new version number.
![image](https://user-images.githubusercontent.com/7032277/57035018-6b3a0680-6c27-11e9-9f9c-0d393596433f.png)
The created date is updated with today's date. And it only says Active & Staging next to the version. The Production label was removed, although it keeps working with the outdated content

**Comment by tsuwandy** [comment]
@martinlarosa, Dispatch always create/refresh the app with the version ("Dispatch") unless version is specified.   To be safe, specify a version when using the --publishToStaging parameter.
