### ISSUE TITLE
Feature Request: Create an automated cognitive KBs, dispatch-integrated update mechanism

### ISSUE THREAD

**Issue by scheyal** [microsoft/botbuilder-tools#1074]
As bots development grows, so is the variety of roles/personas participating in the development. We'll have content "conversation" AI producers, and backend developers for example. 
Content producers should be able to trigger update and push new models to production using automated refresh mechanism, e.g. dispatch will pull in updated models, re-train, and push out.

**Comment by Santhosh0505** [comment]
Actually, I was trying to automate dispatch refresh command using a console application in azure portal, and I have tried to install the botdispatch but I am not able to run the "dispatch init" and other dispatch commands in the azure directory using that console application. Please suggest me that is there any thing other than botdispatch to be installed to make the commands run.

**Comment by stephanbisser** [comment]
Hi you could just use our DispatchUpdater from the BB Community repo: https://github.com/BotBuilderCommunity/botbuilder-community-tools/blob/master/DispatchUpdater/README.md
