### ISSUE TITLE
Region typos in LUIS CLI

### ISSUE THREAD

**Issue by ryanlengel** [Microsoft/botbuilder-tools#1080]
## Tool
Name: LUIS
Version: 2.4.0
OS: Windows

## Describe the bug
There are typos in the valid LUIS regions:
`eastus is not a valid authoring region.  Valid values are [westus|westeuerope|australiaest]`

## To Reproduce
Try deploying LUIS app on an invalid region and get the error response.

## Expected behavior
Regions should be `westeurope`, `australiaeast`?

## Additional context

[bug]

**Comment by mdrichardson** [comment]
@ryanlengel Thanks for bringing this to our attention! I've filed a PR that will fix this and close this issue.
