### ISSUE TITLE
[az bot, CLI/Docs Bugbash] az cli spews warning when invoked.

### ISSUE THREAD

**Issue by scheyal** [Microsoft/botbuilder-tools#1084]
## Tool
Name: az
Version: private build
OS: Win10

## Describe the bug
During bugbash the tool spews warning. Make sure it is cleared prior to release: 
```
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\requests\__init__.py:91: RequestsDependencyWarning: urllib3 (1.25) or chardet (3.0.4) doesn't match a supported version
```

## To Reproduce
Run bugbash tool

## Expected behavior
no warning

[bug]

**Comment by stevengum** [comment]
@yugangw-msft, @marstr any ideas? I built this private cut in a virtual environment that was setup using `pip install azdev`.

**Comment by yugangw-msft** [comment]
@stevengum, this will be fixed by https://github.com/kennethreitz/requests/pull/5063

**Comment by stevengum** [comment]
Perfect, thanks Yugang!

Closing as this is in a dependency and should be fixed by the above linked PR.
