### ISSUE TITLE
[az bot, CLI/Docs Bugbash] Prepare-Deploy: Either ensure the current directory or at least add warning/usage to tell where it should run.

### ISSUE THREAD

**Issue by scheyal** [Microsoft/botbuilder-tools#1085]
## Tool
Name: az cli
Version: private build
OS: win10

## Describe the bug
It's easy to make a mistake when running prepare-deploy (e.g. run in the wrong directory), and there's no clear correction path. 
Corrections:
* Validations: Ensure the tool is run in the expected folder
* Improve help text to include pre-conditions/run usage directions

## To Reproduce
Run the tool

## Expected behavior
Avoid leading the user into potential error path.

[bug]

**Comment by stevengum** [comment]
Closing as Azure/Azure-CLI#9231 has been merged.
