### ISSUE TITLE
 [az bot, CLI/Docs Bugbash] Default az cli create command should create an empty webapp. 

### ISSUE THREAD

**Issue by scheyal** [Microsoft/botbuilder-tools#1086]
## Tool
Name: az cli
Version: private build
OS: win 10

## Describe the bug
The default behavior for az cli command should create an empty webapp. Add a new option --echo to provision the webapp with echo bot. 
Reasoning: az cli is primarily used in advanced flow where devs would be starting from generators or samples. We should optimize for that flow (as opposed to using ABS as code generator).

**Comment by stevengum** [comment]
Closing as Azure/Azure-CLI#9231 has been merged.
