### ISSUE TITLE
Dispatch CLI - formalize down sampling feature 

### ISSUE THREAD

**Issue by tsuwandy** [Microsoft/botbuilder-tools#1090]
## Tool
Name: Dispatch
Version: *tool version*
OS: *os version*

## Describe the bug
1.  Expose this feature
2.  Update documentation

## To Reproduce
1. ...
2. ...
3. ...
4. ...

## Additional context

[bug]

**Comment by hcyang** [comment]
Added an auto active learning feature that can down sample a large intent/utterance set exceeding LUIS
's 15000 limit. Auto active learning will scan through a large training set and intelligently down sample it before creating a LUIS app.
