### ISSUE TITLE
dispatch remove not working for file sources

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#1091]
## Tool
Name: Dispatch
Version: 1.3.0
OS: Windows

## Describe the bug
When trying to run dispatch rremove with a file source, I can't get it to remove. If I do the following:

```
	dispatch remove `
		--type file `
		--filePath LUIS_PATH `
		--dataFolder FOLDER_PATH `
		--dispatch DISPATCH_PATH
```
Nothing happens in my .dispatch file.

If I include the '-name' parameter, I get this error: 

```
ERROR
Unable to cast object of type 'Microsoft.Fuse.FileSource' to type 'Microsoft.Fuse.QnAMakerSource'.

------
REMOVE
Usage: dispatch remove [options]

Remove a data source for dispatch (LUIS/QnA)

Options:

   -t, --type              luis, qna, file
   -i, --id                [Required only if type is qna] LUIS app id or QnA kb id (from application settings page)
   -n, --name              [Required] LUIS app name or QnA name (from application settings page) or module/file name for file type
   -f, --filePath          [Required only if type is file] Path to tsv file containing two tab delimited fields in each line representing intent and utterance or .txt file containing one utterance on each line with the file name representing intent name or .json file of exported LUIS/QnA model
   --dispatch              [Optional] Path to .dispatch file
   --dataFolder            [Optional] Dispatch working directory
```

## Expected behavior
I would expect that if I provide the name of the service I want to remove, regardless of type, that it will be removed from the dispatch file. 

[bug]

**Comment by tsuwandy** [comment]
@lauren-mills, couldn't repro with "-t file -n {name}" args or "-t file -f {path}".  I'll close this out for now, please reactivate if you still getting an error.

**Comment by tsuwandy** [comment]
Thanks @lauren-mills!  This is now fixed and will be available with next private build.
