### ISSUE TITLE
Override Dispatch training with customer provided training

### ISSUE THREAD

**Issue by Dewain27** [Microsoft/botbuilder-tools#1096]
**Is your feature request related to a problem? Please describe.**
When a user trains in utterances to skill bots or QnA Maker, many times the dispatcher guesses wrong at the correct path to dispatch the utterance.  In this case, the user has to go to LUIS and train the dispatcher to the correct way to route, however this is lost every time the dispatcher is updated.

Example: Trained QnA Maker to know "What kind of tires does my car use?" however, dispatcher thinks I want new tires and routes to Schedule service to get new tires...

**Describe the solution you'd like**
The dispatcher should update with the changes that has been provided by the user for additional top-level intent training to be kept when the dispatch refresh runs again.

**Describe alternatives you've considered**
We have discussed making another command that has an input file that could be loaded into training post running the dispatch refresh.

**Comment by darrenj** [comment]
@tsuwandy Would appreciate your thoughts on this requirement. Effectively if there is "nudging" required for certain utterances to help the dispatcher better route how can we provide this to dispatch on refresh operations to apply each time and not use. Whilst edge scenarios can be be added to the respective luis models or qna I think an "alteration" file step could still be required.

**Comment by tsuwandy** [comment]
@Dewain27 and @darrenj , this is already possible today.  Provide the utterances to override in a file (one per line), add this to Dispatch with the same intent name as the QnAMaker, is “add -t file -f {filePath} -intentName q_{QnAMakerName}”.

This will persist over refresh, and there is no need to have to go to luis to update.

Could you please share your dispatch sources with me so we could analyze why Dispatch couldn’t dispatch correctly without overrides?  Thanks!!
