### ISSUE TITLE
Can't install lubuild

### ISSUE THREAD

**Issue by mitkodi** [Microsoft/botbuilder-tools#1102]
I tried `npm install -g lubuild` with the default `https://registry.npmjs.org/` and with `https://botbuilder.myget.org/F/botbuilder-tools-daily/npm` registry but always receive `Error: 404 Not Found`.

**Comment by v-kydela** [comment]
@mitkodi - Thanks for your question.

It looks like lubuild is a preview tool and may not be published yet.

**Comment by v-kydela** [comment]
@mitkodi - I have verified that LUBuild is currently unavailable and I have submitted a PR to change the README
