### ISSUE TITLE
lubuild tests failing

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/botbuilder-tools#1124]
See npm run coveralls task in build 137 at https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=57972&_a=summary&view=logs

> lubuild@1.0.0-preview test /Users/vsts/agent/2.150.3/work/1/s/packages/lubuild
> cd test/ && mocha --opts mocha.opts
lerna ERR! npm run test stderr:
Warning: Could not find any test files matching pattern: test
No test files found

**Comment by cleemullins** [comment]
PR #1143 removes this tool from master.
