### ISSUE TITLE
dialoglint tests failing

### ISSUE THREAD

**Issue by BruceHaley** [microsoft/botbuilder-tools#1125]
See npm run coveralls task in build 140 at https://fuselabs.visualstudio.com/SDK_v4/_build/results?buildId=57986&_a=summary&view=logs

lerna ERR! npm run test exited 1 in 'dialoglint'
lerna ERR! npm run test stdout:
> dialoglint@1.0.0-preview test /Users/vsts/agent/2.150.3/work/1/s/packages/DialogLint
> mocha -r node_modules/ts-node/register test/*.ts
lerna ERR! npm run test stderr:
Warning: Could not find any test files matching pattern: test/*.ts
No test files found

**Comment by cleemullins** [comment]
PR #1143 removes this tool from master.
