### ISSUE TITLE
Composite entity labelling parse error with ludown

### ISSUE THREAD

**Issue by roalexan** [microsoft/botbuilder-tools#1129]
## Tool
Name: Ludown
Version: 1.3.0
OS: Windows 10

## Describe the bug
It appears that the parsed output of my labelled composite and simple entity is incorrect. The text field seems out of order, and the startPos/endPos for the composite entity seems off as well.

## To Reproduce

Consider the utterance "I want to order a shirt please". I want to create a composite entity "order a shirt" that maps to "productOrder". Inside that composite entity, I want to create a simple entity "shirt" that maps to "product".

First, create a labelled utterance file, test.lu, with the following:

` # Order`
` - I want to {productOrder = buy a {product = shirt}} please`

Second, parse the file by running:

`ludown parse ToLuis --in test.lu`

Third, open the output file, test.json, and observe the following in particular:

      "text": "I want to shirtbuy a please",
      "intent": "Order",
      "entities": [
        {
          "entity": "product",
          "startPos": 10,
          "endPos": 14
        },
        {
          "entity": "productOrder",
          "startPos": 10,
          "endPos": 19
        }
      ]

## Expected behavior
I would have expected the following:

      "text": "I want to buy a shirt please",
      "intent": "Order",
      "entities": [
        {
          "entity": "product",
          "startPos": 16,
          "endPos": 20
        },
        {
          "entity": "productOrder",
          "startPos": 10,
          "endPos": 20
        }
      ]

## Screenshots
n/a

## Additional context
n/a

[bug]

**Comment by vishwacsena** [comment]
Fixed via #1130 ; should be available shortly via the [botbuilder myget feed](https://botbuilder.myget.org/gallery/botbuilder-tools-daily) and pushed up to npm on the next publishing cycle.
