### ISSUE TITLE
ludown reporting undefined when refreshing from qnamaker JSON to LU

### ISSUE THREAD

**Issue by darrenj** [microsoft/botbuilder-tools#1132]
## Tool
Name: ludown
Version: 1.2.0
OS: Windows

## Describe the bug
When exporting a JSON QnAMaker file from portal (imported via a TSV personality chat file) I need to go to a LU file but when running ludown refresh I get an empty file (and no error/warning). When running in --verbose it reports undefined.

## To Reproduce
1. ...> ludown refresh -in QnaProfessional.json -o .
2. ... > ludown refresh -in QnaProfessional.json -o . --verbose
3. ...
4. ...

## Expected behavior
- LU file to be created
[qnaexamples.zip](https://github.com/microsoft/botbuilder-tools/files/3153039/qnaexamples.zip)

[bug]

**Comment by vishwacsena** [comment]
Could not repro on 1.2.0, 1.3.0 as well as what's in master .. one thing i noticed is that you are trying to pass in a qna json with --in option but you need to use -q for qna json and -l for luis json. that said, when i try with --in, i see the correct behavior ..

``` bash
$ ludown refresh --in /users/vishwacsenakannan/Downloads/qnaexamples/QnaProfessional.json -o .

  Unknown arguments: --in /users/vishwacsenakannan/Downloads/qnaexamples/QnaProfessional.json -o .
Usage: ludown refresh -i <LUISJsonFile> | -q <QnAJSONFile>

Convert LUIS JSON and/ or QnAMaker JSON file into .lu file

Options:
  -i, --LUIS_File <LUIS_JSON_File>            [Optional] LUIS JSON input file name
  -q, --QNA_FILE <QNA_FILE>                   [Optional] QnA Maker JSON input file name
  -a, --QNA_ALTERATION_FILE <QNA_ALT_FILE>    [Optional] QnA Maker Alteration input file name
  -o, --out_folder <outputFolder> [optional]  [Optional] Output folder for all files the tool will generate
  -n, --lu_File <LU_File>                     [Optional] Output .lu file name
  --verbose                                   [Optional] Get verbose messages from parser
  -s, --skip_header                           [Optional] Generate .lu file without the header comment
  --stdin                                     [Optional] Read input from stdin
  --stdout                                    [Optional] Write output to stdout only. Specifying this option will not write any generated content to disk
  -h, --help                                  output usage information

```

**Comment by vishwacsena** [comment]
And with -q option, all 3 json QnA models in the example parse into LU files without any errors.

**Comment by vishwacsena** [comment]
Closing as no repro per our chat. @darrenj -please reactivate should you continue to hit this.
