### ISSUE TITLE
[Ludown] Failed to parse .lu file back to .json when using the latest luis

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-tools#1135]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Version: *tool version*
OS: *os version*

## Describe the bug
Fail to parse .lu file back .json, after generate the .lu file from .json from the latest luis app.
1. A.json => A.lu
2. A.lu => A.json (failed!)

## To Reproduce
1. ludown refresh -i "Email_enus_official.json"
2. ludown parse toluis --in Email_enus_official.lu

Here is the json file I used. It can be parsed correctly in luis website.
[Email_enus_official.txt](https://github.com/microsoft/botbuilder-tools/files/3161601/Email_enus_official.txt)

Result: error without any information.
![image](https://user-images.githubusercontent.com/16643193/57448040-0caa0380-728b-11e9-89eb-5c08603a7c7e.png)

3. ludown refresh -i "ToDo_IPA_enus_official.json"
4. ludown parse toluis --in ToDo_IPA_enus_official.lu
[ToDo_IPA_enus_official.txt](https://github.com/microsoft/botbuilder-tools/files/3161607/ToDo_IPA_enus_official.txt)

Result like below:
![image](https://user-images.githubusercontent.com/16643193/57448109-2d725900-728b-11e9-9c50-c3edc37e1964.png)

## Expected behavior
the .lu file should able to parse back to .json file.

## Additional context

[bug]

**Comment by dmvtech** [comment]
@DingmaomaoBJTU Does this reproduce in cmd (as apposed to in PowerShell) as well?

**Comment by vishwacsena** [comment]
I verified that this is fixed via #1130

**Comment by SatyaPavanKumar** [comment]
@DingmaomaoBJTU , How you generated .lu file from json file?

**Comment by DingmaomaoBJTU** [comment]
ludown refresh -i "Email_enus_official.json"
