### ISSUE TITLE
Ludown parse error in List Entity where PhraseList name matches that of a Simple Entity

### ISSUE THREAD

**Issue by AndyCW** [microsoft/botbuilder-tools#1137]
## Tool
Name: Ludown
Version: 1.3.1
OS: Windows 10 v1903

## Describe the bug
Note that this is related to #605 . This is a separate issue.
Ludown errors trying to parse an lu file that has a PhraseList that has the same name as a Simple entity, and where it also has a List Entity defined.

## To Reproduce
1. I exported my Luis json file on the portal.
2. I used this json file to produce ludown file in order to add new utterances for next versions
`
ludown refresh -i .\tempLuis.json -n FBLuisExport.lu
`
3. I parsed it again:
`
ludown parse ToLuis --in .\FBLuisExport.lu -n FBLuis -i 0.1
`
4. Ludown fails with an error, where the line number given is the first synonym defined for a List entity which follows the PhraseList definition in the .lu file
![Annotation 2019-05-13 111654](https://user-images.githubusercontent.com/4299590/57614263-ac5be000-7570-11e9-9457-0996c1020064.png)

## Expected behavior
ludown should parse the file

## Screenshots
This is the relevant part of the .lu file:
![ludown](https://user-images.githubusercontent.com/4299590/57614302-c4336400-7570-11e9-86a9-c0f1a824c39f.png)

[bug]

**Comment by AndyCW** [comment]
This issue may be erroneous. The List Entity sublist canonical forms in this example include double colons and this is not currently supported by ludown parse. Existing issue for this: #1166

**Comment by vishwacsena** [comment]
Fixed via #1168
