### ISSUE TITLE
Consider update the doc to make sure people not using newer Azure CLI which breaks msbot

### ISSUE THREAD

**Issue by dawwa** [microsoft/botbuilder-tools#1147]
Related reported issue in Azure CLI

https://github.com/Azure/azure-cli/issues/9414
https://github.com/Azure/azure-cli/issues/9363

https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md
•	[BREAKING CHANGE] Changed bot create -v v4 -k webapp to create an empty Web App Bot by default (i.e. no bot is deployed to the App Service)
•	Added --echo flag to bot create to use the old behavior with -v v4
•	[BREAKING CHANGE] Changed the default value of --version to v4
o	NOTE: bot prepare-publish still uses the its old default
•	[BREAKING CHANGE] Changed --lang to no longer default to Csharp. If the command requires --lang and it is not provided, the command will now error out
•	[BREAKING CHANGE] Changed the --appid and --password args for bot create to be required and can now be created via ad app create
•	Added --appid and --password validation
•	[BREAKING CHANGE] Changed bot create -v v4 to not create or use a Storage Account or Application Insights
•	[BREAKING CHANGE] Changed bot create -v v3 to require a region where Application Insights is available
•	[BREAKING CHANGE] Changed bot update to now affect only specific properties of a bot
•	[BREAKING CHANGE] Changed --lang flags to accept Javascript instead of Node
•	[BREAKING CHANGE] Removed Node as an allowed --lang value
•	[BREAKING CHANGE] Changed bot create -v v4 -k webapp to no longer set SCM_DO_BUILD_DURING_DEPLOYMENT to true. All deployments through Kudu will act according to their default behavior

**Comment by sgellock** [comment]
@dawwa thank you for logging the issue.  Here is some additional information regarding msbot and it's future:

Stepping back a bit, we have a number of CLI tools that we feel complication the experience for developers.  In our 4.5 release (our next scheduled release), we will be releasing a single CLI tool, bot Framework CLI, that is modeled in much the same way as the Azure CLI (command groups/commands/plugins).  When we are done with this effort we will have two CLI tools to consider.  Azure-CLI for Azure resources, and BF-CLI for Bot Framework (non azure) issues.  We hope this simplifies things for the community.
