### ISSUE TITLE
Dispatch apps no longer running in docker containers

### ISSUE THREAD

**Issue by chrisdromey** [microsoft/botbuilder-tools#1152]
## Tool
Name: Dispatch
Version: 1.4.5
OS: macOS 10.14.4
mcr.microsoft.com/azure-cognitive-services/luis IMAGE_ID: d9e5f60e0f80

## Describe the bug
We noticed on 16/5/19 that we were no longer able to run dispatch apps in docker containers.

When querying a running dispatch app in a docker container we receive a 500 response and see the following error in the docker containers log files:

```
fail: Luis[0]
     Failed while prefetching App: AppId: xxxxx-xxxxx-xxxxx-xxxx-xxxxxxxxx - Slot: PRODUCTION Unsupported slot name v0.1
fail: Luis[0]
     Failed while getting response for AppId: xxxxx-xxxxx-xxxxx-xxxx-xxxxxxxxx - Slot: PRODUCTION. Error: Unsupported slot name v0.1
fail: Microsoft.CloudAI.Containers.Controllers.LuisController[0]
     Response status code: 500
     Exception: Unsupported slot name v0.1
```

## To Reproduce
1. Follow the steps to create a dispatch app as detailed [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=js)
2. Follow steps to run LUIS apps in containers as detailed [here](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-container-howto). Using the .gz generate from the previous guide.
3. Query the API endpoint on the local docker container via the swagger interface

## Expected behavior
We expect the dispatch app to be reachable via the rest endpoints on the docker container.

## Screenshots
n/a

## Additional context
The child apps (used to generate the dispatch app) *ARE* reachable as expected when running in the same docker container. 
Dispatch apps were able to be ran successfully in docker container prior to last week.

[bug]

**Comment by sgellock** [comment]
@CezaryMarcjan can you track this one down?

**Comment by tsuwandy** [comment]
Not a Dispatch cli issue but a prediction in LUIS container issue.  There is a new fix for LUIS container coming next week.

**Comment by tsuwandy** [comment]
@AmirGeorge, has the container update been released to address this issue?

**Comment by AmirGeorge** [comment]
@chrisdromey fix deployed. Please pull the latest container image.
