### ISSUE TITLE
[Ludown CLI] Utterances with labelled Roles on List Entities cause Ludown parse toluis to fail

### ISSUE THREAD

**Issue by AndyCW** [microsoft/botbuilder-tools#1164]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Version: *tool version*
OS: *os version*

## Describe the bug
Entity roles can now be used with list entities and builtin entities. However ludown parse toluis cannot handle utterances labelled with roles on list entities and fails with an error.

## To Reproduce
1. Model json (save as rolesBug.json):
{
  "luis_schema_version": "3.2.0",
  "versionId": "0.1",
  "name": "bug",
  "desc": "",
  "culture": "en-us",
  "tokenizerVersion": "1.0.0",
  "intents": [
    {
      "name": "None"
    }
  ],
  "entities": [],
  "composites": [],
  "closedLists": [
    {
      "name": "aListEntity",
      "subLists": [
        {
          "canonicalForm": "some value",
          "list": [
            "avalue"
          ]
        }
      ],
      "roles": [
        "ThisIsARole"
      ]
    }
  ],
  "patternAnyEntities": [],
  "regex_entities": [],
  "prebuiltEntities": [],
  "model_features": [],
  "regex_features": [],
  "patterns": [],
  "utterances": [
    {
      "text": "here's an utterance avalue with a role in it",
      "intent": "None",
      "entities": [
        {
          "entity": "aListEntity",
          "role": "ThisIsARole",
          "startPos": 20,
          "endPos": 25
        }
      ]
    }
  ],
  "settings": []
}
2. this works: ludown refresh -i .\rolesBug.json -n rolesBug.lu
3. this fails: 
c:/> 

ludown parse toluis --in rolesBug.lu --out rolesBug-parse.json --verbose
Parsing file: rolesBug.lu
[ERROR]: 'List' entity: "aListEntity" is added as a labelled entity in utterance "here's an utterance avalue with a role in it". List cannot be added with explicit labelled values in utterances.
Stopping further processing.

## Additional context

[bug]

**Comment by vishwacsena** [comment]
Fixed via #1168
