### ISSUE TITLE
[Ludown CLI] ludown parse toluis fails with Composite entity that has a entity with role defined as a child

### ISSUE THREAD

**Issue by AndyCW** [microsoft/botbuilder-tools#1165]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Version: 1.3.1
OS: Windows 10 1903

## Describe the bug
Entities with roles can be set as a child in a composite entity. After exporting to json and converting to .lu, ludown parsetoluis fails when converting back.

## To Reproduce
1. Create a model with a composite that includes an entity with a role as a child. Convert to .lu format using ludown refresh.
Example .lu file:
> ! Automatically generated by [LUDown CLI](https://github.com/Microsoft/botbuilder-tools/tree/master/Ludown), Sat Jun 01 2019 09:39:22 GMT+0200 (Central European Summer Time)

> ! Source LUIS JSON file: .\rolesBug.json

> ! Source QnA TSV file: Not Specified

> ! Source QnA Alterations file: Not Specified

> # Intent definitions

## None
- here's an utterance avalue with a role in it

> # Entity definitions

> # PREBUILT Entity definitions

> # Phrase list definitions

> # List entities

$aListEntity:some value= Roles=ThisIsARole
- avalue

> # RegEx entities

> # Composite entities

$MyComposite:[aListEntity:ThisIsARole]

2. Attempt to convert the above back to json:

ludown parse toluis --in rolesCompositeBug.lu --out rolesBug-parse.json --verbose
Parsing file: rolesCompositeBug.lu
[ERROR] Invalid entity definition for $MyComposite:[aListEntity:ThisIsARole]
Stopping further processing.

## Expected behavior
Should parse the ludown file to json

## Additional context

[bug]

**Comment by vishwacsena** [comment]
Fixed via #1168
