### ISSUE TITLE
Error parsing double colons in Entity List values

### ISSUE THREAD

**Issue by pawett** [microsoft/botbuilder-tools#1166]
## Tool
Name: Ludown|LuisGen
Version: *1.3.1*
OS: *Windows 10*

## Describe the bug
Parse command does not parse correctly entity values with double colon.
Example:
$Country|Office:Argentina|ar::chc=
- Chaco
- chaco
This is perfectly valid in LUIS and should be able to parse correctlly these values to a valid entity.
## To Reproduce
1. ... Define an entity with double colon as part of its value
2. ... Try to parse to luis file
3. ... An error is thrown: "Line #xxx is not part of a Intent/Entity/ Qna Stop further processing

## Expected behavior
The entity definition should be correctly parsed maintaining the double colon in its value

[bug]

**Comment by vishwacsena** [comment]
Fixed via #1168
