### ISSUE TITLE
[Ludown CLI] ludown parse toluis wrongly reports error for utterance containing composite around nested simple entities

### ISSUE THREAD

**Issue by AndyCW** [microsoft/botbuilder-tools#1167]
## Tool
Name: Ludown
Version: 1.3.1
OS: Windows 10 1903

## Describe the bug
It is legal for one simple entity to cover the same tokens as another. If a composite is defined over the same range as nested simple entities, Ludown cannot parse the .lu file and wrongle reports an error for nested coomposite values.

## To Reproduce
1. Using a ludown file such as this:
> ! Automatically generated by [LUDown CLI](https://github.com/Microsoft/botbuilder-tools/tree/master/Ludown), Sun Jun 02 2019 19:55:56 GMT+0100 (British Summer Time)

> ! Source LUIS JSON file: .\nestedSimpleEntitiesBug.json

> ! Source QnA TSV file: Not Specified

> ! Source QnA Alterations file: Not Specified

> # Intent definitions

## None
- {MyComposite=here's an {Entity2=utterance {Entity1=avalue}}} with a composite in it

> # Entity definitions

$Entity1:simple

$Entity2:simple

> # PREBUILT Entity definitions

> # Phrase list definitions

> # List entities

> # RegEx entities

> # Composite entities

$MyComposite:[Entity1, Entity2]

2. Try to convert to Json:
ludown parse toluis --in nestedSimpleEntitiesBug.lu --out nestedSimpleEntitiesBug-parse.json --verbose
Parsing file: nestedSimpleEntitiesBug.lu
[ERROR]: Utterance "{MyComposite=here's an {Entity2=utterance {Entity1=avalue}}} with a composite in it" has nested composite references. e.g. {a = {b = x}} is valid but {a = {b = {c = x}}} is invalid.
Stopping further processing.

## Expected behavior
ludown should parse the .lu file successfully.

## Additional context
This is the source json file for this model. The .lu file ,listed above was created from this json. Ludown should be able to parse toluis back to this:

{
  "luis_schema_version": "3.2.0",
  "versionId": "0.1",
  "name": "bug",
  "desc": "",
  "culture": "en-us",
  "tokenizerVersion": "1.0.0",
  "intents": [
    {
      "name": "None"
    }
  ],
  "entities": [
    {
      "name": "Entity1",
      "roles": []
    },
    {
      "name": "Entity2",
      "roles": []
    }
  ],
  "composites": [
    {
      "name": "MyComposite",
      "children": [
        "Entity1",
        "Entity2"
      ],
      "roles": []
    }],
  "closedLists": [],
  "patternAnyEntities": [],
  "regex_entities": [],
  "prebuiltEntities": [],
  "model_features": [],
  "regex_features": [],
  "patterns": [],
  "utterances": [
    {
      "text": "here's an utterance avalue with a composite in it",
      "intent": "None",
      "entities": [
        {
            "entity": "Entity1",
            "startPos": 20,
            "endPos": 25
        },
        {
            "entity": "Entity2",
            "startPos": 10,
            "endPos": 25
        },
        {
            "entity": "MyComposite",
            "startPos": 0,
            "endPos": 25
        }
      ]
    }
  ],
  "settings": []
}

[bug]

**Comment by vishwacsena** [comment]
Fixed via #1168
