### ISSUE TITLE
Dispatch seems to be returning the wrong top intent

### ISSUE THREAD

**Issue by rob-derosa** [microsoft/botbuilder-tools#1170]
## Tool
Name: [Dispatch]
Version: 1.4.5
OS: MacOS 10.14.5

## Describe the bug
Dispatch model is returning incorrect top intents with a very low confidence score. For instance, when I type "billing history", Dispatch returns the top intent as l_General with a confidence score of .300 as seen in the screenshot below.
<img width="889" alt="Screen Shot 2019-06-10 at 11 23 23 AM" src="https://user-images.githubusercontent.com/7773968/59213552-6182b780-8b72-11e9-9403-103f5a688c5f.png">

When I test this against the General LUIS model, it returns a confidence score of .106
<img width="803" alt="Screen Shot 2019-06-10 at 11 22 56 AM" src="https://user-images.githubusercontent.com/7773968/59213582-76f7e180-8b72-11e9-95c3-2e41c84ba6fe.png">

When I run this against the correct KB, I get a confidence score of 74.21.
<img width="1493" alt="Screen Shot 2019-06-10 at 11 24 10 AM" src="https://user-images.githubusercontent.com/7773968/59213613-88d98480-8b72-11e9-9bd7-e7f350e28777.png">

## To Reproduce
1. Query the LUIS Dispatch model (64f1e061-ad50-40b8-b468-59e214442f2c) with "billing history"
2. Query the General LUIS model (c035a6bb-d954-40ff-bbc0-80772edaeab3) with "billing history"
3. Query the QnA FAQ KB (2ec0dff0-ff8a-4be3-b451-4abc520ee04e) with "billing history"

## Expected behavior
Dispatch would return the FAQ KB as the top intent that could then be interrogated.

## Screenshots
Inline

[bug]

**Comment by tsuwandy** [comment]
@rob-DeRosa, could you share the exported General LUIS model and the QnA FAQ kb?  You could email it to tiens@microsoft.com. Thanks!

**Comment by tsuwandy** [comment]
@rob-derosa , could you try creating a new dispatch with both LUIS/QnA models, but when adding qna kb, use the optional "includeAnswersForTraining true" parameter and see if this resolves the issue with the dispatch prediction? 

ie

dispatch add -t qna -i 2ec0dff0-ff8a-4be3-b451-4abc520ee04e -n Faq -k xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --includeAnswersForTraining

**Comment by rob-derosa** [comment]
I created a new dispatch model with the instructions above. I wasn't sure if I should include "true" as the param value so I tried both but the json data it adds to the dispatch file is identical to what I had before.  I tested in the new dispatch model but got the same result. I'm guessing the `--includeAnswersForTraining` arg didn't take.

**Comment by tsuwandy** [comment]
What's your Dispatch CLI version?  I just tried with latest version 1.4.7, used "--includeAnswersForTraining true" when adding qna source and I see the answers getting added to the qna intent.

**Comment by tsuwandy** [comment]
@rob-derosa, let me know if you are able to use the optional "--includeAnswersForTraining true" using the latest Dispatch CLI when adding qna source .  More importantly, if that fixes the intent dispatch to Qna at the dispatch level.  Thanks!

**Comment by rob-derosa** [comment]
After upgrading, I can see the new config setting in the dispatch file. It is also returning the correct FAQ intent now .80 confidence. Appreciate the help.

**Comment by tsuwandy** [comment]
@rob-derosa, thanks for letting us know!
