### ISSUE TITLE
Ludown fails to convert regex entities containing a slash followed by a colon

### ISSUE THREAD

**Issue by outofthecave** [microsoft/botbuilder-tools#1177]
## Tool
Name: Ludown
Version: 1.3.1
OS: Windows 10 Enterprise (Microsoft-internal version)

## Describe the bug
If a LUIS JSON file contains a regex entity whose regex contains a slash followed by a colon (`/:`), then Ludown either exits prematurely or truncates the regex just before the slash.

## To Reproduce
1. Create a LUIS JSON file called `Slash.json` with a regex entity whose regex contains a slash followed by a colon (`/:`)
2. Run `ludown refresh -i Slash.json -o . -n Slash.lu`
3. The resulting `Slash.lu` file contains the regex as `/.../:.../` with the slash character not being escaped.
4. Run `ludown parse toluis --in Slash.lu -o . --out Slash_converted.json`
5. Sometimes, Ludown exits prematurely with the message
```
undefined
Stopping further processing.
```
Sometimes, Ludown exits normally, but the regex in the output file is truncated just before the slash character.
The behaviour seems to depend on the character that follows the colon in the regex, but I haven't been able to figure out the pattern behind this.

## Expected behavior
Ludown should not exit prematurely.
The regex should appear in full in `Slash_converted.json` and not be truncated.
Maybe the slash in the regex should be escaped in `Slash.lu` to avoid it being mistaken for the end of the regex?

[bug]

**Comment by vishwacsena** [comment]
@munozemilio - There already is an outstanding PR for this that @outofthecave submitted. I have reviewed and approved it but is pending CI issues in general that are impacting several outstanding PRs - just FYI.
