### ISSUE TITLE
LUIS tool help for permissions has incorrect json example

### ISSUE THREAD

**Issue by negativeeddy** [microsoft/botbuilder-tools#1179]
## Tool
Name: LUIS
Version: 2.5.1
OS: Windows 10

## Describe the bug
The user is prompted with a json example when modifying the collaborators when the LUIS tool. The sample json is incorrect. The "emails" array is incorrectly labeled "email"

It shows 
```
{
   "email": [
      "email@address.org",
      "email2@address.org"
   ]
 }
```

when it should be
```
{
   "emails": [
      "email@address.org",
      "email2@address.org"
   ]
 }
```
## To Reproduce
1. run "luis update permissions"
2. look at the help prompt

## Expected behavior
It should show an example that works. 

[bug]

**Comment by cahann** [comment]
deprecating collaborators experience so closing this issue
