### ISSUE TITLE
dispatch refresh is blocked on Expanding kb * with word alterations

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botbuilder-tools#1181]
## Tool
Name: Dispatch

## Describe the problem
The following runs forever:
```
dispatch refresh --dispatch path/to/dispatchFile --dataFolder path/to/dataFolder
Exporting services for dispatch...
Exporting *_general LUIS application...
Exported LUIS app JSON is at *\_L_*_general.json
Exporting faq QnA kb...
Exported QnA app JSON is at *\_Q_q_faq.json
Expanding kb [id of faq] with word alterations
```

## Describe the solution you'd like
Provide a verbose mode to indicate what is happening or some sanity checks to find wrong configurations.

**Comment by tsuwandy** [comment]
@xieofxie, would you mind sharing your dispatch file (tiens@microsoft.com) so I could take a look?  Thanks for reporting this issue!

**Comment by tsuwandy** [comment]
Thanks @xieofxie, figured out the issue.  Deploying a new version by end of today (6/25/19)

**Comment by xieofxie** [comment]
Cool, botdispatch@1.5.0 works!

**Comment by tsuwandy** [comment]
Awesome, thank you!!
