### ISSUE TITLE
[ludown] translate fails with meta tags

### ISSUE THREAD

**Issue by mekinney** [microsoft/botbuilder-tools#1191]
## Tool
Name: [Ludown]
Version: 1.3.2-preview-190627-01 (nightly build)
OS: Windows 10

## Describe the bug
Ludown translates to the meta tag entries which then causes the ludown parse toqna to fail.  I believe I'm using the correct process to get the latest version of ludown. 

## To Reproduce

1. Start with the english lu file in the attached zip.  I would typically get this by exporting the kb with "qnamaker export kb...".
2. ludown translate --in english-with-metatag.lu -t fr -k <yourkey>  
3. The output file has been renamed to "french-after-translate.lu" and is in the zip file. 
4. ludown parse toqna ... gives the following error:
```
Filter: "metatag - d'abord" does not have a name = value pair.
Stopping further processing.
```

## Expected behavior
It should be possible to translate a QnA knowledgebase with meta tags (and context - haven't tested that).

[ludown-translate-files.zip](https://github.com/microsoft/botbuilder-tools/files/3335742/ludown-translate-files.zip)

[bug]

**Comment by cleemullins** [comment]
Thanks for reporting this. We've got PR #1255 that addresses this. This will release as part of the 4.6 release in October.

**Comment by mekinney** [comment]
Thank you for the update.
