### ISSUE TITLE
az bot: Update bot's icon URL

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-tools#1198]
## Tool
Name: `az bot`

## Describe the bug
Users are unable to update the bot's icon URL via the Azure CLI, a feature available in the Azure Portal.

## Expected behavior
Users should be able to update the icon URL.

## Additional context
This feature would go into `az bot update` to avoid overloading `az bot create` further.

[bug]

**Comment by tsuwandy** [comment]
@stevengum, are you planning to push with with Sprint 74?

**Comment by stevengum** [comment]
PR is out right now, but didn't make the date... It should land by Sprint 75 closes.

**Comment by stevengum** [comment]
Closed via Azure/azure-cli#11318.
