### ISSUE TITLE
Dispatcher does not appear to be able to target Azure Government

### ISSUE THREAD

**Issue by managedcoder** [microsoft/botbuilder-tools#1199]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Version: *tool version*
OS: *os version*

## Describe the bug
Trying to create a dispatcher that targets Azure Government using the dispatch tool but it won’t initialize it.
I run the command

`dispatch init -n /c/Users/.../chatbot/code/Dispatch/myBot.dispatch --luisAuthoringKey "<key>" --luisAuthoringRegion usgovvirginia`

and it never completes, I let it run for over an hour.
Possible government cloud problem perhaps?

## To Reproduce
1. Create a bot
2. Create multiple LUIS app in government LUIS portal at: [https://luis.azure.us](https://luis.azure.us)
3. Configure things for dispatcher as detailed in documentation
4. Run the dispatch command mentioned previously

## Expected behavior
Expect the command to complete successfully and 

## Additional context
I’m aware how dispatch is supposed to work and I’m aware of how to set it up in a commercial environment per the documentation but not sure if its Azure Government aware or not.

[bug]

**Comment by ericchansen** [comment]
Could be related to issue #608. Still awaiting a resolution there for months.

**Comment by FirebornX** [comment]
![20190708](https://user-images.githubusercontent.com/4278203/60828576-9bda7700-a167-11e9-8181-d0022896022c.PNG)

doesn't seem to be able to recognize the Azure government regions

**Comment by tsuwandy** [comment]
This is not related to 608, which is running dispatch command in remote execution script.  

Work around to target Azure government:
1.  Finish “dispatch init” command with one of those valid regions, then manually update them in .dispatch file before running “dispatch create” command. 

2.  Update the endpoints in settings file (find where dispatch cli is installed via "npm root", if globally "npm root -g".

 ie.  \node_modules\botdispatch\bin\netcoreapp2.1\AugmentLuisModelSettings.json

The settings file look like the following, modify AuthoringBaseUrl and the EndpointBaseUrl to match the endpoints in Azure goverment (ie xxx.gov). The placeholder {0} is populated with authoring/subscription region (ie "westus").
{
"LuisApi": {
"DispatchVersion": "1.5.0",
"AuthoringBaseUrl": "https://{0}.api.cognitive.microsoft.com/luis/api/v2.0/apps",
"EndpointBaseUrl": "https://{0}.api.cognitive.microsoft.com/luis/v2.0/apps"
}

Let me know if there issues with the workaround.

**Comment by FirebornX** [comment]
@tsuwandy I was able to complete the "dispatch init" successfully when I use one of the valid regions.
I then edit the resulting .dispatch file to have virginia for the regions.
I also edit AugmentLuisModelSettings.json to point to the .api.cognitive.microsoft.us endpoints for Azure gov.
Then I "dispatch add" LUIS apps to the dispatch file. It succeeds.
Then I "dispatch create" it hangs on one app that has intents but no utterances. This seems to be a limitation of LUIS more than the dispatch tool. LUIS will fail to train if there are intents which contain no utterances.
After filling in some utterances in the empty intents creating seems to function but then throws an error, I don't know if this is at all related to the current issue though.

![20190709](https://user-images.githubusercontent.com/4278203/60917517-fea24000-a245-11e9-86ed-db3dbbd07ef2.PNG)

**Comment by FirebornX** [comment]
@tsuwandy I did add utterances to the problematic intents. That allowed me to get the point in the screenshot above.

**Comment by tsuwandy** [comment]
@firebornx, could you zipped up the data folder (inside the folder where you run the cli) and email me at tiens@microsoft.com?  Trying to figure out what in the json file causing import to fail.  I don't think this is specific to Azure gov environment.  I'm guessing if you use other LUIS file which works in the regular Azure environment, dispatch create will finish. Thank you!

**Comment by tsuwandy** [comment]
Latest cli is deployed to npmjs. Please let me know if you are seeing other errors.  Still need to update the settings file above to point to gov endpoint to target Azure gov environment.  Thanks!

**Comment by FirebornX** [comment]
This issue is resolved as of v1.5.1 of the dispatch cli.
Note that you must still modify AugmentLuisModelSettings.json (inside of the dispatch cli install directory) to point to the Azure government endpoints (.us instead of .com), you will also have to re-modify this file after upgrading the botdispatch package
{
"LuisApi": {
"DispatchVersion": "1.5.1",
"AuthoringBaseUrl": "https://{0}.api.cognitive.microsoft.us/luis/api/v2.0/apps",
"EndpointBaseUrl": "https://{0}.api.cognitive.microsoft.us/luis/v2.0/apps"
}
