### ISSUE TITLE
dispatch command arguments don't accept absolute paths

### ISSUE THREAD

**Issue by ooorndtski** [microsoft/botbuilder-tools#1202]
## Tool
Name: [Dispatch]
Version: 1.5.0
OS: Windows 10

## Describe the bug
The dispatch command does not accept absolute paths that are passed as value of the --dataFolder arguments. It only works using relative paths.

## To Reproduce
1. Create a dispatch model, e.g. at c:\User\<username>\dispatch\
2. Open PowerShell and go to any location, e.g. c:\User\<username>\Documents\
3. Execute the command 'dispatch refresh --dispatch c:\users\<username>\dispatch\my_dispatch_file.dispatch --dataFolder c:\users\<username>\dispatch\'

## Expected behavior
The passed absolute path is accepted

[bug]

**Comment by tsuwandy** [comment]
@ooorndtski , I was able to run dispatch create command successfully from a different folder via powershell.  What was the error you were seeing?

**Comment by tsuwandy** [comment]
@ooorndtski , closing this issue as dispatch takes absolute path (in addition to relative) for the data folder or dispatch file. Let us know if you are getting errors for some reason.
