### ISSUE TITLE
Can I have multiple Intents in LUIS for the same knowledge base.

### ISSUE THREAD

**Issue by tejasvinishelar** [microsoft/botbuilder-tools#1203]
## Issue Description:

I'm referring below github code:

https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/14.nlp-with-dispatch/

I am having trouble to access multiple knowledge bases using LUIS and Dispatcher tool.

Below are my issues:
1. 	Can I have multiple Intents in LUIS for the same knowledge base.
2. 	How to create intent per question in LUIS when you have more than 100 questions.
3.     Can I have same intent in two knowledge bases.
 
Please help me to implement this situation.

**Comment by stevkan** [comment]
Hi @tejasvinishelar, can you post your code so I can better advise you? Please don't include any keys.

**Comment by tejasvinishelar** [comment]
Hello Sir,
I can't post my code publicly.
Is there any other way to send you my code?

**Comment by stevkan** [comment]
@tejasvinishelar, apologies for the delay. You can send the code via email to me. My email is in my profile. Please reference this issue (#, link, etc.) so I can easily find.

**Comment by sgellock** [comment]
@tejasvinishelar, in the future if you can use GitHub issues for product defect or product enhancement requests that would be aligned to the community's exceptions.  How-to questions should be vectored to Stackoverflow where we have an active community.  https://stackoverflow.com/search?q=bot+framework

Support, continue helping.  thank you

**Comment by CoHealer** [comment]
@stevkan, do you have any updates?

**Comment by stevkan** [comment]
@tejasvinishelar, thank you for sending your code. I will take a look at respond as soon as possible with any other solutions/questions.

**Comment by CoHealer** [comment]
@stevkan please provide an update

**Comment by stevkan** [comment]
Hi @tejasvinishelar, I believe the following example should help.

Essentially, I have two LUIS intents that have similar yet distinct utterances: home and vehicle automation (and movie times and list). Dispatcher first processes which LUIS app it belongs to and returns a value which is then mapped to a process (e.g "turn my Xbox on" => "l_HomeAutomation"). "l_HomeAutomation" and "l_VehicleAutomation" both map to `this.processAutomation`. Within the process the utterance is processed again against the specific home automation LUIS app returning a specific intent. The returned intent can then be mapped to the QnA KB to retrieve a response. In this scenario, home and vehicle automation questions pull from the same KB as do movie times and list.

Does this answer your question / solve your issue?

```js
class DispatchBot extends ActivityHandler {
    constructor() {
        super();
        const dispatchRecognizer = new LuisRecognizer({
            applicationId: process.env.LuisAppId,
            endpointKey: process.env.LuisAPIKey,
            endpoint: `https://${process.env.LuisAPIHostName}.api.cognitive.microsoft.com`
        }, {
                includeAllIntents: true,
                includeInstanceData: true
            }, true);

        const qnaMaker = new QnAMaker({
            knowledgeBaseId: process.env.QnAKnowledgebaseId,
            endpointKey: process.env.QnAEndpointKey,
            host: process.env.QnAEndpointHostName
        });

        this.dispatchRecognizer = dispatchRecognizer;
        this.qnaMaker = qnaMaker;

        this.onMessage(async (context, next) => {
            console.log('Processing Message Activity.');

            // First, we use the dispatch model to determine which cognitive service (LUIS or QnA) to use.
            const recognizerResult = await dispatchRecognizer.recognize(context);

            // Top intent tell us which cognitive service to use.
            const intent = await LuisRecognizer.topIntent(recognizerResult);

            // Next, we call the dispatcher with the top intent.
            await this.dispatchToTopIntentAsync(context, intent, recognizerResult);
            await next();
        });


    async dispatchToTopIntentAsync(context, intent, recognizerResult) {
        switch (intent) {
            case 'l_HomeAutomation':
                await this.processAutomation(context, recognizerResult.luisResult);
                break;
            case 'l_VehicleAutomation':
                await this.processAutomation(context, recognizerResult.luisResult);
                break;
            case 'l_MovieTimes':
                await this.processMovies(context, recognizerResult.luisResult);
                break;
            case 'l_MovieList':
                await this.processMovies(context, recognizerResult.luisResult);
                break;
            default:
                console.log(`Dispatch unrecognized intent: ${intent}.`);
                await context.sendActivity(`Dispatch unrecognized intent: ${intent}.`);
                break;
        }
    }

    async processAutomation(context, luisResult) {
        console.log('processHomeAutomation');

        // Retrieve LUIS result for Process Automation.
        const result = luisResult.connectedServiceResult;
        const intent = result.topScoringIntent.intent;

        [...Make QnA call...]
    }
}

module.exports.DispatchBot = DispatchBot;
```

**Comment by tejasvinishelar** [comment]
> Hi @tejasvinishelar, I believe the following example should help.
> 
> Essentially, I have two LUIS intents that have similar yet distinct utterances: home and vehicle automation (and movie times and list). Dispatcher first processes which LUIS app it belongs to and returns a value which is then mapped to a process (e.g "turn my Xbox on" => "l_HomeAutomation"). "l_HomeAutomation" and "l_VehicleAutomation" both map to `this.processAutomation`. Within the process the utterance is processed again against the specific home automation LUIS app returning a specific intent. The returned intent can then be mapped to the QnA KB to retrieve a response. In this scenario, home and vehicle automation questions pull from the same KB as do movie times and list.
> 
> Does this answer your question / solve your issue?
> 
> ```js
> class DispatchBot extends ActivityHandler {
>     constructor() {
>         super();
>         const dispatchRecognizer = new LuisRecognizer({
>             applicationId: process.env.LuisAppId,
>             endpointKey: process.env.LuisAPIKey,
>             endpoint: `https://${process.env.LuisAPIHostName}.api.cognitive.microsoft.com`
>         }, {
>                 includeAllIntents: true,
>                 includeInstanceData: true
>             }, true);
> 
>         const qnaMaker = new QnAMaker({
>             knowledgeBaseId: process.env.QnAKnowledgebaseId,
>             endpointKey: process.env.QnAEndpointKey,
>             host: process.env.QnAEndpointHostName
>         });
> 
>         this.dispatchRecognizer = dispatchRecognizer;
>         this.qnaMaker = qnaMaker;
> 
>         this.onMessage(async (context, next) => {
>             console.log('Processing Message Activity.');
> 
>             // First, we use the dispatch model to determine which cognitive service (LUIS or QnA) to use.
>             const recognizerResult = await dispatchRecognizer.recognize(context);
> 
>             // Top intent tell us which cognitive service to use.
>             const intent = await LuisRecognizer.topIntent(recognizerResult);
> 
>             // Next, we call the dispatcher with the top intent.
>             await this.dispatchToTopIntentAsync(context, intent, recognizerResult);
>             await next();
>         });
> 
> 
>     async dispatchToTopIntentAsync(context, intent, recognizerResult) {
>         switch (intent) {
>             case 'l_HomeAutomation':
>                 await this.processAutomation(context, recognizerResult.luisResult);
>                 break;
>             case 'l_VehicleAutomation':
>                 await this.processAutomation(context, recognizerResult.luisResult);
>                 break;
>             case 'l_MovieTimes':
>                 await this.processMovies(context, recognizerResult.luisResult);
>                 break;
>             case 'l_MovieList':
>                 await this.processMovies(context, recognizerResult.luisResult);
>                 break;
>             default:
>                 console.log(`Dispatch unrecognized intent: ${intent}.`);
>                 await context.sendActivity(`Dispatch unrecognized intent: ${intent}.`);
>                 break;
>         }
>     }
> 
>     async processAutomation(context, luisResult) {
>         console.log('processHomeAutomation');
> 
>         // Retrieve LUIS result for Process Automation.
>         const result = luisResult.connectedServiceResult;
>         const intent = result.topScoringIntent.intent;
> 
>         [...Make QnA call...]
>     }
> }
> 
> module.exports.DispatchBot = DispatchBot;
> ```

Thank you Stevan for your reply.
But this is not my problem.

**1]** I want to handle multiple intents for the same QnA maker in dispatch LUIS app.

While creating dispatch app we use below command:
dispatch add -t qna -i "QNA_ID" -n "KBNAME" -k "KBID" --intentName **name_of_intent**

Here **name_of_intent** will be the only one intent for full knowledge base in **dispatch LUIS app**.
How to distribute questions of knowledge base to different intents in "dispatch LUIS app"?

**2]** Is there any other way to handle intents without switch case?
What if I have 100 intents. It will be difficult to manage 100 intents in switch case or in if else

**Comment by CoHealer** [comment]
Closing as answered. @tejasvinishelar, please let us know otherwise.
