### ISSUE TITLE
[ludown] Why is --Version with capital V?

### ISSUE THREAD

**Issue by msimecek** [microsoft/botbuilder-tools#1209]
## Tool
Name: Ludown
Version: 1.3.1
OS: Windows 10 1903

## Describe the bug
The long variant of the global "version" parameter in Ludown is `--Version`. Every CLI tool I have ever encountered uses `--version`. Is there a reason why Ludown went the capital V way? Or is it just a typo?

## To Reproduce
1. run `ludown --version`
2. see error that this argument is unknown
3. run `ludown --Version` 
4. see version

## Expected behavior
The version argument should be all lower-case: `--version`.

## Screenshots
N/A.

## Additional context
https://github.com/microsoft/botbuilder-tools/blob/d9a88572ec3973890035d04c2e3ec77ec8c7859b/packages/Ludown/lib/ludown.js#L35

[bug]

**Comment by sgellock** [comment]
C# engineer not necessarily familiar with what the community has come to expect.  given that we are in the process of moving all the classic CLI tools into a more comprehensive tool, BF-CLI, we won't fix this issue.
