### ISSUE TITLE
"dispatch add" command with missing parameter should prompt for that parameter

### ISSUE THREAD

**Issue by BruceHaley** [Microsoft/botbuilder-tools#121]
The command:
dispatch add -type luis -name v-brhale-luisapp -id 046b01bd-1de4-4a14-a0a4-0d828c749755

Actual behavior: 
Displayed "Missing argument: -key" plus help text, then returned to the command prompt.

Expected: 
Would prompt for the missing parameter, then continue executing.

**Comment by tsuwandy** [comment]
We will address this after //build.
