### ISSUE TITLE
"Dispatch add" command containing a typo gets no error message.

### ISSUE THREAD

**Issue by BruceHaley** [Microsoft/botbuilder-tools#122]
The command:
dispatch add type luis -name v-brhale-luisapp -id 046b01bd-1de4-4a14-a0a4-0d828c749755

The error in the above command: "type" parameter is missing the hyphen ("-").

Actual behavior:
Displayed no message, returned to the command prompt.

Expected behavior:
An error message would be displayed, like "Argument 'type' not recognized."

**Comment by tsuwandy** [comment]
Fixed!
