### ISSUE TITLE
[Adaptive] no need to create luis app if using import

### ISSUE THREAD

**Issue by ToddN** [microsoft/botbuilder-tools#1224]
## Tool
Name: LUBuild
Version: *tool version*
OS: *os version*

## Describe the bug
LUBuild calls createApplication (from processLUVariants). But the luis import() api always creates a new LUIS application.  The parameter that you can pass is the application name, not the application ID.  So calling createApplication actually leaks a LUIS application. 

## To Reproduce
By code inspection

[bug]

**Comment by vishwacsena** [comment]
@ToddN is this resolved per our chat yesterday about import application .vs. import version? If so, can you please close this ticket?
