### ISSUE TITLE
LUDown CLI generates bad URL

### ISSUE THREAD

**Issue by SpaceKatt** [microsoft/botbuilder-tools#1230]
URL in autogenerated output leads to a `404` page.

https://github.com/microsoft/botbuilder-tools/blob/6a4101b962b3da5c2cfea5bdbc7836034d1841dc/packages/Ludown/lib/toLU-helpers.js#L224

URL should be `https://github.com/microsoft/botbuilder-tools/tree/master/packages/Ludown`, instead of `https://github.com/Microsoft/botbuilder-tools/tree/master/Ludown`.

**Comment by sgellock** [comment]
@SpaceKatt thanks for opening the issue.  We'll take a look at it.  I would expect a fix to land in our 4.6 release (oct 31)

**Comment by vishwacsena** [comment]
Closed via #1254
