### ISSUE TITLE
LUIS as node app doesn't find LUIS config settings

### ISSUE THREAD

**Issue by v-geberr** [Microsoft/botbuilder-tools#124]
## Information:
* Tools Libraries:  LUIS (luis apis as npm installed package called from typescript compiled file
* Libraries' Versions:  1.0.26
* OS:  Win 10 
* Node: v8.9.1
* Library installed from NPM

## Issue Description:

Created typescript file that compiles and runs:
several issues:

1) global fetch isn't found when run from node index.js. Worked when I added fetch to \lib\api\serviceBase.js
2) LUIS config settings are not found if using just from node (not command line). I tried a .luisrc as well as environment variables. 
3) is npm test supposed to work with the .luisrc file? I added one but the tests are failing. 

## Commands Example:

```bash

```

## Reproduction Steps:
1.  started with readme for ./LUIS
2. created .luisrc as well as environment variables
3. LUIS config settings are empty by the time fetch is called but I stepped through and it isn't calling the code that looks for env variables

As a side: I was going to submit a PR as a sample to get the npm project running.

**Comment by vishwacsena** [comment]
@Tom can you take a look?

**Comment by v-geberr** [comment]
@vishwacsena @tomlm Would you prefer I submit a PR with the fixes? Or are the issues not showing up when you test?

**Comment by justinwilaby** [comment]
The solution for this is found in the `/bin/luis` file. Since the cli is a node app that consumes the apis as a library, duplicating the global definition of the `fetch` method is preferred. e.g.
somewhere in your node program include this line:
`global.fetch = require('node-fetch');`
