### ISSUE TITLE
Create Dispatch out of Dispatch

### ISSUE THREAD

**Issue by SreekanthOAuth** [microsoft/botbuilder-tools#1246]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Version: *tool version*
OS: *os version*

## To Reproduce
1. ...
2. ...
3. ...
4. ...

## Additional context

[bug]

**Comment by CoHealer** [comment]
Closing as not enough information to even reply to this.

**Comment by SreekanthOAuth** [comment]
> Closing as not enough information to even reply to this.

My Bad, the details not saved. So created another ticket for the same. You can find the link below for that ticket,

https://github.com/microsoft/botbuilder-tools/issues/1248
