### ISSUE TITLE
OrdinalV2 prebuild entity type not supported

### ISSUE THREAD

**Issue by ionut-matei** [microsoft/botbuilder-tools#1258]
## Tool
Name: Ludown
Version: 1.3.2
OS: Windows 10

## Describe the bug
If I have a .lu file which contains an OrdinalV2 entity type, the _ludown parse toluis_ command fails.

## To Reproduce
1. Run the _ludown parse toluis_ command on this .lu file
```text
$PREBUILT: ordinalV2

# Intent
- test
```
2. The output will be
```text
[ERROR] Invalid entity definition for $PREBUILT: ordinalV2
Stopping further processing. 
```

## Expected behavior
Parser needs to support ordinalV2 prebuilt entity type.

**Comment by sgellock** [comment]
@ionut-matei thanks for creating an issue.  We'll work to get this addressed in our 4.6 release.  we are also doing work to add ludown functionality into our new bf-cli
