### ISSUE TITLE
Enable dispatch.json generation without publish

### ISSUE THREAD

**Issue by mattklup** [microsoft/botbuilder-tools#1269]
## Tool
Name: Dispatch

## Describe the problem
`dispatch create` will generate the json file and also deploy to luis.ai in one command.  To better facilitate CI/CD pipelines, we would like the ability to generate the dispatch json file without publish (or any secret credentials like authoringKey).  This file will be used by us as part of the build process to generate code and possibly run some static sanity tests. 

## Describe the solution you'd like
Adding a flag such as '--offline' or '--noPublishToLuisAi' to `dispatch create` that doesn't require any user secrets would be ideal.

**Comment by sgellock** [comment]
@mattklup, thanks for logging the issue.

**Comment by sgellock** [comment]
This is an ask for the team working on the coke scenarios

**Comment by sgellock** [comment]
@cleemullins when Hung-chih gets a build, we'll need to push out updated bits to npm

**Comment by cleemullins** [comment]
The 1.5.2 build of dispatch is published to NPMJS. 

https://www.npmjs.com/package/botdispatch/v/1.5.2

**Comment by sgellock** [comment]
@mattklup the team has published an updated version of botdispatch with the fix you requested.

**Comment by sgellock** [comment]
Reopening as 1.5.2 was mistakenly assumed to contain the change.  the change will be in 1.5.3.

**Comment by hcyang** [comment]
Hi, the said feature requests have been added in Dispatch CLI v1.5.3 and released. Also notified the user this new feature and there is no further complaint. Will close this bug.
