### ISSUE TITLE
[LuisGen] Generating single model for multiple Dispatch files

### ISSUE THREAD

**Issue by Batta32** [microsoft/botbuilder-tools#1279]
## Tool
Name: [LuisGen]

## Describe the problem
We deployed a **Virtual Assistant** and a **Skill** bots of [botframework-solutions](https://github.com/microsoft/botframework-solutions) in two different languages (`en-us`, `es-mx`).
Then, we connected each other using [Botskills CLI Tool](https://www.npmjs.com/package/botskills) which during the [refresh command](https://microsoft.github.io/botframework-solutions/howto/skills/addingskills/#refresh-connected-skills) executes the **LuisGen tool**.
Finally, we reviewed that there was only one model generated containing the dispatch model of the last culture executed.

## Describe the solution you'd like
An unique model generated using LuisGen which appends all the different models.

## Describe alternatives you've considered
Separate each created LuisGen model in different files, however, it would be difficult to identify in run time.

## Additional context
This functionality was tested following the Pull Request microsoft/botframework-solutions#2131 (Multilanguage functionality for `Botskills` CLI Tool).

### Repro steps
1. Deploy a bot with more than one dispatch
1. Execute LuisGen for each of the deployed dispatch
1. Check that the generated model contains the last culture/dispatch executed

_skillManifest.json of the Skill used to connect in en-us and es-mx_
![image](https://user-images.githubusercontent.com/11904023/64176335-9df14700-ce33-11e9-8906-577374cf9210.png)

_Botskills connect command indicating to connect just in en-us_
![image](https://user-images.githubusercontent.com/11904023/64176347-a6498200-ce33-11e9-93ac-1b7b02060c2d.png)

_Model generated after the execution of LUISGen (which took es-mx dispatch as last model)_
![image](https://user-images.githubusercontent.com/11904023/64176364-b19cad80-ce33-11e9-895b-3d2b28bc6394.png)

[enhancement]

**Comment by hcyang** [comment]
Hi @Batta32, we have assigned a developer to look into this issue.

**Comment by axelsrz** [comment]
Hi @Batta32 , we're currently in the develop of a new tool that will replace LuisGen, we'll discuss the viability of the suggested feature for that new tool. Thank you

**Comment by axelsrz** [comment]
@hcyang and @tsuwandy I'm removing the Customer tags given that the person who opened the thread works for an internal supporting team (Southworks)

**Comment by hcyang** [comment]
@axelsrz, any reason we should not close this issue?

**Comment by axelsrz** [comment]
Per talk with @vishwacsena we confirmed that some changes in Luis are necessary before considering taking this feature, I'm closing this issue
