### ISSUE TITLE
QnA using hyperlink text

### ISSUE THREAD

**Issue by kabatmartin123** [microsoft/botbuilder-tools#1280]
## Tool
Name: [|QnAMaker|]

## Describe the problem
i would like to add hyperlinks to the answers in qnamaker
At the moment we are using QnAprompting build with HeroCard

## Describe the solution you'd like
We need to use hyperlinks in answers to navigate students to courses etc 

## Describe alternatives you've considered
don't have one

## Additional context
don't have one
[enhancement]

**Comment by hcyang** [comment]
Hi @kabatmartin123, you can revise the question and answer pairs in your qnamaker model at QnAMaker.ai. In short, you can add a URL in the answers.

**Comment by jwiley84** [comment]
Hi @kabatmartin123!

As @hcyang said, it's possible to manually edit the answers in your knowledgebase to use URLs, using both text and images. You can see the guide for the markdown that QnAMaker uses [here](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/concepts/data-sources-supported#formatting-considerations), but the gist of it that QnAMaker uses simplified markdown, similar to what github uses, for URLS. The text you want the link to show as between [ and ] and the link itself immediately after between ( and ).
