### ISSUE TITLE
Botdispatch: Handling of none intents

### ISSUE THREAD

**Issue by ooorndtski** [microsoft/botbuilder-tools#1284]
## Tool
Name: [Dispatch]
Version: 1.5.3
OS: Windows 10

## Describe the bug
This bug report is nearly the same as [this one](https://github.com/Microsoft/botbuilder-tools/issues/190) from last year. We have several luis apps and created a dispatch model. Now, some of the luis apps contains utterances in their none intents which are also utterances in an intent of another luis app. Say luis app A contains utterance X in its none intent but X is an utterance of an intent "SomeIntent" of luis app B. The dispatch model conatins the utterance X in its none intent and because of that the utterance X is predicted as None instead of "SomeIntent". I would have expected utterance X to not appear in the dispatchers none intent, like suggested by tsuwandy in the bug report linked above.

## Expected behavior
If utterance X occures in any intent that is not the none intent, then X must not occure in the dispatchers none intent.

Maybe I'm doing something wrong, but I tracked this behaviour back to version 1.3.0.

Just one thing: Is there ANY documentation about how exactly the dispatcher tool is working?

**Comment by hcyang** [comment]
Hi @ooorndtski, Dispatch CLI did implement the described logic dedupping None utterances from actual intents. Can you take a look of the generated Dispatch LUIS JSON app and double check if utterance X is in "None" or "SomeIntent?" BTW, even if utterance has been correctly dedupped from the None intent, there is a very small chance it can still get misclassified into None. We have an internal diagnostic tool to explain how exactly an utterance is predicted and/or misclassified. 
It would be great if you can provide us the related LUIS JSON files, so we can do a thorough diagnostics. Let me know if you need to 'r' me. Thanks.

**Comment by hcyang** [comment]
Hi @ooorndtski, you can 'r' me at hunyang@microsoft.com

**Comment by ooorndtski** [comment]
Hi hcynag, thank you for your answer. Utterance X is in the None intent only. 

I've to confess that my explanations of the error are not quite right. I'm sorry. Think I confused myself. ...

The luis app A contains utterance X in SomeIntent and luis app B contains an utterance Y in its None intent that contains X as a substring.

For example luis app A contains "play music" in SomeIntent and B contains "I want to play music" in None. Now the dispatcher put "play music" to intent A (which is the intent representing the luis app A) and "I want to play music" into None. "play music" got a lower score in intent A than "I want to play music" in the None intent. 

Now, the dispatchers prediction of input "play music" is not intent A what I would have expected, but "None", although it is a perfect match in intent A.

There is one more thing that confused me: While creating the dispatch model I used the includedIntents-option to include all intents from my luis apps but the None intents. When using includedIntents and not specifiing "None" i would have expected, that all utterances of the none intents will be completely ignored by the dispatcher.

**Comment by hcyang** [comment]
@ooorndtski, thanks, so the issue is not logic, but quality. For a quality issue, we really need you to share with us the sub apps, so we can repro. One way is to add my email (see my previous post) as a collaborator to your LUIS sub-apps.

'None' is a special intent and the --includedIntents option has no effect over it.
I will discuss this issue with my colleagues.

**Comment by ooorndtski** [comment]
@hcyang Sorry, I can't share the sub apps because of data protection reasons. But I'm very interested in the results of the discussion.

**Comment by tsuwandy** [comment]
@ooorndtski, we'll deploy latest version of Dispatch where it'll not treat None as special intent when --"includedIntents" parameter is specified and we could see if this fixes this issue?

**Comment by ooorndtski** [comment]
@tsuwandy Thank you. I'll try again with the new version.

**Comment by tsuwandy** [comment]
@ooorndtski , will update this thread when it’s deployed.  Thanks!

**Comment by tsuwandy** [comment]
@ooorndtski,  latest dispatch cli is now on npmjs, None should be treated as other intents when “includedIntents” parameter is used.  Let us know if you are seeing what’s expected or otherwise.  Thank you!
