### ISSUE TITLE
[ludown] Dup roles are founded for .json file generated by ludown

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-tools#1295]
## Tool
Ludown
Version: *tool version*
OS: *os version*

ludown version: 1.3.3

How to repro:
1.  ludown refresh Calendar.json
[Calendar.json.txt](https://github.com/microsoft/botframework-cli/files/3634488/Calendar.json.txt)
Calendar.json is a luis with role export from luis.ai. 

2. ludown parse ToLuis --in Calendar.lu

Here is the generated lu file from step 1:
[Calendar1.lu.txt](https://github.com/microsoft/botframework-cli/files/3634499/Calendar1.lu.txt)

Here is the json file from the lu file, you can see dup roles are generated:
[Calendar1.json.txt](https://github.com/microsoft/botframework-cli/files/3634498/Calendar1.json.txt)
![image](https://user-images.githubusercontent.com/16643193/65304655-c4dda600-dbb3-11e9-98f1-e7d2bb2dd5fd.png)

**Comment by DingmaomaoBJTU** [comment]
This is a blocking issue for composer to use luis with roles.

**Comment by vishwacsena** [comment]
Fixed via #1251
