### ISSUE TITLE
Dispatch refresh doesn't add the multi turn questions

### ISSUE THREAD

**Issue by muminasaad** [microsoft/botbuilder-tools#1300]
## Tool
Name: Dispatch
Version: 1.5.1
OS: Windows 10

## To Reproduce
1. Create QNA Maker Cognitive model
2. Add question with multi turn
3. Create Luis Cognitive model
4. Run the dispatch refresh command
5. Test the multi turn question 

## Expected behavior
To have multi turn question to return q_faq.

## Screenshots
dispatch returns l_general

[bug]

**Comment by dmvtech** [comment]
Able to reproduce behavior. My assumption is this is because multi turn is relatively new and hasn't been added to dispatch functionality (assuming it can). 

I'll check for more info.

**Comment by dmvtech** [comment]
Also, doesn't add the questions in `dispatch create` either.

**Comment by tsuwandy** [comment]
We have the update ready and planning on deploying today or tomorrow at the latest.

**Comment by vishwacsena** [comment]
We've added support for this via a --includePrompts flag that you can pass while adding QnA KB. 

See `dispatch add -h` for more information.

**Comment by muminasaad** [comment]
It is not working on Bot file, and working on Dispatch File

"includePrompts": true

please add support to bot file

**Comment by tsuwandy** [comment]
@muminasaad, unfortunately we no longer support any changes msbot (and thus changes to its schema).  IncludePrompts is dispatch specific schema/option.  For refresh,  if you have .dispatch file, bot file is not required.   You could modify the qna maker kb element in the .dispatch file and add “includePrompts” : true.  The dispatch is now set for subsequent refreshes.  

Let me know if you need more info.  Thanks!

**Comment by muminasaad** [comment]
@tsuwandy 
Thanks for your response.
While working with bot framework the bot schema file is somewhat important to test the bot, save the configuration for other non-developer testing.
And having for each tool a file is too much to maintain, can you provide the reason to drop the bot file ?

**Comment by tsuwandy** [comment]
@muminasaad, it’s not dropped yet, Dispatch still supports it as of now.  Unfortunately, we no longer update the bot schema.  Once .dispatch file is created, there is really no reason to use .bot file with Dispatch cli.   Is there a way not use .bot file as it’s deprecated.  Thanks!
