### ISSUE TITLE
Dispatch tool IncludePrompts doesn't work on bot file

### ISSUE THREAD

**Issue by muminasaad** [microsoft/botbuilder-tools#1307]
#1300  Tool
Name: Dispatch
Version: 1.5.5
OS: Windows 10

## Describe the bug
Dispatch command new option IncludePrompts is not working when refresh using bot file

## To Reproduce
Prerequisite:
Bot file.
QnA with multiturn

1- Add "IncludePrompts": true to bot file.
2- Run Dispatch command
3- Check the Dispatch Luis.

## Expected behavior
Prompts to be added to the q_faq (or any name) in the dispatch

## Actual behavior
Prompts will not be added

[bug]

**Comment by tsuwandy** [comment]
@muminasaad, continuing our discussion from https://github.com/microsoft/botbuilder-tools/issues/1300, is there a way you use .dispatch file instead?

**Comment by muminasaad** [comment]
@tsuwandy yes there is a way to use the dispatch file.

I still prefer having the bot file supported as the Bot Emulator Accepts the Bot File and having a new file for each environment we have on each project we deliver is too much for us but again we well endure if you will not support it  for future usages

**Comment by muminasaad** [comment]
@tsuwandy as per our discussion I will close the bug due to your response that the bot file is obsolete and deprecated in dispatch utility.
