### ISSUE TITLE
dispatch init fails when targeting usgovvirginia

### ISSUE THREAD

**Issue by managedcoder** [microsoft/botbuilder-tools#1311]
## Tool
Name: Dispatch
Version: 1.5.3
OS: Windows

## Describe the bug
I've been whitelisted into QnA Maker in Azure Government which now allows me to attempt to use the Virtual Assistant Template in Azure Government.  The deploy_congnitive_models.ps1 script from that template calls:

`dispatch init --name <dispatch name> --luisAuthoringKey <key> --luisAuthoringRegion <gov region> --dataFolder <folder>`

This call hangs when passed `--luisAuthoringRegion usgovvirginia` and the error in deploy_cognitive_models_log.txt says, "Invalid region"

## To Reproduce
1. From PowerShell 6 command line, connect to Azure Government by entering:
`az cloud set --name AzureUSGovernment`
2. Login in to your Azure Gov subscription using your Azure Gov user account:
`az login`
3. run the dispatch command  by entering:
`dispatch init --name <dispatch name> --luisAuthoringKey <key> --luisAuthoringRegion usgovvirginia --dataFolder <folder>`

## Expected behavior
The command should complete without hanging or reporting "Invalid region" in log

## Additional context

[bug]

**Comment by tsuwandy** [comment]
@managedcoder, for gov, one would need to use "--gov true" parameter.  Let me know if you are still having troubles getting it to work with the gov parameter.

**Comment by managedcoder** [comment]
Thanks so much!  That did the trick and `dispatch init` now completes successfully

**Comment by tsuwandy** [comment]
@managedcoder, thanks!

**Comment by stevengum** [comment]
@tsuwandy can you or someone familiar with the tool update dispatch's readme with the --gov flag and any other new flags?
