### ISSUE TITLE
Dispatch refresh for LUIS and QnA

### ISSUE THREAD

**Issue by SreekanthOAuth** [microsoft/botbuilder-tools#1312]
## Tool
Name: Dispatch
Version: *1.5.3*
OS: *Windows 10*

## Describe the bug
When I run this command **dispatch refresh --dispatch** it's not refreshing the QnA models. Based on document also it says the same. Seems we need to run the refresh with --bot to update both QnA and LUIS.

## To Reproduce
1. Create Dispatch LUIS model
2. Create LUIS model
3. Create QnA model
4. Add both to Dispatch
5. Try to refresh the dispatch by --dispatch file.

## Expected behavior
Need a sample .bot file to run the dispatch refresh --bot command.
And need details on how does this refreshing the LUIS and QnA models under dispatch with that intent name. Because by seeing the information in below link, I don't find a way to differentiate between Dispatch LUIS and just LUIS. And also don't find to way to give intent name for those LUIS or QnAs.
 
## Additional context

[bug]

**Comment by dmvtech** [comment]
Hi @SreekanthOAuth 

To be clear; are you saying that after running `dispatch refresh --dispatch <filename.dispatch>`, the QnA knowledgebase is not being updated? Or is it not updating the *.qna file?

It _should_ be updating the q_**kbname** LUIS intent in the LUIS dispatch app.

**Comment by SreekanthOAuth** [comment]
Hi @dmvtech - Yes, the QnA KBs are not being updated.

Yes, q_[name]/l_[name] is getting added to the dispatcher when you try to create the QnA and LUIS apps first time. 

Problem is when you have some updates in QnA KBs, and try to refresh the dispatch.

Thanks,
Sreekanth

**Comment by dmvtech** [comment]
I'm unable to reproduce the issue. I have it successfully refreshing the dispatch model when adding a qna pair to qna KB. 

I am running version 1.5.4. Can you update your version and try again?

**Comment by CoHealer** [comment]
@SreekanthOAuth, do you still require assistance?

**Comment by dmvtech** [comment]
Closing as haven't heard back. If this issue persists on version 1.5.4, please let me know and reopen the issue.
