### ISSUE TITLE
Add Application information in LuDown as Library

### ISSUE THREAD

**Issue by Hatzman91** [microsoft/botbuilder-tools#1321]
## Tool
Name: Ludown as Library
Version: 1.3.3

## Describe the bug
I created an Azure Function for generating a json for Luis with ludown, now I wanted to upload that Json as new Version but then I noticed that I still needed some Application information.
I just might be to stupid, but i didn't find a way to add the same variables as with the normal command tool.

so in order to really use it I need a possibility to add those
```
  "luis_schema_version": "3.0.0",
  "versionId": "0.1",
  "name": "mybotname",
  "culture": "de-de",
  "tokenizerVersion": "1.0.2"
```

in this call
```
ludown.parser.parseFile(luFile, false, "de-de")
    .then(function(parsedContent) {
      context.bindings.luisJson = parsedContent.LUISJsonStructure;
      context.bindings.qnaJson = parsedContent.qnaJsonStructure;
      context.done();
    })
```

## Expected
I excpect to have the same possibilities from the command tool in the library version.

**Comment by cleemullins** [comment]
@Hatzman91, thanks for reporting this. 

The *new* version of this library, found in the [bf-cli](https://github.com/microsoft/botframework-cli/tree/master/packages/luis) repo, supports this. That version will be released as part of the 4.6 cycle (Oct 31). 

That version has evolved quite a bit from this one, and one of the core design tenants of the new library is that it's suitable for use as a stand-alone package. We've not tested it in Azure Functions but we are consuming it from other platforms.
