### ISSUE TITLE
marina-ana2011@mail.ru

### ISSUE THREAD

**Issue by marinaannak** [microsoft/botbuilder-tools#1327]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Version: *tool version*
OS: *os version*

## To Reproduce
1. ...
2. ...
3. ...
4. ...

## Additional context

[bug]

Mk

**Comment by jwiley84** [comment]
Closing this issue, as there are 0 details as to what may be a problem and is possibly an accidental posting. If you are having issues with any of the botbuilder tools, please reopen and fill out the template with the appropriate details.
