### ISSUE TITLE
Ignoring QnA Maker multi-turn child utterances

### ISSUE THREAD

**Issue by RenanCarso** [microsoft/botbuilder-tools#1333]
## Tool
Name: Dispatch
Version: 1.5.6
OS: Win

## Describe the bug
It is only generating utterances for QnA Maker multi-turn parent utterances and ignoring the child ones.

## To Reproduce
1. Create a QnA KB with multiturn utterances.
2. Publish KB
3. run the command 'dispatch create' with the KB related
4. check the *.json file over utterances and will see that only parent QnA utterances were considered.

## Expected behavior
Consider the child utterances.

## Additional context
On the test over QnaMaker.ai is available interactions starting with a child utterance.

[bug]

**Comment by johnataylor** [comment]
@trojengui can you take a look at this

**Comment by stevkan** [comment]
@RenanCarso, a couple questions for you:

1) Are you training and publishing your KB?
2) Are you running `dispatch add` before `dispatch create`?
3) Are you looking at the right .json file?

When I test this (with regards to QnA), I use the following commands and parameters. I then end up with a `_Q_distribution.json` file (based on my QnA kb of the same name) and an `nlp-dispatch.json` file. The "distribution" file contains the prompt(s) - the "displayText" represents the actual prompt; "questions" represents what the prompt is referencing; and, the "answer" is the returned value when the prompt is selected.

```
> dispatch add -t qna -i 6932XXXX-XXXX-XXXX-XXXX-XXXXXXXXb55a -n distribution -k 5b94XXXXXXXXXXXXXXXXXXXXXXXX4abf

> dispatch create
```

**Test** - QnAmaker.ai:

![image](https://user-images.githubusercontent.com/18403946/67726946-ca918d00-f9a4-11e9-93d7-cc9b43060222.png)

**_Q_distribution.json**:

![image](https://user-images.githubusercontent.com/18403946/67726977-e301a780-f9a4-11e9-91cc-28d10b5ce19d.png)

**Comment by stevkan** [comment]
Closing due to a lack of activity. Please feel free to reopen if the issue persists. Review the above responses and post any new information.

**Comment by RenanCarso** [comment]
@stevkan, I'm really sorry for late response. Now I'll have proper time for caring this subject.

I've double checked all steps you suggested and no child multiturn utterances.

Actually, I tried the @tsuwandy suggestion and didn't worked as well.

If I check the data\_Q_*.json, it is exactly as you related, with all the multiturn utterances, parent and child.

But if I check json file on the root folder, which is outside the data folder, you will see no child multiturn utterance. This json file reflects exactly the Luis KB created with dispatch process.

Commands that I'm running in order:

> dispatch init -n DispatchKBPT --luisAuthoringKey "8892XXXXXXXXXXXXXXXXX836c" --luisAuthoringRegion westus
> 
> dispatch add -t luis -i 9a16XXXXXXXXXXXXXXXXXXXXX9ae3 -n "LuisKBase" -v 0.2 -k 8892XXXXXXXXXXXXXXXXX836c
> 
> dispatch add -t qna -i 532bXXXXXXXXXXXXXXXXXXXXX8919 -n QnaPersonalityPT -k 0cf7XXXXXXXXXXXXXXXXXXXX67cd
> 
> 
> dispatch add -t qna -i 4ddbXXXXXXXXXXXXXXXXXXXXXXXXXXXX66e0 -n QnaPT -k 0cf7XXXXXXXXXXXXXXXXXXXX67cd --includePrompts true

Worth mention points:

- there is also 1 Luis KB on this dispatch

- my bot is in pt-BR

**Comment by RenanCarso** [comment]
@stevkan could you please reopen this issue?

**Comment by tsuwandy** [comment]
@RenanCarso, would you mind sharing your .dispatch file to tien.suwandy@microsoft.com so I could investigate?  Thanks!

**Comment by RenanCarso** [comment]
Just sent it.

**Comment by tsuwandy** [comment]
Thanks Renan, taking a look.

**Comment by tsuwandy** [comment]
@RenanCarso, try starting a clean dispatch (in a different folder), and run these commands again:

dispatch init -n DispatchKBPT --luisAuthoringKey "8892XXXXXXXXXXXXXXXXX836c" --luisAuthoringRegion westus
dispatch add -t qna -i 4ddbXXXXXXXXXXXXXXXXXXXXXXXXXXXX66e0 -n QnaPT -k 0cf7XXXXXXXXXXXXXXXXXXXX67cd --includePrompts true

Check the updated .dispatch file.  Make sure the services element looks like the following (note the "includePrompts": true property for the QnaPT kb):

"services": [
    {
      "includePrompts": true,
      "kbId": "4ddb36b3-e93d-4f16-b7c1-53ecb38566e0",
      "subscriptionKey": "0cf7c2f1e345472cb4062cc3f2be67cd",
      "type": "qna",
      "name": "QnaPT",
      "id": "1"
    }
  ],

Add the other sources (might worth checking the .dispatch file just to make sure the QnaPT still has the "includePrompts" property).  Run the "dispatch create" command and check the resulting json or check the dispatch app on LUIS portal and see if the prompts are part of the utterances for the kb intent.

**Comment by danielt113** [comment]
I am having a very similar issue. When I use "includePrompts", it includes ones with **context-only** enabled. We have many prompts that are simply "Yes" or "No" and dispatch can't detect the intent for those.

Is there an option to ignore prompts with the **context-only** flag?

**Comment by tsuwandy** [comment]
@danielt113, we were not aware of **context-only** flag, thanks for bringing this up.  It makes complete sense to update Dispatch to ignore these prompts.  Will update this thread once I take a look and update the cli.

**Comment by tsuwandy** [comment]
@danielt113, latest dispatch is published.  It’ll now ignore prompts with isContextOnly for QnA kb added with “—includePrompts true”

**Comment by tsuwandy** [comment]
closing th
