### ISSUE TITLE
[Docs] Given recent changes, LU files dont' represent both QnA & LUIS

### ISSUE THREAD

**Issue by jameslew** [microsoft/botbuilder-tools#1339]
The readme for .LU files indicates that it supports both LUIS & QNA via LuDown.  That may need to be updated as I understand it for recent changes.

**Comment by scheyal** [comment]
I believe bf qnamaker does support .LU file format conversion. @vishwacsena should confirm.

**Comment by vishwacsena** [comment]
@jameslew - I presume you are looking for a doc update for LU format deep-link from composer? Can you confirm?

**Comment by Kaiqb** [comment]
@jameslew - can you confirm?

**Comment by jameslew** [comment]
I was told that there were now two files, an LU file and a QnA file of some sort, and that they were different.  I may be misinformed on that point, but if I'm not, this document indicated the one file format was supporting both services.

**Comment by vishwacsena** [comment]
There now are two separate documents that cover the [LU](https://github.com/microsoft/botframework-cli/blob/master/packages/lu/docs/lu-file-format.md) and [QnA](https://github.com/microsoft/botframework-cli/blob/master/packages/lu/docs/qna-file-format.md) file formats.
