### ISSUE TITLE
Luis tool does not support Get/Set publish settings

### ISSUE THREAD

**Issue by DingmaomaoBJTU** [microsoft/botbuilder-tools#1340]
## Tool
Name: LUIS
Version: 2.6.2
OS: *os version*

## Describe the bug
Luis tool does not support Get/Set publishsettings, which declared here:
https://github.com/microsoft/botbuilder-tools/blob/278155eb71a58c8367b912593feacc60387d5395/packages/LUIS/src/operations/apps.ts
Line 439

References should be added here also:
https://github.com/microsoft/botbuilder-tools/blob/c74b7e210e06d166a042ad04c2a1bbab69e1261a/packages/LUIS/bin/operations.json

otherwise, the following api won't work with luis tool:
https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5ae32174d5b81c02cc64c6d3

**Comment by cleemullins** [comment]
We are rewriting the LUIS API tool in our R7 release. This will be done as part of the [BF CLI](https://github.com/Microsoft/botframework-cli). 

This work is being done against the following spec:
https://github.com/microsoft/botframework-cli/blob/master/specs/LUIS-CLI-IN-BF.md

*INCLUDED* in that spec is the get publish settings. Suggestions for additional scenarios should be created as issues in that repo, referencing that spec.

**Comment by axelsrz** [comment]
This is coming soon in the new version of the tool, if you feel there is an issue with the spec please open an issue in the respecting repository.
