### ISSUE TITLE
Dispatch Refresh terminates with Object Reference not set error

### ISSUE THREAD

**Issue by singzzz** [microsoft/botbuilder-tools#1354]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Version: 1.5.8
OS: macOS Mojave

## Describe the bug
dispatch refresh command does not complete, terminates at the republish stage with Object Reference error
 
## To Reproduce
run the dispatch refresh command

## Expected behavior
Refresh completes and dispatch models update

## Screenshots
dispatch refresh --luisSubscriptionKey ** --luisSubscriptionRegion westeurope
Exporting services for dispatch...
etc...
Creating dispatch LUIS model json...
Creating training data...
WARNING: Number of samples in '***/model_001/train.txt' that were used by multiple categories: 60
WARNING: very few samples (breaking-point for debugging purpose), foldSize=0.2, foldsCount=5, Samples.Length=1, category=None, TrainingSamplesCount=1, TestingSamplesCount=0
etc...
Training LUIS_1...
Training LUIS_2...
etc...
Importing dispatch model...
Setting up intents to child services mapping for dispatch...
Add subscription key and publish child LUIS apps...
Publishing LUIS_1 model...

ERROR
Object reference not set to an instance of an object.

------
REFRESH
Usage: dispatch refresh [options]

Retrain and republish existing LUIS dispatch application after modifications. Dispatch application id will be unchanged.

## Additional context

[bug]

**Comment by EdwinOtten** [comment]
I am having the same issue on botdispatch `1.5.8`. When it starts publishing the first child model, the error is thrown.

**Comment by aishwaryaumachandran** [comment]
I'm facing the same issue as well. When it tries publishing the first child model

**Comment by anusharavindrar** [comment]
Assigning the issue to @tsuwandy. The issue is similar to the dispatch eval error.

**Comment by tsuwandy** [comment]
@EdwinOtten, @aishwaryaumachandran, something changed with LUIS publishing API.  I'm not sure yet why but publish now starts throwing error.  However, LUIS dispatch app is created and published to LUIS so please ignore the error for now.  Investigating the error at the moment, thanks!

**Comment by tsuwandy** [comment]
Quick update.  I contacted LUIS team and they are working on mitigating the issue at the moment.

**Comment by tsuwandy** [comment]
@EdwinOtten, @aishwaryaumachandran, I have confirmed that this issue is now mitigated.  Please let me know otherwise.
