### ISSUE TITLE
Chatdown: Fix deprecation message

### ISSUE THREAD

**Issue by scheyal** [microsoft/botbuilder-tools#1368]
Old Message:
`WARNING:  chatdown is deprecated.  For more information refer to https://aka.ms/botframework-cli.`

New Message:
`WARNING:  chatdown is deprecated.  For more information refer to https://aka.ms/bfcli`

**Comment by gabog** [comment]
Hi @scheyal, are you driving this one to closure? Any updates

**Comment by scheyal** [comment]
@munozemilio - Can you please update chatdown asap for R7?
