### ISSUE TITLE
dispatch test not work

### ISSUE THREAD

**Issue by xhr0804** [microsoft/botbuilder-tools#1377]
## Tool
Name: Dispatch
Version: 1.6.1
OS: win10

## Describe the bug
Can't run the test successfully, while the Dispatch eval works ok.
![image](https://user-images.githubusercontent.com/44257569/69127839-03291000-0ae6-11ea-9bb6-e4c68ed6f0a1.png)

## To Reproduce
1. ...
2. ...
3. ...
4. ...

## Additional context

[bug]

**Comment by tsuwandy** [comment]
@xhr0804, what version of Dispatch do you have?  I just ran the test command and it was working fine for me.  Thanks!

**Comment by tsuwandy** [comment]
@xhr0804, would you mind sharing your .dispatch and the test files to tien.suwandy@microsoft.com/hunyang@microsoft.com?  Thanks!

**Comment by xhr0804** [comment]
@tsuwandy , I've tried this again this morning without any changes, It turns to be OK now. Didn't know which part went wrong yesterday.  Anyway, Thanks for reply.

**Comment by tsuwandy** [comment]
@xhr0804, thanks for the update.  LUIS server could have been down at the time.
