### ISSUE TITLE
Dispatch Luis Model is erroring out with an "the operation has timed out" message when trying to add in a luis model to the dispatch

### ISSUE THREAD

**Issue by xtianus79** [microsoft/botbuilder-tools#1383]
## Tool
Name: Dispatch
Version: botdispatch@1.6.2
OS: MacOs

## Describe the bug
When trying to import in a luis model upon exporting a particular luis app model it gives a time out error. 

```javascript
ERROR
One or more errors occurred. (The operation has timed out.)

****UNHANDLED EXCEPTION****
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Fuse.Core.Command.ConsoleApp.HandleWebError(WebException we) in D:\a\1\s\oss\core\Command\ConsoleApp.cs:line 285
   at Microsoft.Fuse.Core.Command.ConsoleApp.HandleError(Exception ex) in D:\a\1\s\oss\core\Command\ConsoleApp.cs:line 243
   at Microsoft.Fuse.Core.Command.ConsoleApp.Eval(String[] input) in D:\a\1\s\oss\core\Command\ConsoleApp.cs:line 167
   at Microsoft.Fuse.Core.Command.ConsoleApp.Run(String[] input) in D:\a\1\s\oss\core\Command\ConsoleApp.cs:line 129
   at Microsoft.Fuse.Dispatch.DispatchConsole.Main(String[] args) in D:\a\1\s\oss\Dispatch\Program.cs:line 51
```

## To Reproduce
1. dispatch create

## Expected behavior
to work

## Additional context

[bug]

**Comment by xtianus79** [comment]
I've done a testing where I scaled back the limit on the amount of intents which right now is 386 intents with underlying entities to 5 intents and that works.  So I am wondering what the limitations are exactly on the dispatcher.

**Comment by tsuwandy** [comment]
@xtianus79, the as dispatch app is a LUIS app, the limit is the same as LUIS limit here:  https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-boundaries#model-boundaries

Did you try to create a dispatch with 386 child LUIS apps?  Or a dispatch with one child LUIS app with 386 intents (and other LUIS app and/or QnA kb)?  If the 2nd, it should work.  

Could you share your .dispatch file (you could remove the keys) and the LUIS/Qna kb json files (you could fine them in dispatch folders (_L_<LUISName>.json or _Q_<QnAKBName>.json)?  Feel free to email tien.suwandy@microsoft.com.  Thanks.

**Comment by xtianus79** [comment]
Hi @tsuwandy I am going to try this for your but to be honest I think the very error is the fact that you can't create those json files.  that is the point where it times out if that helps.

**Comment by xtianus79** [comment]
in fact what i will do is email you the split and then I will email you what the full one is if I can get that json

**Comment by xtianus79** [comment]
@tsuwandy Hi! So I sent you an email giving you the split model of the 3 luis files and sent another follow up email with the dispatch file.  

When i try and run the single model those files don't even create... only the first original model creates and the other combined luis model we have that is not split doesn't even create anything else in that data directory.  this is where the error occurs and times out.

**Comment by tsuwandy** [comment]
@xtianus, I was able to create a dispatch with the 3 LUIS files and a modified dispatch file (from what you sent).   I attached the final dispatch json file in the email. 

If you have similar output as the following, that'll be helpful for me to diagnose where it errors out on your side.  Thanks!  

Exporting services for dispatch...
Creating dispatch LUIS model json...
Creating training data...
WARNING: Number of utterances in 'D:\src\EmbedML\Data\Test\RCCL\data\_experiments\model_001\train.txt' that were used by multiple intents: 2
WARNING: very few samples (breaking-point for debugging purpose), foldSize=0.8, foldsCount=5, Samples.Length=4, category=None, TrainingSamplesCount=3, TestingSamplesCount=1
WARNING: Number of utterances in 'D:\src\EmbedML\Data\Test\RCCL\data\_experiments\model_001\cv5\fold001\train.txt' that were used by multiple intents: 1
WARNING: Number of utterances in 'D:\src\EmbedML\Data\Test\RCCL\data\_experiments\model_001\cv5\fold002\train.txt' that were used by multiple intents: 1
WARNING: Number of utterances in 'D:\src\EmbedML\Data\Test\RCCL\data\_experiments\model_001\cv5\fold003\train.txt' that were used by multiple intents: 2
WARNING: Number of utterances in 'D:\src\EmbedML\Data\Test\RCCL\data\_experiments\model_001\cv5\fold004\train.txt' that were used by multiple intents: 2
Updating rccl_dispatch model...
Importing rccl_dispatch model...
Setting up intents to child services mapping for rccl_dispatch...
Add subscription key and publish child LUIS apps...
Training rccl_dispatch model...
Adding LUIS subscription key to rccl_dispatch...
Publishing rccl_dispatch model...
Writing summary file ('test_prediction')...
{
  "authoringRegion": "westus",
  "subscriptionRegion": "westus2",
  "hierarchical": true,
  "useAllTrainingData": false,
  "dontReviseUtterance": false,
  "copyLuisData": true,
  "normalizeDiacritics": true,
  "services": [
    {
      "intentName": "l_RoyalAgent",
      "path": ".\\_L_RoyalAgent.json",
      "type": "file",
      "name": "_L_RoyalAgent",
      "id": "1"
    },
    {
      "intentName": "l_RoyalQnA1",
      "path": ".\\_L_RoyalQnA1.json",
      "type": "file",
      "name": "_L_RoyalQnA1",
      "id": "2"
    },
    {
      "intentName": "l_RoyalQnA2",
      "path": ".\\_L_RoyalQnA2.json",
      "type": "file",
      "name": "_L_RoyalQnA2",
      "id": "3"
    }
  ],
  "serviceIds": [
    "1",
    "2",
    "3"
  ],
  "appId": "5f1f69dc-852a-4c1f-b3a2-c43489408d87",
  "authoringKey": "4db5bf288edd4945822aeb124c59d8a5",
  "subscriptionKey": "dad5deec52ac4f19b36c1d8d66af8fec",
  "version": "Dispatch",
  "region": "westus",
  "type": "dispatch",
  "name": "rccl_dispatch"
}
Please review your dispatch model in D:\src\EmbedML\Data\Test\RCCL\Summary.html

**Comment by xtianus79** [comment]
@tsuwandy Hi, I believe you sent an email you had recreated the issue.  Just following up here

**Comment by tsuwandy** [comment]
@xtianus79, it’ll be published today.

**Comment by xtianus79** [comment]
@tsuwandy Works perfect!!! thank you
