### ISSUE TITLE
Dispatch test won't recognize "canadacentral" region

### ISSUE THREAD

**Issue by danielt113** [microsoft/botbuilder-tools#1384]
## Tool
Name: Dispatch
Version: 1.6.2
OS: Windows 10

## Describe the bug
After running "dispatch test", I am prompted for a region. When I type canadacentral it says "Invalid region".

## To Reproduce
1. Run dispatch test on a LUIS model on a canadacentral prediction endpoint
2. When prompted for a region type canadacentral

## Expected behavior
canadacentral should be accepted as a valid region. My prediction endpoint is https://canadacentral.api.cognitive.microsoft.com/luis/v2.0/apps/...

## Additional context
Below is the terminal output, notice how canadacentral is not suggested.

- PS C:\Users\****\Desktop\dispatch\eng> dispatch test --testFilePath C:\Users\****\Desktop\dispatch\eng\dispatch_test.txt --luisSubscriptionKey *****
- LUIS Cognitive Service information is needed to do model evaluation
- 
- What's your LUIS Cognitive Service region [westus, westus2, eastus, eastus2, westcentralus, southcentralus, westeurope, northeurope, southeastasia, eastasia, australiaeast, brazilsouth]:
- canadacentral
- Invalid region

[bug]

**Comment by dmvtech** [comment]
@danielt113 In this case, you need to use `westus `as the authoring region. The authoring region for LUIS isn't available in `canadacentral` (although the publishing/query region is).

See here for more info:
https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-regions#other-publishing-regions

**Comment by danielt113** [comment]
I can't retest it just yet however I'm confused, doesn't dispatch test use the prediction endpoint? Our authoring is on westus but prediction is canadacentral.

**Comment by dmvtech** [comment]
I'm not quite sure. I'll see if I can confirm. Test might go against authoring as well. When you run dispatch add for LUIS resources, you specify the authoring key/region. 

Does your .dispatch file have entries for _all three_ of these (westus is my .dispatch example):

```
  "authoringRegion": "westus",
  "subscriptionRegion": "westus",
  "region": "westus",
```

What are they set to?

**Comment by tsuwandy** [comment]
@danielt113, looks like Dispatch cli is not yet aware of the canada central region for runtime.  Workaround for this would be updating cli settings file where botdispatch is installed. If installed globally, it's in %appdata%\npm\node_modules\botdispatch\bin\netcoreapp2.1\appsettings.json.

Add canadacentral to SubscriptionRegions property in the file and save.

"SubscriptionRegions": [
    "westus",
    "westus2",
    "eastus",
    "eastus2",
    "westcentralus",
    "southcentralus",
    "westeurope",
    "northeurope",
    "southeastasia",
    "eastasia",
    "australiaeast",
    "brazilsouth"
  ],

test command should recognize the region after.  I'll update the settings file for the cli and will deploy an update.  In the meanwhile, you should be unblocked by updating the appsettings.json file.  Let us know if you were not able to proceed after updating the settings file.  Thanks!

**Comment by tsuwandy** [comment]
@danielt113, latest dispatch is published and it should now recognize the latest regions.
