### ISSUE TITLE
Getting error while exporting from remote to local

### ISSUE THREAD

**Issue by SreekanthOAuth** [microsoft/botbuilder-tools#1388]
## Tool
Name: QnAMaker
Version: *1.3.2*
OS: *Windows 10*

## Describe the bug
Today, while trying export command getting below error,

`Sorry, unable to parse stdin as JSON!

 {}

Stopping further processing.`

## To Reproduce
1. Create QnA Model
2. Export Sample Assistant from [here](https://github.com/microsoft/botframework-solutions/tree/master/templates/Virtual-Assistant-Template/typescript/samples/sample-assistant)
3. And update cognitive models with KB model
4. Run the update_cognitive_models.ps1

## Expected behavior
Should export the .lu file.

## Additional context

[bug]

**Comment by dmvtech** [comment]
I'm seeing if I can reproduce this issue. I'll let you know if I have any questions.

**Comment by dmvtech** [comment]
I believe this is related to https://github.com/microsoft/botframework-solutions/issues/2689

**Comment by SreekanthOAuth** [comment]
@dmvtech , Tried based on the above link and now getting below exception,

Sorry, error parsing file as QnA JSON: D:\Test-Chatbot\test-new\test\src\virtualAssistant\deployment\scripts\..\resources\QnA\en\myskill.qna
Stopping further processing.

Could you please look into it.

Thanks,
Sreekanth

**Comment by darrenj** [comment]
I believe this might be related to a recent change in qnamaker CLI around the deprecated message. To prove this could you install 1.3.1 directly and see if you can repro please?

`npm install qnamaker@1.3.1`

**Comment by darrenj** [comment]
I have reproed the issue with qnamaker@1.3.2, regressing to @1.3.1 resolved the issue for me.

**Comment by a-b-r-o-w-n** [comment]
@SreekanthOAuth `qnamaker@1.3.3` was released on Friday which we believe fixes this issue. Can you please try that version and let us know if the issue is fixed? If not, please re-open this issue.

**Comment by SreekanthOAuth** [comment]
@a-b-r-o-w-n , thanks for the update and will let you know if we see any issues.
