### ISSUE TITLE
Ludown After upgrading to 1.4 parse ToLuis errors on apostrophe (' and  ’) and other characters

### ISSUE THREAD

**Issue by saroup** [microsoft/botbuilder-tools#1392]
## Tool
Name: LuDown
Version: 1.4
OS: Windows10

## Describe the bug
After upgrading to 1.4 and running  > ludown parse ToLuis command errors out on apostrophe.

## To Reproduce
1. have a client_info.lu that has
# fetch_client_info
-Is Macy's Inc a public company?.
2. run ludown parse ToLuis

result : token recognition error at: '’'

## Expected behavior
I would expect this to be compatible with 1.3 and not error out 

[bug]

**Comment by tsuwandy** [comment]
@saroup, could you use BF instead as LuDown has been deprecated?  More info here: https://github.com/microsoft/botframework-cli/blob/master/PortingMap.md
