### ISSUE TITLE
Dispatch Refresh created

### ISSUE THREAD

**Issue by dkonyayev** [microsoft/botbuilder-tools#1395]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Version: Latest
OS: Windows 10

## Describe the bug
WE have been using dispatch refresh to keep our dispatch app up to date. In the last few  days we observed that every time we run dispatch refresh the applicaton is dropped and recreated with new App ID. It also drops our Azure prediction resource.

The only thing that changed in the last few days is that we upgraded to using Azure Resources as per link on luis.ai

## To Reproduce
1. Do dispatch refresh dispatch application. Note App ID on luis.ai
2. Do dispatch refresh again. Note that App ID changed on luis.ai

## Expected behavior
App ID should stay the same as application is refreshed, not created.

## Additional context

[bug]

**Comment by srinaath** [comment]
@tsuwandy Can you take a look at this ticket?

**Comment by tsuwandy** [comment]
@dkonyayev, I couldn't repro with dispatch -v 1.6.3.   After refresh, the dispatch app still have the same app id.  

Could you try accessing the app page (something like https://www.luis.ai/applications/33cb82a3-6778-4fba-a737-430e8ed2b88c/versions/Dispatch/dashboard), run "dispatch refresh", then back to the browser and refresh the page.  Does it show the same app with updated published date?

**Comment by dkonyayev** [comment]
@tsuwandy See attached screenshots with my script and script output.
[dispatch process.docx](https://github.com/microsoft/botbuilder-tools/files/4040696/dispatch.process.docx)

**Comment by tsuwandy** [comment]
@dkonyayev, thanks for the screenshot!  I see what the problem is.  If you only want to refresh, you shouldn't need to do "dispatch init" command as everything is already in the .dispatch file in the working folder.   In your specific case, you simply want to add another intent to the Dispatch app by (by adding sub LUIS model), so just do "dispatch add", then "dispatch refresh".  "dispatch init" recreates the dispatch config (dispatch app id is in it) and this explains the app id changing.

Let me know if you need more info.   Thanks!

**Comment by dkonyayev** [comment]
@tsuwandy So if sub-Luis has changed do I still need to do "dispatch add" to extract most recent changes from sub-luis?

Which actually brings me to another question - once dispatch is created should we maintain the intents in teh dispatch itself or should we continue to maintain the sub-luis, and run dispatch refresh to update the dispatch app?

**Comment by tsuwandy** [comment]
@dkonyayev, if only the sub LUIS apps are changed (no new intents for Dispatch app), there is no need to do "dispatch add", only "dispatch refresh" as the dispatch configuration in .dispatch file has all the info.  

Best practice is to never update the dispatch app on LUIS at all.  Update only the sub LUIS apps (and/or QnA kb if you use one) and run "dispatch refresh" to update.   If you'd like to add examples directly to dispatch app for a certain intent, you could add them to a txt file, use "dispatch add --intentName l_{{intent name for sub LUIS app}} -t file --{{file path}}".  

https://github.com/microsoft/botbuilder-tools/tree/master/packages/Dispatch has the info, look under "Common Tasks".
