### ISSUE TITLE
LUIS Gen does not support apps using LUIS APIs v3.0

### ISSUE THREAD

**Issue by kayousef** [microsoft/botbuilder-tools#1398]
App created using LUIS APIs v3.0 does not work with LUIS Gen tool to convert json file to cs code. 
 
It looks like the syntax generated by apps from APIs v3.0 is not compatible LUIS Gen.

**Comment by scheyal** [comment]
Hi @kayousef 
LUISGen tool has been deprecated. Instead, please use the the latest [BF CLI](https://github.com/microsoft/botframework-cli).
Thanks.
