### ISSUE TITLE
QnA Maker compares user input with question and answer samples in the KB

### ISSUE THREAD

**Issue by frarin** [microsoft/botbuilder-tools#1402]
## Describe the bug
QnA Maker echoes user input if it is matched with answer samples in the KB.
QnA Maker should compare user input only with **question** samples and **not** with **answer** ones.

## To Reproduce
1. Add QnA pair
2. Add "Who are you?" as a question
3. Add "I'm a bug!" as an answer
4. Test "I'm a bug" as user input

## Expected behavior
QnA Maker should not match user input with answer samples in the KB.

## Screenshots
OK

![bug1](https://user-images.githubusercontent.com/55706259/72987748-51f76c80-3deb-11ea-9fe5-dbbfe61976ff.PNG)

**NOT** OK

![bug2](https://user-images.githubusercontent.com/55706259/72987768-5ae83e00-3deb-11ea-9760-e53ee22a633c.PNG)

**Comment by simer99** [comment]
Hi, 

QnA Maker's default behavior is to look at both question and answer fields to get the most relevant answer. For users, who want only questions to be matched with the user query can use the 'rankerType:QuestionOnly' parameter in the Generate Answer call. 

The documentation is covered here: https://docs.microsoft.com/en-us/rest/api/cognitiveservices/qnamakerruntime/runtime/generateanswer

**Comment by frarin** [comment]
Hi,
thanks for your reply! We'll modify our Generate Answer call.

As a suggestion, it would be amazing to edit this settings from the QnA Maker website, in order to test the different behavior (rankerType:QuestionOnly **true** vs **false**) directly from there.
