### ISSUE TITLE
Directline sites has to be a list

### ISSUE THREAD

**Issue by damaca** [microsoft/botbuilder-tools#1404]
## Tool
Name: [Msbot]
Version: *az cli*
OS: *all*

## Describe the bug
The azure cli create option for directline channel (az bot directline create ) just allow one site. In the web portal several can be added and the response object from the az bot directline show is even an array.
Running the command multiple times override the previous one.

## To Reproduce
`az bot directline create --name foo --resource-group bar -s Site1`

## Expected behavior
Several sites can be used as command parameter:
`az bot directline create --name foo --resource-group bar -s Site1 Site2`
Or
`az bot directline create --name foo --resource-group bar -s Site1 -s Site2`

[bug]

**Comment by tonyanziano** [comment]
@stevengum can you please take a look at this?

**Comment by stevengum** [comment]
Ouch, this isn't good... It looks like `az bot directline` will need to be refactored:

`az bot directline sites list --name <bot-name> -g <resource-group> --subscription <subscription-name-or-guid>`

I'll take a look and have an update after I plan out some changes.

@scheyal FYI

**Comment by stevengum** [comment]
I'm going to tentatively plan this for just after R8 release. the [S167 milestone](https://github.com/Azure/azure-cli/milestone/84).

**Comment by cleemullins** [comment]
"Started working on this last week, planning for R9". from Steven.

**Comment by sgellock** [comment]
@stevengum This goes out on the Az-CLI release train, not mapped to ours, yes?

**Comment by stevengum** [comment]
That's correct, code complete for the Azure CLI release train is next week; so it doesn't map completely to our train... Post R9 Release is more accurate in this case.

**Comment by stevengum** [comment]
This is still expected to land next week, just doing some label management.

**Comment by daveta** [comment]
@stevengum : What's the current status on this one?

**Comment by peterinnesmsft** [comment]
@stevengum are you able to take a look and respond to @daveta's question here?

**Comment by stevengum** [comment]
Sorry for the delay, I'm targeting https://github.com/Azure/azure-cli/milestone/93 for this feature.

**Comment by stevengum** [comment]
I am syncing with @munozemilio who will have the final date

**Comment by chrimc62** [comment]
Closing as repo is obsolete.
