### ISSUE TITLE
Westeurope redirection to Dispatch luis app

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botbuilder-tools#1405]
Opening [this](https://github.com/MicrosoftDocs/bot-docs/issues/1529) here on behalf of @BillLeBoquet (I don't have permissions to transfer):

> When you create a Dispatch luis application hosted in westeurope (eu.luis.ai), clicking in "View in LUIS portal" from Summary.html try to open your application in westus, you end up with a 400 error in the console and an infinite Loading page. You should be redirected thanks to the region specified in your dispatch file.

**Comment by mdrichardson** [comment]
@BillLeBoquet What version of `botdispatch` are your running? `botdispatch -v`

**Comment by mdrichardson** [comment]
@BillLeBoquet `www.luis.ai` is currently statically set in the `Summar.html` file. We're working on a fix now that can change it dynamically based on the authoring region.

**Comment by tsuwandy** [comment]
@BillLeBoquet, @mdrichardson, we'll publish a new dispatch package (v 1.6.6) today.

**Comment by tsuwandy** [comment]
botdispatch v 1.6.6 is deployed to npm with fix to this issue.  Let me know if you are seeing problems with it.  Thanks!
