### ISSUE TITLE
[Dispatch] LUIS json files with closed lists entities do not import properly

### ISSUE THREAD

**Issue by csteelatgburg** [microsoft/botbuilder-tools#1406]
## Tool
Name: Dispatch
Version: 1.6.5
OS: macOS 10.15.2

## Describe the bug
After creating a LUIS app that contains list entities and exporting to json, the resulting file contains the appropriate closedLists entries. Adding the json file to a dispatch model is successful and the intents and utterances are added as expected. Closed lists, however, are not in the resulting json file and do not get imported into LUIS.

## To Reproduce
1. Create a LUIS app with closed list intent
2. Export LUIS app to json
3. Add json as source to dispatch model
4. Run dispatch refresh to import new data to LUIS

## Expected behavior
ClosedList entities should be imported to LUIS model

[bug]

**Comment by csteelatgburg** [comment]
I just tested adding my LUIS apps with closed lists directly to my dispatch model (instead of downloading the json files) and the same behavior is observed.

**Comment by tsuwandy** [comment]
@csteelatgburg, Dispatch does not transfer any entities (closed list is a type of entity in LUIS), except when they are used in patterns.  Dispatch deals only with intent classification (not entities) and thus does not transfer any entities from child LUIS apps to Dispatch.
