### ISSUE TITLE
QNAMaker sharepoint URL links, file links and files should have bidirectionally between updates in the QNA portal and the file source 

### ISSUE THREAD

**Issue by xtianus79** [microsoft/botbuilder-tools#1414]
## Tool
QNAMaker 

## Describe the problem
As of now, there is an almost awkward user experience when trying to manage and maintain spreadsheets and sources of truth files, mainly excel, even through sharepoint links.   Specifically, there is only a single direction, from file to QNAMaker, that exists in updating a QNAMaker model.

Because of this when you go back to the portal to do an update there is no longer a way to either retrieve that new file (without doing a full export of the entire model) or update a hyperlink through sharepoint.  

Essentially, you are stuck with a unidirectional update that has to be re-worked in order to update the original source of truth.    

## Describe the solution you'd like

1. a way to export a directly updated file source from within the QNA portal.  So if I source in a file name xyz.xcl then I can export out that model source back to that file name xyz.scl and not only just the entire export that would include everything. 
2. ***Also the sharepoint refresh to either refresh from sharepoint and also go the other way which would take the qna portal source info and source back to the sharepoint source.  

## Describe alternatives you've considered
There are alternatives and they are not UX friendly and well thought out. 

[enhancement]

**Comment by simer99** [comment]
Thanks @xtianus79  for the feedback. We have a part of it covered in our backlog. We add your feedback to it.

**Comment by simer99** [comment]
Closing it as i have acknowledged the feedback and added in our backlog
