### ISSUE TITLE
Error Deploying Python Dispatch App to Azure

### ISSUE THREAD

**Issue by mabu-dev** [microsoft/botbuilder-tools#1415]
Hi community!

I followed the below tutorials to create a Python Bot via Dispacth with multiple LUIS models and QnA Maker. The Bot runs smoothly on local env via the Bot Emulator. I can also deploy the Bot to Azure without any errors. However, I can't reach the Bot via Web Bot in the Channel Registration Service. When I lookup the logs in the App Service, I see an import error - aiohttp not found, as shown below.  Is this a known bug?  Am I doing something wrong? Your assistance will be highly appreciated. 

1. [bot-builder-tutorial-dispatch](https://docs.microsoft.com/en-gb/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs)

2. [bot-builder-deploy-az-cli](https://docs.microsoft.com/en-gb/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)

<img width="1238" alt="Screenshot 2020-02-27 at 00 29 44" src="https://user-images.githubusercontent.com/22409996/75394205-51755880-58f8-11ea-819f-6e5f0bd6ff22.png">

**Comment by jwiley84** [comment]
was aiohttp in your requirements.txt when you deployed your bot?

**Comment by tsuwandy** [comment]
@mabu-dev , could you check if aiohttp is in requirements.txt when deploying bot? Thanks!

**Comment by mabu-dev** [comment]
Thanks for responding, I found that I wasn't zipping the requirements file as part of the deployment! Thanks a lot!
