### ISSUE TITLE
QnA Maker does not support Emoji or Emoticons | No good match found in KB

### ISSUE THREAD

**Issue by frarin** [microsoft/botbuilder-tools#1418]
### Describe the bug
QnA Maker does not take in consideration or support emoji / emoticons even if it accepts them in the KB and shows no error during training. If I try to test it, it says "No good match found in KB."

### To Reproduce
1. Add QnA pair
2. Add "<3" and "❤" as a question
3. Add an answer

![image](https://user-images.githubusercontent.com/55706259/77587339-fe3af980-6ee7-11ea-9fc6-7a46f2ae55c1.png)

4. Test "<3" as user input
5. Test "❤" as user input

### Expected behavior
QnA Maker should reply to both "<3" and "❤" with the same answer, the first one does it work but the latter says "No good match found in KB".

![image](https://user-images.githubusercontent.com/55706259/77587683-aea8fd80-6ee8-11ea-893b-b40ff9945274.png)

Case "<3" is OK

![image](https://user-images.githubusercontent.com/55706259/77588268-d482d200-6ee9-11ea-9968-b9cad0b6a2f6.png)

Case "❤" is *NOT* OK

![image](https://user-images.githubusercontent.com/55706259/77588343-f419fa80-6ee9-11ea-8802-bafdfe3e1453.png)

**Comment by congysu** [comment]
@simer99 can you please take a look on this?  thanks.

**Comment by simer99** [comment]
Was able to repro this. will get back on the fix and root cause.

**Comment by simer99** [comment]
We have to whitelist this unicode ❤ (U+2764). the current unicode range whitelisted is U+D800 && U+DFFF. Could you try using an emoji from the whitelisted range that works for you?

Have added to our action list to expand our unicode range.

**Comment by pchoudhari** [comment]
Hi @frarin, we will all support for this particular emoji ❤ in our next sprint. You can expect a fix by next month.

**Comment by frarin** [comment]
Thank you all! Are you also thinking to whitelist other emoji? Our customers will interact with QnA by means of their smartphones (both iOS and Android), and it's very likely they will use a lot of them!

**Comment by somigithub** [comment]
QnA Maker team investigation complete.

No changes required in the product. Here is the guidance / recommendation

emoji reference list: https://unicode.org/emoji/charts/full-emoji-list.html 

Any emoji unicode of 5 chars works in QnA Maker. i.e unicodes like U+1FXXX works. Or If the overall UTF-8 encoded bytes >=4, its working

**Comment by frarin** [comment]
@somigithub unfortunately the red heart emoji ❤ is U+2764...

What about the emoji unicode of **4** chars? Will they be supported too in the future?
