### ISSUE TITLE
[AzureCLI]No result after running the 'az bot create ..' command

### ISSUE THREAD

**Issue by lzc850612** [Microsoft/botbuilder-tools#142]
## Information:
* Tools Libraries: 
* Libraries' Versions: 
* OS: 

## Issue Description:
No result after running the 'az bot create ..' command

## Commands Example:
az bot create
```bash

```

## Reproduction Steps:
1. Run 'az bot create ...' command
2. After following the step (paste the magic code to browser), the command line doesn't have a result of whether the operation succeeded or not

## Expected Behavior:
There should be a result of the command.

## Actual Results:
There isn't any result indicating the command succeeded or not.

**Comment by carlosscastro** [comment]
This was fixed before the //BUILD conference.
