### ISSUE TITLE
LUIS v3 is Severely lagged in its resolution of a dispatch create or refresh via a restful API call

### ISSUE THREAD

**Issue by xtianus79** [microsoft/botbuilder-tools#1423]
I don't know if this is the right place to report this but LUIS Dispatch refresh and or create has a severe lag of what is trained and published vs what can be resolved in the botframework itself. 

Here is a screen shot of the LUIS train vs even the LUIS Rest api call
correct but still technically lagged 
<img width="195" alt="luisChildappCorrect" src="https://user-images.githubusercontent.com/8476336/78631517-9af78280-786a-11ea-9be6-879e20316251.png">
Rest call here is severely lagged behind the real published version
<img width="221" alt="luisChildappWrong" src="https://user-images.githubusercontent.com/8476336/78631516-9af78280-786a-11ea-930c-2563dd5a7fd6.png">

[bug]

**Comment by cleemullins** [comment]
Hi @xtianus79, the tooling in this repo is largely deprecated. Please use the CLI Tooling found in https://github.com/Microsoft/botframework-cli

The newer "bf" CLI tools are the currently supported and maintained set of tooling.
