### ISSUE TITLE
Dispatch tool is not working as autojob

### ISSUE THREAD

**Issue by rajeeshmenoth** [microsoft/botbuilder-tools#1427]
## Tool
Name: **LUIS Dispatch**
Version: *1.6.6*
OS: *Windows 10 Enterprise*

## Describe the bug
Need to run dispatch manual process ( dispatch refresh ) as a web job in azure app service. The manual process is working in our machine as expected but auto job is not running.

## To Reproduce
1. Created dispatch job 
2. Created app service with .Net Core 3.0 as Target framework in windows.
3. Installed "npm i -g botdispatch" command in app service console ( "dispatch --help" command is working)
4. Created .Net Core 3.0 Console application and added the dispatch generated files inside the application. Also given "Copy always" permission to the dispatch generated files. Running the application using batch file will execute.
5. Published all the files into app service as a web job.
6. Getting timeout error ( If it increase 1 hour also getting the same issue ).

## Expected behavior
Should run as a web job based on the qna updates ( daily job process ).

## Screenshots
![image](https://user-images.githubusercontent.com/8437883/79114234-602ca780-7da0-11ea-9d5f-c4901b7c9913.png)

[bug]

**Comment by axelsrz** [comment]
Hey @tsuwandy could you take a look at this?

**Comment by tsuwandy** [comment]
@rajeeshmenoth, when using the refresh command, could you add the parameter "--remote true", something like "dispatch refresh --remote true" 

Let me know if this helps.

**Comment by rajeeshmenoth** [comment]
@tsuwandy 

The time delay issue is resolved but now installed package is not recognizing in app service. I tried to reinstall "npm i -g botdispatch" but no use.

![image](https://user-images.githubusercontent.com/8437883/79179877-3ddd6d00-7e26-11ea-81e1-d23065e4479e.png)

**Comment by tsuwandy** [comment]
@rajeeshmenoth , not sure if I understand.  So steps #2 & #3 in original repro are no longer working?  Doesn’t look like you have gotten to using the command “dispatch refresh --remote true”?  What changed?

**Comment by rajeeshmenoth** [comment]
Thank you @tsuwandy , The given command is working in app service as expected. I never seen this  #2 & #3 that you have mentioned and currently I am following the microsoft document [dispatch](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=cs#create-the-dispatch-model)

**Comment by tsuwandy** [comment]
@rajeeshmenoth, great!

With regard to #2&#3, I was referring to these steps in the your repro steps (wasn’t sure why dispatch wasn’t installed):
2. Created app service with .Net Core 3.0 as Target framework in windows.
3. Installed "npm i -g botdispatch" command in app service console ( "dispatch --help" command is working)

But all seems to be working well now?  Thanks!

**Comment by rajeeshmenoth** [comment]
@tsuwandy  Still I am facing this issue, 

1. Remove all questions and answers from KB and try to run the dispatch command.
2. dispatch command will fail because we are trying to push empty KB.
3. That time app service removing the dispatch package. 
4. If I trying to reinstall I am able to see the below output. So this is a blocker for my side.

![image](https://user-images.githubusercontent.com/8437883/79301500-6721fa00-7f07-11ea-82e0-66391cda0773.png)

**Comment by tsuwandy** [comment]
@rajeeshmenoth , not sure what this one is: 

3. That time app service removing the dispatch package.

**Comment by rajeeshmenoth** [comment]
@tsuwandy , just skip out the step 3 and see step 4, why it's showing as 

> dispatch is not recognized as an internal or external command

Already we have installed and application successfully run 14 hours back but why now it showing this error ?

**Comment by tsuwandy** [comment]
@rajeeshmenoth, I’m not sure if you could install a package in app service?

Could the “dispatch refresh —remote true” be done in a VSO ci/cd step instead?

**Comment by rajeeshmenoth** [comment]
@tsuwandy, I think CI / CD will work based on the each check-in or deployment but our business requirement is different. Daily the qna updates is happening so that time we are triggering the dispatch web job and the respective kb information update in the dispatch model.

**Comment by tsuwandy** [comment]
@rajeeshmenoth, since you noticed that the package couldn’t be installed on app service, perhaps do it as a scheduled task on a VM or simply a local machine?

**Comment by rajeeshmenoth** [comment]
@tsuwandy , Customer is using azure environment for their business purpose and for this dispatch generated file which is small in size, maintaining seperate VM is worthless. Currently I am running this dispatch in my local machine as manual process and it is working fine. Do u know why this installed packages are not recognizing in azure app service ?. I heard about all the applications that are running inside sandbox environment in azure app service. Is this creating any security blocker for dispatcher ?Or do we need to  setup any environment variable in azure?

**Comment by tsuwandy** [comment]
@rajeeshmenoth, I don’t think app service is the right azure service for this task, as you could see, it didn’t seem to allow package install.  It’s simpler to have the customer run a scheduled task in the on premise machine like the way you have it now (with “remote true” parameter.

**Comment by rajeeshmenoth** [comment]
@tsuwandy , I have troubleshoot and found out that the packages are removed from Appdata folder once app service restart is happen. Is this a restriction of App service?

**Comment by tsuwandy** [comment]
@rajeeshmenoth , I’m not an expert in app service but I’m believe so.  Perhaps you could install the package locally within the project deployed with app service so you won’t have to install it on the service after deployment.

Another thing you could do is to create a VSO release pipeline (triggered to run daily), which simply has a power shell command to run “dispatch refresh —remote true”.

**Comment by rajeeshmenoth** [comment]
@tsuwandy , This issue is resolved, package moved into application level and added few scripts .
