### ISSUE TITLE
Dispatch refresh isnt working in Azure Pipelines for me

### ISSUE THREAD

**Issue by danieldangler** [microsoft/botbuilder-tools#1437]
## Tool
Name: Dispatch
Version: latest

## Describe the bug
I want to refresh my Dispatch model using the "Dispatch refresh" command inside azure Pipelines.
But when i use this method i always get the Output "Please use init to initiliaze the dispatch first". But why do i need to generate another .dispatch file if i already have one? Im pretty new to the dispatch tool and pipelines so maybe its my missing knowledge of one of these features hehe.

## To Reproduce
1. Configure the Dispatch-Model with the tool locally
2. Publish the Bot in AZure Repos
3. Load the Dispatch model files in the working directory of the release Pipeline
4. Use the dispatch refresh command inside the Command line Task

## Expected behavior
The Pipeline should update the luis model

## Screenshots
<img width="935" alt="Bildschirmfoto 2020-05-25 um 13 51 56" src="https://user-images.githubusercontent.com/39704877/82810558-15b64480-9e8f-11ea-8704-16e5ea1bb585.png">

<img width="1166" alt="Bildschirmfoto 2020-05-25 um 13 52 32" src="https://user-images.githubusercontent.com/39704877/82810578-1bac2580-9e8f-11ea-9adc-9df8da7489a2.png">

<img width="1166" alt="Bildschirmfoto 2020-05-25 um 13 52 44" src="https://user-images.githubusercontent.com/39704877/82810621-31214f80-9e8f-11ea-8a7c-f924d3aad125.png">

<img width="1166" alt="Bildschirmfoto 2020-05-25 um 13 52 53" src="https://user-images.githubusercontent.com/39704877/82810640-3bdbe480-9e8f-11ea-97e4-1dcb7ee2b16a.png">

[bug]

**Comment by Zerryth** [comment]
Hi @danieldangler. This doesn't seem like the appropriate place to inquire about help regarding your issue. The Bot Framework Team uses GitHub as a means for the community to raise issues that are bugs in the framework/CLI tool itself. For how-to questions, please create a post on [StackOverflow](https://stackoverflow.com/search?q=%23botframework) to leverage the help of our support engineers and the community at large.

Briefly, it seems to be a problem with what you're doing on the *Azure Pipeline's* end and *not* necessarily an issue on the *dispatch cli* bit of things. You are correct, if you have a dispatch file, you should not receive a prompt asking you to initialize a dispatch file. This would indicate that somewhere in your pipeline setup, your dispatch file is not actually located where the command is searching for it.

___
**Additional context showing `dispatch refresh` working when able to find the file**

Created and added a dispatch file to directory using `dispatch init` and `dispatch add`. Then used `dispatch refresh -v newDispatchVersion` to update the dispatch model's version. 


<details>
    <summary>Command line details for 1st refresh, without any existing dispatch LUIS created in portal still</summary>

```
C:\Users\AshleyFinafrock\Work\dispatch>dir
 Volume in drive C is OSDisk
 Volume Serial Number is 48BA-14C2

 Directory of C:\Users\AshleyFinafrock\Work\dispatch

05/26/2020  11:13 AM    <DIR>          .
05/26/2020  11:13 AM    <DIR>          ..
05/26/2020  11:13 AM    <DIR>          data
05/26/2020  11:13 AM               374 ghDispatch.dispatch
               1 File(s)            374 bytes
               3 Dir(s)  326,548,770,816 bytes free

C:\Users\AshleyFinafrock\Work\dispatch>code .

C:\Users\AshleyFinafrock\Work\dispatch>dispatch refresh -v newDispatchVersion
Exporting services for dispatch...
Exporting FreshFlightBooking LUIS application...
Exported LUIS app JSON is at C:\Users\AshleyFinafrock\Work\dispatch\data\_L_FreshFlightBooking.json
Creating dispatch LUIS model json...
Creating training data...
Updating ghDispatch model...
Training FreshFlightBooking...
Importing ghDispatch model...
Setting up intents to child services mapping for ghDispatch...
Add subscription key and publish child LUIS apps...
Publishing FreshFlightBooking model...
Training ghDispatch model...
Publishing ghDispatch model...
Writing summary file ('test_prediction')...
{
  "authoringRegion": "westus",
  "hierarchical": true,
  "useAllTrainingData": false,
  "dontReviseUtterance": false,
  "copyLuisData": true,
  "normalizeDiacritics": true,
  "services": [
    {
      "appId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "authoringKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "version": "0.1",
      "region": "westus",
      "type": "luis",
      "name": "FreshFlightBooking",
      "id": "1"
    }
  ],
  "serviceIds": [
    "1"
  ],
  "appId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "authoringKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "version": "newDispatchVersion",
  "region": "westus",
  "type": "dispatch",
  "name": "ghDispatch"
}
Please review your updated dispatch model in C:\Users\AshleyFinafrock\Work\dispatch\Summary.html

```

</details>

Tried refreshing dispatch again to a new version (`secondDispatchRefresh`) to ensure things are working, even after dispatch model has been created.

<details> 
    <summary>Command-line details for 2nd refresh with existing dispatch LUIS created</summary>
```
C:\Users\AshleyFinafrock\Work\dispatch>dispatch refresh --dispatch ghDispatch.dispatch --version secondDispatchRefresh
Exporting services for dispatch...
Exporting FreshFlightBooking LUIS application...
Exported LUIS app JSON is at C:\Users\AshleyFinafrock\Work\dispatch\data\_L_FreshFlightBooking.json
Creating dispatch LUIS model json...
Creating training data...
Updating ghDispatch model...
Training FreshFlightBooking...
Importing ghDispatch model...
Setting up intents to child services mapping for ghDispatch...
Add subscription key and publish child LUIS apps...
Publishing FreshFlightBooking model...
Training ghDispatch model...
Publishing ghDispatch model...
Writing summary file ('test_prediction')...
{
  "authoringRegion": "westus",
  "hierarchical": true,
  "useAllTrainingData": false,
  "dontReviseUtterance": false,
  "copyLuisData": true,
  "normalizeDiacritics": true,
  "services": [
    {
      "appId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
      "authoringKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "version": "0.1",
      "region": "westus",
      "type": "luis",
      "name": "FreshFlightBooking",
      "id": "1"
    }
  ],
  "serviceIds": [
    "1"
  ],
  "appId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "authoringKey": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "version": "secondDispatchRefresh",
  "region": "westus",
  "type": "dispatch",
  "name": "ghDispatch"
}
Please review your updated dispatch model in C:\Users\AshleyFinafrock\Work\dispatch\Summary.html
```

![image](https://user-images.githubusercontent.com/35248895/82939926-e532e100-9f48-11ea-99f9-2884a4061116.png)
