### ISSUE TITLE
Run dispatch from code

### ISSUE THREAD

**Issue by mchuck** [microsoft/botbuilder-tools#1440]
## Tool
Name: Dispatch

## Describe the problem
I'd like to provision new bots automatically and be able to call dispatch from e.g. Azure Function. 

## Describe the solution you'd like
Have access to .NET part of `dispatch` via a NuGet package or another way to call `dispatch` from code.

## Describe alternatives you've considered
Currently we're running dockerized powershell Azure Function which is buggy and feels like a hack just to call `dispatch` alone.

**Comment by tsuwandy** [comment]
@mchuck, unfortunately there is currently no plan to publish Dispatch as NuGet package.  I have seen folks deploy it with Azure app service (run it as scheduled task in the app service) or from Azure DevOps CI/CD pipeline.

**Comment by a-b-r-o-w-n** [comment]
Closing this issue because we currently do not have any plans to publish Dispatch as a nuget package.
