### ISSUE TITLE
Cannot delete an intent using the LUIS CLI

### ISSUE THREAD

**Issue by bksnel** [microsoft/botbuilder-tools#1446]
## Tool
Name: LUIS
Version: LUIS CLI 2.6.2
OS: Windows 10
PowerShell: 5.1 (Build 19041)

## Describe the bug
Cannot delete an intent using the Azure LUIS CLI.  When I delete an intent using the following statement, I get the error message "Unknown resource: intent".
`luis delete intent --intentId $intentId --deleteUtterances $true`

To proof that I'm using the correct identifier: when I execute the following statement, I do get the details of that intent: 

```
luis get intent --intentId $intentId
{
 "id": "9e675cfc-96dd-4e43-b4c4-597aab65d8ec",
"name": "FromPowerShell",
"typeId": 0,
 "readableType": "Intent Classifier"
}
```

## To Reproduce
1. Get an identifier of an intent in LUIS
2. Execute luis delete intent --intentId $intentId --deleteUtterances $true' in Powershell.
3. You'll receive the error message "Unknown resource: intent"

## Expected behavior
Expect to delete an intent by Id.

## Additional context
Als commands are executed from PowerShell ISE

[bug]

**Comment by vishwacsena** [comment]
@bksnel `LUIS CLI` is deprecated and replaced by [`BF CLI`](https://github.com/microsoft/botframework-cli). Can you outline your need to manipulate the intent directly? E.g. could you do this via updates made to [.lu file](https://aka.ms/lu-file-format)

@munozemilio we should add `deprecated` message to relevant CLI groups in `botbuilder-tools`.

**Comment by bksnel** [comment]
@vishwacsena Thanks for your reply. 

We are building a DevOps pipeline that migrates content from different sources and uploads this to a single LUIS application. We want to control this per environment in the DTAP-environment.
Being able to manage a single intent with examples allows us to import from each individual source. We've looked at the LUIS dispatch tool, but that does not satisify our needs; it would not give us the control per environment in a DevOps pipeline.

We're using the bot framework CLI, but for the following operations we still need the LUIS CLI: 
- luis add intent
- luis delete intent
- luis add examples

These seem not available in the bot framework cli?

**Comment by vishwacsena** [comment]
@bksnel have you considered the [.lu file format][1] to describe your LUIS application? Depending on your scenario, you can also define your application via individual .lu files that describe specific intents and entities and combine them to make a single application using [import references][2]. 

If you are able to use the .lu format, then you can use [`bf luis:convert`][3] to convert .lu to LUIS application definition JSON format as well as use `bf luis:version:create` to create new application version. 

[1]:https://aka.ms/lu-file-format
[2]:https://docs.microsoft.com/en-us/azure/bot-service/file-format/bot-builder-lu-file-format?view=azure-bot-service-4.0#external-references
[3]:https://github.com/microsoft/botframework-cli/tree/master/packages/luis#bf-luisconvert

**Comment by bksnel** [comment]
@vishwacsena. I was not aware of the external references. Based on the documentation, I think this should work.

Thanks, I'll close the issue now.
