### ISSUE TITLE
Dispatch create fails with Cannot find the feature with the Id (SalePrice) in the specified application version.

### ISSUE THREAD

**Issue by devedse** [microsoft/botbuilder-tools#1448]
## Tool
Name: Dispatch
Version: 1.7.0
OS: Windows 10 - 18363

## Describe the bug
We've created both a General model and a QnA maker. Creating a Dispatch model worked fine up untill the point that we did some changes to the LUIS model. Now I keep getting the following error:

```
Importing ******-Dev-Dispatch model...

ERROR
Failed importing ******-Dev-Dispatch app - {
  "error": {
    "code": "BadArgument",
    "message": "Cannot find the feature with the Id (SalePrice) in the specified application version."
  }
}
```

The issue also happens when I manually export a .LU file in LUIS and then try to import that .LU file again. I created a separate comment on an existing issue here: 
https://github.com/microsoft/botframework-cli/issues/789#issuecomment-644783190

To me this really feels like a bug in LUIS or the dispatch tool.

## To Reproduce
1. Include the desired models in the dispatch tool
2. Run dispatch create

## Expected behavior
I nicely generated dispatch model

## Screenshots
![image](https://user-images.githubusercontent.com/2350015/84786077-8e22a800-afec-11ea-88e2-a00beaf3f75a.png)

## Additional context
N/A

[bug]

**Comment by vishwacsena** [comment]
This appears to be an issue with the LUIS portal and their implementation of the LU file format support if not, is an issue in BF-LU library itself. Best to track this via microsoft/botframework-cli#789

**Comment by devedse** [comment]
@vishwacsena, I saw you added a workaround for the export --> import. However is there also a workaround available for the dispatch tool? If not, I can't generate the dispatch model to be used by my bot.

**Comment by vishwacsena** [comment]
@devedse can you verify and confirm that you continue to see issue with the latest dispatch? The latest should be 1.7.1. We shipped a patch to address various issues and I expect this issue to be addressed as well. Please leave a comment here if it isn't. 

https://www.npmjs.com/package/botdispatch

**Comment by devedse** [comment]
@vishwacsena, version 1.7.1 indeed addressed this issue as I can now create the dispatch model again.
