### ISSUE TITLE
[Ludown][LUIS] Prebuilt entities for Italian causes parsing issues

### ISSUE THREAD

**Issue by GitDruid** [microsoft/botbuilder-tools#1453]
Same error of #1007 appears also for it-it locale.

(Note: I reproduced the bug in calendar skill by first commenting-out the personName prebuild reference from the it-it Calendar.lu file, to bypass the bug https://github.com/microsoft/botframework-cli/issues/876, not yet closed).

_Originally posted by @GitDruid in https://github.com/microsoft/botbuilder-tools/pull/1024#issuecomment-655353307_

**Comment by munozemilio** [comment]
Hello @GitDruid ludown is deprecated. Please track the botframework-cli only
