### ISSUE TITLE
Failed importing latest version

### ISSUE THREAD

**Issue by dkonyayev** [microsoft/botbuilder-tools#1459]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Version: Latest
OS: Window Server 2016

## Describe the bug
When refreshing the domain getting error "Failed importing latest version..." It also takes VERY LONG time after it says "Importing Demo mode" until it displays an error. This is a very small sample domain. There is also no option to actually see what is the error.

Exporting Demo.UseCases LUIS application...
Exported LUIS app JSON is at C:\Dispatch\staging\demo\data\_L_Demo.UseCases.json
Exporting MetLife.Sam.HumanResources.Pto LUIS application...
Exported LUIS app JSON is at C:\Dispatch\staging\demo\data\_L_Demo.HumanResources.json
Creating dispatch LUIS model json...
Creating training data...
Updating Demo model...
Training Demo.UseCases...
Training Demo.HumanResources
Importing Demo model...
ERROR
Failed importing latest version of Demo app

## To Reproduce
Tried with and without --version, as I saw that as an answer in some other post

dispatch refresh --publishToStaging true --dataFolder c:\dispatch\staging\demo --version 1
or
dispatch refresh --publishToStaging true --dataFolder c:\dispatch\staging\demo

## Expected behavior
Complete process.

## Additional context

[bug]

**Comment by compulim** [comment]
@tsuwandy Please take a look at this issue. 😉

**Comment by tsuwandy** [comment]
@dkonyayev, is it possible to get a copy of your dispatch json so we could get a repro of the import failure?   From where you run your dispatch command, it's  \data\_experiments\model_001\train_luis_model_augmented.json.  Could you email it to tien.suwandy@microsoft.com?  Thank you!

**Comment by dkonyayev** [comment]
Emailed the JSON.

**Comment by tsuwandy** [comment]
@dkonyayev, closing this per our conversations in email.  Let me know if you are seeing other issues.  Thank you!
