### ISSUE TITLE
Add a Health Check feature to msbot

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botbuilder-tools#1461]
## Tool
Name: [Msbot]

## Describe the problem
"Best practice" when creating a skill consumer is perform a health check on the skill before adding it to your bot. There is currently no straight forward way to do so.

## Describe the solution you'd like
I'd like to be able to perform a bot health check from the command line.

## Describe alternatives you've considered
Add a Health Check feature to the Emulator ([Emulator issue 2166](https://github.com/microsoft/BotFramework-Emulator/issues/2166)).

Ideally, both the command-line and the Emulator would support a health check feature.

## Additional context
We cannot add documentation for a process that doesn't exist, even if that process is part of a best practice.

See [bot-docs issue 1770](https://github.com/MicrosoftDocs/bot-docs/issues/1770).

[enhancement]

**Comment by EricDahlvang** [comment]
MSBot is obsolete.  Please use bfcli tooling.  If this should be a feature of bfcli, please add this issue there.
