### ISSUE TITLE
Dispatch tool version 1.7 create works 100%, but if i say refresh it fails

### ISSUE THREAD

**Issue by InfoZone** [microsoft/botbuilder-tools#1463]
## Tool
Name: Dispatch and LUIS and Qna
Version: 1.7.1
OS: Windows 10

## Describe the bug
When i run dispatch create, it works and creates it all in LUIS. Then without changing anything to test I am running dispatch refresh .I get an error that says it failed but no helpful info. I have run refresh a few times a couple of weeks ago and it worked when we added new stuff to our qna services. it was imported into LUIS dispatch. This worked a few times we added new itmes to our qna service, and we needed this to be updated in our dispatch service. I have never added a -v version when i did this and had no issues.:

Exporting services for dispatch...
Exporting DispatchModel LUIS application...
Exporting  LUIS application...
Exporting  QnA kb...
Creating dispatch LUIS model json...
Creating training data...
Updating model...
Importing  model...

ERROR
Failed importing latest version of  app

## To Reproduce
1. I created a dispatch services
2. we added 1 new item in the qna service 
3. ran dispatch refresh
4. failed

## Screenshots
![image](https://user-images.githubusercontent.com/17723426/89186467-1f99a980-d59c-11ea-941d-adf75cda8e08.png)

## Additional context

[bug]

**Comment by tsuwandy** [comment]
@InfoZone, could you check what versions the dispatch app has on luis portal?  When was the last time create runs successfully?   Could you try using the same .dispatch file, rename the dispatch app name, set appId to "" and then run dispatch create and see if it could finish successfully?

**Comment by InfoZone** [comment]
Hello,

So i deleted the dispatch app in luis, ran the create it worked, then an update and it worked

Same dispatch file so not sure if there was something funny in the luis app?

Anyways thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tsuwandy** [comment]
@InfoZone , thanks for the update.  I’m guessing there was some dispatch versions preventing the refresh (previous failures).  I’ll close this issue but let me know if you run into this issue again.  Thanks!
