### ISSUE TITLE
Dispatch-App doesn't use features or seems to use ten random features

### ISSUE THREAD

**Issue by Salzberger** [microsoft/botbuilder-tools#1471]
## Issue Description:
We have several LUIS Dispatch Apps which share some child apps and usually have a custom app with client-specific answers. When looking at "Features" in the "Intents" Tab (under "Build") of the Dispatch Apps, some models use ten features, others use none. 

The child apps use ML entities and phrase lists. The Dispatch Apps only use a maximum of ten features. Since we have more than ten entities in our child apps, it seems completely random, which features are picked to be used in the Dispatch App.

Is there any way to pick and choose (I think it would also help, if the Dispatch App could recognize ALL instead of only ten features)?

## Reproduction Steps:
1. Create Dispatch-App
2. Train Dispatch-App
3. Look at "Features" in the Intents tab.

## Expected Behavior:
Consistency between our Dispatch Apps → all should use ten features and the same features, instead of the presumed randomness. 

## Actual Results:
Some Dispatch Apps use ten features, some just don't. Some Dispatch Apps automatically use other features than the other Dispatch Apps.

**Comment by tsuwandy** [comment]
@Salzberger, Dispatch CLI doesn't move entities from sub LUIS apps unless they are used in patterns.  Are the entities used in patterns?  Dispatch will move phrase lists from sub LUIS apps to Dispatch app.

**Comment by tsuwandy** [comment]
Closing this issue.  Let me know if you have other issues outside this.  Thanks!

**Comment by Salzberger** [comment]
Hi tsuwandy,

thank you for your quick reply.

Not all of our entities are used in patterns, so I get that point.
But I don't understand your point, that "Dispatch will move phrase lists from sub LUIS apps to Dispatch App"

Where can I see them? Do you mean the following part? With a maximum of 10 features?
![image](https://user-images.githubusercontent.com/71824624/94272578-86579580-ff43-11ea-9d1c-c801c1bde23c.png)

We have more than ten features/phrase lists and LUIS seems to pick and choose 10 of those features randomly. 
I use the same commands and parameters to create Dispatch-Apps, so I can't comprehend why LUIS is choosing which features  to include in the Dispatch App.

Thanks for your reply in advance.

**Comment by tsuwandy** [comment]
@Salzberger, Dispatch will combine the phrase lists not used in entities (I think it’s now called features) so it could get around LUIS limits.  You might not see the same name but you’ll see the words from sub LUIS apps in the lists.
