### ISSUE TITLE
LUIS CLI: client.model.getIntentSuggestions is not a function

### ISSUE THREAD

**Issue by bartbilliet** [microsoft/botbuilder-tools#1479]
## Tool
Name: LUIS
Version: 2.6.2
OS: Windows 10 1809

## Describe the bug
Running following luis suggest command to get the list of utterances listed under "review endpoint utterances" section fails: 
`luis suggest intents --intentId "<IntentId>"`

Following error is produced after running this command: 
**client.model.getIntentSuggestions is not a function**

## To Reproduce
1. Run `luis init` and enter all configuration parameters.
2. Run `luis list intents` to list the intent ID's.
3. Run `luis suggest intents --intentId "<IntentId>"`, replacing `<IntentId>` with one of the intent ID's found in the previous cmdlet.

## Expected behavior
The tool should produce a list of all endpoint utterances for the given intent id. 

## Additional context
Seems to relate to the following line code: 
https://github.com/microsoft/botbuilder-tools/blob/c74b7e210e06d166a042ad04c2a1bbab69e1261a/packages/LUIS/bin/luis.js#L553

[bug]

**Comment by taicchoumsft** [comment]
Hi @bartbilliet, thanks for reporting this issue. I can indeed repro this issue, and confirm that the function `getIntentSuggestions` has been renamed to `listIntentSuggestions`.

To unblock you right now, if you're on windows you can go to your global npm cache and modify the `luis.js` file :
1) On windows, it'll be found here `\AppData\Roaming\npm\node_modules\luis-apis\bin\luis.js`
2) search for `getIntentSuggestions` and rename the method to `listIntentSuggestions`

I'll try to find the right owner for this, if not I'll fix this shortly. Thanks for reporting this again.

**Comment by bartbilliet** [comment]
@taicchoumsft Thanks, I confirm that your proposed temporary workaround is successful!

**Comment by bartbilliet** [comment]
@CezaryMarcjan was this fixed? I seem to still see the wrong name in code?

**Comment by CezaryMarcjan** [comment]
@bartbilliet, indeed, lets wait for @taicchoumsft  to address this.

**Comment by taicchoumsft** [comment]
Hi @bartbilliet , there was some internal discussion on this, and the recommendation was not to take this change in this repo. Apologies. 

Instead, we are encouraging our customers to use the [BotFramework-CLI](https://github.com/microsoft/botframework-cli), which should have this functionality in the LUIS packages, or if it doesn't, we should provide it for you there. 

Hi @munozemilio, per our internal discussions on this issue, do you have a suggestion for what @bartbilliet can use to replicate this functionality in BF-CLI?

**Comment by munozemilio** [comment]
Hello @bartbilliet currently we don't support this operation in the botframework cli, but please go ahead and open an issue in the [repo](https://github.com/microsoft/botframework-cli) explaining how this functionality is used on your end so we can understand your needs and provide the best experience using our tools.
