### ISSUE TITLE
Dispatch tool support for arabic

### ISSUE THREAD

**Issue by SSanjeevi** [microsoft/botbuilder-tools#1481]
## Information:
* Tools Libraries: botdispatch 
* Libraries' Versions: latest
* OS: Windows

## Issue Description:
Bot dispatch tool support Arabic?

## Commands Example:
dispatch refresh
```

## Expected Behavior:
dispatch tool to support arabic.

**Comment by cwhitten** [comment]
@tsuwandy can you glance at this please? Thanks.

**Comment by tsuwandy** [comment]
@SSanjeevi, Dispatch CLI supports whatever language supported by LUIS/QnAMaker. 

Arabic is not yet supported by LUIS, as shown here:
 https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-language-support#multi-language-luis-apps

**Comment by SSanjeevi** [comment]
@tsuwandy  - we are planning to use arabic preview version, so is it supported?

**Comment by tsuwandy** [comment]
Dispatch CLI doesn't work with preview version unfortunately (different endpoints) and we would have to wait until that preview is GA-ed.  Thanks!

**Comment by SSanjeevi** [comment]
Is there any preview version of dispatch available which will work for arabic Luis preview?
