### ISSUE TITLE
In Microsoft Teams, what is the maximum number of adaptive cards that can be stacked on a carousel using Bot Framework?

### ISSUE THREAD

**Issue by amoyalan20** [microsoft/botbuilder-tools#1482]
Could you please suggest the maximum number of carousal attachments for Microsoft teams?

**Comment by mrivera-ms** [comment]
@amoyalan20, thank you for opening this issue. For product behavior, how-to, or general understanding questions, please use [StackOverflow.](https://stackoverflow.com/search?q=bot+framework)
