### ISSUE TITLE
Entity limit dispatch tool

### ISSUE THREAD

**Issue by JorJames1** [microsoft/botbuilder-tools#1495]
## Information:
* botdispatch

## Issue Description:
I have an issue if I want to create the dispatch tool. I want to create a dispatch tool with three LUIS applications. 
I thought I can use the dispatch tool if I want to use more entities. Do I have to use a LUIS container instead of the Dispatch tool? How can I solve the issue?

## Reproduction Steps:
1. npm install -g bot dispatch
2. dispatch init [...]
3. dispatch add [...]
4. dispatch create

## Expected Behavior:
Creation of the dispatch tool is successful.

## Actual Results:
The following error pops up after "dispatch create":
"ERROR
Exceeded entity limit for Dispatch"

Appreciate your help.

**Comment by stevkan** [comment]
I'm presently researching this and will keep you updated. In the mean time, can you tell me if this error occurred with previous version of the tool? Is this something you tried previously and worked but is now failing?

**Comment by JorJames1** [comment]
No, I didn´t try and work with previous versions of the tool. The tool works with two LUIS apps (less than 100 entites) but doesn´t work with all LUIS apps (more than 100 entities).

**Comment by stevkan** [comment]
@JorJames1, I'm not experiencing an issue with attaching multiple LUIS apps. Can you list the specific commands you are passing thru just to double check they are correct?

**Comment by JorJames1** [comment]
I have done it like there: https://github.com/microsoft/botbuilder-tools/tree/master/packages/Dispatch
1. npm install -g bot dispatch
2. dispatch init -n TestDispatch --luisAuthoringKey "[...]" --luisAuthoringRegion westeurope
3. dispatch add -t luis -i [...] -n "LUIS01" -v 0.1 -k [...]
4. dispatch add -t luis -i [...] -n "LUIS02" -v 0.1 -k [...]
5. dispatch add -t luis -i [...] -n "LUIS03" -v 0.1 -k [...]
6. dispatch add -t qna -i [...] -n kb -k [...]
7. dispatch create

As I said before, I can create the tool with less than hundred entities but if I want to create a tool with more entities, it fails:
"Exporting services for dispatch...
Exporting LUIS01 application...
Exported LUIS app JSON is at [...].json
Exporting kb QnA kb...
Exported QnA app JSON is at [...]json
Expanding kb [...] with word alterations
Exporting LUIS02 application...
Exported LUIS app JSON is at [...].json
Exporting LUIS03 application...
Exported LUIS app JSON is at [...].json
Creating dispatch LUIS model json...

ERROR
Exceeded entity limit for Dispatch"

**Comment by stevkan** [comment]
Hi @JorJames1, thank you for your patience. Let me research this today and I'll try and have a response by EOD for you.

**Comment by stevkan** [comment]
@JorJames1, I'm able to confirm that this is actually expected behavior. LUIS has a hard limit of 100 main entities when the total pattern entities used in child LUIS apps exceeds 100 (reference [Limits - LUIS - Azure Cognitive Services | Microsoft Docs](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-limits)). Dispatch merely employs LUIS and therefore respects those limits.

The only recourse is to ensure the child LUIS apps do not exceed 100 pattern entities. It is possible to have more than 100 entities, but not 100 entities used in patterns.

Closing as resolved.
