### ISSUE TITLE
Dispatch Tool fails to train the luis based on preview version of qnamaker

### ISSUE THREAD

**Issue by SSanjeevi** [microsoft/botbuilder-tools#1496]
## Tool
Name: Dispatch
Version: 1.7.2
OS: Windows 10

## Describe the bug
Unable to use dispatch to train the LUIS using QnaMaker preview version from north Europe, its referring to old endpoint and getting permission denied or invalid key.
It has to look for the new preview URL to get the qna.
Error:
```
(The remote server returned an error: (401) PermissionDenied.)

Request url: https://westus.api.cognitive.microsoft.com/qnamaker/v4.0/knowledgebases/"kbid"/Test/qna
Response: {"error":{"code":"401","message":"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."}}

```

## To Reproduce
1. create a qnamaker in preview version in north europe.
2. try to use that to train the dispatch LUIS

## Expected behavior
It should train the LUIS.

## Screenshots
provided the error message in description.

[bug]

**Comment by joshgummersall** [comment]
[`bf-cli`](https://github.com/microsoft/botframework-cli) tools have replaced `botbuilder-tools`, so I would recommend taking a look at https://github.com/microsoft/botframework-cli/tree/beta/packages/orchestrator and https://github.com/microsoft/botframework-sdk/tree/main/Orchestrator. In particular, Orchestrator is now recommended in place of Dispatch for stitching together multiple LUIS and/or QnA Maker models.

**Comment by sschutten** [comment]
`Orchestrator` is not an option for us, since it is in preview and only supports English as of now. I would love to have an option to continue to use `dispatch`, even though it may require a workaround, until `Orchestrator` is ready.

**Comment by munozemilio** [comment]
@tsuwandy can you provide input on this one please?

**Comment by tsuwandy** [comment]
Will check with QnAMaker team on the preview endpoint...

**Comment by tsuwandy** [comment]
@SSanjeevi, we'll be releasing an update to Dispatch CLI where you could optionally specify the endpoint for QnAMaker preview API in config, targeting sometime tomorrow.

**Comment by tsuwandy** [comment]
@SSanjeevi, sorry for the delay.  We just deployed Dispatch version 1.7.3, which will let you:
- Override the QnAMaker endpoint to point to preview endpoint
- Add an optional region field to qna maker source

To try this:
- To point to QnAMaker endpoint:
       Find where dispatch is installed.  If globally, it should be in C:\Users\<USER_NAME>\AppData\Roaming\npm\node_modules\botdispatch\bin\netcoreapp2.1
       Open appsettings.json, replace "QnAMakerDownloadUrlFormat": "{0}/qnamaker/v4.0/knowledgebases/{1}/Test/qna{2}" with "QnAMakerDownloadUrlFormat": "{0}/qnamaker/v5.0-preview.1/knowledgebases/{1}/Test/qna{2}"


- Open the .dispatch file (in folder where you run dispatch CLI), add a region property for QnAMaker source, ie:
         {
      "kbId": "8a707cd7-c07c-4575-942e-4f999ffc42fd",
      "subscriptionKey": "ace6dbe611bf4e2b8f00cfea494a5fd2",
      "type": "qna",
      "name": "TravelPolicy",
      "region": "northeurope",
      "id": "2"
    }

That should be all the changes needed before running "dispatch create"/"dispatch refresh".

Let me know if you have any questions.  Thanks!
