### ISSUE TITLE
Feature Request: ability to use Custom Subdomain instead of regional domain

### ISSUE THREAD

**Issue by daelsala** [microsoft/botbuilder-tools#1506]
## Issue Description:

Bot Dispatcher currently does not support use of custom subdomains. This prevents users from allowing their QnA or LUIS resources to be behind a VNET since once they are behind a vnet they will need to be called using the custom subdomain only.

ex:
This:
**region**.api.cognitive.microsoft.com/qnamaker/

cannot be used to call a qna or luis resource behind a VNET. The following:

**customSubDomainName**.api.cognitive.microsoft.com/qnamaker/

Is the only way to successfully call a qna or luis resource which is behind a vnet. 

We have seen an increasing need for this feature with multiple customers attempting to use dispatcher with QnA and LUIS resources behind a VNET. Can we please have an ETA of when this feature will be implemented in dispatcher?

**Comment by tsuwandy** [comment]
@daelsala, we'll try to get this deployed before end of the week.

**Comment by tsuwandy** [comment]
@daelsala, https://www.npmjs.com/package/botdispatch v 1.7.5 is now available and should let user fully customize QnAMaker kb API url.

Follow these steps to customize QnAMaker API endpoint url:

Where you Dispatch CLI is installed, ie C:\Users\<username>\AppData\Roaming\npm\node_modules\botdispatch\bin\netcoreapp2.1

Edit appsettings.json, replace this line:

 "QnAMakerEndpointUrlFormat": "https://{0}.api.cognitive.microsoft.com/qnamaker/v4.0"
with

"QnAMakerEndpointUrlFormat": "https://<QnAMakerEndpointBehindVNET>/qnamaker/v4.0"

Run "dispatch refresh" or "dispatch create" again

**Comment by daelsala** [comment]
Hello Tien,

Customer claims to have done the following steps, I am not sure if they followed them correctly or if there was an extra step they were supposed to add, but how to they add the custom domain? Please let me know if you see any red flags in the customers info below:

I have tried it and got the same error. Here's the steps I took


1.       Updated dispatch package with command "npm i -g botdispatch". The version was updated to 1.7.5 (see below in output)

2.       Opened the appsettings.json file. The settings has been added.

3.       Run dispatch process. Same error occurred. I am not sure if there is a new parameter I need to use for any of the dispatch commands. I checked documentation and didn't find anything.

PS C:\Users\dkonyayev> C:\Ezra\Dispatch\Create_DACC.ps1
Transcript started, output file is c:\ezra\dispatch\Logs\create_202103110925.log
What environment would you like to use to create dispatch domain?
Valid options are staging or production
You can also enter q to quit this process
Environment: staging
----------------------------------------------------------------------------------------------------------
What is the name of the chatbot dispatch domain you are creating (ex. Metlife.Sam.Covid19) ?
You can also enter q to quit this process
Domain: dispatch_test
----------------------------------------------------------------------------------------------------------
What is the chatbot culture or locale (ex. en-US, es-ES, pb-BR) ?
You can also enter q to quit this process
Culture: en-US
node.exe : dispatch_test.dispatch created
At C:\Users\dkonyayev\AppData\Roaming\npm\dispatch.ps1:15 char:3
+   & "node$exe"  "$basedir/node_modules/botdispatch/bin/dispatch.js" $ ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (dispatch_test.dispatch created:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

QnA kb id:af899630-c840-41fa-b5ce-01ead92f450f, name:bot-personality-professional-en-us, subscription key:defa1686e13e49e497253d4466128892 added to dispatch_test.dispatch
QnA kb id:e767bdfd-6a9e-498c-bf6a-28e301d13d94, name:dacc-en-us, subscription key:ae83cb40d9924eb48de4919320f254e8 added to dispatch_test.dispatch
node.exe : Exporting services for dispatch...
At C:\Users\dkonyayev\AppData\Roaming\npm\dispatch.ps1:15 char:3
+   & "node$exe"  "$basedir/node_modules/botdispatch/bin/dispatch.js" $ ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Exporting services for dispatch...:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Exporting bot-personality-professional-en-us QnA kb...
Exported QnA app JSON is at c:\ezra\dispatch\staging\dispatch_test\data\_Q_q_bot-personality-professional.json
Expanding kb af899630-c840-41fa-b5ce-01ead92f450f with word alterations
Exporting dacc-en-us QnA kb...
ERROR
One or more errors occurred. (The remote server returned an error: (403) Forbidden.)
Request url: https://westus.api.cognitive.microsoft.com/qnamaker/v4.0/knowledgebases/e767bdfd-6a9e-498c-bf6a-28e301d13d94/Test/qna?getFlattened=true
Response: {"error":{"code":"AccessDenied","message": "Access denied due to Virtual Network/Firewall rules. Your IP address is 216.163.247.3."}}
------
CREATE
Usage: dispatch create [options]
Usage: dispatch create [.bot file]

Create/retrain and publish a LUIS application for dispatch

Options:

   -b, --bot               [Optional] Path to .bot file or bot services json file
   -s, --secret            [Optional] Secret used to encrypt/decrypt .bot file
   -c, --culture           [Optional] Used to set LUIS app culture for dispatch. Required if none of dispatch source(s) is LUIS app.
   --dispatch              [Optional] Path to .dispatch file
   --dataFolder            [Optional] Dispatch working directory
   --hierarchical          [Optional] Default to true. If false, existing intents from source LUIS model(s) will be available as the dispatch intents.
   --copyLuisData          [Optional] Default to false, Dispatch app will not contain data from LUIS source(s).  They will be pulled for Dispatch app at training time.  If true, all utterances from LUIS model(s) will be copied to Dispatch app.
   --useAllTrainingData    [Optional] Default to true. LUIS UseAllTrainingData flag (see https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-reference-application-settings).
   --normalizeDiacritics   [Optional] Default to true.
   --normalizePunctuation  [Optional] Default to false.
   --dontReviseUtterance   [Optional] Default to false. Dispatch sometimes minorly revises an utterance for generalization. If set to true, utterances won't be revised.
   --publishToStaging      [Optional] Default to false. Publish to LUIS staging instead of production platform.
   --dedupeTrainingSet     [Optional] Default to false. If false, Dispatch won't dedupe duplicated training instances.
   --gov                   [Optional] Set to true to target Azure goverment.
   --remote                [Optional] Set to true if invoking remotely.
   --dontImport            [Optional] Default to false. If set to true, do not communicate with luis.ai for importing, training, and publishing the augmented LUIS JSON app
   --doAutoActiveLearning                     [Optional] Default to false. LUIS limit on training-set size is 15000. When a LUIS app has much more utterances for training, Dispatch's auto active learning process can intelligently down sample the utterances for training a model.
   --aalUseSubwordFeatures                    [Optional] Default to false. Enable auto-active-learning to use subword features.
   --aalNumberOfInstancesPerIteration         [Optional] Default to 2500. Max #instances processed during each auto-active-learning down-sampling iteration.
   --aalMaxNumberOfActiveLearningIterations   [Optional] Default to -1. Max number of auto active learning iterations, each processes a fixed batch of instances. Negative setting enables scanning through all available instances.
   --aalFixedNumberOfActiveLearningIterations [Optional] Default to -1. Fixed number of iterations to process all available instances. Number of instance batch in each instance is calaulated based on this parameter.
   --aalInitialNumberOfSamplesPerIntent       [Optional] Default to 20. Initial #instances randomly sampled for each intent before kicking off the auto-active-learning down-sampling process.
   --aalInitialNumberOfInstancesPerIteration  [Optional] Default to 200. #instance per iteration can be configured to grow until reaching aalNumberOfInstancesPerIteration.
   --aalNumberOfSamplesPerIntentGrowthRatio   [Optional] Default to 1.5. The growth rate of #instances per auto-active-learning iteration.
   --aalSelectionThreshold                    [Optional] Default to 0.5. Threshold for filtering out high confidence test instances from adding into training set during each auto-active-learning iteration.



Domain created done
Transcript stopped, output file is C:\ezra\dispatch\Logs\create_202103110925.log

PS C:\Users\dkonyayev> dispatch -v
1.7.5

PS C:\Users\dkonyayev>

***@***.***D7165C.654C23D0]



Best,
Daia
