### ISSUE TITLE
dispatch refresh v1.7.6 throws null reference exception

### ISSUE THREAD

**Issue by sschutten** [microsoft/botbuilder-tools#1510]
## Tool
Name: Dispatch
Version: 1.7.6
OS: Windows 10

## Describe the bug
Running dispatch refresh results in the following error:
```
ERROR
Object reference not set to an instance of an object.
```

Downgrade to v1.7.5 and using the identical dispatch file works as expected.

**Comment by hhasenauer** [comment]
I can confirm this issue with `dispatch add`

**Comment by anusharavindrar** [comment]
Attempting a repro results in NullReferenceException with `dispatch add` on v1.7.6. Investigating further.

**Comment by anusharavindrar** [comment]
@tsuwandy, any pointers on what might be causing this error?

**Comment by tsuwandy** [comment]
@anusharavindrar, found the issue.  Working on a fix, will update this once fix is deployed.  Thanks!

**Comment by tsuwandy** [comment]
@anusharavindrar, @sschutten, @hhasenauer, dispatch v 1.7.7 is deployed to npmjs with the fix.  Let me know if and reactivate this issue if you are still having issues with it.  Thanks!
