### ISSUE TITLE
Update tile thumbnails to match template & tutorial

### ISSUE THREAD

**Issue by mareekuh** [microsoft/botbuilder-tools#1512]
Currently, the build shows the placeholder tutorial tiles, and the tiles are stretched wide which does not look right.
Please create or identify illustration or graphic from Fluent/Azure asset library for the tutorial tiles with the following requirements:
- informative & relevant for the tutorial
- differentiating (user can tell the different tutorials apart
- preferably 1 line of sub-copy (tile "#2' see image below)
- dimensions are as follows
width: 253px; 
height: 138px;
left: 0px;
top: 0px;

Toolkit example
<img width="808" alt="Screen Shot 2021-04-17 at 6 16 14 PM" src="https://user-images.githubusercontent.com/48503434/115131048-a4511a00-9fa9-11eb-83ed-2eb10cd522d7.png">

Illustration examples in Cog.Services toolkit:  https://www.figma.com/file/mBEQmdk8jnySpn0JtRnlqu/Cognitive-Services-portal-UX-toolkit?node-id=970%3A39457
Brand central: https://microsoft.sharepoint.com/teams/brandcentral

**Comment by xiyangdesign** [comment]
The tiles image stretching issue should've been fixed in the more recent nightly build:) Will close this for now.
