### ISSUE TITLE
Dispatch init command is getting hanged and taking forever to complete

### ISSUE THREAD

**Issue by neelammourya** [microsoft/botbuilder-tools#1528]
## Issue Description:
I am trying to run the dispatch init command in my YMAL pipeline, but it is taking forever to complete. It is not giving any error.

## Commands Example:
dispatch init -n $appName --luisAuthoringKey "$luisKey" --luisAuthoringRegion westus

I even tried with remote property set to true like below:
dispatch init -n $appName --luisAuthoringKey "$luisKey" --luisAuthoringRegion westus -remote true

## Reproduction Steps:
Run below commands:
dispatch init -n $appName --luisAuthoringKey "$luisKey" --luisAuthoringRegion westus -remote true
dispatch add -t luis -i ${env:luisemailskillappid}  -n ${env:luisemailskillname}  -v 0.1 -k ${env:luisemailskillkey}  --intentName ${env:luisemailintent}
dispatch add -t luis -i ${env:luistodoskillappid}  -n ${env:luistodoskillname}  -v 0.1 -k ${env:luistodoskillkey}  --intentName ${env:luistodointent}
dispatch add -t luis -i ${env:luiscalendarskillappid}  -n ${env:luiscalendarskillname}  -v 0.1 -k ${env:luiscalendarskillkey}  --intentName ${env:luiscalendarintent}
dispatch add -t luis -i $luisAppId  -n ${env:luAppNameGe} -v 0.1 -k $luisKey --intentName l_General
dispatch add -t qna -i $qnaAppId -n $qnaAppName -k $qnaAppKey --intentName q_Faq
Write-Host "Creating Dispatch "
$app = dispatch create
$appId = (ConvertFrom-Json -InputObject (Out-String -InputObject ($app))).appId
Write-Output "##vso[task.setvariable variable=dispatchAppId]$appId"

## Expected Behavior:
Dispatch initi should run successfully and then it should add other luis models to the dispatch file

## Actual Results:
This command is getting hanged and not giving any error

@tsuwandy Can you please help here

**Comment by tsuwandy** [comment]
@neelammourya, could you try adding the flag “--remote true”?

**Comment by neelammourya** [comment]
> @neelammourya, could you try adding the flag “--remote true”?

Thank you so much for pointing it out, i was using -remote instead of --remote that was causing issues for me.
