### ISSUE TITLE
Not able to create knowledge base on QnA app created through ARM template

### ISSUE THREAD

**Issue by neelammourya** [microsoft/botbuilder-tools#1529]
## Issue Description:
I am creating QnA app using ARM template, then through powerShell script i am trying to create knowledge base into the same QnA app using its key. But it  is geting failed with below error, also tried from UI but there also it fails:

![image](https://user-images.githubusercontent.com/63057412/129852604-c8a58bc9-31e4-47d2-86b4-95a70a2d2254.png)

Error from UI:
![image](https://user-images.githubusercontent.com/63057412/129852723-06e3be14-cef8-49fe-992a-d3fbb78f7eea.png)

## Commands Example:
$appId = (ConvertFrom-Json -InputObject (Out-String -InputObject (bf qnamaker:kb:create --name $qnaAppName --subscriptionKey $key --in $qnaAppPath))).kbId

## Reproduction Steps:
After running my ARM template, i  have few other steps to run, then I run my powershell step to crate KB of newly created QnA.
## Expected Behavior:
It should create the KB and return the KB ID

## Actual Results:
It is throwing error at the line of creating KB

##Note:
I am able to manually create KB for the QnA app which is created through Azure portal

Please check if this is a service issue or what is causing this. @tsuwandy 
@RohitMungi-MSFT

**Comment by joshgummersall** [comment]
@tsuwandy can you take a look at this?

**Comment by tsuwandy** [comment]
@neelammourya, what is the CLI command you ran?  From the screenshot, looks like the parameters provided to the cli command is not correct.

**Comment by neelammourya** [comment]
> @neelammourya, what is the CLI command you ran? From the screenshot, looks like the parameters provided to the cli command is not correct.

I have shared you the ARM template which i am using to create QnA resources as well as the Script which is used to create knowledge base.

To narrow down the issues, i created i template in azure portal and with that i created QnA related resources, then just went to https://www.qnamaker.ai/ and tried creating Knowledge base. It still gives same endpoint error  what i have already attached in the issue.
3 people from my team has reported this same issue.

**Comment by tsuwandy** [comment]
More info from @neelammourya 

![image](https://user-images.githubusercontent.com/10739108/130025427-a3311b9a-e73e-47ec-94c1-89db98252ba6.png)

**Comment by neelammourya** [comment]
I had appsettings part missing in my ARM template QnA service code.

I had taken the template from here: [https://github.com/sebastianzolg/azure-qna-deployment/tree/master/src/qnaMaker](url)
And this has fixed the issue.
It was part of Microsoft.Web/sites resource used in QnA maker resource

You can close this request.
