### ISSUE TITLE
Hello everyone - is there a way we can fix the Image display size in the Teams chatbot conversation?

### ISSUE THREAD

**Issue by PrajwalShambhu1990** [microsoft/botbuilder-tools#1530]
Hello everyone - is there a way we can fix the Image display size in the Teams chatbot conversation?
 When i test the bot on QnAMaker, it display the results with correct image display as shown below.
![image](https://user-images.githubusercontent.com/50304499/131361591-14ab3a89-406f-44e0-a7d7-a66bb2aedf38.png)

The same is not displaying properly on the Teams chat window.

![image](https://user-images.githubusercontent.com/50304499/131370785-5fd600fe-9a87-43d2-b4b1-9d99fb2f455d.png)

How can we fix the image rendering issue on Teams chat window?

_Originally posted by @PrajwalShambhu1990 in https://github.com/microsoft/botbuilder-tools/issues/1409#issuecomment-908478121_

**Comment by clearab** [comment]
Please reach out to the Teams group directly using one of the methods outlined here: https://docs.microsoft.com/en-us/microsoftteams/platform/feedback
