### ISSUE TITLE
Authoring key not working uploading models to LUIS

### ISSUE THREAD

**Issue by jameslew** [Microsoft/botbuilder-tools#161]
**Describe the bug**
Something is not right about the API calls to LUIS/authoring keys.  I am trying to use the LUIS command to upload my LUIS model but keep getting errors with the authoring keys; either via .luisrc or --authoringKey parameter

**To Reproduce**

jameslew@DESKTOP-KLEMGA8:\~/repos/diabot$ cat .luisrc
{
  "authoringKey": "{myAuthoringKey}",
  "endpointBasePath": "https://westus2.api.cognitive.microsoft.com/luis/api/v2.0"
}
jameslew@DESKTOP-KLEMGA8:\~/repos/diabot$ luis add application --in ./inquiry.json
{
  "statusCode": 401,
  "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription."
}jameslew@DESKTOP-KLEMGA8:\~/repos/diabot$ luis add application --in ./inquiry.json --authoringKey {myAuthoringKey}{
  "statusCode": 401,
  "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription."

**Expected behavior**
Model to be created

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Comment by vishwacsena** [comment]
I believe this is fixed in 1.0.35. The issue was that we were accepting all luis endpoint regions in luis init. In the latest we only accept the 4 authoring regions. 

@jameslew can you please verify and reactivate if you still have an issue here?
