### ISSUE TITLE
Emulator is silent when encountering malformed/incorrect transcript files

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#165]
When opening a transcript file, if the file is either totally the wrong type or just perhaps slightly malformed it opens a new empty window and doesn't report it experienced issues parsing the transcript file or give any hints on how to resolve.

The nature of the chatdown CLI tool (piping) can quite easily lead to error information being piped to a file without the user realising then generating head-scratching downstream with an empty window in the Emulator.

**To Reproduce**
1. Go to Emulator (40.013-alpha)
2. Click on File. Open Transcript File - choose any old file
3. No error

**Expected behavior**
At the very least an error saying the file failed to read, ideally some help if it's actually a transcript file but something is missing but not critical.

[malformedTranscriptFile.txt](https://github.com/Microsoft/botbuilder-tools/files/1980218/malformedTranscriptFile.txt)
[invalidTranscriptFile.txt](https://github.com/Microsoft/botbuilder-tools/files/1980219/invalidTranscriptFile.txt)

**Comment by vishwacsena** [comment]
@emadelwany ; @eanders-MS - can you please take a look?

**Comment by emadelwany** [comment]
@vishwacsena - I can repro, will triage it for an upcoming release.

**Comment by szul** [comment]
Is this just with errors? I can't even get a transcript to open in the new emulator when I pull the samples directly from the chatdown repo. I just get a blank tab when I open the transcript file regardless.

I'm using the samples in the repo and the most recent alpha release of the emulator.

**Comment by emadelwany** [comment]
@szul can you please share the transcript file you're trying to open or which specific sample you were using?

**Comment by szul** [comment]
@emadelwany My first attempt was with [this transcript](https://gist.github.com/szul/45f138267b0bede5ffe2a93097a385a2), and when that didn't work, I generated a transcript from the [sample](https://github.com/Microsoft/botbuilder-tools/blob/master/Chatdown/Examples/Greeting.chat) in this repo, but to no avail... and that's a pretty basic sample.

Are there any restrictions on file placement? I put mine in a folder called `chats` in the root of the app.

**Comment by tonyanziano** [comment]
Hey @szul, did you try changing the file extension to `.transcript`? I just downloaded your transcript and was able to view it in the Emulator (v4.0.14-alpha) after changing the extension to transcript.

When you generate the transcript using chatdown, try making the extension of the output file `.transcript`.

Ex:

`chatdown sample.chat > sample.transcript`

**Comment by szul** [comment]
@tonyanziano Yeah, they're all `.transcript` files. Maybe I'll try uninstalling and reinstalling the emulator.

**Comment by szul** [comment]
Yeah, so I'm getting the following in the Developer Tools console when I load any transcript file--whether my own, or one generated from the sample greetings chat. Looks like the chatdown CLI is generating something invalid?

![Console Error](https://1drv.ms/u/s!AsXbi5E9HRsKs5loC0T3TPUw85nIgw)

**Comment by tonyanziano** [comment]
What version of chatdown are you running? 1.0.1?

**Comment by szul** [comment]
@tonyanziano Yes.

**Comment by tonyanziano** [comment]
@szul  Could you please share your .transcript file generated from `Greetings.chat` so I can compare it with my own?

**Comment by szul** [comment]
@tonyanziano 

Gist:
https://gist.github.com/szul/d17f182c45ad09d18f04d67c06cef5ce

Chatdown file:
https://1drv.ms/u/s!AsXbi5E9HRsKs5lp0fe4Xe-7NUjIQg

Transcript file:
https://1drv.ms/u/s!AsXbi5E9HRsKs5lqBE0Cmh-Ig1cUSg

**Comment by eanders-MS** [comment]
This is almost certainly a file encoding issue. The emulator needs transcript files to be utf-8 encoded. It will fail on anything else. We need to fix this in the code, but in the meantime can you verify your transcript file is utf-8?

**Comment by tonyanziano** [comment]
Was just able to repro the error by downloading your transcript file, saving it as Unicode big endian encoded, and trying to open it in the emulator.

Seems like @eanders-MS's assumption was right.

**Comment by szul** [comment]
Is this a chatdown CLI output issue or is it from the way my VSCode is saving the initial *.chat file?

**Comment by eanders-MS** [comment]
We've seen this before, when running the CLI tool from within VSCode's command window. Is that your workflow? Ultimately, it's an emulator issue. It should be more robust about loading text files of different encodings. It shouldn't care about encoding.

**Comment by vishwacsena** [comment]
This should be fixed with the latest [emulator](https://github.com/Microsoft/BotFramework-Emulator/releases/tag/v4.0.15-alpha) and the latest [CLI tools](https://github.com/Microsoft/botbuilder-tools). We pushed an update across the board to support different file encodings.
