### ISSUE TITLE
rename luis update version command to luis rename version 

### ISSUE THREAD

**Issue by srozga** [Microsoft/botbuilder-tools#172]
I have created a new LUIS json by using ludown parse over a .lu file. The json looks fine. I tried updating a version by using luis update version, but I get the error:
`FetchError: invalid json response body at https://westus.api.cognitive.microsoft.com/luis/api/v2.0/apps/a6159065-068f-465a-b69e-bc781891237f/versions/0.1/ reason: Unexpected end of JSON input`

It is unclear what may be happening. Any thoughts on debugging?

**Comment by vishwacsena** [comment]
@srozga - that's right. This might be an incorrect command for what it actually does. @tomlm we should probably consider updating this to be luis rename version instead. 

At the moment, there isn't a way for you to update an existing LUIS app version by passing in a new JSON payload. One option for you is to create a new luis application version using luis import version instead.

**Comment by srozga** [comment]
Thanks @vishwacsena, I know those are the semantics of the LUIS Authoring API so I suppose that makes sense. Always found it confusing.

I suppose for now I can simply do a hard delete version and import version. We're thinking of the scenario where we have a development LUIS App and we want it to be updated as part of a CI pipeline. I can imagine a world in which we simply use the .lu format in git and assume that is our master version.

Much thanks!
-s

**Comment by tomlm** [comment]
I am changing the name from update version -> rename version
