### ISSUE TITLE
can't install botdispatch

### ISSUE THREAD

**Issue by vjcspy** [Microsoft/botbuilder-tools#176]
i've installed dotnet core and when i run command to install botdispatch it show error. It's look like botdispatch try to install dotnet-2.0.0 without sudo permission.

/usr/bin/dispatch -> /usr/lib/node_modules/botdispatch/bin/dispatch.js

> botdispatch@1.0.0 postinstall /usr/lib/node_modules/botdispatch
> npm install -g dotnet-2.0.0

Unhandled rejection Error: EACCES: permission denied, open '/home/vjcspy/.npm/_cacache/tmp/3a1bd628'

┌──────────────────────────────────────────────────────────┐
│                 npm update check failed                  │
│           Try running with sudo or get access            │
│           to the local update config store via           │
│ sudo chown -R $USER:$(id -gn $USER) /home/vjcspy/.config │
└──────────────────────────────────────────────────────────┘
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! botdispatch@1.0.0 postinstall: `npm install -g dotnet-2.0.0`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the botdispatch@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vjcspy/.npm/_logs/2018-05-10T08_38_24_043Z-debug.log

Please help. Thanks.

**Comment by tsuwandy** [comment]
Dispatch might have already installed.  Did you try running the command “dispatch”? Or “dispatch init”?

**Comment by vjcspy** [comment]
Thank you for your promptly reply. But i've installed .NET Core Runtime. I tried to install both of mac and linux but failed. Please take a look at output of npm.
![image](https://user-images.githubusercontent.com/11264727/39904385-bb79e400-5501-11e8-9ee9-8586f187d685.png)

**Comment by tsuwandy** [comment]
I found a discussion thread here which may help:
https://github.com/npm/npm/issues/2049

There is one with installing nvm first which seems to help one of us with Linux here earlier.

**Comment by vishwacsena** [comment]
@vjcspy per your last comment you appear to be unblocked. For housekeeping, I'm closing this issue. 

@tsuwandy - can you please update dispatch readme as needed to help others that might run into this as well?
