### ISSUE TITLE
Bot builder v4 for Node.js

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/botbuilder-tools#184]
I would like to have Node.js support language for Bot builder v4. Any ideas on when its coming ?

**Comment by szul** [comment]
@rjgmail88 Can you clarify? The preview of the Node.JS SDK v4 is here:
https://github.com/Microsoft/botbuilder-js

This includes a roadmap for the SDK.

**Comment by rjgmail88** [comment]
Hi, I did not see node.js as supported language for Bot builder v4 so I wasn't sure. Also, example under following aren't updated ? [https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node](https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node)

**Comment by szul** [comment]
@rjgmail88 The README for the samples repo you link to specifically states that it is for SDK v3, and that SDK v4 samples can be found under the repos for their respective language SDKs. You can see the SDK v4 ones here: https://github.com/Microsoft/botbuilder-js/tree/master/samples

**Comment by rjgmail88** [comment]
Thanks. I missed it.
