### ISSUE TITLE
az bot webchat show throws ResourceNotFound

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/botbuilder-tools#185]
**Describe the bug**
Running `az bot webchat show` throws ResourceNotFound. However this behavior is inconsistent. It works some times and throws error other times. However once it starts throwing error, it will continue to do it until I recreate bot service.

**To Reproduce**
`az bot webchat show`

**Expected behavior**
Should show webchat resource

**Screenshots**
![image](https://user-images.githubusercontent.com/3169316/39980493-d14b854e-5769-11e8-95c8-9b870dd83ab8.png)

**Comment by swagatmishra2007** [comment]
seems like the bot record wasnt in our system at that time for some reason, are you still facing this issue? if so, please reopen
