### ISSUE TITLE
Dispatch handling of the None intent in component LUIS apps

### ISSUE THREAD

**Issue by srozga** [Microsoft/botbuilder-tools#190]
This is more of a question I was hoping the `dispatch` team could address. I am breaking down a LUIS app into various constituent parts. During Build, the LUIS team emphasized then importance of populating the None intent in LUIS to tell the model what it can't handle. I used the same utterances in the different apps, and `dispatch` came back with a report indicting the utterances are duplicated among the applications.

Now I am curious how dispatch handles the None intent. Say I have LUIS apps A and B and an Utterance X. Say X is in the None intent in A and in another intent in B. How does `dispatch` handle such scenarios? Shouldn't the None intent be treated differently than other as it pertains to routing across LUIS models?

**Comment by tsuwandy** [comment]
Hi Szymon, excellent question, thank you!  Currently, Dispatch treats individual models as black box.  To get Dispatch to work correctly today, one will have to clean up the None intent in the source models before training Dispatch.  

We will add this to our future Dispatch improvements.

**Comment by srozga** [comment]
Thanks @tsuwandy. Could you perhaps give a bit more context on what cleaning up entails at this time? Removing all utterances? Should those be populated into the None intent of the Dispatch model manually?

**Comment by tsuwandy** [comment]
Hi Szymon,  given your example, I would get rid of X since it exists in an intent within B.  Basically, any utterance in None intent of any app which exist in non None intent of other apps should be removed before training Dispatch.   

In the future, Dispatch should take care of this step.  Thanks!

**Comment by tsuwandy** [comment]
Szymon, will do!  I have created a work item to track this on our end.  Let us know if you run into any issues using the tool. Thank you!

**Comment by vishwacsena** [comment]
Closing this based on resolution above.
