### ISSUE TITLE
Luis delete Unexpected end of JSON input

### ISSUE THREAD

**Issue by srozga** [Microsoft/botbuilder-tools#191]
This is a false negative. When I populated my .luisrc file completely and run `luis delete version`, I receive the error: 
`FetchError: invalid json response body at https://westus.api.cognitive.microsoft.com/luis/api/v2.0/apps/{appid}/versions/0.1/ reason: Unexpected end of JSON input`
In fact, the version has been deleted so the command executed correctly.

**Comment by tomlm** [comment]
This was fixed with 2.0.2
