### ISSUE TITLE
Dispatch create error on importing model

### ISSUE THREAD

**Issue by sschutten** [Microsoft/botbuilder-tools#197]
I receive an error on importing the model when running `dispatch create`. The error doesn't provide any further information on what went wrong. The command hangs on importing the model for several minutes before it quits with the error.

**To Reproduce**
1. Initialize a new dispatch by running `dispatch init`
2. Add a LUIS and QnAMaker source using `dispatch add`
3. Create the dispatch model with `dispatch create`

**Expected behavior**
I would expect the dispatch model in LUIS to be created

**Output**
The output of running `dispatch create`:
![image](https://user-images.githubusercontent.com/10097564/40171890-0466c960-59cd-11e8-8fb7-3d50901df77c.png)

**Additional context**
I'm using "authoringRegion": "westeurope". My LUIS model is in west europe and the QnA model is in west us.

**Comment by tsuwandy** [comment]
Hi, I wonder if import timed out.  Could you retry "dispatch create" command?  Also, could you copy and paste NikkiLUISQnA.json file?  Or you could email NikkiLUISQnA.dispatch file to tiens@microsoft.com?  Thanks!

**Comment by tsuwandy** [comment]
I was able to repro.  We will get this fixed, thanks for reporting!

**Comment by tsuwandy** [comment]
Latest dispatch is published with fix for this issue. 
https://www.npmjs.com/package/botdispatch
