### ISSUE TITLE
AzureCLI: 'az bot create' doesn't complete in VSTS release process

### ISSUE THREAD

**Issue by jamesemann** [Microsoft/botbuilder-tools#199]
**Describe the bug**
The converged app registration requires the device login flow, which doesn't work in VSTS release pipelines.  

If I run ``az bot create -k webapp -g "testing123456" -n "testing123456-bot1" `` on my local dev environment, it works great.  If I try the same in a VSTS continuous release pipeline, it can't complete - it gets stuck on the device login prompt. 

Note this message isn't visible until you cancel the operation... so you can't manually work around it.

```2018-05-17T01:00:09.8640881Z D:\a\r1\a\_Build demos>call az bot create -k webapp -g "testing123456" -n "testing123456-bot1" 
2018-05-17T01:00:20.4406328Z WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code EE**D9**H to authenticate.
2018-05-17T01:15:53.3424014Z ##[error]The operation was canceled.
```

**To Reproduce**
1. Create a VSTS release pipeline
2. Add the 'Azure CLI' task
3. Reference a .bat, .sh, etc file with the Azure CLI script. Mine looks like this:
```call az extension add -n botservice
call az group create -l "UK South" -n "testing123456"
call az bot create -k webapp -g "testing123456" -n "testing123456-bot1"
call az bot show --msbot -n "testing123456-bot1" -g "testing123456" 
```
4. Run the release process

**Expected behavior**
Release process completes the bot registration.  Ideally, this would be completely automated.

**Comment by swagatmishra2007** [comment]
This is expected behavior for now. We can't create an msa appid and password on your behalf without having you login again. the team that handles this are working on a solution where it would be possible to do this without authentication, so once that work is done, this should go away.

As a workaround, you can specify an msaappid and password using --msa-app-id and --password and then you wont have the blocking token call.

**Comment by jamesemann** [comment]
@swagatmishra2007 thanks I see what you are saying and understand why you have closed this. 

For the workaround - and I appreciate this is not an issue specific to Bot Framework, but can I just ask if you know if it is it possible to me to generate this MSA App ID/Password separately - for example with the Azure AD cli or PowerShell? I haven't been able to find any good documentation on MSA, it seems like the converged app model in Azure AD will fix this, if it doesn't already. But again it is not clear to me how this works.  

It would be great if I could fix this for onboarding new developers to our project - the rest of the Azure provisioning workflow is fully automated.

Thanks!
