### ISSUE TITLE
luis: assigning subscription keys

### ISSUE THREAD

**Issue by srozga** [microsoft/botbuilder-tools#205]
I'm not sure if this is a feature that exists or not. Is it possible to assign a subscription key to an app via the luis tool? 

I know the APIs that seem to be related to it like [this one](https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c47) are deprecated. So I am not sure how I can automatically assign a subscription key from Azure to a LUIS app.

**Comment by vishwacsena** [comment]
@chrimc62 what's the recommended approach/ solution here?

**Comment by JeffCordes** [comment]
We are looking for a solution here also while building CI/CD release automation for LUIS.

**Comment by ukphillips** [comment]
This seems like a large oversight to remove the ability to programmatically associate a cognitive services key with a LUIS application. The the recommended approach just manual intervention until the release that fixes this is completed?

**Comment by vishwacsena** [comment]
Yes this is a known gap that the LUIS team is looking into. We are working through a solution that should be made available this calendar year.

**Comment by JeffCordes** [comment]
There is now an API to do this. [https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5be32228e8473de116325515](url)  

So it seems I can now do.
az login --service principal
az account get-access-token --subscription  (this token you need for the api)

then use Invoke-RestMethod to use the new api and that associates azure cs account to the luis account.

Then get the luis endpoint access keys from the azure cs account
az cognitiveservices account keys list --name

So all the pieces are there now.

**Comment by vishwacsena** [comment]
@cahann - can you comment on this? Is there a plan to rev the LUIS CLI to reflect the new APIs added? 
@sgellock, @tomlm FYI

**Comment by cahann** [comment]
yes but the new API was just released a couple of days ago so it'll still take us sometime to rev the LUIS CLI

**Comment by garypretty** [comment]
@cahann @vishwacsena Did this happen? Can you now set the subscription key via the CLI?

Thanks.

**Comment by chrimc62** [comment]
This has been implemented in bf cli.
