### ISSUE TITLE
LuDown CLI - Provide guidance to incomplete parameters

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#207]
LuDown should guide the user on missing parameters rather than terminate with no feedback

**To Reproduce**
1. Type LuDown, review commands (parse, refresh, help)
2. Type LuDown parse file.lu (incorrect!)
3. No response - tool terminates

**Expected behavior**
Highlight to the user missing commands (ToLuis or ToQnA) which aren't clear on the first help page leading users into expecting just parse to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/33519520/40475069-80cc0496-5f38-11e8-8234-fbc0bf8b2746.png)

**Comment by vishwacsena** [comment]
Fixed in v1.0.26
