### ISSUE TITLE
dispatch init fails with "did you mean to run..."

### ISSUE THREAD

**Issue by NiteLordz** [Microsoft/botbuilder-tools#212]
**Describe the bug**
Attempting to run the commands from https://github.com/Microsoft/botbuilder-tools/tree/master/Dispatch it fails when running "dispatch init..." with "Did you mean to run dotnet SDK commands?"

I have the dot net sdk installed (from the link provided), and have closed and reopened the node.js command prompt. same results.

**To Reproduce**

**Expected behavior**
To be able to follow the tutorial provided

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Insider Preview Build 17677

**Comment by tsuwandy** [comment]
Did you see any errors after the command to install the dispatch tool:
npm install -g botdispatch

**Comment by NiteLordz** [comment]
No, no error messages.

Is there a version or a method I can call to verify?

**Comment by tsuwandy** [comment]
What do you see when you just type “dispatch” in the command line?  You should see dispatch usage information displayed.

Also, could you try running “npm install -g dotnet-2.0.0.0” from the command line?

**Comment by NiteLordz** [comment]
I tried to run dispatch, and got the message to download DotNet.

I then installed using the command “npm install -g dotnet-2.0.0.0”. This yielded an error message of "No executable found matching command "dotnet-C:\Users\Stephen".

**Comment by tsuwandy** [comment]
Sorry, I got an extra 0 in the command, could you try running (as administrator):
npm i -g dotnet-2.0.0

Also, what's your npm and node version?  This is a Windows machine, correct?
npm -v
node -v

Thank you!

**Comment by NiteLordz** [comment]
Yea, i saw the extra .0 and already went thru and updated that.

as for versions, 

npm -v yielded 5.6.0
node -v yielded v8.11.1

**Comment by tsuwandy** [comment]
Thanks! Any error from running the command "npm i -g dotnet-2.0.0"?  And you are running Windows on the machine?

**Comment by NiteLordz** [comment]
No error from running 2.0.0

And yes, windows 10 insider build 17677

**Comment by tsuwandy** [comment]
can you run "dotnet" from the command line after running the command "npm i -g dotnet-2.0.0"?

**Comment by NiteLordz** [comment]
running dotnet from the command line yields the usage declarations

running dispatch from the command line yields "No executable found matching command "dotnet-C:\Users\Stephen"

**Comment by NiteLordz** [comment]
so i am looking for the dispatch command (is it cmd, exe, ...?)

i am curious if my name has a space in it is causing it to not be found.

**Comment by tsuwandy** [comment]
it's just a js file actually, dispatch.js in bin folder where the package is installed.  

i'm just confused by this "dotnet-C:\Users\Stephen", guessing you are right, is there space after Stephen?

also, if you found dispatch.js, perhaps you could try modifying the following line:

require('child_process').execSync('dotnet ' + __dirname + '/netcoreapp2.0/Dispatch.dll ' + args, { stdio: [0, 1, 2] });

to 

require('child_process').execSync('dotnet "' + __dirname + '/netcoreapp2.0/Dispatch.dll" ' + args, { stdio: [0, 1, 2] });

**Comment by NiteLordz** [comment]
BOOM!

dispatch command now displays usage !!!

thanks sir

**Comment by tsuwandy** [comment]
updated package published.
