### ISSUE TITLE
Chatdown: consider fixed bot ID and user ID

### ISSUE THREAD

**Issue by compulim** [Microsoft/botbuilder-tools#213]
Every time a transcript is generated out of a `.chat` file, the bot ID and user ID will be changed. According to [`Chatdown/lib/index.js:61`](https://github.com/Microsoft/botbuilder-tools/blob/master/Chatdown/lib/index.js#L61), both ID will be generated using UUID.

When we commit a transcript file to Git, a small update to the Chatdown file will update the ID, which result in lots of unnecessary changes.

It will be great if the bot ID and user ID can be specified or fixed.

**Comment by tomlm** [comment]
checked in
