### ISSUE TITLE
AZ CLI publish error: the following arguments are required: ---

### ISSUE THREAD

**Issue by jamesemann** [Microsoft/botbuilder-tools#219]
**Describe the bug**
If I run az bot publish following the instructions I see the error "az bot publish: error: the following arguments are required: ---"
Occurs with Version 0.0.2 of botservice az extension.

**To Reproduce**
1. Run ``az bot publish -g "simplebot2018-resourcegroup" -n "simplebot2018"``
2. See the following error:
```
az bot publish: error: the following arguments are required: ---
usage: az bot publish [-h] [--verbose] [--debug]
                      [--output {json,jsonc,table,tsv}] [--query JMESPATH] ---
                      _ --resource-group RESOURCE_GROUP_NAME --name NAME
                      [--git-url GIT_URL] [--git-token GIT_TOKEN]
                      [--git-branch GIT_BRANCH] [--code-dir CODE_DIR]
```

**Expected behavior**
A clear description of expected parameters if this is intentional.

**Screenshots**

![image](https://user-images.githubusercontent.com/6830648/41195505-5cb3ceea-6c26-11e8-9421-618aa3f6678f.png)

**Comment by swagatmishra2007** [comment]
i can repro this. will fix and update the extension .thanks for reporting!

**Comment by swagatmishra2007** [comment]
this should be fixed now. please get the latest extension via - 
az extension remove -n botservice
az extension add -n botservice (you should have 0.0.3 version now)
