### ISSUE TITLE
MSBot sees parameters as missing even though they are passed in

### ISSUE THREAD

**Issue by szul** [Microsoft/botbuilder-tools#222]
**Describe the bug**
Using the `msbot` command line utility: The `--help` gives me different parameters than the README docs, and connecting azure keeps saying my `subscriptionId` is missing, while connecting LUIS keeps saying my `appId` is missing--even when I have those parameters set on the command line.

Is there some sort of validation that is occurring with the actual services?

**Comment by szul** [comment]
@vishwacsena @tomlm I was able to get this to work, so I don't think this is a bug per se, but the documentation being mismatched from the expected parameters makes things difficult to work through. Is anybody working on updating the README? If not, I'd be happy to do a PR.

Another potential issue is that an error message of the parameter being absent also seems to be the error that returns when a parameter is malformed (or if the UUID is not valid), so that can be misleading.

**Comment by vishwacsena** [comment]
@szul glad to hear that you were able to resolve this. Please feel free to do a PR! Thanks a bunch.

**Comment by szul** [comment]
README updated in PR #223, which will solve the confusion in this issue.
