### ISSUE TITLE
dispatch: Ability to override version name

### ISSUE THREAD

**Issue by srozga** [Microsoft/botbuilder-tools#224]
We would like to be able to name the version that gets created when we call `dispatch refresh`. Reason being is that we already have control over the versions of each of our LUIS applications and would like to tie those version names to what's in dispatcher. There's probably something to be said about being able to easily rollback without doing a re-gen or compare the versions in a diff tool of some sort, though we haven't had that need quite yet.

Being able to do this by either setting a version name in the .dispatch file or as a command line param would work.

**Comment by tsuwandy** [comment]
Good one, will add this to our list.  Thanks!

**Comment by tsuwandy** [comment]
Latest dispatch update is published.  You can now supply optional parameter "version" to the "refresh" command.  https://www.npmjs.com/package/botdispatch

Thanks for the feature suggestion!
