### ISSUE TITLE
msbot: can’t add luis connection

### ISSUE THREAD

**Issue by anastasiia-zolochevska** [Microsoft/botbuilder-tools#23]
Adding luis connection:
msbot connect luis --secret EncryptItPlease --name "My Luis Model" --appId “id" --version v0.1 --authoringKey “key"

No errors, but 'msbot list’ doesn’t list this connection (see screenshot)

![screen shot 2018-04-04 at 1 41 46 pm](https://user-images.githubusercontent.com/3801171/38333818-84f4b51e-380e-11e8-91af-fa3ca48ebe34.png)

**Comment by tomlm** [comment]
fixed with 1.0.9-alpha
