### ISSUE TITLE
ludown refresh: optional auto-gen line

### ISSUE THREAD

**Issue by srozga** [Microsoft/botbuilder-tools#230]
**Is your feature request related to a problem? Please describe.**
We use ludown to export our LUIS apps and we maintain the exported .lu file in git. Most times, the LUIS models don't change at all but git finds a diff because the first line of the `ludown refresh` output is:
`> ! Automatically generated by [LUDown CLI](https://github.com/Microsoft/botbuilder-tools/tree/master/Ludown), Tue Jun 19 2018 08:29:47 GMT-0400 (Eastern Daylight Time)`

Ideally, we would have an easy way to _not_ include this line so we could use a toolchain based on git diffs.

**Describe the solution you'd like**
A command line flag into `ludown refresh` should be sufficient.

**Describe alternatives you've considered**
We could write some scripts to remove that first line from the ludown refresh output. Would prefer to keep it native to ludown if possible. Others might find this useful. 

Looking forward to your feedback.

**Comment by vishwacsena** [comment]
Fixed in version 1.0.28. 

You can now do ludown refresh -i <luis json file> -s | --skip_header
