### ISSUE TITLE
MSBOT: Add samples/ structure to use .bot file in my bot code

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#238]
.bot file has service references; we should streamline the structure to enable being able to use my .bot file in the bot code especially to pull IDs and keys to provide to LUIS and QnA recognizers to talk to the service. 

This is also required for a good E2E solution for #237

**Comment by szul** [comment]
Is there currently no way to pull the bot file configuration into the bot code short of loading the JSON and parsing it manually?

**Comment by szul** [comment]
In the meantime, I put this together as a JavaScript/Node module to load, parse, and decrypt the bot file in your bot code... it’s a start: https://github.com/szul/botbuilder-config

**Comment by vishwacsena** [comment]
Covered via V4 samples using the bot configuration library.
