### ISSUE TITLE
[chatdown]: Malformed configuration error

### ISSUE THREAD

**Issue by kbrimble** [Microsoft/botbuilder-tools#241]
## Information:
* Tools Libraries: chatdown
* Libraries' Versions: 1.0.3
* OS: Mac OS

## Issue Description:
When using a simple .chat file such as:
```
bot=Bot
user=User

user:hello
bot:please add an attachment.
```

Running: `$ chatdown sample.chat > sample.transcript` produces the error
> Error: Malformed configurations options detected. Options must be in the format optionName=optionValue

**Comment by vishwacsena** [comment]
Unable to reproduce this issue. Can you please attach your actual file and reactivate if you continue to see this issue? 

![image](https://user-images.githubusercontent.com/20918136/41859950-3732d6ce-7852-11e8-9c13-60e876b302b4.png)

**Comment by kbrimble** [comment]
@vishwacsena still receiving this. I noticed that you tried this on Windows. Perhaps me being on macOS makes a difference.

<img width="779" alt="chatdown" src="https://user-images.githubusercontent.com/2620389/41966183-66956a30-79f6-11e8-9730-cb892187a88f.png">

[simplechat.chat.txt](https://github.com/Microsoft/botbuilder-tools/files/2140639/simplechat.chat.txt)
