### ISSUE TITLE
[Chatdown] Error parsing chatdown files with \n instead of \r\n as line breaks

### ISSUE THREAD

**Issue by pcostantini** [Microsoft/botbuilder-tools#252]
Error when parsing .chatdown file with `\n` instead of `\r\n` for line breaks.
Repro on latest version (1.0.4). Did not happen with version 1.0.2.

**Error message:**
Error: Malformed configurations options detected. Options must be in the format optionName=optionValue

**Possible issue**
https://github.com/Microsoft/botbuilder-tools/blame/master/Chatdown/lib/index.js#L435

**Possible solution**
Should the line split be done using a RegEx that works on multiple systems?
E.g.: `var parts = fileContents.split(/\r?\n/)`

**Comment by tomlm** [comment]
This has been fixed
