### ISSUE TITLE
QnA Word Alterations added to Ludown?

### ISSUE THREAD

**Issue by wilsondy** [Microsoft/botbuilder-tools#263]
I can't find any documentation or examples for the QnA word alterations inside of ludown files.  It would be nice to be able to place them there and have them flow throw with the ludown tool and the qnamaker tool.

Syntactically, they seem pretty similar to the LUIS closed lists.

**Comment by vishwacsena** [comment]
@wilsondy can you please clarify what you mean by word alterations? Are you referring to [metadata](https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/metadata-generateanswer-usage#metadata-example) or something else?

**Comment by wilsondy** [comment]
No, see "Use Synonyms" here: https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/concepts/best-practices

And 

https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/5ac266295b4ccd1554da75fd

**Comment by vishwacsena** [comment]
@wilsondy this is now available in ludown version 1.0.31. You can do 
```bash
> npm i -g ludown
```
to pick up the latest. 

[Alterations in .lu file](https://github.com/Microsoft/botbuilder-tools/blob/master/Ludown/docs/lu-file-format.md#qna-maker-alterations)

[Parsing alterations](https://github.com/Microsoft/botbuilder-tools/blob/master/Ludown/docs/create-qna-json.md#creating-word-alterations-synonyms-list)

[Replacing alterations using QnAMaker CLI](https://github.com/Microsoft/botbuilder-tools/blob/master/Ludown/docs/create-qna-json.md#replacing-qna-maker-word-alterations-synonyms-list)

Alterations are also supported in the [refresh command](https://github.com/Microsoft/botbuilder-tools/blob/master/Ludown/docs/commands.md#refresh-command) as well in [translate command](https://github.com/Microsoft/botbuilder-tools/blob/master/Ludown/docs/commands.md#machine-translate-lu-files)

**Comment by neerajsagar** [comment]
Guys.. This is really good tool to add synonyms on qnamaker service..
http://query-me.com/qnamaker/SynonymEditor.aspx
