### ISSUE TITLE
Error: MSA App ID already in use thrown while provisioning a new Bot Service in Azure using ARM Template

### ISSUE THREAD

**Issue by mutanttech** [Microsoft/botbuilder-tools#264]
**Describe the bug**
Error: "MSA App ID already in use" thrown 3 times while provisioning a new Bot Service in Azure using ARM Template. 
Each time I have deleted existing and created a new registration on https://apps.dev.microsoft.com portal and also deleted the incorrect resource group provisioned on Azure Portal.

**To Reproduce**
1. Deploy any Bot Service using ARM template
2. Provide AppID and Secret generated after App Id Registration

**Expected behavior**
It should work because the new app registration is done and it is being used in ARM template and PS script using command:
```
$result = New-AzureRmResourceGroupDeployment `
	-DeploymentName $deploymentName `
    -ResourceGroupName $ResourceGroupName `
    -TemplateFile $Template `
    -TemplateParameterFile $TemplateParameters `
    @additionalParameters `
	-Verbose
```
**Screenshots**
Please refer to screenshot below:
![image](https://user-images.githubusercontent.com/98785/42692408-38816ae2-86c9-11e8-82ac-9f49ad89cee7.png)

**Desktop (please complete the following information):**
 - OS: Win 8.1 Enterprise
 - Browser: N/A

**Comment by mutanttech** [comment]
@vishwacena, Please let me know any update on abovementioned.

**Comment by swagatmishra2007** [comment]
this is a botframework service side issue and is being fixed. I will update the thread once the fix is deployed on the service.

**Comment by mutanttech** [comment]
@swagatmishra2007, From your comment above I understand that the reported issue is confirmed from the Service Team and they are pursuing it. But this looks to be a bigger problem, as it will halt the process of setting up new Bot Service using ARM Template. I have tried a new deployment today, but it failed as well with same error message.

![image](https://user-images.githubusercontent.com/98785/42803948-25208452-89c5-11e8-816e-64ba5f8f0a59.png)

Can I get any tentative timeline about the fix and more details on this issue? Thanks..

**Comment by swagatmishra2007** [comment]
a potential fix has been deployed for this. Are you trying to use a particular app id for creating the bot? if so, it's possible that the appid got written to the records  and so it's not allowing the same appid to be used to create a new bot. Can you try creating a bot with a new appid? If for some reason, you need to use a particular appid, let me know the appid.

**Comment by dazhao-msft** [comment]
@swagatmishra2007 can you please confirm if the following "multi-tenancy scenario" is what you're going to support and a fix is being deployed for it?

Scenario:
I have a bot service (a REST API service) running with a pair of app id/app secret, which connects to a bot channels registration entry. With the fix, I will be able to add more bot channels registration entries with the same app id/app secret and same endpoint to connect to the same bot service.

**Comment by dazhao-msft** [comment]
BTW, I used the following Azure CLI command to register multiple channels registrations with the same app id this morning. It still returns "MsaAppId: MsaAppId is already in use.."

Command:
```
az bot create --kind registration --name test-test2 --resource-group dazhao-bot-group --appid {{appid}} --password {{password}} --endpoint https://contoso.com/api/messages --location global
```

**Comment by carlosscastro** [comment]
@dazhao-msft This was a bug on the usage of a single app id + password. Multi-tenancy in the way you are requesting it is not something we plan on supporting right now. That means that one app id can only be related to one bot. Feel free to add another issue for this.

Closing this one since the original bug is now fixed.

**Comment by Saleem-Syed** [comment]
@swagatmishra2007 we have the same issue, but in my case we need to use specific application id.. Is there an alternate approach we can use to clear the records and use this appid?
