### ISSUE TITLE
LuDown JS files need to move from /bin/ to /lib

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-tools#276]
**Describe the bug**
The .js files found in the /bin/ directory for LuDown should be moved to the Lib directory. Only the ludown.js file should remain. 

Ludown.js should be renamed -> "ludown". 

**Expected behavior**
Only the "ludown" file should be in the /bin/ directory. Other files should be in the lib directory.

**Comment by JuanAr** [comment]
We reopen this issue since we found issues after moving several .js files from bin/ to lib/. We need to investigate further to remove all extra .js files from bin folder.

**Comment by vishwacsena** [comment]
@JuanAr this appears to be fixed in the latest in master. Is there any pending work here? If not, can we close this?

**Comment by JuanAr** [comment]
@vishwacsena yes it is fixed. I'll close this issue now. Thanks!
