### ISSUE TITLE
QnAMaker: list for any resources throws 'ArgumentError: The operation does not exists'

### ISSUE THREAD

**Issue by JuanAr** [Microsoft/botbuilder-tools#278]
** QnAMaker list operation doesn't work**
The list operation for any resources (alternations/endpoints/kb) throws 'ArgumentError: The operation does not exists'

**To Reproduce**
1. npm install qnamaker -g
2. qnamaker init (and enter valid QnA Maker credentials
3. qnamaker list alternations

**Expected behavior**
A list of alternations is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/805847/43158914-3afc2b02-8f81-11e8-8cc5-4c9a58a7cbac.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Nodejs v10.7.0

**Comment by vishwacsena** [comment]
@JuanAr - you have a typo in your command. the correct command is 

```bash
> qnamaker list alterations
```

I verified that this works in the latest qnamaker version.
