### ISSUE TITLE
Chatdown: ConversationUpdate activity does not provide the recipient information

### ISSUE THREAD

**Issue by ejadib** [Microsoft/botbuilder-tools#280]
**Describe the bug**
The conversation activity does not provide the recipient information. This seems due to a bug in https://github.com/Microsoft/botbuilder-tools/blob/master/Chatdown/lib/index.js#L176 where the recipient information is tried to be retrieved using `botId `as key.

**To Reproduce**
1. Generate a transcript out of https://github.com/Microsoft/botbuilder-tools/blob/master/Chatdown/Examples/ConversationUpdate.chat
2. Check that the `conversationUpdate  activity in the transcript doesn't have the recipient information

**Expected behavior**
The `conversationUpdate` activity should have the recipient information

**Screenshots**
The screenshot below shows that the `conversationUpdate` activity in the transcript does not have the recipient information.

![image](https://user-images.githubusercontent.com/307826/43293000-6b1aec54-910e-11e8-80c2-dd263cde6bb7.png)

**Comment by ejadib** [comment]
BTW, the from property is also missing

**Comment by tomlm** [comment]
fixed in chatdown 1.0.10
