### ISSUE TITLE
Use Lerna to manage build & publish tasks

### ISSUE THREAD

**Issue by JuanAr** [Microsoft/botbuilder-tools#295]
**Build script is getting complex and difficult to maintain **
Since the botbuilder-tools repo contains several published packages, tests and CI metrics the build script is growing in lines and complexity making it difficult to troubleshoot and maintain.
We had a good experience using lerna to manage build and publish tasks in the https://github.com/Microsoft/Recognizers-Text repo. We can reuse that knowledge in this repo as well.

**Describe the solution you'd like**
Building and publishing packages should be a single line script. The build script should be as simple as ` lerna bootstrap` 

**Describe alternatives you've considered**
We can continue using bash based build script as long as we want. Lerna is just an optional improvement as A tool for managing JavaScript projects with multiple packages.

**Additional context**
Lerna is being already used in https://github.com/Microsoft/Recognizers-Text and  https://github.com/Microsoft/botbuilder-js repo.

**Comment by vishwacsena** [comment]
I believe this is complete..
