### ISSUE TITLE
MSBot: Include TSLint as part of CI

### ISSUE THREAD

**Issue by JuanAr** [Microsoft/botbuilder-tools#313]
**CI is running ESLint for most tools. MSBot is based on TS and its generated JS code ignored**
Since MSBot is entirely based on TS code is seems more suitable for TSLint than ESLint. It was added to the ignore list for ESLint.

**Describe the solution you'd like**
We should simply include TSLint as part of CI and run it against the MSBot code on each commit.

**Additional context**
We want to include as much code quality improvements as possible in this repo.

**Comment by vishwacsena** [comment]
@JuanAr - I see several PRs that have been merged. Closing this as complete. Let's file a new ticket for any scoped work that remains.
