### ISSUE TITLE
No way to update Dispatcher LUIS app's utterances when LUIS app/QnAMaker changes 

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/botbuilder-tools#319]
**Describe the bug**
I am not sure if this is known bug but I am seeing an issue where I am locked down with my luis dispatcher app. I followed this [doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=csaddref%2Ccsbotconfig) and created dispatcher form my 1 Luis app and 1QnA service. 

After 2 days child luis app had some updates in intents, entities and utterances. Also QnA KB changes where new QnA pairs added. Of course I wanted incorporate these changes in Dispatcher Luis app. 
So I thought I would run **dispatch refresh** & it will solve my issue. But it didn't. 

**To Reproduce**
1. Create a luis dispatcher app using [https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=csaddref%2Ccsbotconfig](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&tabs=csaddref%2Ccsbotconfig)
2. Change something in child apps , LUIS and/OR QnA
3. run dispatch refresh
4. Go to Intents of dispatcher app > look at utterances. There were no changes. 

**Expected behavior**
How to keep luis dispatcher app up to date when children apps changes.

**Comment by tsuwandy** [comment]
Hi, I just tried this and it seems to work fine.  I updated the child LUIS app, then run "dispatch refresh", check to intent for the child LUIS app and I was able to find the new utterances I added. 

What version of Dispatch you have?  The latest one is 1.0.7 (one I tried) although this functionality hasn't changed.

**Comment by rjgmail88** [comment]
I am using 1.0.2 version. @tsuwandy , should I be using **dispatch refresh** command or there is anything else I am missing.?
What's the recommended approach in such cases?

**Comment by rjgmail88** [comment]
@tsuwandy , I am still not seeing updated on dispatch app after doing **dispatch refresh**

**Comment by vishwacsena** [comment]
@rjgmail88 - did your keys change? I just tried this again and cannot repro this with dispatch 1.0.7. Also can you try to publish your child LUIS and QnA maker applications before you tried dispatch refresh.

**Comment by hcyang** [comment]
@rjgmail88, please try again with the latest release.
