### ISSUE TITLE
QnAMaker auto-generated code in api directory are below 40%

### ISSUE THREAD

**Issue by enzocanoo** [Microsoft/botbuilder-tools#321]
**Is your feature request related to a problem? Please describe.**
The code in [`QnAMaker/lib/api`](https://github.com/Microsoft/botbuilder-tools/tree/master/QnAMaker/lib/api) directory is auto-generated and its coverage is below 40%

**Describe the solution you'd like**
We should skip the auto-generated code from code coverage metrics.

**Describe alternatives you've considered**
Another alternative that we could take is to generate trivial tests for the code.

**Comment by sgellock** [comment]
Yes please skip the auto generated code from code coverage metrics.
