### ISSUE TITLE
SuggestedActions only appears if its the last item in the chat

### ISSUE THREAD

**Issue by drmcghee** [Microsoft/botbuilder-tools#322]
**Describe the bug**
When using SuggestedActions in Chat, it will only appear in the emulator when its the last item of chat.

**To Reproduce**
Any suggested actions not on last line will be ignored
bot: Do you like cheese? [Suggestions=Yes|No]

**Expected behavior**
It may be that this is expecting user input - perhaps there should be a prompt or list function instead.
It is unusual however as the chatdown is largely static and this allows user input and provides an error in the console"does not have an endpoint, cannot post message actvity"

**Comment by tomlm** [comment]
this is emulator behavior, not chatdown, and known issue which will be fixed when chat supports step by step playback of activities
