### ISSUE TITLE
Malformed .bot file generates general JSON error

### ISSUE THREAD

**Issue by darrenj** [microsoft/botbuilder-tools#340]
If a developer (accidentally) leaves the .bot file with a syntax error (e.g. trailing , on an element with no element following a deletion), running the msbot tool generates a vague JSON error rather than highlighting it's found a problem with the provided Bot file.

**To Reproduce**

Bot File:

```
{
    "name": "PrototypeBot",
    "description": "",
    "secretKey": "",
    "services": [
        {
            "appId": "",
            "id": "http://localhost:3978/api/messages",
            "type": "endpoint",
            "appPassword": "",
            "endpoint": "http://localhost:3978/api/messages",
            "name": "PrototypeBot"
        },
        {
            "type": "qna",
            "id": "d07d0b81-f6d6-4b8b-8711-b7ddbb4e5629",
            "name": "skillprototypebot_faq",
            "kbId": "d07d0b81-f6d6-4b8b-8711-b7ddbb4e5629",
            "subscriptionKey": "YOURKEY",
            "endpointKey": "ENDPOINTKEY",
            "hostname": "https://yourresource-qna.azurewebsites.net/qnamaker"
        },
    ]
}
```
Run

`msbot connect luis --name skillprototypebot_general --bot ..\SkillPrototypeBot.bot --appId APPID --authoringKey YOURAUTHKEY --subscriptionKey YOURSUBSCRIPTIONKEY
`
Error Raised:

SyntaxError: Unexpected token ] in JSON at position 797

**Expected behavior**
Validate the Bot file for valid JSON during parsing and highlight the issue as being due to a malformed Bot file to the user clearly.

**Comment by sgellock** [comment]
bot files are deprecated.
