### ISSUE TITLE
Dispatch tool available as NuGet package

### ISSUE THREAD

**Issue by mennolaan** [Microsoft/botbuilder-tools#345]
We are creating a bot app for a client. To run the dispatch tool manually is not really handy for the client so we're investigating the possibilities of running the dispatch tool in azure as a function, opposed to from CMD prompt.

I would like to request to have this dispatch tool available as a NuGet package so we can use azure functions to run or dispatch files.

If anybody has a solution, I would greatly appreciate it. I have tried importing the Dispatch.dll in our azure function project without success. We're using c# functions, would creating a JS functions project be a solution to somehow?

**Comment by tsuwandy** [comment]
Will be fixed when all tools are published for Ignite.

**Comment by hansmbakker** [comment]
@tsuwandy can you please give a status update of this?

Also, this feature request is related: https://github.com/Azure/azure-sdk-for-net/issues/5278

**Comment by sealight** [comment]
Any update about this?
