### ISSUE TITLE
Process multiple Chatdown files at once

### ISSUE THREAD

**Issue by szul** [Microsoft/botbuilder-tools#350]
Currently, Chatdown files need to be processed one at a time. To process multiple files, you need to use a folder watcher like Chokidar, or alternative means, such as a PowerShell one-liner and a VSCode task.

The Bot Builder Community team has built out a preview solution on top of Chatdown called [chatdown-glob](https://github.com/BotBuilderCommunity/botbuilder-community-tools/tree/master/packages/chatdown-glob) that can be installed globally, and accomplishes this task. It would be nice to eventually fold this into the core Chatdown CLI. An `-r` or `--recursive` switch could be used on the command line to identify the action as a recursive one for all files, and then the code from chatdown-glob could be folded in and utilized.

We would be more than will to add in this functionality, and do a PR if desirable.

**Comment by vishwacsena** [comment]
@tomlm we should look to snap to ludown. I use -l <folder_name> and optionally add -s to recursively include sub-folders as well.

**Comment by szul** [comment]
@vishwacsena @tomlm The [Bot Builder Community](https://github.com/BotBuilderCommunity) is more than willing to do a PR on this, since we already built the functionality with [chatdown-glob](https://github.com/BotBuilderCommunity/botbuilder-community-tools/tree/master/packages/chatdown-glob). Just give us the nod, and we'll fold it in using the command line switches you referenced from LUDown.

**Comment by vishwacsena** [comment]
@szul - yes. sounds good. look forward to the PR. Please include unit tests as well. Thanks!

**Comment by szul** [comment]
@vishwacsena @tomlm Integrated the code locally. Will write the unit tests before doing a PR. Probably sometime this weekend.
