### ISSUE TITLE
Dispatch refresh takes forever to finish

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/botbuilder-tools#354]
**Describe the bug**
I have created a dispatch app with 4 faq's and 1 luis. When I had 2 faq's and 1 luis , dispatch refresh used to finish quickly and I saw updates. But, now with more faqs and luis total 5 apps it takes time and never finishes. 

cmd control is stuck on Training phase as mentioned below. 

**Expected behavior**
Dispatch refresh command should be able finish importing , training and publishing within reasonable  time limit. 

```
Exporting services for dispatch...
Exporting CalendarAssistantDev LUIS application...
Exporting HRQnA QnA kb...
Exporting CEPKb QnA kb...
Exporting ExperienceGeneralKb QnA kb...
Exporting ExperienceStrategistKb QnA kb...
Creating dispatch LUIS model json...
Creating training data...
WARNING: Number of samples in '/Users' that were used by multiple categories: 60
WARNING: Number of samples in '/Users//
WARNING: Number of samples in '/Users//
Updating DispatchDev model...
Importing DispatchDev model...
Training DispatchDev model...
**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

```

**Additional context**
Are there any known performance issue with dispatch tool ?
Can we use dispatch refresh to add each child model one by one?

**Comment by vishwacsena** [comment]
@Zerryth can you help investigate? 
@rjgmail88 - if possible can you share your luis/ qna models? 
@tsuwandy  FYI.

**Comment by rjgmail88** [comment]
@vishwacsena  , sorry can't share

**Comment by hcyang** [comment]
Hi @rjgmail88, as indicated in another thread, we suspect you have duplicate utterances that lead to zero-utterance intent in the dispatch model. Please remove duplicates and also try the latest Dispatch release.

Thanks,

**Comment by rjgmail88** [comment]
Is this correct latest version ?
+ botdispatch@1.0.7
