### ISSUE TITLE
Dispatch app is missing Utterances from few Qna's

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/botbuilder-tools#356]
**Describe the bug**
I am creating dispatch app with 1 luis and 4 faqs. Until the end everything work fine and I can see dispatch app created on luis.ai. But, there are few concerns 

1. I am not able to see any utterances under 2 Intents in dispatch app which supposed to be fetched from 2 respective qna's. 

Intent names as all follows. 
q_ExperienceStrategistKb
q_ExperienceGeneralKb

![image](https://user-images.githubusercontent.com/32375467/44602960-ccf7c600-a7a6-11e8-9256-f0374a1bae49.png)

2. Here are the logs from CMD that shows ExperienceStrategistKb and ExperienceGeneralKb was exported correctly. 

What does these WARNINGs mean ??

```
Exporting services for dispatch...
Exporting CalendarAssistantDev LUIS application...
Exporting HRQnA QnA kb...
Exporting CEPKb QnA kb...
Exporting **ExperienceGeneralKb** QnA kb...
Exporting **ExperienceStrategistKb** QnA kb...
Creating dispatch LUIS model json...
Creating training data...
WARNING: Number of samples in '/Dispatch/data/_experiments/model_011/train.txt' that were used by multiple categories: 60
WARNING: Number of samples in '/Dispatch/data/_experiments/model_011/cv5/fold000/train.txt' that were used by multiple categories: 42
WARNING: Number of samples in 'Dispatch/data/_experiments/model_011/cv5/fold000/test.txt' that were used by multiple categories: 7
WARNING: Number of samples in 'Dispatch/data/_experiments/model_011/cv5/fold001/train.txt' that were used by multiple categories: 42
WARNING: Number of samples in 'Dispatch/data/_experiments/model_011/cv5/fold001/test.txt' that were used by multiple categories: 6
WARNING: Number of samples in 'Dispatch/data/_experiments/model_011/cv5/fold002/train.txt' that were used by multiple categories: 41
WARNING: Number of samples in Dispatch/data/_experiments/model_011/cv5/fold002/test.txt' that were used by multiple categories: 3
WARNING: Number of samples in 'Dispatch/data/_experiments/model_011/cv5/fold003/train.txt' that were used by multiple categories: 41
WARNING: Number of samples in 'Dispatch/data/_experiments/model_011/cv5/fold003/test.txt' that were used by multiple categories: 6
WARNING: Number of samples in 'Dispatch/data/_experiments/model_011/cv5/fold004/train.txt' that were used by multiple categories: 39
WARNING: Number of samples in 'Dispatch/data/_experiments/model_011/cv5/fold004/test.txt' that were used by multiple categories: 3
Updating GinaDispatchDev model...
Importing GinaDispatchDev model...
Training GinaDispatchDev model...
Publishing GinaDispatchDev model...
Writing summary file...
{
  "authoringRegion": "westus",
  "hierarchical": true,
  "services": [


````
**To Reproduce**
Just used this [document](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-dispatch?view=azure-bot-service-4.0&branch=master&tabs=csaddref%2Ccsbotconfig) to create dispatch app. 

**Expected behavior**
All the questions from QnA's should be fetched under respective INTENT in Dispatch App. 

**Additional context**
Not sure if this issue is related another issue I reported where dispatch takes over 3-4 hours to finish.

**Comment by hcyang** [comment]
Hi @rjgmail88, from the Dispatch CLI  warning messages, your LUIS and QnA apps have some duplicate utterances. These duplicates will be de-duped by LUIS when the dispatch JSON model was uploaded to luis.ai, thus some intents may have zero utterances in them.

luis.ai will fail training an app with any zero-utterance intents. Dispatch CLI retries training LUIS models over transient failures, but early Dispatch CLI release will also retry for the zero-utterance failures -- this can lead to 3-4 hour training time that ends in failure. 

Recent Dispatch CLI release checks if there is any intent with zero utterances and will end the process with an error message.
