### ISSUE TITLE
[P1] Add --msbot option to luis import version

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#362]
Once you have a bot file configured with a luis application, you might want to update your luis application with a new version. In these cases, the .bot file should be updated with the new luis version. 

Ask: 
support --msbot flag on luis import version command.

**Comment by tomlm** [comment]
do you mean that you want to use the data from msbot get service to call into luis and get the version?

**Comment by vishwacsena** [comment]
@tomlm - no. this and #363 is about updating the .bot file with updates to specific fields under a service section in the .bot file. 

e.g. I have a luis service section with versionId = 0.1. I want to do something like this 

> msbot get service luisFoo | luis import version --stdin --in bar.json --versionId 0.2 --msbot | msbot update service luisFoo

there are 3 commands here - first one gets the current luis service section from the .bot file w/ versionId 0.1, luis import verison right now does not support --msbot flag for me to get an updated luis service configuration and finally we dont have msbot update service command to update specific properties in a service section.

**Comment by tomlm** [comment]
this should work with --stdin instead of --msbot.  Did you try that?

**Comment by vishwacsena** [comment]
msbot get service luisFoo | luis import version --stdin --in bar.json --versionId 0.2 works with the --stdin flag on luis cli. 

But the luis command here is creating a new 0.2 luis version and i now need to update the luis version information in the bot file from 0.1 to 0.2.

**Comment by tomlm** [comment]
ohhhhhh I get it, sorry...yeah I can do that.
