### ISSUE TITLE
Dispatch CLI should consume the new .bot file using configuration builder library

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#365]
Filing this issue to track work to update the dispatch CLI to use the new .bot file format as well as consider using the bot configuration library.

Specific issues - 
1. dispatch should consume and output LUIS region information (added to .bot file)
2. dispatch create, refresh commands should be able to take a --secret with the -b option if the bot file is encrypted. At the moment dispatch expects the bot file to be unencrypted. Using the bot configuration library will help with this issue. At minimum, dispatch should prompt for the secret if the bot file is encrypted.

**Comment by tsuwandy** [comment]
Merged to master.
