### ISSUE TITLE
Make generated json file have the .json extension

### ISSUE THREAD

**Issue by fbeauchemin** [Microsoft/botbuilder-tools#368]
It could also be a flag/options to include or not (or specify the actual extension to use).

For example:
`ludown parse --in Weather.lu` should create a file `Weather.json`

**Comment by vishwacsena** [comment]
@fbeauchemin 

This is supported in ludown v1.0.35. 

ludown parse toluis --in weather.lu will output weather.json in cwd.

ludown parse toluis --in weather.lu -n weather.luis will output a file named weather.luis in cwd. 

ludown prase toluis --in weather.lu -n myweather will output a file named myweather.json in cwd.

Please reactivate this issue if there is a specific scenario you have in mind that isn't covered.
