### ISSUE TITLE
Export KB is not working with invalid subscription key error

### ISSUE THREAD

**Issue by brharr** [Microsoft/botbuilder-tools#369]
**Describe the bug**
I am using the qnamaker export kb command to pull out the contents of an application that was created by a previous user at a customer. The QnA stills works within my Bot Application, but when I do an export so that we can put it into a new application that is controlled by IT, I get the following error: 

Error: {
    "code": "Unspecified",
    "message": "Access denied due to invalid subscription key. Make sure you are subscribed to an API you are trying to call and provide the right key."
}

The contents of the qnamkerrc is the following: 

{
  "subscriptionKey": "ff74d3ba-2987-4db6-af32-e7e3e7025899",
  "kbId": "6d98d7a5-0082-48d6-90dc-7d7429372a67"
}

These are the same values that I am using within my bot application without any issue, but the export from the CLI will not work. 

I have even passed the KB and Subscription as parameters to the CLI command with no luck. 

Any ideas of suggestion on how I can resolve this. I am visiting the customer tomorrow and need to get that export.

Thanks,
Brian C Harrison, CSA

**Comment by vishwacsena** [comment]
@brharr are you using he legacy qnamaker or the new qnamaker GA service (tied to an azure subscription)? Depending on this, you might need to use two different commands - 

legacy (pre-GA service - this is where your QnA Maker KB is not tied to an azure subscription)
```bash
qnamaker export legacykb --kbId <legacyKB> --subscriptionKey <key>
```

For QnA Maker GA service in your azure subscription, use
```bash
qnamaker export kb --kbId <string> --environment <string> --subscriptionKey <key>
```

**Comment by brharr** [comment]
Please do not close this before I have even responded. I am using the GA service and have been since the beginning. I used the correct commands and syntax both according to the documentation and according to the error messages. I also made sure to update the qnamaker cli before running anything without any luck.

**Comment by stevkan** [comment]
@brharr, are you still experiencing issues in exporting the kb?

**Comment by stevkan** [comment]
Closing issue due to lack of response.
