### ISSUE TITLE
[ludown] BadArgument: Prebuilt extractor names cannot be null or empty.

### ISSUE THREAD

**Issue by anastasiia-zolochevska** [Microsoft/botbuilder-tools#37]
Following the documentation we created LUIS json file based on the sample .lu files, could not import them through the portal (BadArgument: Prebuilt extractor names cannot be null or empty.)

**Comment by vishwacsena** [comment]
By design. At the moment, you need to use the LUIS CLI tool to import a new LUIS app.

luis import application --in <LUIS_JSON_FROM_LUDOWN> --authoringKey <YOUR LUIS AUTH KEY>

**Comment by TringaYmeraga** [comment]
hi @vishwacsena do you perhaps know how to fix this issue with importing the .lu file directly in LUIS without using the LUIS CLI tool? Thanks in advance!
