### ISSUE TITLE
User activities on Chatdown does not show up in Emulator

### ISSUE THREAD

**Issue by compulim** [Microsoft/botbuilder-tools#377]
**Describe the bug**
User activities are being filtered by Web Chat because they do not have `channelData.clientActivityId`.

**To Reproduce**
1. Create a transcript using Chatdown, using `Greeting.chatdown`
2. Load the transcript file in Emulator

**Expected behavior**
In Emulator, one should see "hi" from the user.

**Additional context**
Talked to @vishwacsena offline, we should add `channelData.clientActivityId` on the output transcript from the Chatdown tool.

**Related**
- Emulator [#675](https://github.com/Microsoft/BotFramework-Emulator/issues/675)
- Web Chat [#1110](https://github.com/Microsoft/BotFramework-WebChat/issues/1110)

**Comment by vishwacsena** [comment]
@compulim yes. let's fix this.

**Comment by compulim** [comment]
PR in BotFramework-WebChat#1162.

**Comment by compulim** [comment]
It is in with version 0.14.3-master.57360e4.

@corinagum, please wait until the Microsoft/BotFramework-WebChat#1161 is in, then we bump Web Chat version together. Will let you know the version number.

**Comment by compulim** [comment]
Please bump to `botframework-webchat@0.14.3-master.41d14fd`. It will contains 2 fixes, one for Chatdown, another for Emulator accessibility bug.

![image](https://user-images.githubusercontent.com/1622400/45647222-2f787500-ba7a-11e8-8f6c-e5a73cb7d374.png)

**Comment by sgellock** [comment]
This was successfully built today.
