### ISSUE TITLE
[MSBot] Connect to luis. Error: bad or missing --subscriptionKey

### ISSUE THREAD

**Issue by anastasiia-zolochevska** [Microsoft/botbuilder-tools#38]
Not sure why it requires subscription key in addition to authoring key and app id.
Subscription key is not mentioned in readme and in the example.
Using authoring key as subscription key didn’t work as well, the error “Error: bad or missing –subscriptionKey”

**Comment by tomlm** [comment]
fixed as of v1.0.22
