### ISSUE TITLE
Add authentication config to Endpoint schema

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botbuilder-tools#384]
**Is your feature request related to a problem? Please describe.**
I want to use .bot as the primary configuration source for my bot project, including my authentication config. 

**Describe the solution you'd like**
I want to be able to access my OAuth connections from my Azure Bot settings in my bot endpoint configuration.
 
      {
            "appId": "",
            "id": "http://localhost:3978/api/messages",
            "type": "endpoint",
            "appPassword": "",
            "endpoint": "http://localhost:3978/api/messages",
            "name": "MyBot",
            "oauthSettings": [
              {
                "name": "AzureADConnection",
                "provider": "Azure ActiveDirectory v2"
              },
              {
                "name": "GoogleAuthConnection",
                "provider": "Google"
              }
            ]
         },
`

Another option is to have Authentication as a connected service type and access it that way.

**Comment by vishwacsena** [comment]
@lauren-mills - Is there a reason why you cannot use generics to capture this?

**Comment by lauren-mills** [comment]
@vishwacsena I can make it work with generics today, but since its a bot setting in the portal it would be nice to have symmetry.

**Comment by swagatmishra2007** [comment]
the az botservice cli supports getting your auth connections.
try `az bot authsetting list -g <resourcegroup> -n <botname>`

**Comment by sgellock** [comment]
bot files are deprectated
