### ISSUE TITLE
add support for creating msa app id using microsoft graph api's to azure cli

### ISSUE THREAD

**Issue by swagatmishra2007** [Microsoft/botbuilder-tools#393]

**Comment by stevengum** [comment]
@carlosscastro, I think this is on track for 4.3, but correct me if I'm wrong. Will this also address #841 and #813? (Problems with provisioning MSA AppID/PWs when using non-AAD accounts) 

I think the issue I filed, #859, is a dupe by virtue that the work for this issue will improve the Auth flow.

For now I'm going to put this for the Sprint 52 milestone.

**Comment by stevengum** [comment]
Closing via [stevengum/Azure-Cli#f9469d8287d8c4e32c11c7e8cbe9b4a5d0831b4e](https://github.com/Azure/azure-cli/commit/f9469d8287d8c4e32c11c7e8cbe9b4a5d0831b4e).

`--appId` and `-p/--password` are now required for `az bot create` and can be provisioned via Azure CLI (`az ad app create`).
