### ISSUE TITLE
[LUIS] AppName parameter for create app doesn’t work

### ISSUE THREAD

**Issue by anastasiia-zolochevska** [Microsoft/botbuilder-tools#40]
![image](https://user-images.githubusercontent.com/3801171/38706819-7e7ec9a8-3e63-11e8-8b3f-a3f5fce46215.png)

**Comment by vishwacsena** [comment]
Verified that this is fixed. Note that your input JSON for luis import command can also include an app name. If present LUIS will override anything you pass in command line via --appName with that.

**Comment by vishwacsena** [comment]
luis import application --in all_LUISApp.json --appName fooBar
