### ISSUE TITLE
"dispatch create" output does not set region

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#407]
**Describe the bug**
When piping the output of dispatch create into msbot connect dispatch, the region field is blank.

**To Reproduce**
`
dispatch create --name $FileName --bot $BotFilePath --luisAuthoringRegion $luisLocation --luisAuthoringKey $luisAuthoringKey --subscriptionKey $SubscriptionKey --dataFolder $OutputPath | msbot connect dispatch --stdin --bot $BotFilePath
`

.bot output:
`
    {
      "type": "dispatch",
      "id": "***",
      "name": "**************",
      "appId": "**********",
      "authoringKey": "**********",
      "serviceIds": [
        "***",
        "***"
      ],
      "subscriptionKey": "**************",
      "version": "Dispatch",
      "region": ""
    }
`

**Expected behavior**
Expect region property to be populated.

**Context**
Dispatch version: 1.0.8-1

**Comment by tsuwandy** [comment]
Region is a new property recently added to LuisService in bot config.  I'm currently updating Dispatch code to use the latest bot configuration -  this should be fixed when that work is done.  Thanks!

**Comment by vishwacsena** [comment]
dupe of #365

**Comment by tsuwandy** [comment]
Merged to master, will be fixed when npm package is updated for Ignite
