### ISSUE TITLE
ludown: Give users ability to specify output file name

### ISSUE THREAD

**Issue by srozga** [Microsoft/botbuilder-tools#430]
**Is your feature request related to a problem? Please describe.**
Minor nice to have issue here.

 `ludown parse ToLuis --in model.lu -n "My Luis App Name"` generates an output file called `My Luis App Name.json`. LUIS app names don't always make for the friendliest file names. It would be nice to be able to have a way to specify the output file name or a mode in which `ludown parse ToLuis --in model.lu` prints output JSON to std out so I can redirect. To this last point, the `luis `command line tools return all output into stdout so it surprised me that `ludown `doesn't, though I understand `ludown `has a batch use case.

**Describe the solution you'd like**
Being able to do something like `ludown parse ToLuis --in model.lu -n "My App" --out model.json` would work.

**Comment by cleemullins** [comment]
Fixed by #462
