### ISSUE TITLE
luis: Enable a force flag for version and app deletion

### ISSUE THREAD

**Issue by srozga** [Microsoft/botbuilder-tools#431]
**Is your feature request related to a problem? Please describe.**
We have a few scripts that run the `luis` tool to delete versions and re-import them. I noticed that in v 2.0.9, `luis delete version` now asks if you are sure you want to delete. Makes sense. For the scripts, it would be great to be able to pass a --force flag or something like that so there's no questions asked.

**Describe the solution you'd like**
`luis delete version --force`

**Describe alternatives you've considered**
I might try to build a way for the script to call `luis delete version` and then send "yes<RETURN>" into std in.

**Comment by vishwacsena** [comment]
@tomlm - we should add an option to not prompt for confirmation and we need to ensure that the delete application/ version for LUIS as well as delete kb command for qnamaker have this option.
