### ISSUE TITLE
msbot readme claims to support CosmosDB, CLI claims not to

### ISSUE THREAD

**Issue by JonathanFingold** [Microsoft/botbuilder-tools#436]
The **msbot** readme claims that you can add CosmosDB service to the bot file. I get errors when trying to follow the instructions.

**To Reproduce**
1. Look at the [msbot instructions for connecting to CosmosDB](https://github.com/Microsoft/botbuilder-tools/tree/master/packages/MSBot#connecting-to-azure-cosmosdb-service). The remaining steps are just trying to following those instructions.
1. Open a command prompt or power shell  window in a folder that has a .bot file.
1. Run the following commands:
   ```cmd
   npm install -g npm
   npm install -g msbot
   msbot connect -h cosmosdb
   ```
1. **Note**: `cosmosdb` is not listed as a recognized command.
1. Try: `msbot connect cosmosdb`.
1. Get the error message: `Unknown arguments: cosmosdb`.

**Expected behavior**
1. I expected to be able to follow the instructions in the readme.
1. I expected that CosmosDb was supported.

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise x64
 - Browser: n/a
 - Version: msbot v1.0.51

**Comment by tomlm** [comment]
The problem is that this is functionality for msbot 2.0 which has not been published publicly yet.

You can install msbot v2 from myget

**Comment by JonathanFingold** [comment]
@tomlm , Excellent, thanks. What are the `npm install` arguments for pointing npm at the myget feed that contains the package? The command line help is very thin on that front.

**Comment by vishwacsena** [comment]
```bash
> npm config set registry https://botbuilder.myget.org/F/botbuilder-tools-daily/npm/
> npm i -g msbot
```

To reset the registry 
```bash
> npm config set registry https://registry.npmjs.org/
```
