### ISSUE TITLE
Luis should pick up region, versionId from msbot

### ISSUE THREAD

**Issue by carlosscastro** [Microsoft/botbuilder-tools#438]
When piping ```msbot get``` output to luis train version, the region is not picked up by luis CLI and thus we need to pass it explicitly.

**Comment by tomlm** [comment]
This works with --stdin switch

**Comment by vishwacsena** [comment]
These commands do not work without explicitly passing in --versionId to the LUIS command. Note that I'm using these with --stdin option.

> msbot get <service-name> | luis rename version --newVersionId 0.1_old --stdin
> luis train version --wait --stdin
> luis publish version --stdin

All these commands report - versionId cannot be null or undefined.

Verified in latest LUIS CLI version 2.0.11-2.5.12

**Comment by vishwacsena** [comment]
Tried with latest - 2.0.11-12

These commands fail without explicitly adding **--versionId** to the luis command.
```bash
> msbot get cafeDispatchModel | luis rename version --newVersionId 0.1_old --stdin **--versionId 0.1**
> msbot get cafeDispatchModel | luis train version --wait --stdin **--versionId 0.1**
```
This command fails without explicitly adding **--region** and **--versionId** to the luis command. 

```bash
> msbot get cafeDispatchModel | luis publish version --stdin **--versionId** 0.1 **--region** westus
```
