### ISSUE TITLE
.LuisRC file isn't picked up unless in current working directory

### ISSUE THREAD

**Issue by SaqibS** [Microsoft/botbuilder-tools#448]
**Describe the bug**
LUIS CLI isn't picking up my .luisrc file unless it is in the current working directory.

**To Reproduce**
1. On Windows 10, I enter `luis init` but get an error about permissions.
2. I open an admin command prompt, reissue the same command, and the `.luisrc` file is successfully created in `c:\windows\system32`.
3. Since I won't usually be running this as admin, I copy `.luisrc` to `c:\users\saqibs`.
4. If I run LUIS CLI from an arbitrary directory on my machine, I get an error about the keys not being found in the `.luisrc` file.
5. If I run the same command from my home directory, or indeed any other directory which has the `.luisrc` file in, it works as expected.

**Expected behavior**
After running `luis init` I should be able to run LUIS CLI from any directory on my machine.

**Comment by tomlm** [comment]
It is by design that .luisrc is only the current folder because people work with multiple models.
