### ISSUE TITLE
Not obvious how to train/publish

### ISSUE THREAD

**Issue by SaqibS** [Microsoft/botbuilder-tools#449]
I've read the info on `docs.microsoft.com`, the intro blog post, as well as `luis --help` and `luis --!`, but training and publishing is still non-intuitive to me.

In the below, I do not enter `AppID` or `VersionID` as they are already in my `.luisrc`.

When I enter the command `luis train version` I get the following output:

```
{
  "statusId": 9,
  "status": "Queued"
}
```

I have tried this several times on different days. To me, it isn't clear if `9` is some ID that I should be querying, but then where is the `GetStatus` command? Or, perhaps, every time I run `luis train version` it kicks off a new training session, which is why it's always queued, and perhaps `9` is some magical number I should just ignore. Regardless, how do I know when training is done, and whether it was successful?

I have tried running `luis publish version` but it says that one or more of the models hasn't been trained yet.

Supposing I can figure out how to train, then the docs say that I should specify a JSON file, but it isn't obvious to me what should be in that file, and I can't find info on the internet. I would have imaged that training would give me back a model ID, and then I would publish using that model ID - but perhaps this is an incorrect model of the system.

**Comment by tomlm** [comment]
When you run a luis train you are requesting for training to happen.  This can be a long running operation.  
You can run 
```
luis get status --appId xxxx --version vvvv 
```

to get the status, or you can simply add --wait to luis train
```
luis train version --wait
```
