### ISSUE TITLE
MSBot connect luis output mismatch with LuisApplication definition in BotBuilder packages

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#450]
**Description**
The latest Microsoft.Bot.Builder.AI.Luis package definition for LuisApplication now requires the Luis endpoint rather than the region. MSBot connect version 2.0.4 currently uses the region code in the .bot file. 

![image](https://user-images.githubusercontent.com/27976702/45311795-d9db2000-b4ef-11e8-96b5-98cc5fb1a9c4.png)

**Additional context**
MSBot version 2.0.4

**Comment by tomlm** [comment]
**dotnet**
- [x] PR https://github.com/Microsoft/botbuilder-dotnet/pull/950
- [ ]  Checked in

**javascript**
- [x] PR https://github.com/Microsoft/botbuilder-js/pull/425
- [ ]  Checked in

**Comment by tomlm** [comment]
done
