### ISSUE TITLE
Rename msbot export and clone commands

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#451]
|Current|Proposed|
|--------|----------|
|msbot export|msbot export services|
|msbot clone|msbot import services|

**Comment by tomlm** [comment]
I think import doesn't seem right, as it implies it will pull it into existing resource group/services, where clone was a bout creating all new resources.
What about
 msbot provision services
 msbot create services
 ??

**Comment by vishwacsena** [comment]
Let's do msbot export services and msbot clone services instead.
