### ISSUE TITLE
LUIS option to produce output that can be pasted into .bot

### ISSUE THREAD

**Issue by daveta** [Microsoft/botbuilder-tools#469]
Low Pri:
Currently, when I create an app, it outputs json suspiciously close to a .bot config file.

`C:\Samples\daveta-basic-template\BotBuilder-Samples\csharp_dotnetcore\13.Basic-Bot-Template>luis import application --in .\CognitiveModels\Interrupts.json --authoringKey "keyhere" --endpointBasePath https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/guidhere?subscription-key=keyhere
{
  "id": "idhere",
  "name": "Interrupts",
  "description": "",
  "culture": "en-us",
  "usageScenario": "",
  "domain": "",
  "versionsCount": 1,
  "createdDateTime": "2018-09-13T18:40:56Z",
  "endpoints": {},
  "endpointHitsCount": 0,
  "activeVersion": "0.1"
}`

It would be nice to have an output option that produces .bot config sections:
`    {
      "type": "luis",
      "name": "BasicBot",
      "id": "",
      "appId": "appid",
      "authoringKey": "keyhere",
      "subscriptionKey": "keyhere",
      "version": "0.1",
      "region": "westus"
    },
`

**Comment by vishwacsena** [comment]
This is already supported.. Try

Luis import application - - msbot | msbot connect luis - - stdin
