### ISSUE TITLE
MSBOT recipes support

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botbuilder-tools#475]
MSBOT should also help orchestrate sequence of commands you need to run to do few regular development tasks. 

Key tasks: 
- Replace LUIS application version
- Train and publish LUIS application version
- Replace QnA Maker KB, publish
- Ludown to LUIS
- Ludown to QnA

In order to facilitate this way, we should add a MSBOT execute <Recipe name> command. 
A recipe file has a name, outputFolder and a collection of recipes.

A recipe has 
Required: 
- name: recipe name
- command: command to execute
    - command can be one of 'replaceLUISAppVersion' | 'publishLUISAppVersion' | 'updateQnAKB' | 'ludownToLUIS' | 'ludownToQnA' | 'recipeSequence'
Commmand specific:
- botFileServiceNameOrId: pointer to service name or id in bot file
    - required for 'replaceLUISAppVersion' | 'publishLUISAppVersion' | 'updateQnAKB'
- modelFile: model file name
    - required for 'replaceLUISAppVersion' | 'updateQnAKB'
- pointer to .lu file 
    - required for 'ludownToLUIS' | 'ludownToQnA'
Optional: 
- keepOldLUISVersions: only available for 'replaceLUISAppVersion'
- sequence: ordered list of recipes defined in the recipe file to execute

# Recipe file
Recipe is a simple .json file that contains a list of recipe objects.  
```json
{
    "name": "my-msbot-recipe",
    "outputFolder": "./cognitiveModels",
    "recipes": [
        {
            "name": "updateRootDispatcher",                 
            "command": "replaceLUISAppVersion",             
            "botFileServiceNameOrId": "rootDispatcher",     
            "keepOldLUISVersions": "true",                  
            "modelFile": "./rootDispatcher.luis"            
        },
        {
            "name": "publishRootDisptcher",
            "command": "publishLUISAppVersion",
            "botFileServiceNameOrId": "rootDispatcher"
        },
        {
            "name": "updateQnAKB",
            "command": "updateQnAKB",
            "botFileServiceNameOrId": "rootDispatcher",
            "modelFile": "./faq.qna" 
        },
        {
            "name": "buildRootDispatcher",
            "command": "ludownToLUIS",
            "luFile": "./rootDispatcher.lu"
        },
        {
            "name": "buildQnAModel",
            "command": "ludownToQnA",
            "luFile": "./root-qna.lu"
        },
        {
            "name": "buildAndPublishAll",
            "command": "recipeSequence",
            "sequence": [
                "buildRootDispatcher",
                "buildQnAModel",
                "updateRootDispatcher",
                "publishRootDisptcher",
                "updateQnAKB"
            ]
        }
    ]
}
```

With a recipe file above, I should be able to do - 
```bash
> msbot execute recipe \<recipeName> [--secret <Key if bot file is encrypted>]
```
### Recipe command: replaceLUISAppVersion

```bash
> msbot get rootDispatcher [--secret <Key if bot file is encrypted>] | luis rename version --newVersionId 0.1_old --stdin
> msbot get rootDispatcher [--secret <Key if bot file is encrypted>] | luis import version --stdin --in <modelFile>
\<if keepOldLUISVersions is not true>
> msbot get rootDispatcher [--secret <Key if bot file is encrypted>] | luis delete version --stdin --versionId 0.1_old
```

### Recipe command: publishLUISAppVersion

```bash
> msbot get rootDispatcher [--secret <Key if bot file is encrypted>] | luis train version --wait --stdin
> msbot get rootDispatcher [--secret <Key if bot file is encrypted>] | luis publish version --stdin
```

### Recipe command: updateQnAKB

```bash
> msbot get rootDispatcher [--secret <Key if bot file is encrypted>] | qnamaker replace kb --in <modelFile>
> msbot get rootDispatcher [--secret <Key if bot file is encrypted>] | qnamaker publish kb --stdin
```

### Recipe command: ludownToLUIS

```bash
> ludown parse toluis --in ./root.lu -o ./cognitiveModels -n rootDispatcher --out rootDispatcher.luis
```

### Recipe command: ludownToQnA

```bash
> ludown parse toqna --in ./root-qna.lu -o ./cognitiveModels -n qnaModel --out qnaModel.qna
```

### Recipe command: recipeSequence

Execute every recipe in the sequence array in order specified.

All recipes should write to stdout.

**Comment by darrenj** [comment]
A dispatch model is a dynamic thing, a bit like a compiled binary. For deployment and update scenarios we should build the dispatch from the dispatchDefinition (containing QnA and LUIS) ideally using the dispatch tool. dispatch create for creation and dispatch refresh for refresh. Otherwise managing the dispatch JSON representation is very hard work, you have to make changes to an LU file, publish to LUIS, create the dispatcher and export to get the JSON :-o

Key first deliverable from a Virtual Assistant point of view is removing the .luis JSON files from recipies by referencing a path to a LU file. This removes a lot of complexity. Then removal of the dispatch file again removing a lot of maintenance/complexity.
