### ISSUE TITLE
DCR: Change secretKey to padlock

### ISSUE THREAD

**Issue by yochay** [Microsoft/botbuilder-tools#476]
**Describe the bug**
The .bot file includes a property called secretKey. Which can be misleading to think it is the key to unlock the bot file. 

Change it to something else like: GUID; Flag; Id; etc.

{
  "name": "091318-YK-Test-4",
  "description": null,
  "secretKey": "PRF9TiaNb4lOkJkd/Z+AIw==!zFwdNaFL6e97GGUqygyoEPZf0EJdWJyudNP1PFGHDtaa8UlNjXLX+XQ+VcNiEIf3",
  "version": "2.0",
  "services": [
    {

**Comment by tomlm** [comment]
** dotnet **
- [ ] PR
- [ ] Checked In


** js **
- [ ] PR
- [ ] Checked In

**Comment by sgellock** [comment]
This portion of the ticket is done.  there is a dependent work item on the emulator tracked here:  microsoft/botframework-emulator#866
