### ISSUE TITLE
msbot secret -n writes out some json

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#477]
msbot 2.0.4-15

>msbot secret -n
Command {
  commands: [],
  options:
   [ Option {
       flags: '-b, --bot <path>',
       required: true,
       optional: false,
       bool: true,
       short: '-b',
       long: '--bot',
       description: 'path to bot file.  If omitted, local folder will look for a .bot file' },
     Option {
       flags: '--secret <secret>',
       required: true,
       optional: false,
       bool: true,
       long: '--secret',
       description: 'secret used to confirm you can do secret operations' },
     Option {
       flags: '-c, --clear',
       required: false,
       optional: false,
       bool: true,
       short: '-c',
       long: '--clear',
       description: 'clear the secret and store keys unencrypted' },
     Option {
       flags: '-n, --new',
       required: false,
       optional: false,
       bool: true,
       short: '-n',
       long: '--new',
       description: 'generate a new secret and store keys encrypted' } ],
  _execs: {},
  _allowUnknownOption: false,
  _args: [],
  _name: 'msbot secret',
  Command:
   { [Function: Command]
     super_:
      { [Function: EventEmitter]
        EventEmitter: [Circular],
        usingDomains: false,
        defaultMaxListeners: [Getter/Setter],
        init: [Function],
        listenerCount: [Function] } },
  Option: [Function: Option],
  _events:
   { 'option:bot': [Function],
     'option:secret': [Function],
     'option:clear': [Function],
     'option:new': [Function],
     'command:*': [Function: listener] },
  _eventsCount: 5,
  rawArgs:
   [ 'C:\\Program Files\\nodejs\\node.exe',
     'C:\\Users\\vkannan\\AppData\\Roaming\\npm\\node_modules\\msbot\\bin\\msbot-secret.js',
     '-n' ],
  new: true,
  args: [] }
Your bot is encrypted with secret:

**Comment by sgellock** [comment]
merged into master
