### ISSUE TITLE
AZ cmd - .env file created with Windows path separator instead of OS specific

### ISSUE THREAD

**Issue by jameslew** [Microsoft/botbuilder-tools#478]
**Describe the bug**
The .env file created with the Az Bot Download CLI is created using windows path separators for BotFilePath instead of os specific

**To Reproduce**
1. Create a bot
2. Az Bot Download on a unix distro
3. Look at the .env file

**Expected behavior**
Unix path separator for BotFilePath

**Comment by swagatmishra2007** [comment]
fixed in latest private extension
