### ISSUE TITLE
AZ CLI: download should show some progress indication

### ISSUE THREAD

**Issue by yochay** [Microsoft/botbuilder-tools#480]
AZ bot download can take a while. It will be great if it can show some progress and communicate  something to the user. Like Create zip, download zip,

**Comment by sgellock** [comment]
moved out from current release train and moved to backlog for consideration in the next release

**Comment by stevengum** [comment]
Given the recent feedback, I'm rescheduling this for 4.3 and will tentatively put it in Sprint 52.

**Comment by stevengum** [comment]
Closing via merge of **Azure/Azure-cli#8080**.
