### ISSUE TITLE
MSBot not working on v4 scratch basic bot's .bot file for LUIS

### ISSUE THREAD

**Issue by diberry** [Microsoft/botbuilder-tools#484]
**Describe the bug**

**To Reproduce**
1. Create v4 basic bot on scratch subscription
2. download code
3. npm install && npm start
4. bot works with newly created LUIS app
5. change .bot file to work with existing LUIS app with the following command:
msbot update luis --applicationId <previous-luis-app-id> --bot "luis-nodejs-bot.bot" --authoringKey <LUIS-authoring-key> --secret <secret-from-web-app-settings-in-azure-portal>
6. bash shell response: Unknown arguments: update luis

Tried to just unencrypt but that doesn't work either:
1.  msbot secret --bot "luis-nodejs-bot.bot" --secret <secret-from-web-app-settings-in-azure-portal> --clear
2. bash shell response: TypeError: Cannot read property 'length' of undefined

The v4 template id of "6" or 6 for LUIS doesn't work and if I add a value to the "name" of the LUIS section that doesn't work either. 

**Expected behavior**
Expect to either work without encryption or be able to unencrypt. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 on corpnet
 - Browser - chrome

**Smartphone (please complete the following information):**
 - Version [e.g. 22] which doesn't lowercase v work, why does it have to be uppercase? 1.0.51

**Additional context**

**Comment by tomlm** [comment]
Both of these bugs look like old version of msbot  Can you please include the version of msbot with this?

**Comment by diberry** [comment]
1.0.51

**Comment by vishwacsena** [comment]
@diberry  you can get the latest from the nightly feed - 

```shell
npm config set registry https://botbuilder.myget.org/F/botbuilder-tools-daily/npm/
```

Install using npm:
```shell
npm i -g msbot
```

To reset registry:
```shell
npm config set registry https://registry.npmjs.org/
```

**Comment by diberry** [comment]
@vishwacsena Thank you.
