### ISSUE TITLE
Dispatch create not making QnA intent

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#488]
**Describe the bug**
When running dispatch create against a bot file with 1 qna model and 2 luis models, the resulting dispatch model only has intents for the luis models, even though output shows the qna model being exported:

![image](https://user-images.githubusercontent.com/27976702/45600060-69c71100-b9ab-11e8-95b1-86fe3a1bd0c1.png)

![image](https://user-images.githubusercontent.com/27976702/45600066-7ea3a480-b9ab-11e8-8881-b62f6dcb7c1e.png)

Dispatch version 1.0.8-14

**Comment by tsuwandy** [comment]
I can't repro this.  Lauren, could you share your dispatch file in email?  Thanks!

**Comment by tsuwandy** [comment]
QnA is empty and thus not being added to Dispatch.
