### ISSUE TITLE
MSBot clone: Default Luis service name breaks LuisGen

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#489]
The default naming of Luis services with a '-' can lead to errors with LuisGen + Dispatch.

Steps:
1. Run msbot clone services
2. Get luis name:  IPABot-General
3. Run dispatch, get intent named "l_IPABot-General"
4. Run LG against dispatch model, and the intent enum is in an error state

This could be fixed by making the default naming:
let luisAppName = `${args.name}_${luisResource.name}`; 

https://github.com/Microsoft/botbuilder-tools/blob/18b4287a0f228aee67bc319450ba2e34017182b4/packages/MSBot/src/msbot-clone-services.ts#L598

**Comment by carlosscastro** [comment]
PR out: https://github.com/Microsoft/botbuilder-tools/pull/515
