### ISSUE TITLE
Missing msbot delete services command

### ISSUE THREAD

**Issue by yochay** [microsoft/botbuilder-tools#497]
**Is your feature request related to a problem? Please describe.**
msbot clone services is awesome
In Azure I can delete all resource using `az group delete -g 091628-YK-Test1 --no-wait `. However this doesn't delete the specific LUIS application. Aka I can see the app listed in luis.ai. 

**Describe the solution you'd like**
I would like to see 'msbot delete services' that accept either the same recipe file or directly the .bot file

BTW maybe change the `msbot **clone** services` , to `msbot **creates** services`. msbot doesn't really clone anything as it creates a set of new resources.

**Comment by sgellock** [comment]
msbot is deprecated
