### ISSUE TITLE
Question - how to update LUIS section app ID only

### ISSUE THREAD

**Issue by diberry** [Microsoft/botbuilder-tools#500]
If I want to update a LUIS sections's appID, the following command doesn't seem to work because the reference to update takes the appid instead of the id or name:

msbot update luis --serviceName HumanResources --applicationId <existing app id> -b diberry-nodejs-bot-v4.bot --secret <my-secret> --appId <new app id>

Do I need to delete the current luis service, then add it back in with the new app id?

**Comment by sgellock** [comment]
We believe this to be fixed, please verify with latest build
