### ISSUE TITLE
[bug bash 9/17] msbot clone errors out with "[msbot] Cannot read property 'split' of undefined"

### ISSUE THREAD

**Issue by Andrea-Orimoto** [Microsoft/botbuilder-tools#509]
followed the bug bash instructions and got this
![2018-09-17_12-03-46](https://user-images.githubusercontent.com/17152540/45644202-f6d49d80-ba71-11e8-843f-729a4f465a9f.png)

this is the folder I was working on. a clean clone of the v4 branch of the samples github
[13.basic-bot.zip](https://github.com/Microsoft/botbuilder-tools/files/2389895/13.basic-bot.zip)

**Comment by tomlm** [comment]
fixed
