### ISSUE TITLE
msbot clone: endpointBasePath missing in Luis import

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#510]
**Describe the bug**
When running msbot clone, the luis deployment fails saying the endpointBasePath is missing. 

Error received (see bold below)
`
[msbot] Creating and importing LUIS application [ConstosoBot1-General]
[msbot] Command failed: luis import application --appName "ConstosoBot1-General" --in DeploymentScripts\msbotClone\120.luis --authoringKey ***** --msbot The endpointBasePath is missing from the configuration. Did you run luis init yet?
`
**Additional context**
msbot verison: 2.0.4-54

**Comment by tomlm** [comment]
**dotnet**
- [x] PR Microsoft/botbuilder-dotnet#966 
- [ ] checked in

**js**
- [x] PR Microsoft/botbuilder-js#449 
- [ ] checked in
