### ISSUE TITLE
upgrade az botservice version (remove and add) did not work

### ISSUE THREAD

**Issue by elaine-chang** [Microsoft/botbuilder-tools#511]
**Describe the bug**
I was trying to run msbot clone following the documentation for Enterprise Template, then got an error 
![image](https://user-images.githubusercontent.com/25210203/45645577-c42ca400-ba75-11e8-825c-9020bff4de38.png)
However, I tried to remove and add botservice, but that did not work. 

**To Reproduce**
After following the deployment instruction for Enterprise Template, in this step
msbot clone services --name "DJEnterpriseBot" --luisAuthoringKey "YOUR_AUTHORING_KEY" --folder "DeploymentScripts\msbotClone" --location "westus" --verbose

If we see the error 
[msbot] Checking az botservice version
[msbot] [msbot] You need to upgrade your az botservice version to >= 0.4.0.
To do this run:
   az extension remove -n botservice
   az extension add -n botservice

**Expected behavior**
az extension remove -n botservice
az extension add -n botservice
should fix the version issue 

**Screenshots**
![image](https://user-images.githubusercontent.com/25210203/45645500-74e67380-ba75-11e8-90f1-a645a3a01e88.png)

**Comment by vishwacsena** [comment]
This is because the az extension -n botservice pulls from the published extension and the latest changes haevnt been published yet. 

@carlosscastro; @swagatmishra2007  - when are we publishing the bot extension?

**Comment by Joll59** [comment]
@sgellock 
> this is a dup.

a duplicate of which issue?
