### ISSUE TITLE
Refresh access token failed with status: 401 when opening .bot created with msbot clone services in Emulator

### ISSUE THREAD

**Issue by Zerryth** [Microsoft/botbuilder-tools#512]
**Describe the bug**
When opening bot file in Emulator, we get a "Refresh access token failed with status code: 401"

**To Reproduce**
**Create  required services for basic bot**:
```
C:\Users\v-asho\source\repos\BugBash2\BotBuilder-Samples\javascript_nodejs\13.basic-bot>msbot clone services -n AshleyHoBugBash2Bot -f deploymentScripts/msbotClone --location westus --luisAuthoringKey MY_LUIS_KEY --verbose
[msbot] Checking az botservice version
[msbot] Fetching subscription account
[msbot] Creating resources in subscription: Bot Service Testing (Scratch) MY_LUIS_KEY
[msbot] Creating Azure group [AshleyHoBugBash2Bot]
[msbot] Creating LUIS Cognitive Service [AshleyHoBugBash2Bot-LUIS]
[msbot] Fetching LUIS Keys [AshleyHoBugBash2Bot-LUIS]
[msbot] Creating Azure Bot Service [AshleyHoBugBash2Bot]
[msbot] [az bot] To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code FT79EPKJ3 to authenticate.

[msbot] [az bot] obtained msa app id and password. Provisioning bot now.
 (this will take several minutes)
[msbot] Fetching bot extended information [AshleyHoBugBash2Bot]
[msbot] Fetching co-created resources [AshleyHoBugBash2Bot]
[msbot] Creating and importing LUIS application [AshleyHoBugBash2Bot-basic-bot-LUIS]
[msbot] Training LUIS application [AshleyHoBugBash2Bot-basic-bot-LUIS]
[msbot] Publishing LUIS application [AshleyHoBugBash2Bot-basic-bot-LUIS]
[msbot] Updating LUIS settings [AshleyHoBugBash2Bot-basic-bot-LUIS]
[msbot] Fetching storage connection string [shleyoup2oz]
[msbot] AshleyHoBugBash2Bot.bot created.
[msbot] Done cloning.
```

AshleyHoBugBash2Bot.bot successfully created:

```
{
    "name": "AshleyHoBugBash2Bot",
    "description": "",
    "services": [
        {
            "type": "endpoint",
            "id": "http://localhost:3978/api/messages",
            "name": "development",
            "appId": "...",
            "appPassword": "...",
            "endpoint": "http://localhost:3978/api/messages"
        },
        {
            "type": "luis",
            "name": "AshleyHoBugBash2Bot-basic-bot-LUIS",
            "appId": "...",
            "authoringKey": "...",
            "subscriptionKey": "...",
            "version": "0.1",
            "region": "westus",
            "id": "5"
        },
        {
            "type": "abs",
            "name": "AshleyHoBugBash2Bot",
            "tenantId": "...",
            "subscriptionId": "...",
            "resourceGroup": "AshleyHoBugBash2Bot",
            "serviceName": "AshleyHoBugBash2Bot",
            "appId": "...",
            "id": "220"
        },
        {
            "type": "endpoint",
            "name": "AshleyHoBugBash2Bot",
            "appId": "...",
            "appPassword": "...",
            "endpoint": "https://shleyougashlo27.azurewebsites.net/api/messages",
            "id": "175"
        },
        {
            "type": "appInsights",
            "tenantId": "...",
            "subscriptionId": "...",
            "resourceGroup": "AshleyHoBugBash2Bot",
            "name": "AshleyHoBugBash2Botmvsg6g",
            "serviceName": "AshleyHoBugBash2Botmvsg6g",
            "instrumentationKey": "...",
            "applicationId": "...",
            "apiKeys": {},
            "id": "148"
        },
        {
            "type": "blob",
            "name": "shleyoup2oz",
            "serviceName": "shleyoup2oz",
            "tenantId": "...",
            "subscriptionId": "...",
            "resourceGroup": "AshleyHoBugBash2Bot",
            "connectionString": "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=shleyoup2oz;AccountKey=ACCOUNT_KEY",
            "container": null,
            "id": "60"
        }
    ],
    "secretKey": "",
    "version": "2.0"
}

```

Running the clone command successfully created it in Azure portal, however note that it does not have appId/password in Application Settings:
![image](https://user-images.githubusercontent.com/35248895/45647561-09070980-ba7b-11e8-9535-e1da78e34029.png)

* **npm config set registry https://botbuilder.myget.org/F/botbuilder-v4-js-daily/npm/**
* **npm install**
* **add to .env: botFilePath = .\AshleyHoBugBash2Bot.bot**
* **edit line 20 in bot.js: const LUIS_CONFIGURATION = 'AshleyHoBugBash2Bot-basic-bot-LUIS';**
* in terminal: **npm start**
* in Emulator: **File -> open AshleyHoBugBash2Bot.bot**
![image](https://user-images.githubusercontent.com/35248895/45647837-bf6aee80-ba7b-11e8-8728-136a86ebab62.png)

**at both development and AshleyHoBugBash2Bot endpoints, 401 authorization errors**:
![image](https://user-images.githubusercontent.com/35248895/45647906-f04b2380-ba7b-11e8-895a-ed145537be5a.png)

**Expected behavior**
to be able to connect to bot at both development and AshleyHoBugBash2Bot endpoints without 401 errors

**Additional context**

### SDK Platform: 
 Node

### URL of Code Sample
 https://github.com/Microsoft/BotBuilder-Samples/tree/v4/javascript_nodejs/13.basic-bot

**Comment by vishwacsena** [comment]
@Zerryth - was this resolved with @tonyanziano ? It might be better to track this in botframework-emulator repo. If you agree, can you move this issue and close this one?

**Comment by darrenj** [comment]
I am seeing the same issue after msbot clone services. Might be related to https://github.com/Microsoft/botbuilder-tools/issues/528

**Comment by vishwacsena** [comment]
Per Chat with Andrea, this might be related to our scratch and ppe environment. Jeff has checked in a fix and Andrea can no longer repro this. 

@Zerryth Closing this as fixed; please reactivate if you continue to see this.

**Comment by darrenj** [comment]
I can repro this again this afternoon, v4 emulator doesn't work but v3 does. I'm going to tear down the bot and re-create with latest template and will reopen if I see it

**Comment by mickallen** [comment]
I am having the same issue @darrenj what did you do to resolve this?

**Comment by darrenj** [comment]
You might have an old version do the emulator. Try the latest version from here: https://github.com/Microsoft/BotFramework-Emulator
________________________________

**Comment by mickallen** [comment]
> THis is down to the emulator not having the new changes for the .bot file padlock

Thanks @darrenj I'll give that a try and post back

**Comment by mickallen** [comment]
@darrenj, I downloaded the latest release (4.1.0)  from the releases page but still get the error, I am trying to run the NLP with Dispatch example from the samples repo  [https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/14.nlp-with-dispatch](url)

**Comment by Murthy582** [comment]
@mickallen, getting same error for javascript (node) version of "NLP with Dispatch" sample. Were you able to resolve?

**Comment by NoPinky** [comment]
got the same issue after following this tutorial:

[Tutorial: Create and deploy a basic bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-tutorial-basic-deploy?view=azure-bot-service-4.0&tabs=javascript)
