### ISSUE TITLE
msbot clone: "cannot read property 'split' of undefined" error

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/botbuilder-tools#516]
**Describe the bug**
Ran into this message in the Basic bot bugbash, step 8:
8)	You will now create all required services to for your basic bot. Run the following command
msbot clone services -n GIVE YOU BOT A NAME -f deploymentScripts/msbotClone --location westus --luisAuthoringKey YOUR LUIS AUTHORING KEY --verbose

msbot did create a resource in Ibiza, but not in LUIS.ai.

**Screenshots**
Messages from console:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/39317542/45655141-83438800-ba93-11e8-8dba-def2ab5e8884.png">

Resource created in Ibiza:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/39317542/45655100-568f7080-ba93-11e8-9a57-365f63246936.png">

(followed bug bash instructions on my Mac.)

**Comment by tomlm** [comment]
already been fix
