### ISSUE TITLE
undefined error whilst executing ludown translate

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#524]
ludown tool fails with an undefined error midway through translation of a large LU file (which itself was created through the ludown refresh command.

```shell
ludown translate --in model.lu -t de-DE -k mykey -o de
```

[LUISModel.zip](https://github.com/Microsoft/botbuilder-tools/files/2392492/LUISModel.zip)

**Comment by vishwacsena** [comment]
Thanks for this .lu file @darrenj. I did end up fixing 2 bugs in ludown with the parse route. In PR #535

That said, after peeling the layers of onion, the core issue with this specific file is that it has nested entity references in line 11511 - "{KEYWORD=s{ADDRESS=smog test queen only} on {ADDRESS=columbia} and smog test queen only". 

At the core, ludown still does not support nested entity references and I filed this issue (#534) to track that feature ask. 

Finally, I also just did hit my translator limits and received this error (more meaningful) than the generic undefined you ran into...
```shell
- {Adresse = 27. Straße} um {Stichwort = erster kanadischer Ort] fahren Sie uns dorthin

Text translator service call failed with [403] : Forbidden.
Please check key & language code validity
Stopping further processing.
```
