### ISSUE TITLE
msbot clone services creates new .bot files

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#527]
Repro:

- run msbot clone services and have it reach an error condition part way through (e.g. use region as westeurope
- delete the resource group
- note you still have djignitebot.bot file locally (which is OK)
- run the clone operation again (new resource group name) and it completes but creates a new .bot file (e.g. djignitebot2.bot)
- run project and it defaults (Correctly) to the original djignitebot.bot which isn't populated with the right secrets
- Exceptions raised due to misconfiguration

Desired Behaviour

- Prompt to overwrite settings in existing .bot file, warn that your bot may not use the expected file if you choose not to overwrite

**Comment by sgellock** [comment]
@darrenj if you hit this again, please capture repo steps and reopen.  thanks
