### ISSUE TITLE
msbot clone services deployment key padlock not working correctly

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#528]
Repro

- Successful deployment of a recipe using msbot clone services
- Run project and get an exception saying the LUIS key is not valid
- Observation 1 - the created LUIS key is not assigned to the published model (added it manually)
- Run project and then observe that the key being provided from configuration has not been decrypted
- Observation 2 - BotConfiguration.LoadAsync(..) isn't being passed a secret. appSettings.json not being updated with the secret provided to the user at the end of msbot clone services
- Added secret to appSettings.json file
- Same issue - returned key is still encrypted despite secret being passed

Expected

- msbot clone to update appsettings.json file or at least warn the user should do that
- the correct LUIS key to be returned for successful operation
- luis model publish by msbot clone services should use the key it's already received not a starter key

**Comment by sgellock** [comment]
@darrenj believe this is not-repo'd based on my conversation with TomLm.  Please reopen if you have a repo and we'll jump on it.

**Comment by darrenj** [comment]
Resolved - needed the latest packages which changed the schema
