### ISSUE TITLE
az cli error on mac: "No module named 'azure.mgmt.botservice' "

### ISSUE THREAD

**Issue by mewa1024** [Microsoft/botbuilder-tools#533]
**Describe the bug**
Followed the instructions for the Basic Bot bug bash and ran into this error. Continued to get the error after reinstalling AZ CLI.

**To Reproduce**
1. az extension remove -n botservice
2. az extension add -s https://icscratch.blob.core.windows.net/bot-packages/botservice-0.4.2-py2.py3-none-any.whl <https://icscratch.blob.core.windows.net/bot-packages/botservice-0.4.2-py2.py3-none-any.whl>  -y
3. az account set --subscription "Bot Service Testing (Scratch)"
msbot clone services -n basic-bot-mewa3 -f deploymentScripts/msbotClone --location westus --luisAuthoringKey *my-luis-authoring-key* --verbose

Got the error

**Screenshots**
<img width="599" alt="image" src="https://user-images.githubusercontent.com/39317542/45717273-4d170e80-bb4e-11e8-93b8-a541d182b6c4.png">

**Desktop (please complete the following information):**
 - OS: macOS high sierra 10.13.6

**Comment by tomlm** [comment]
fixed, added version check for 0.4.1
