### ISSUE TITLE
Dispatch tool & multi-region support

### ISSUE THREAD

**Issue by daltskin** [Microsoft/botbuilder-tools#537]
**Describe the bug**
Authoring regions can be different between LUIS and Qna Maker.  If luis model was created on https://eu.luis.ai.  QnA Maker region looks always to be set to westus - dispatch tool is unable to find the 
european based model.

**To Reproduce**
Create a luis model on eu.luis.ai
Create a Qna Maker model on qnamaker.ai
Add both models eg:

- dispatch add -type luis ...
- dispatch add -type qna ..
- dispatch create/refresh

**Error**
One or more errors occurred. (The remote server returned an error: (401) Access Denied.)

Request url: https://westus.api.cognitive.microsoft.com/luis/api/v2.0/apps/aeed9faf-[removed]/versions/0.1/export
Response: { "statusCode": 401, "message": "Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription." }

**Suggestion**
Perhaps the authoringRegion should be set at the services level within the dispatch json eg:

` {
      "authoringRegion": "westus"
      "kbId": "",
      "subscriptionKey": "",
      "type": "qna",
      "name": "",
      "id": ""
    },
    {
      "authoringRegion": "north europe"      
      "appId": "",
      "authoringKey": "",
      "version": "",
      "type": "luis",
      "name": "",
      "id": ""
    }`

**(Temp) Resolution**
Export eu.luis.ai model and import into luis.ai portal
Remove the previous (eu.luis.ai) luis app (eg. dispatch remove -t luis ..)
Add the luis.ai app
Regenerate the dispatch model

**Comment by tsuwandy** [comment]
you could add authoringRegion on Dispatch level.  Dispatch init —name dispatchName —authoringRegion westus —authoringKey <authoringKey>

**Comment by daltskin** [comment]
But that assumes both QnA Maker and LUIS are in the same region.  So you need to be able to do something like this at the service level:

`dispatch add -t luis -i {some guid} name 'some name' -version 0.1 -key {somekey} -luisAuthoringRegion 'north europe'`

**Comment by tsuwandy** [comment]
Ah, I see, we need to take --region or -r for "add" command.  For some reason, I thought we have this already.   I'll add this.   Thanks.

**Comment by tsuwandy** [comment]
Latest package published.  You can now specify --region or -r parameter on "add".
