### ISSUE TITLE
Update dispatch tool to check for .bot files

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#539]
When creating a Dispatcher through the msbot tool a .dispatchrc file isn't created meaning the dispatch tool cannot be used with msbot created dispatchers. 

If a developer types `dispatch refresh` they are prompted for a dispatch name even though there is a .bot file (but no dispatch) file.

It's not clear dispatch supports .bot files unless you type (dispatch refresh -h).

Behaviour should be to use the .bot file if present locally, then check for dispatchrc and then prompt as it does today.

dispatch refresh -b BOTFILE -s SECRET works well, this then creates a dispatchrc file which of course is then available for future refresh scenarios

**Comment by tsuwandy** [comment]
"dispatch refresh" should really not be called without existence of .dispatch file (dispatch definition file), it's meant to be called after "dispatch create" is called.  

We can check for existence of bot file but then use it but then again we have to make sure services in bot file and sources in dispatch are the same resources (LUIS/QnA).

**Comment by fbeauchemin** [comment]
shouldn't dispatch create/refresh use the .bot file (when specified) to create a .dispatch using the configuration of the service of type "dispatch"?

**Comment by vishwacsena** [comment]
@fbeauchemin - you can use the .bot file to create a dispatch model and update the .bot file with the dispatch service reference using this command - 

```bash
> dispatch create -b <bot file> | msbot connect dispatch --stdin
```

@tsuwandy - the ask here is that dispatch create and dispatch refresh use this order of precedence when creating/ refreshing the dispatch model - 1. bot file 2. dispatchrc file. Are there strong reasons why refresh cannot be handled with the dispatch service reference in the .bot file?

**Comment by fbeauchemin** [comment]
@vishwacsena you're right about the command and that's what we're using now. Prior to it, we had a `.dispatchrc` and that was creating the same *issue* as @darrenj.

**Comment by tsuwandy** [comment]
I'll use this to update Dispatch to automatically search for .bot file if there's any so no need to specify .bot file...

**Comment by tsuwandy** [comment]
Latest dispatch is deployed.
