### ISSUE TITLE
AZ: az bot create: Not outputting the AppInsights instrumentation key

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#542]
## Tool
Name: msbot
Version: 2.0.5-57
OS: Windows

## Describe the bug
When cloning the appInsights service from a .recipe file, the resulting config is missing the instrumentation key:

        {
            "type": "appInsights",
            "id": "3",
            "tenantId": "*****",
            "subscriptionId": "*****",
            "resourceGroup": "LamilEntepriseBot5",
            "name": "LamilEntepriseBot5mdussj",
            "serviceName": "LamilEntepriseBot5mdussj",
            "instrumentationKey": "",
            "applicationId": "",
            "apiKeys": {}
        },

**Context**
This did not occur in the previous version.

**Comment by tomlm** [comment]
this is bug in az resource extension

**Comment by swagatmishra2007** [comment]
this has been fixed in the latest cli extension
