### ISSUE TITLE
AZ CLI should map regions to app insights

### ISSUE THREAD

**Issue by carlosscastro** [Microsoft/botbuilder-tools#543]
Use this code

export const regionToAppInsightRegionMap: { [region: string]: string } = {
    australiaeast: 'southeastasia',
    australiacentral: 'southeastasia',
    australiacentral2: 'southeastasia',
    australiasoutheast: 'southeastasia',
    eastasia: 'southeastasia',
    southeastasia: 'westus',
    eastus: 'eastus',
    eastus2: 'eastus',
    southcentralus: 'southcentralus',
    westcentralus: 'westus2',
    westus: 'westus2',
    westus2: 'westus2',
    brazilsouth: 'southcentralus',
    centralus: 'southcentralus',
    northcentralus: 'southcentralus',
    japanwest: 'southeastasia',
    japaneast: 'southeastasia',
    southindia: 'southeastasia',
    centralindia: 'southeastasia',
    westindia: 'southeastasia',
    canadacentral: 'southcentralus',
    canadaeast: 'eastus',
    koreacentral: 'southeastasia',
    koreasouth: 'southeastasia',
    northeurope: 'northeurope',
    westeurope: 'westeurope',
    uksouth: 'westeurope',
    ukwest: 'westeurope',
    francecentral: 'westeurope',
    francesouth: 'westeurope'
}

**Comment by carlosscastro** [comment]
We should have smart region fallback instead of defaulting to south central us

**Comment by swagatmishra2007** [comment]
fixed in the latest cli
