### ISSUE TITLE
[bug] Dispatch init doesn't work

### ISSUE THREAD

**Issue by diberry** [Microsoft/botbuilder-tools#545]
## Tool
Name: Dispatch
Version: 1.1.0-14
OS: windows 10

## Describe the bug
Trying to init dispatch

## To Reproduce
1. dispatch init 
2. never returns

## To Reproduce
1. dispatch init -n diberrydispatch --luisAuthoringKey "<my-luis-auth-key>" --luisAuthoringRegion westus
2. never returns

## To Reproduce
1. dispatch init --help
2. returns

## Expected behavior
Expect an error if the syntax is wrong and expect init file on drive if not an error. Neither of these happen. 

## Additional context
Ultimately I want to run dispatch over my LUIS model to understand the analytics it reports but I can't get to that part until I get past this part -- according to the doc on this site. 
[bug]

**Comment by tsuwandy** [comment]
Dina thinks could be bash issue, regardless, it’s working now.
