### ISSUE TITLE
Generated bot file is missing configuration for some of the provisioned services

### ISSUE THREAD

**Issue by yochay** [microsoft/botbuilder-tools#571]
## Tool
Name: [Msbot|
Version: 2.0.5-61
OS: Win10

## Describe the bug

msbot clone 
This is the confirmation prompt I see
![image](https://user-images.githubusercontent.com/896149/45910686-10eae480-bdc0-11e8-819d-9728cd16ff40.png)
 

generated bot file includes only :
- abs
- original development 
- blob (this was not listed) 

Generated bot file is missing:
- production end point
- app insights (even after including entry in the recipe file, app insights is missing)

![image](https://user-images.githubusercontent.com/896149/45910866-a0dd5e00-bdc1-11e8-9299-58ae1c7d5657.png)

## To Reproduce
1. run msbot clone services on 02.Echobotwithcounter

using this recipe file
```json
{
  "version": "1.0",
  "resources": [
    {
      "type": "endpoint",
      "id": "1",
      "name": "development",
      "url": "http://localhost:3978/api/messages"
    }
  ]
}
```

## Expected behavior
Bot file should include a list of all resources that get created.

**Update**
When including production in the recipe it was included in the generated .bot file 
```
    {
      "type": "endpoint",
      "id": "2",
      "name": "production",
      "url": "https://your-bot-url.azurewebsites.net/api/messages"
    },
```

[bug]

**Comment by sgellock** [comment]
bot files are deprecated
