### ISSUE TITLE
Msbot clone should pull --luisAuthoringKey from environment or .luisrc

### ISSUE THREAD

**Issue by chrimc62** [microsoft/botbuilder-tools#578]
## Tool
Name: Msbot

## Describe the problem
Cloning samples is more difficult than it should be because of explicitly requiring everything and not being consistent with other tools.

## Describe the solution you'd like
When cloning samples it would be nice if:
LUIS_AUTHORING_KEY was the default authoring key.  That is what the LUIS tool does.
Name defaulted to the name the bot was exported from.  When cloning this is usually because you want to either clone a sample or move to another region or something.
It would be nice if --location defaulted like our other tools, but this is less important.  (And LUIS for example uses --region.)

## Describe alternatives you've considered
You could make a case that clone should be explicit.  

## Additional context

[enhancement]

**Comment by Kaiqb** [comment]
Closing as `msbot` is deprecated.
