### ISSUE TITLE
msbot blows away the bot file even if you say 'no' when asked to clone

### ISSUE THREAD

**Issue by chrimc62** [Microsoft/botbuilder-tools#579]
## Tool
Name: msbot
Version: 2.0.5-61
OS: Windows 10

## Describe the bug
When doing clone services if you answer "no" it will blow away the .bot file being created.  It should wait to create it until you confirm your intention.  

## To Reproduce
1. ...Create a foo.bot file and put stuff in it.
2. ...msbot clone services <args> --name foo.bot
3. ...Say 'n' when asked to proceed
4. ...foo.bot file is changed.

## Expected behavior
An existing .bot file should not be changed until you confirm the clone.  

## Additional context

[bug]

**Comment by vishwacsena** [comment]
Addressed via #804
