### ISSUE TITLE
msbot - name length validation would be nice

### ISSUE THREAD

**Issue by daveta** [microsoft/botbuilder-tools#581]
## Tool
Name: Msbot
## Describe the problem
msbot is gets through majority of deploy (with name 'daveta-enterprise' and then get the following:

[msbot] Command failed: az storage account create -g daveta-enterprise -n "daveta-enterpriseh5fp6pstorage" --location we  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\commands\__init__.py", line  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-core\azure\cli\core\__init__.py", line 436, in   File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-cli-storage\azure\cli\command_modules\storage\opera  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-mgmt-storage\azure\mgmt\storage\v2018_03_01_preview  File "C:\Users\troyd\AppData\Local\Temp\pip-install-8mvi0rnf\azure-mgmt-storage\azure\mgmt\storage\v2018_03_01_preview  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\msrest\serialization.py", line 662, in validamsrest.exceptions.ValidationError: Parameter 'account_name' must have length less than 24.

## Describe the solution you'd like
We should length check name and fail early.

**Comment by Kaiqb** [comment]
Closing as msbot is deprecated. For deployment, we recommend you use the ARM templates. For an example, see the samples repo.
