### ISSUE TITLE
MSBot is not consistent about reporting service names during progress

### ISSUE THREAD

**Issue by chrimc62** [Microsoft/botbuilder-tools#583]
## Tool
Name: Msbot
Version: 2.0.5-61
OS: Windows 10

## Describe the bug
Naming is not consistent for prefixes when reporting status.  It flips between - and _ when the real name should have _. 

## To Reproduce
1. ...Clone a bot with LUIS.
2. ...Look at the status in the text below look at the bolded text which is wrong because it uses - instead of _.
Creating LUIS Cognitive Service [### **basic-bot-LUIS**]
Fetching LUIS Keys [**basic-bot-LUIS**]
3. ...
4. ...

## Expected behavior
I would expect the names to align.

## Screenshots
C:\Users\chrimc\Source\repos\botbuilder-samples\samples\csharp_dotnetcore\13.basic-bot>msbot clone services --location westus --luisAuthoringKey %LUIS_AUTHORING_KEY% --name basic-bot --folder DeploymentScripts/MsbotClone
The following services will be created by this operation:
 Service                                 Location            SKU                 Resource Group
 Azure LUIS Cognitive Service            westus              S0                  basic-bot
Would you like to perform this operation? [y/n]y
Checking az botservice version
Fetching subscription account
Creating resources in subscription: User-chrimc 3d72e51f-7846-4704-8b1a-289d83776aec
Creating Azure group [basic-bot]
Creating LUIS Cognitive Service [### **basic-bot-LUIS**]
Fetching LUIS Keys [**basic-bot-LUIS**]
Creating and importing LUIS application [basic-bot_LUIS]
Updating LUIS settings [basic-bot_LUIS]
Training LUIS application [basic-bot_LUIS]

## Additional context

[bug]

**Comment by tomlm** [comment]
I have explained this, they are different services and the names output are accurate.

Your bug should be named "I don't like the default names for services"
