### ISSUE TITLE
msbot defaults to paid tier for Azure Search

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#584]
When cloning a bot that has an Azure Search service in the recipie we default to the Standard tier which costs around $80/£60 a month. We cover this by highlighting what we're going to do up front and warn in the docs. However Azure Search is one of the few services that doesn't let you reduce the tier after cloning. Meaning you'd have to msbot disconnect, delete, create and msbot connect.

Thinking about this, it might be good to have a property in the recipe for in this qna to indicate you want the free tier. If you already have a free tier then creation will fail as azure search limits the free instances you can have. Perhaps in the validation step we can check if a free tier is available and throw an error or just simply through a warning at the validation step to say creation may fail later if a free tier already exists would simplify the logic.

**Comment by garypretty** [comment]
As an additional note on this, the Standard service, which is currently being deployed for search, actually costs nearly £190 per month. At the very least I think the default should be Basic (approx. £60 per month) with a switch to allow to user to specify the search tier required when cloning service.

**Comment by garypretty** [comment]
Is there likely to be any movement on this soon?  We now have a live customer project where this is going to be an issue for us when automating our environment deployments. 
Thanks.

**Comment by stevengum** [comment]
Pinging @sgellock and @yochay for a priority on this one.

**Comment by tiagodenoronha** [comment]
Hey! I just blew up my monthly credits because I never read anything :) What is the procedure to "downgrade" (meaning delete and create) the Azure Search? I need to disconnect with msbot, delete the Azure Search, recreate and then connect?
