### ISSUE TITLE
Refine error when deploying LUIS with an incorrect region authoring key

### ISSUE THREAD

**Issue by darrenj** [microsoft/botbuilder-tools#585]
Developers often defautl to www.luis.ai as the portal and aren't aware of eu.luis.ai or interchange the too. If you run msbot clone services and specify a region of westeurope but provide authoring key from luis.AI it will fail

```
Command failed: luis import application --region westeurope --appName "EnterpriseBotTest_General" --in DeploymentScripts\msbotClone\general.luis --authoringKey MYAUTHORINGKEY--msbotAccess denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.
```

I've fixed the documentation to highlight this issue but we should consider refining the error message (i.e. Access denied to invalid subscription key. Did you retrieve this from the LUIS authoring website in the same region as you passed to msbot")

There are command line overrides for authoring / publishing to solve this but worth helping the developer out In docs/warnings

**Comment by britishbadger** [comment]
I've just spent 2-3 hours trying to figure this one out. Had no idea about eu.luis.ai. Changed the authoring key and hey presto it worked

**Comment by britishbadger** [comment]
@darrenj - I'm a sucker for not reading the docs and thinking I know best, until I don't. 

I'm still just trying to work out how things fit together at the minute especially with Azure and Ubuntu. I've been trying to see how much I can get away with in VSCode (Ubuntu) vs VisualStudio. The best conclusion I've come to is to set everything up in Azure and download the code, deviating from this seems to cause issues and the Visual Studio starter requires a lot of extra fiddling.

**Comment by darrenj** [comment]
Me too on the docs point :-)  That route of downloading the code is OK for the simpler scenarios but anything more complex requires LUIS, Dispatcher, QnA, etc. hence we've been pushing on the msbot clone services route to simplify creation of bots out of the box and provision of templates.

**Comment by chrimc62** [comment]
I believe this is obsolete with the bf cli work.
