### ISSUE TITLE
Wrong error from luis suggest intents 

### ISSUE THREAD

**Issue by yochay** [Microsoft/botbuilder-tools#588]
## Tool
Name: [LUIS]
Version: 2.0.13-13
OS: Win 10

## Describe the bug
Running the following command 
 luis suggest intents --intentId Greeting --appId <appid here>  --take 10

Generates the following error 
```
applicationPublishObject cannot be null or undefined.

LUIS Command Line Interface - © 2018 Microsoft Corporation

Suggests examples that would improve the accuracy of the intent model.

Usage:
luis suggest intents --intentId <string> --take <integer>

Command arguments are:
 --appId <string> (required)             The application ID.
 --versionId <string> (required)         The version ID.
 --intentId <string> (required)          The intent classifier ID.
 --take <integer>                        The number of entries to return. Maximum page size is 500.
                                         Default is 100.
```

Missing versionId yield a different error --> "applicationPublishObject cannot be null or undefined." which is not part of the help command

## Expected behavior
Provide error message that helps, like missing versionId
.

[bug]

**Comment by sgellock** [comment]
user error

**Comment by HarlowBurgess** [comment]
I am getting the same error. It would be helpful to know what "user error" yochay was making so that I might be able to avoid the same fate.

**Comment by CoHealer** [comment]
Triage and assigning tomorrow am

**Comment by anusharavindrar** [comment]
@cahann I tried recreating the issue and got the same error "applicationPublishObject cannot be null or undefined."  when I run this command ```luis suggest intents  --intentId <string> --appId <string> --versionId <string>```.
I tried adding the parameters for ApplicationPublishObject ( isStaging ,region, versionId ) in the command ```luis suggest intents --intentId <string> --appId <string> --versionId <string> --isStaging <Boolean> --region <string>``` , but it still throws the same error.
