### ISSUE TITLE
luis suggest intents return value doesn't make sense

### ISSUE THREAD

**Issue by yochay** [Microsoft/botbuilder-tools#589]
## Tool
Name: [luis]
Version: 2.0.13-13
OS: Win10

## Describe the bug
running the following luis suggest intents 
```
 luis suggest intents --intentId Greeting --appId <appID here> --version 0.1  --take 10
```

Results in showing the luis version? 
```
2.0.13-13
```

## Expected behavior
provide a meaningful results. 
- If there are no suggestions, return meaningful result "no suggestions at this time. Read more..."
- if there are result, show them :) 
- do not show the luis version

[bug]

**Comment by tomlm** [comment]
it's --versionId not --version 

--version returns the version of the tool
