### ISSUE TITLE
msbot clone services fails to provision MSA id

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#596]
When running clone services:

```shell
msbot clone services --name "SB_EnterpriseBot" --luisAuthoringKey "REDACTED" --folder "DeploymentScripts\msbotClone" --location "westeurope" --verbose
```

Customer receives this error 

"ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try again"

Verbose logs below:

[msbot] The following services will be created by this operation:
Service Location SKU Resource Group
Azure App Site Plan westeurope S1 SB_EnterpriseBot
Azure AppInsights Service West Europe F0 SB_EnterpriseBot
Azure Blob Storage Service westeurope Standard_LRS SB_EnterpriseBot
Azure Bot Service Registration Global SB_EnterpriseBot
Azure CosmosDB Service westeurope 1 write region SB_EnterpriseBot
Azure LUIS Cognitive Service westeurope S0 SB_EnterpriseBot
Azure LUIS Cognitive Service westeurope S0 SB_EnterpriseBot
(Dispatch)
Azure QnA Maker Service westus S0 SB_EnterpriseBot
Azure Search Service westeurope Standard SB_EnterpriseBot
Azure WebApp Service (Bot) westeurope SB_EnterpriseBot
Azure WebApp Service (QnA) westeurope SB_EnterpriseBot
Would you like to perform this operation? [y/n]y
[msbot] Checking az botservice version
[msbot] az -v
[msbot] Fetching subscription account
[msbot] az account show
[msbot] Creating resources in subscription: SBI-MVP-AzureSubscription **REDACTED**
[msbot] Creating Azure group [SB_EnterpriseBot]
[msbot] az group create -g SB_EnterpriseBot -l westeurope
[msbot] Creating Azure Bot Service [SB_EnterpriseBot]
[msbot] az bot create -g SB_EnterpriseBot --name SB_EnterpriseBot --kind webapp --location westeurope --insights-location "West Europe" --version v4
[msbot] [az bot] To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code C2Y6LR2HT to authenticate.
[msbot] az bot create -g SB_EnterpriseBot --name SB_EnterpriseBot --kind webapp --location westeurope --insights-location "West Europe" --version v4 exit code: 1
WARNING: The behavior of this command has been altered by the following extension: botservice
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code *REDACTED* to authenticate.
ERROR: Unable to provision MSA id automatically. Please pass them in as parameters and try again.
[msbot] Usage: msbot clone services [options]
allows you to clone all of the services a bot into a new azure resource group
Options:
-n, --name name of new bot
-f, --folder path to folder containing exported resources
-l, --location location to create the bot service in (westus, ...)
--luisAuthoringKey authoring key from the appropriate luisAuthoringRegion for luis resources
--luisAuthoringRegion (OPTIONAL) [westus|westeurope|australiaeast] authoring region to put LUIS models into (default is based on location)
--luisPublishRegion (OPTIONAL) region to publish LUIS models to (default fallback is based location || luisAuthoringRegion)
--subscriptionId (OPTIONAL) Azure subscriptionId to clone bot to, if not passed then current az account will be used
--insightsRegion (OPTIONAL) region to create appInsights account in (default is based on location)
--groupName (OPTIONAL) groupName for cloned bot, if not passed then new bot name will be used for the new group
--sdkLanguage (OPTIONAL) language for bot [Csharp|Node] (Default:CSharp)
--sdkVersion (OPTIONAL) SDK version for bot [v3|v4] (Default:v4)
-q, --quiet minimize output
--verbose show commands
-f, --force do not prompt for confirmation
-h, --help output usage information
[msbot] NOTE: You did not complete clone process.
[msbot] To delete the group and resources run:
[msbot] az group delete -g SB_EnterpriseBot --no-wait

**Comment by PowershellNinja** [comment]
Having exactly the same issue, is there an update?

**Comment by virajpangam** [comment]
> > ```
> >       Having exactly the same issue, is there an update?
> > ```
> 
> Hey - can I double check that az login worked beforehand and you were able to see your Azure Subscription? Just testing a theory.

Yes. I can confirm az login worked and I was able to see the subscription.

**Comment by QaisAlkhateeb** [comment]
I'm having the same Issue when running 'msbot clone services', 
I found that the error happen when executing 'az bot create' on "createBot()" function without passing appid and password.

**Comment by PowershellNinja** [comment]
I can also confirm I was able to see the subscription. I was also able to provision the bot directly using az bot create with a preprovisioned app id and password. But on rerunning the clone command it still tried to provision the bot although it was already there. This might  be a second issue

**Comment by darrenj** [comment]
Thanks - helpful narrowing down. We have a triage meeting today so will loop back with an update.

**Comment by QaisAlkhateeb** [comment]
The problem happen when the script try to create new chatbot by the command 'az bot create' without passing appid and password.
for me as a temporary solution I change the command and passing appid and password.
on "node_modules\msbot\bin\msbot-clone-services.js" createBot() function and edit the command to:

let command = `az bot create -g ${args.groupName} --name ${args.name} --kind webapp --location ${args.location} --insights-location "${args.insightsRegion}" --appid "my_appid" --password "my_password"`

**Comment by darrenj** [comment]
Hi,

Yes, this should be auto-provisioned. For some people this doesn’t appear to work.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by QaisAlkhateeb** [comment]
As Microsoft mentions on their documentation the --appid passed is your MSA ID not the application id.
you can read more details here https://docs.microsoft.com/en-us/cli/azure/bot?view=azure-cli-latest#az-bot-create.
I know it's very bad approach to save a password as plain text on this file but you can write some code that prompted you to enter the password instead of writing it on the file.

**Comment by virajpangam** [comment]
This is helpful. I will try it out. Thanks!

**Comment by virajpangam** [comment]
> As Microsoft mentions on their documentation the --appid passed is your MSA ID not the application id.
> you can read more details here https://docs.microsoft.com/en-us/cli/azure/bot?view=azure-cli-latest#az-bot-create.
> I know it's very bad approach to save a password as plain text on this file but you can write some code that prompted you to enter the password instead of writing it on the file.

Where do I find the MSA id?

**Comment by marvinbuss** [comment]
The MSA ID (Microsoft Account Identity) is afaik a typical Microsoft account consisting of an E-Mail address and an account password. 

Any updates on this issue? @darrenj

**Comment by virajpangam** [comment]
> The MSA ID (Microsoft Account Identity) is afaik a typical Microsoft account consisting of an E-Mail address and an account password.
> 
> @darrenj Any updates on this issue?

If that is true I am not sure why folks from Microsoft have been pointing us to https://apps.dev.microsoft.com/

Even on this https://github.com/Azure/azure-cli/issues/7192 
they have pointed us to the same link.

**Comment by darrenj** [comment]
MSA is misleading, it is an Application Id and Secret manually created through apps.dev.microsoft.com.  We are likely going to add the ability to provide a manually created appid/secret to msbot clone to work around this but I'm keen to understand what is different about your accounts that is causing this to fail.

Could you try two things using the same credentials. Go into the Azure Portal, Create a Web App Bot and see if that works (automatically create a AppId and Password is the default). I'm assuming this works fine.

In addition try logging into apps.dev.microsoft.com and creating an App there.

**Comment by virajpangam** [comment]
@darrenj 
I created a converged app on app.dev.microsoft.com.
I tried to run the command by hard coding the app id and key as @QaisAlkhateeb had told. But it doesn't seem to work.
When I checked the activity log I see the following error on the azure portal

`Error code
BadRequest
Message
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`

**Comment by adamhewitt627** [comment]
@darrenj I am able to create a Web App Bot from within the Azure Portal, and it successfully creates the MSA app id & password. However, I do hit this same error. The suggested workaround _does_ succeed.

Additionally, I'm seeing this behavior:
```powershell
az login
az account set --subscription "my_sub_name"

# Without the workaround, this launches the browser, like login above didn't work
msbot clone services ...

# Once adding the workaround in msbot-clone-services.js, no login prompts
msbot clone services ...

```

**Comment by marvinbuss** [comment]
> @darrenj
> I created a converged app on app.dev.microsoft.com.
> I tried to run the command by hard coding the app id and key as @QaisAlkhateeb had told. But it doesn't seem to work.
> When I checked the activity log I see the following error on the azure portal
> 
> `Error code BadRequest Message The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`
> 
> To your 2nd question I had followed https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-nodejs-tutorial-build-bot-framework-sample the other day and it worked fine.

I have the same issue. I tried multiple accounts and subscriptions and I was not able to run the deployment successfully.

**Comment by virajpangam** [comment]
@marvinbuss I found the issue.

I was passing --name with a dot. Though this can create a resource group, it is not possible to create a bot with dot.

I finally was able to get it working.

Summarizing the entire workaround below

1. Create a new converged app at https://apps.dev.microsoft.com
2. Create a new secret for the newly created converged app.
3. Go to C:\Users\{Username}\AppData\Roaming\npm\node_modules\msbot\bin and modify the line 
in createBot function with your app id and secret
let command = `az bot create -g ${args.groupName} --name ${args.name} --kind webapp --location ${args.location} --insights-location "${args.insightsRegion}" --appid "my_appid" --password "my_password"`
4. Execute the command clone command and keep in mind not to put a dot as the --name parameter.

**Comment by darrenj** [comment]
Thanks @virajpangam, @marvinbuss, @adamhewitt627 - There appears to be some known issues with auto-provision of Application Ids which are being looked at by another team. I've submitted a PR with a change that accepts applicationId and Secret being passed into clone services providing a workaround to unblock you al..

**Comment by ran2078** [comment]
I found the issue (after fixing the AppId etc) was with --location, 
Azure QnA Maker (also other resources) not avilable outside westus
Try change the location of all resources to westus (or hand code a valid combination)

**Comment by svarcoe** [comment]
Found out that you must be authenticated with a Microsoft Live account, otherwise you will run into this error. AD accounts will not be able to create apps automatically or manually. @virajpangam's work around is good if you have a live id.

**Comment by danuw** [comment]
All of the above seemed to unlock issues, but still got stuck further down the line with 

az bot create -g dispatcher-bot --name dispatcher-bot --kind webapp --location westus --insights-location "West US 2" --subscription REDACTEDID --version v4 --lang CSharp exit code: 1
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code REDACTEDCODE to authenticate.
**ERROR: Unable to provision Microsoft Application automatically. To manually provision a Microsoft Application, go to the Application Registration Portal at https://apps.dev.microsoft.com/. Once you manually create you application, pass the application Id and password as parameters for bot creation.**

I have just upgraded my tools to latest version (botservice extension version 0.4.3, dotnet core 2.2.101, azure CLI 2.0.52)

**Comment by chaolyang** [comment]
Just tried following the instructions [here](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/12.nlp-with-luis) and got this error about not being able to provision the app automatically. Tried go to https://apps.dev.microsoft.com/ and create a web app, clicked the setup guide but it also does not work.

Is this issue fixed yet? I installed all the prerequisites and started fresh following the instructions.

**Comment by darrenj** [comment]
Can you share the error you get when providing appid and secret as command line parameters? It should accept these and move forward. Also check the name of your bot is likely to be unique

**Comment by chaolyang** [comment]
@darrenj Thanks for the reply. Actually I got it to work after some tinkering. The issue was not the appid and secret, it was my LUIS configuration. Manual provision does work.

**Comment by darrenj** [comment]
Thanks for letting us know, if you've got any feedback on docs/tools to make it easier for others let us know.

Sent from Outlook Mobile<https://aka.ms/sdimjr>
________________________________

**Comment by ikendall** [comment]
Same problem, struggled for ages with this same error, but further abstracted as was using the deploy_bot.ps1 script for the Virtual Assistant solution. Work around by provisioning the app manually in apps.dev.microsoft.com and modifying the deploy_bot.ps1 script to ask for user input of AppID and AppSecret copied and pasted from apps.dev.microsoft.com. Is there any sign of a proper fix for this issue on the horizon?

**Comment by omega1119** [comment]
Hi there,

I'm also having this issue. Just wanted to find out if there is any news on a fix?

Thanks!

**Comment by ikendall** [comment]
Once you "get" it - the work around is easy for this one ... just make sure that you register the app name on https://apps.dev.microsoft.com/ ... note the App Id GUID and the App Password, and pass these in to msbot clone on the command line, with --appId and --appSecret. If you are using the pre-built Virtual Assistant solution, there is a Powershell script called deploy_bot.ps1 which you can edit to prompt for App ID and Password as inputs and then pass into msbot clone later in the script.

**Comment by omega1119** [comment]
Our team has been using the manual work around for a while now. However, satisfying our requirements are based on this fix becoming available at some point, which is why we are quite eager to find out if there are any indications of when this may be done.

**Comment by RobinRobinG** [comment]
Maybe the workaround should be added to the documentation.
