### ISSUE TITLE
Dispatch cli tool does not error correctly

### ISSUE THREAD

**Issue by JeffCordes** [Microsoft/botbuilder-tools#599]
## Tool
Name: Dispatch
Version: 1.1.0
OS: win 10 1803

## Describe the bug
Running dispatch commands from powershell does not properly set the $? (if last call succeeded) variable or exit codes on errors.  

## To Reproduce
1. in powershell Run a dispatch init command with a bad char in the -dataFolder 
2. example: dispatch init -name AdminDispatcher-n2a -luisAuthoringKey avalidkey -luisAutho
ringRegion westus -dataFolder AdminDispatcher.?*
3. in powershell execute the command $?

## Expected behavior
False (actual behavior is True)

## To Reproduce (scenario 2)
1. create a powershell .ps1 script with the following contents
```
try
{
    dispatch init -name AdminDispatcher-n2a -luisAuthoringKey myauthoringkey -luisAuthoringRegion westus -dataFolder AdminDispatcher.?*
}
catch
{
    Write-Error "A Error has occured"
    exit 1
}
```
2. Execute the script

## Expected behavior (scenario 2)
the script outputs "A Error has occured" and returns exit code 1

The actual result is that it returns exit code 0

[bug]

**Comment by tsuwandy** [comment]
Latest package published to npm with fix.
