### ISSUE TITLE
dispatch: file type filePath attribute renamed to path

### ISSUE THREAD

**Issue by srozga** [Microsoft/botbuilder-tools#603]
## Tool
Name: Dispatch
Version: 1.1.0
OS: Windows 10

## Describe the bug
I guess this may not exactly be a bug, but it seems that the file type of input into Dispatch now uses the attribute "path" for the path to the file of utterances to add into that intent was changed in the latest version from "filePath". All of my old .dispatch files use "filePath". When I run Dispatch, I get the error:
> ERROR
> Object reference not set to an instance of an object.

If there are breaking schema changes, the tool should provide a more descriptive error.

**Comment by tsuwandy** [comment]
Thanks for reporting this Szymon!  We had a revamp of types for msbot services and this is one of the changes which inadvertently caused this backward compat issue.  Working on a fix.

**Comment by srozga** [comment]
I figured. Thank you @tsuwandy !

**Comment by tsuwandy** [comment]
Latest package published to npm.
