### ISSUE TITLE
Luis import issue for Prebuilt models

### ISSUE THREAD

**Issue by ikivanc** [microsoft/botbuilder-tools#606]
## Tool
Name: [luis]
Version: 2.0.13

In order to produce modifed json file I followed [these](https://github.com/Microsoft/botbuilder-tools/issues/605) steps.

In my application I used Prebuilt models, then exported my application. After that when I try to import using luis-cli it gives below error. In this prebuilt model I populate with my own utterances, I need to import them.

Is it possible to fix prebuilt models name conflict using luis-cli import?

![image](https://user-images.githubusercontent.com/118657/46195592-72093f80-c30d-11e8-9cc3-e841023ee570.png)
```

 "entities": [
    {
      "name": "Communication.ContactName",
      "inherits": {
        "domain_name": "Communication",
        "model_name": "ContactName"
      },
      "roles": []
    },
    {
      "name": "Entertainment.Nationality",
      "inherits": {
        "domain_name": "Entertainment",
        "model_name": "Nationality"
      },
      "roles": []
    },
```
Thanks.

**Comment by sgellock** [comment]
Talked with @chrimc62, moving out to be a 4.3 deliverable

**Comment by daden-ms** [comment]
Is this going to be resolved in the next release? What's the time line for it? Thanks!

**Comment by aforank** [comment]
Is this issue resolved?
