### ISSUE TITLE
chatdown command won't  generate the appropriate transcript file

### ISSUE THREAD

**Issue by jitendriyag2** [Microsoft/botbuilder-tools#607]
Hi Team,
As per the suggestion given i followed the steps to generate the transcript file but the generated file won't open anything in BotBuilder v4.
[CreateABug.zip](https://github.com/Microsoft/botbuilder-tools/files/2427777/CreateABug.zip)

**Comment by corinagum** [comment]
Hi @jitendriyag2 
Could you try updating chatdown to v.1.0.10?  
This was a known error in chatdown that has been resolved. Please see this [issue in BotFramework-Emulator](https://github.com/Microsoft/BotFramework-Emulator/issues/931) for more information.

I recompiled your chatdown file with my updated chatdown version, and the transcript loads in Emulator with no problems. Please let me know if you have other questions.
