### ISSUE TITLE
Dispatch remote execution output issues

### ISSUE THREAD

**Issue by JeffCordes** [microsoft/botbuilder-tools#608]
## Tool
Name: Dispatch
Version: 1.1.0
OS: win 10 1803

## Describe the bug
Dispatch tool output does not support remote execution from tools like psexec that use remote execution protocols.  

## To Reproduce
1.  create a ps1 script with the following contents

```
dispatch init -name AdminDispatcher-n2a -luisAuthoringKey myauthoringkey -luisAuthoringRegion westus -dataFolder AdminDispatcher

echo "the dispatch command is complete"
```
2.  place it on a remote network pc
3. create a cmd script that contains the command "Powershell .\dispatchscript.ps1" (the name of the script you made above.)
4. use a tool like psexec to execute this remotely
"psexec \\myremotepc -u myuser -p mypass -w myremoteworkingdirectory -c mybatscript.bat"

## Expected behavior
the dispatcher is initialized, and the text "the dispatch command is complete" is echoed.

## what actually happens
the dispatcher init commands creates folders, but not the dispatch .json.  then everything hangs. 

Then you realize it has hung, and you hit ctrl-c (or otherwise try to cancel the execution)  immediately after that the dispatch.json file gets created, and the echo line executes.

## Additional context
We are trying to build CI\CD process around dispatcher\luis\qna for a client that does not use Azure devops.  this makes executing dispatch commands on build agents of other CI\CD systems fail.

[bug]

**Comment by ericchansen** [comment]
Any updates on this issue? I'm facing the same problem.

**Comment by tsuwandy** [comment]
@ericchansen, is the issue is with regard to remote execution or to target Azure government, more specifically for luis apps in azure government?  To target Azure government, we could set the endpoint in the json setting file.  Will follow up with the file name and the specifics property to update tomorrow.

**Comment by ericchansen** [comment]
@tsuwandy No. I'll explain my specific scenario.

In Azure DevOps, I'm running an Azure CLI task. This executes as batch. The batch script calls a PowerShell 6 script (https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/deploy.ps1), which then calls another PowerShell 6 script (https://github.com/microsoft/botframework-solutions/blob/master/templates/Virtual-Assistant-Template/csharp/Sample/VirtualAssistantSample/Deployment/Scripts/deploy_cognitive_models.ps1). Inside of `deploy_cognitive_models.ps1`, it runs `dispatch init` (line 120). This is where the entire process hangs indefinitely.

**Comment by tsuwandy** [comment]
@ericchansen, what's in deploy_cognitive_models.ps1?  dispatch init along with dispatch add and dispatch create commands?  

regarding running dispatch to target Azure government, you could update the endpoints in (find where dispatch cli is installed via "npm root", if globally "npm root -g".

\node_modules\botdispatch\bin\netcoreapp2.1\AugmentLuisModelSettings.json

The settings file look like the following, modify AuthoringBaseUrl and the EndpointBaseUrl to match the endpoints in Azure goverment (ie xxx.gov).  The placeholder {0} is populated with authoring/subscription region (ie "westus").
{
  "LuisApi": {
    "DispatchVersion": "1.5.0",
    "AuthoringBaseUrl": "https://{0}.api.cognitive.microsoft.com/luis/api/v2.0/apps",
    "EndpointBaseUrl": "https://{0}.api.cognitive.microsoft.com/luis/v2.0/apps"
  }
}

**Comment by ericchansen** [comment]
@tsuwandy There's a direct link to the full contents of `deploy_cognitive_models.ps1` in my previous comment. It's on Microsoft's https://github.com/microsoft/botframework-solutions/.

I don't believe your suggestion for Azure government is relevant here in particular.

**Comment by tsuwandy** [comment]
Thanks, will take a look and see if I could repro.

**Comment by ericchansen** [comment]
@tsuwandy Thanks! Let me know if there's anything I can do to help. I'm very much invested in being able to completely deploy a bot from a single click in an Azure DevOps pipeline. This is the only blocker I'm facing before completion.

**Comment by tsuwandy** [comment]
@ericchansen, will definitely do, thanks!  I have one thing to finish soon but this is the next priority.  I might need you to test out some changes but hopefully I could set up a similar environment to repro.

**Comment by ericchansen** [comment]
@tsuwandy Here's a bit more help if you're trying to recreate the same setup.

- Start off by creating a solution using the [virtual assistant v4 template](https://marketplace.visualstudio.com/items?itemName=BotBuilder.VirtualAssistantTemplate).
- Commit your solution code in Azure DevOps.
- Create an app registration for your bot.
  - Make note of the application ID.
  - Create a secret on your app registration.
- Create a release pipeline.
  - Add the repo as an artifact in your pipeline.
  - Navigate to the pipeline's tasks. Inside of the agent job (`Hosted VS2017` or `Hosted Windows 2019 with VS2019`), add an Azure CLI task.
    - For `Task version`, select `1.*`.
    - For `Script Location`, select `Inline script`.
    - For an example of what to put under `Inline Script`, see the code block below.
- Create a release using the pipeline. If you monitor the logs, you will see that execution hangs at `dispatch init`. All hosted jobs are automatically terminated after one hour.

```
call npm install -g botdispatch ludown luis-apis qnamaker luisgen@2.0.2
call npm install -g botskills
call pwsh -File _YourRepoName\YourSolutionName\YourSolutionName\Deployment\Scripts\deploy.ps1 -name "whatever-name-you-want" -location "westus" -luisAuthoringKey "xxx-xxx-xxx" -luisAuthoringRegion "westus" -resourceGroup "whatever-name-you-want-for-your-resource-group" -appPassword "whatever-password-you-created" -appId "xyz-xyz-xyz"
```

**Comment by FirebornX** [comment]
@tsuwandy in regards to 

> @ericchansen, what's in deploy_cognitive_models.ps1? dispatch init along with dispatch add and dispatch create commands?
> 
> regarding running dispatch to target Azure government, you could update the endpoints in (find where dispatch cli is installed via "npm root", if globally "npm root -g".
> 
> \node_modules\botdispatch\bin\netcoreapp2.1\AugmentLuisModelSettings.json
> 
> The settings file look like the following, modify AuthoringBaseUrl and the EndpointBaseUrl to match the endpoints in Azure goverment (ie xxx.gov). The placeholder {0} is populated with authoring/subscription region (ie "westus").
> {
> "LuisApi": {
> "DispatchVersion": "1.5.0",
> "AuthoringBaseUrl": "https://{0}.api.cognitive.microsoft.com/luis/api/v2.0/apps",
> "EndpointBaseUrl": "https://{0}.api.cognitive.microsoft.com/luis/v2.0/apps"
> }
> }

I modified this file per your suggestion to point the Urls to .api.cognitive.microsoft.us which is the azure government api endpoint for LUIS. Even having done that you still can't get it to accept the region, virginia / usgovvirginia which to my knowledge is the only datacenter setup to provide LUIS services for Azure government... looks like there's some validation going on that only allows it to accept westus/westeurope/australiaeast per the prompt.
![20190708](https://user-images.githubusercontent.com/4278203/60849094-1de59280-a19e-11e9-87ae-d0c98dcab93a.PNG)

**Comment by FirebornX** [comment]
Just downloaded the bot tools and decompiled Dispatch.dll
I can confirm that it is not setup to work with Azure government regions.

Class : CreateLuisDispatchCommands
Method : TryGetLuisRegion

It only accepts Authoring regions from LuisAuthoringRegions if isAuthoring is true or LuisSubscriptionRegions if isAuthoring is false

LuisAuthoringRegions and LuisSubscriptionRegions are hard coded HashSet<string> objects

You can only select from the following options:

public static readonly HashSet<string> LuisAuthoringRegions = new HashSet<string>((IEnumerable<string>) new string[3]
    {
      "westus",
      "westeurope",
      "australiaeast"
    });
    public static readonly HashSet<string> LuisSubscriptionRegions = new HashSet<string>((IEnumerable<string>) new string[12]
    {
      "westus",
      "westus2",
      "eastus",
      "eastus2",
      "westcentralus",
      "southcentralus",
      "westeurope",
      "northeurope",
      "southeastasia",
      "eastasia",
      "australiaeast",
      "brazilsouth"
    });

I don't know if all it would take is to add "virginia" to those lists and then modify the AugmentLuisModelSettings.json file to point to the government endpoints or not... but with it just rejecting unlisted regions outright you're not going to get past that validation step no matter what you do.

**Comment by tsuwandy** [comment]
@FirebornX, good catch.  Work around would be to finish “dispatch init” command with one of those valid regions, then manually update them in .dispatch file before running “dispatch create” command.  Let me know if you are still having trouble with it.  I’ll add the valid gov regions for the next cli update.  Thanks.

**Comment by FirebornX** [comment]
@tsuwandy I'll try that tomorrow and see if it works. Thanks for your help!

**Comment by ericchansen** [comment]
@FirebornX nice ideas with the gov issue!

I think the issue in #608 (here) is a bit different though.

**Comment by FirebornX** [comment]
@tsuwandy I was able to complete the "dispatch init" successfully when I use one of the valid regions.
I then edit the resulting .dispatch file to have virginia for the regions.
I also edit AugmentLuisModelSettings.json to point to the .api.cognitive.microsoft.us endpoints for Azure gov.
Then I "dispatch add" LUIS apps to the dispatch file. It succeeds.
Then I "dispatch create" it hangs on one app that has intents but no utterances. This seems to be a limitation of LUIS more than the dispatch tool. LUIS will fail to train if there are intents which contain no utterances.
Creating seems to function but then throws an error, I don't know if this is at all related to the current issue though.
![20190709](https://user-images.githubusercontent.com/4278203/60916282-d06f3100-a242-11e9-95f5-62a89a6b60a7.PNG)

**Comment by FirebornX** [comment]
@ericchansen you may be right, I don't want to hijack this thread if it is different. I do however think that the issues I'm having might be causing the underlying hang-up issue that you're having.

**Comment by tsuwandy** [comment]
@FirebornX thanks for the update.  Did you try adding a few utterances to the problematic intent?  I agree with @ericchansen we should discuss the gov issue in https://github.com/microsoft/botbuilder-tools/issues/608.  I don’t think they are related, i’m trying out script with just init in it.

**Comment by FirebornX** [comment]
Since the consensus is that the two issues aren't related I'll keep my comments in #1199 rather than muddying the waters here. : )

**Comment by tsuwandy** [comment]
@ericchansen , got a repro following original repro steps from jeff, debugging it now and trying to narrow down the offending code.

**Comment by ericchansen** [comment]
@tsuwandy Keep me posted. Glad you found the offending code! It would be great if an update was pushed soon!

**Comment by tsuwandy** [comment]
The offending code is needed to handle input from pipe (output from msbot), ie:

type foo.bot | dispatch create

Unfortunately, we couldn't distinguish between standard input redirection from pipe or when cli is executed remotely (anonymous vs named pipe).  To support both, there is now an optional parameter for running remotely "--remote true".  If piping in input in remote execution, no need to use the --remote parameter.

Will deploy an updated cli by tomorrow.

**Comment by ericchansen** [comment]
That's excellent news. Let me know when the update is live and the version number. If I'm understanding correctly, once I use the updated version, I can use `dispatch init` as before but add in `--remote true`, so `dispatch init --all-my-other-arguments-here --remote true`?

**Comment by tsuwandy** [comment]
Yes, exactly!   Just trying to see if I could bundle the fix with issue @FirebornX found with running in azure gov.  If this takes too long then i’ll just split the two fixes.  Version 1.5.1.

**Comment by ericchansen** [comment]
@tsuwandy This is one of the last deliverables that I have for one of my clients, but don't let me sway you. 😛

**Comment by tsuwandy** [comment]
Latest cli is deployed to npmjs.  Please let me know if you are seeing other errors.  Thank you!!
