### ISSUE TITLE
Latest az bot extension is not available via az extension add -n botservice

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#615]
## Tool
Name: Az bot
Version: 0.0.3
OS: any

## Describe the bug
```bash
C:\repos\BotBuilder-Samples\samples\javascript_nodejs\51.cafe-bot>az extension list
[
  {
    "extensionType": "whl",
    "name": "botservice",
    "version": "0.0.3"
  }
]

C:\repos\BotBuilder-Samples\samples\javascript_nodejs\51.cafe-bot>az extension remove -n botservice

C:\repos\BotBuilder-Samples\samples\javascript_nodejs\51.cafe-bot>az extension list
[]

C:\repos\BotBuilder-Samples\samples\javascript_nodejs\51.cafe-bot>az extension add -n botservice
The installed extension 'botservice' is in preview.

C:\repos\BotBuilder-Samples\samples\javascript_nodejs\51.cafe-bot>az extension list
[
  {
    "extensionType": "whl",
    "name": "botservice",
    "version": "0.0.3"
  }
]

```

## Expected behavior
Expect az extension command to install the latest 0.4.1 az bot extension

[bug]

**Comment by vishwacsena** [comment]
@swagatmishra2007; @carlosscastro  - this appears to be an issue because I was on the older AZ CLI version. We should update the README to call out that the users need to have AZ CLI version >= 2.0.45 installed.

**Comment by sorgina13** [comment]
I am still getting the same error as per the first entry!

**Comment by swagatmishra2007** [comment]
@sorgina13  what is your core cli version? Can you run `az --version`?
See the topmost line of the output. It should be azure-cli (2.0.45) or greater.

**Comment by sorgina13** [comment]
@swagatmishra2007 , thanks for your reply. It is indeed azure-cli (2.0.35). How do I upgrade it?

**Comment by sorgina13** [comment]
sorted! just downloaded the latest msi and reinstalled!

**Comment by ashoksamal6363** [comment]
Hi, i have cli 2.0.53 and i am expecting bot service 0.4.3. But i only have botservice 0.4.1. 
How can i get botservice 0.4.3?

**Comment by carlosscastro** [comment]
You can run

 ```
az extension remove -n botservice
az extension add -n botservice
```

**Comment by ashoksamal6363** [comment]
It ll still install bot service 0.4.1 but i am looking for 0.4.3 to run my virtual assistant

**Comment by mhyon** [comment]
I have the same problem (az version 2.0.53).  Debug output shows this: 
Skipping 'botservice-0.4.3-py2.py3-none-any.whl' as not compatible with this version of the CLI. Extension compatibility result: is_compatible=False cli_core_version=2.0.53 min_required=2.0.52 max_required=2.0.52

**Comment by AllanXu49** [comment]
@ashoksamal6363 how did you get the msi file? The google drive link has the source code only. MSI file is missing.

**Comment by ashoksamal6363** [comment]
Please check this. 
https://drive.google.com/open?id=1OmGtfMkd5bEuz3hwqiLstJDGsshK6-AN

**Comment by armstrong-charles** [comment]
az --version ? shows azure-cli as 2.0.54, but botservice as 0.1.3, when i try to remove botservice thru this command, az extension remove -n botservice, it says The extension botservice is not installed. How to update botservice extension.
When i run my msbot clone services...., i keep getting You need to upgrade your az bot service version to >= 0.4.3... how to fix it?

**Comment by stevengum** [comment]
@armstrong-charles, we’re planning on releasing a new version of msbot soon that will fix this problem. With the upcoming release you won’t need to add the extension in addition to having azure-cli installed to use msbot

**Comment by armstrong-charles** [comment]
Is there any workaround now? it is a blocking issue, any help will be greatly appreciated.

**Comment by armstrong-charles** [comment]
@stevengum, how about uninstalling and installing older version of Azure CLI? any suggestion?

**Comment by armstrong-charles** [comment]
@stevengum, how to get binary release of azure CLI v2.0.52 without building it from https://github.com/Azure/azure-cli/releases source.

**Comment by stevengum** [comment]
We haven’t done a release on NPM yet, but our daily feed does have the bits needed for msbot to work with azure-cli 2.0.53 and greater. It can be found here:

https://botbuilder.myget.org/feed/botbuilder-tools-daily/package/npm/msbot/4.3.2-125

**Comment by stevengum** [comment]
@armstrong-charles, I've found a link that should work; this should get you azure-cli 2.0.52: https://azurecliprod.azureedge.net/msi/azure-cli-2.0.52.msi

**Comment by MilanMej** [comment]
@armstrong-charles Have you solved your problem? I am facing the same issue as you did (need to upgrade my botservice). 
Tried hints from this thread but doesnt work with me (I am totally new in programming so not sure if its my mistake or other issues)

**Comment by AllanXu49** [comment]
I solved it by downgrading to the older version of azure CLI. Two options:

Option1: use chocolatey
choco install azure-cli --version 2.0.52

Option 2: Get it from here:
https://azurecliprod.azureedge.net/msi/azure-cli-2.0.52.msi

A few hints:

When `MsBot ` fails, it shows you the `az bot` command failed.  you can run the command at the command line and get more detail by `az group deployment operation list --resource-group` 

I spent a few hours until I found that I have to change the bot name everytime I re-try the `MsBot ` command.


I think `MsBot ` is just a patch solution untill this product becomes more mature. You would not see such bad product design when Google engineers to design and deliver something.

**Comment by vasavenk** [comment]
Hi @AllanXu49 
 
I tried following your solution, however, I get the following error:

With msbot 4.3.2 and later, the only AZ CLI prerequisite is having an AZ CLI version >= 2.0.53. If you have the botservice extension installed as well, please remove this via "az extension remove --name botservice".
Checking az botservice version
az -v
You need to upgrade your AZ CLI version to >= 2.0.53.
        You can install the latest AZ CLI from https://aka.ms/az-cli-download

what version of msbot are you running?

**Comment by MilanMej** [comment]
@AllanXu49 I tried the first option (not 100% sure how to use the other one) and proceeded like this:
1. install choco (0.10.11)
2. install azure - cli (2.0.52) using the command you sent 
3. used command: 'az extension add -n botservice' 
with error No matching extensions for 'botservice'.
my msbot is 4.3.1
Did I miss some step? Thanks.

**Comment by chasemwilliams** [comment]
Any update here? I am getting the same error 'No extension found with name 'botservice''

**Comment by AllanXu49** [comment]
Hi Folks,

The setup I mentioned worked for me. Mind that I used  `msbot clone services` command only. 

Please take a look at #738 as well. The product group supposed to fix this last Friday. You might want to follow up with them too. @sgellock explained that they are updating MSBOT tool.

**Comment by DennisdeRooAsapnet** [comment]
Here the same; I do have the same version but getting error No matching extensions for 'botservice'. while trying to add extention botservice using command az extension add -n botservice. @stevengum any idea when the release is ready. Is support for azure-cli 2.0.54 included?

**Comment by sgellock** [comment]
Az CLI 2.0.54 has shipped.  It installs botservice 0.1.3.

Running: az extension add -n botservice errors out with:
No matching extensions for 'botservice'. Use --debug for more information.

**Comment by DennisdeRooAsapnet** [comment]
@stevengum , Thanks, that's working now!

**Comment by stevengum** [comment]
Closing as this has been addressed with the latest public release of msbot, version [**4.3.2**](https://www.npmjs.com/package/msbot/v/4.3.2). This version of msbot does not use the botservice extension, so you are not required to call az extension add -n botservice. 

If you still run into this issue, please **@mention** me in this issue or open up a new issue.

**Comment by olufemig** [comment]
@stevengum, i have version 4.3.2 of msbot and come up with the same error

`C:\Users\olgeorg\Documents\Visual Studio 2017\Projects\SovereignBot\SovereignBot>msbot clone services --name "SovereignBot" --luisAuthoringKey "2c92b0812f6b47cfa5d4da293f2bbaa3" --folder "DeploymentScripts\en" --location "westus"
With msbot 4.3.2 and later, the only AZ CLI prerequisite is having an AZ CLI version >= 2.0.53. If you have the botservice extension installed as well, please remove this via "az extension remove --name botservice".
Checking az botservice version
You need to upgrade your AZ CLI version to >= 2.0.53.
        You can install the latest AZ CLI from https://aka.ms/az-cli-download`

**Comment by sgellock** [comment]
@olufemig what version of Azure CLI to you have, also, if you've installed a version of Azure CLI prior to 2.0.53, can you check if the bot extension is installed?  The error message you've supplied would imply that an old extension is installed and needs to be removed:

_If you have the botservice extension installed as well, please remove this via "az extension remove --name botservice"._

**Comment by LuNest** [comment]
@stevengum  @sgellock I'm having the same issue. 
    msbot version 4.3.2
    Azure CLI version: 2.0.58
    Bot extension has not been previously installed.

**Comment by stevengum** [comment]
@LuNest and @olufemig please use Azure CLI 2.0.57 while we investigate this issue. This specific version of Azure CLI can be installed via this link: https://azurecliprod.azureedge.net/msi/azure-cli-2.0.57.msi

**Comment by lukaesch** [comment]
I am having the same issue on macOS High Sierra 10.13.6.
msbot: 4.3.2
Azure CLI: 2.0.58
Command `az extension add -n botservice --debug` results in :
...
Skipping 'botservice-0.4.3-py2.py3-none-any.whl' as not compatible with this version of the CLI. Extension compatibility result: is_compatible=False cli_core_version=2.0.58 min_required=2.0.52 max_required=2.0.52
..
At the moment most of the official sample bots can not be configured as described in their readme files on github.

**Comment by sgellock** [comment]
We're working to get 4.3.3 of msbot out that contains a fix for this.
