### ISSUE TITLE
Proposal - Msbot clone services should support additional services’ configuration options

### ISSUE THREAD

**Issue by yochay** [microsoft/botbuilder-tools#620]
## Tool
Name: [Msbot]

## Describe the problem
msbot clone services is hard coded to specific set of service configuration, specifically to the default values of the services created. Developers want to control the specific setup and configuration of services that get created for a given bot. 

ARM was created as a consistent programmatic method to control resources in Azure and provided full CRUD support over any resources in Azure. msbot clone services should provide the level of support provided by ARM by taking additional parameter per services (for example App Aervice Plan for the web host), on top of the existing functionality that include setting up language services such as LUIS and QnA, and training them. Considering the .bot file is integral part of bot configuration and run-time (_Microsoft.Bot.Configuration.BotConfiguration_) and get generated by msbot clone, it is expected that msbot will provide more granular configuration support for Azure resources (LUIS included…)

## Describe the solution you'd like
Suggesting: add ability for msbot clone services to generate an azure deploy ARM template and allow customers to change parameters in that file before creating all services. The default behavior of clone services should remain the same, however, msbot clone will generate an ARM file with all services, allowing customers chooses to change parameters and configuration. A given customer should be able to review and change the auto generated ARM deploy template before msbot clone creates all services. 

Alternative, msbot clone services can receive an Azure ARM template file. 
msbot clone services works takes a recipe file, which includes list of services. For each ‘type’ of service, msbot can have a predefined ARM template (fragment) of that given resources.  msbot clone will then generate an ARM template that can be deployed. We still need extra steps for setting up LUIS and calling the training methods for both QnA and LUIS. 

This might look like the following:
Msbot clone services -> generate AEM template -> allow user to change arm template 
1.	_msbot clone services -f <>  --luis-key <>_
2.	(generates ARM template)
3.	Ask user to approve default create (as today) or allow to edit ARM template. (user choose to further configure suggested deployment)

Customer runs msbot clone again pointing to the ARM, recipe files, and cognitive models.
1.	_msbot clone services --armdeploy <ARM-Template-file> --luis-key <asasa>_
a.	(note, as soon as LUIS becomes a first class Azure file we do not need to special case LUIS.)
2.	ask the user if he wish to continue creating all services 
(note, as soon as LUIS becomes a first class Azure file we do not need to special case LUIS.)

## Describe alternatives you've considered
An alternate option is to add additional meta-data to the bot file mimicking the configuration options that ARM provides. However that can prove very costly and hard to maintain in the long run.  

{
  "version": "1.0",
  "resources": [
    {
      "type": "endpoint",
      "id": "1",
      "name": "development",
      "url": "http://localhost:3978/api/messages"
    },
    {
      "type": "luis",
      "id": "7",
      "name": "homeautomation.luis"
    },
    {
      "type": "luis",
      "id": "50",
      "name": "weather.luis"
    },
    {
      "type": "qna",
      "id": "201",
      "name": "sample.qna"
    },
    {
      "type": "dispatch",
      "id": "161",
      "name": "bot-dispatch",
      "serviceIds": [
        "7",
        "50",
        "201"
      ]
    },
    {
      "type": "endpoint",
      "id": "2",
      "name": "production",
      "url": "https://your-bot-url.azurewebsites.net/api/messages",
**"AppServicePlanName": “”,
"AppServicePlan": "”…**

    },
    {
      "type": "abs",
      "id": "3",
      "name": "Dispatch-Bot",
	"WebApp": “or a function bot”,
    },
    {
      "type": "appInsights",
      "id": "4",
      "name": "Dispatch-Insights"
    },
    {
      "type": "blob",
      "id": "5",
      "name": "Dispatch-Blob",
      "container": "botstatestore",
**"BlobType": “”,**
    }
  ]
}

## Additional context

[enhancement]

**Comment by vishwacsena** [comment]
We can do this once LUIS is ARM configurable. @cahann FYI

**Comment by sgellock** [comment]
msbot is deprecated.
