### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-tools#621]
The travis-ci build of the repo is broken with the inclusion of .Net Core 2.1 code as part of LuisGen. The .Net components are building as part of the AzureDevops pipeline, but the JS code is not being build.

For now, I've disabled the Travis-CI build and will sync with @tomlm in the morning to figure out what our plan is for this repo.

**Comment by stevengum** [comment]
I took Tom’s changes and added some of my own changes to a new branch to get the build up and [running](https://travis-ci.org/Microsoft/botbuilder-tools/builds/435963862?utm_medium=notification&utm_source=email)... except the dotnet tests for LUISGen are still disabled; the TS side of things is functioning.

One thing to note, the bot.builder.ai.luis dependency in the csproj for the LUISGen tests needs to be updated to 4.0.7
