### ISSUE TITLE
[LUIS] Deprecated code should be removed

### ISSUE THREAD

**Issue by JuanAr** [Microsoft/botbuilder-tools#628]
## Tool
Name: **LUIS**

## Describe the bug
Passing `list patterns` as argument to `luis.js` results in an error message saying `client.pattern.list is not a function`. 

## To Reproduce
1. `npm install luis-apis`
2. Execute the following command:  `node node_modules\luis-apis\bin\luis.js list patterns --authoringKey dummyKey`.
3. The following error message appears: `client.pattern.list is not a function`.

## Expected behavior
Executing LUIS with those arguments should result in a `'patterns' is not a valid resource'` error message.
Also the code validating the arguments `list patterns` should be removed from [`luis.js`](https://github.com/southworkscom/botbuilder-tools/blob/789af040c7dc6009b3b39f42e2b83df3b0fe3c24/packages/LUIS/bin/luis.js#L409-L411)

## Screenshots
![image](https://user-images.githubusercontent.com/805847/46430935-e0406e80-c720-11e8-8132-16c869378a94.png)

![image](https://user-images.githubusercontent.com/805847/46430945-e6364f80-c720-11e8-8c6e-42b7827ae114.png)

## Additional context
However the code for it still exists inside `luis.js`, and it is shown when using `--help` command.
`LUIS-authoring.json` mentions patterns being deprecated.

[bug]

**Comment by cristianossd** [comment]
I would like to work on this
