### ISSUE TITLE
[msbot] can not clone service

### ISSUE THREAD

**Issue by Samurais** [Microsoft/botbuilder-tools#632]
There is a bug with these lines:

https://github.com/Microsoft/botbuilder-tools/blob/08ff1fb1e2ef7b060549b57ee8189549556d04ce/packages/MSBot/src/msbot-clone-services.ts#L255

```
        command = `az account show `;
        if (args.subscriptionId) {
            command += `--subscription ${args.subscriptionId}`;
        }
```

The error is like this:

![image](https://user-images.githubusercontent.com/3538629/46512571-4d6e1400-c887-11e8-868d-44792232fb12.png)

it should be 

```
        command = `az account show `;
        if (args.subscriptionId) {
            command += ` --subscription ${args.subscriptionId}`;
        }
```.

**Comment by Samurais** [comment]
create PR in https://github.com/Microsoft/botbuilder-tools/pull/634

**Comment by sgellock** [comment]
fixed in latest nightly builds.
