### ISSUE TITLE
Ludown translate does not handle multi-word labels correctly

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#636]
## Tool
Name: Ludown
Version: latest
OS: any

## Describe the bug
Ludown translate with multi-word labeled utterance does not translate correctly. Results in malformed utterances that cannot be imported to LUIS.

[bug]

**Comment by darrenj** [comment]
Fix tested on FIGS and ZH languages - I can now create LUIS files :)

**Comment by vishwacsena** [comment]
@darrenj - did you try the fix off my branch or are you commenting that what's available in master/ npm already works for your scenarios?

**Comment by darrenj** [comment]
@vishwacsena off your branch ;-)

**Comment by vishwacsena** [comment]
@darrenj - just so we are on the same page, you tested the fix off **vishwac/ludown-test-fix** branch? I had WIP fix in this branch and so I'm a bit surprised that it worked for you .. :)

**Comment by darrenj** [comment]
Yep. Chinese I struggle to read but reproed the same issue with german which I can just about read and it appears to have resolved the "corruption" of utterances that was occurring during translation scenarios. I'm able to create .luis files now - can't speak to the performance of the models yet but they look OK. Needs more exploration though.

**Comment by vishwacsena** [comment]
@darrenj - Thanks. I also added support for multiple target languages as well. Both tickets are addressed via this PR - #640
