### ISSUE TITLE
Add multiple langauges to to_lang (-t) parameter

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#638]
## Tool
Name: Ludown

## Describe the problem
In my scenario I have a LU file that I want to translate into EFIGS languages. Right now I need to call LU for each language.

## Describe the solution you'd like
-t parameter to accept a comma separated list of locales -eg. `-t zh-hans, fr, it, de, es` which Ludown then uses to iterate through each locale pushing files into the output directory under a locale folder

[enhancement]

**Comment by vishwacsena** [comment]
Supported via this PR - #640
