### ISSUE TITLE
LUISGen build failure in Travis

### ISSUE THREAD

**Issue by dfavretto** [Microsoft/botbuilder-tools#651]
## Tool
Name: LuisGen
Version: *2.0.0*
OS: *Windows 10 Pro V1803*

## Describe the bug
When building BotBuilder-Tools project, the message from `lerna` has an error when displaying LUISGen name.
![image](https://user-images.githubusercontent.com/23645105/46835668-4d897a80-cd85-11e8-9217-6bbfab409605.png (7 kB))

This is because the `package.json` is missing the **name** property. We traced the file's history and identified [this commit](https://github.com/Microsoft/botbuilder-tools/commit/d336a7db93f2256379c5635ff7e2618274aef9ab#diff-60bf97c657644046ec4a9ee060510ed1) moving the original file, and [this other commit](https://github.com/Microsoft/botbuilder-tools/commit/04fb7b174cd57cd997b8b3a1ecfe7fa99a5a6416#diff-60bf97c657644046ec4a9ee060510ed1) restoring it without the property. The [Travis build](https://travis-ci.org/Microsoft/botbuilder-tools/jobs/440256241#L1061), despite being a successful build, the publish of LUISGen tool is failing.
![image](https://user-images.githubusercontent.com/23645105/46835962-1071b800-cd86-11e8-903a-60ecf641c121.png (13 kB))

## To Reproduce
1. Run `npm run build` command in **BotBuilder-Tools**
2. Check the **lerna** result in the terminal

## Expected behavior
The **lerna** result should state the correct name for the different tools.
![image](https://user-images.githubusercontent.com/23645105/46836068-5d558e80-cd86-11e8-8e45-8d35128f2c38.png (14 kB))

[bug]

**Comment by cleemullins** [comment]
@dfavretto I just filed (and fixed) #653, which was a broken build of the LuisGen Nuget package. 

You can see that the LuisGen Nuget package is now publishing to our [daily build feed](https://botbuilder.myget.org/feed/botbuilder-tools-daily/package/nuget/LUISGen).

... although the version # is wrong. :(

**Comment by sgellock** [comment]
Fixed in the currently daily builds.
