### ISSUE TITLE
Dispatch refresh doesn't use correct luis version number

### ISSUE THREAD

**Issue by garypretty** [Microsoft/botbuilder-tools#661]
## Tool
Name: Dispatch
Version: 1.1.2-41
OS: Windows

## Describe the bug
Calling dispatch refresh --bot MyBot.bot --secret [my-secret] should refresh my dispatch model using the details within my .bot file. This fails for me because it is trying to use v0.1 for my luis model, however, this version doesn't exist as I have deleted it.  Entry is bot file shows correct version, 0.16, but running the dispatch refresh command doesn't respect this version.

```json
{
            "type": "luis",
            "name": "MyBot_General",
            "appId": "redacted",
            "authoringKey": "redacted",
            "subscriptionKey": "redacted",
            "version": "0.16",
            "region": "westeurope",
            "id": "general"
        }
```

## Expected behavior
Dispatch refresh should use the correct version (0.16 in the example)

[bug]

**Comment by tsuwandy** [comment]
@garypretty, did you pass the .bot file to the refresh command? ie dispatch refresh -b {botfile}

**Comment by garypretty** [comment]
Hi. Apologies for the slow reply. Yes, I passed the bot file to the dispatch refresh which is why I assumed it would look at that version number.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tsuwandy** [comment]
Thanks for the confirmation @garypretty!

**Comment by tsuwandy** [comment]
found the bug, will try to get the fix out by tomorrow.  Thanks @garypretty for reporting!

**Comment by tsuwandy** [comment]
updated CLI with this fix was published to npm yesterday.
