### ISSUE TITLE
ludown translate/parse generated JSON file doesn't import into LUIS

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#662]
## Tool
Name: ludown
Version: 1.0.35-69
OS: Windows

## Describe the bug

When using `ludown translate` to convert an en .LU file to zh-hans and then performing `ludown parse` the resulting file cannot be imported into LUIS:

>BadArgument: Character indicies 6,7 do not correspond to the start and end of a token

Conversation with the LUIS team highlights the following

```
We expect the beginning and end of the entity label to be the character indices of the required label, however, we tokenize the input string, and require that those two indices enclose one or more tokens, such that “startPos” is the index of the first character of the first token of the label, and “endPos” is the index of the last character of the last token of the label. 

In case of the calendar app provided, you can find examples such as:
    {
      "text": "提出我4o ' 时钟约会2小时",
      "intent": "ChangeCalendarEntry",
      "entities": [
        {
          "entity": "OriginalStartTime",
          "startPos": 3,
          "endPos": 3
        },
        {
          "entity": "MoveEarlierTimeSpan",
          "startPos": 12,
          "endPos": 14
        }
      ]
    }
After tokenization, The token starting at position 3, is the token “4o” which ends at position 4, therefore the indices [3, 3] indicated by the first label is incorrect, there are a few occurrences of this error in the app.
```

## Expected behavior
The generated LU file imports into LUIS

## Screenshots
![image](https://user-images.githubusercontent.com/33519520/46946562-0abeef80-d070-11e8-8299-8ca1bef972b2.png)

## Additional context

[calendar.zip](https://github.com/Microsoft/botbuilder-tools/files/2478408/calendar.zip)

[bug]

**Comment by SiddharthSunchu** [comment]
Why this error occurs ?
