### ISSUE TITLE
When canceling msbot clone services, there is a .bot file left over (should be deleted?)

### ISSUE THREAD

**Issue by yochay** [Microsoft/botbuilder-tools#666]
## Tool
Name: [Msbot|
Version: *4.0.6-86*
OS: *Win10*

## Describe the bug
ran msbot clone services <> 
and then cancel the operation. Pressed _n_  to cancel the operation. 

There is an 'empty' (see hereunder) bot file

```
{
    "name": "YK-10-15-2018-EntBot1",
    "description": "",
    "services": [],
    "padlock": "",
    "version": "2.0"
}

```

## To Reproduce
1. run msbot clone services
2. see the list of services to create
3. cancel the operation
4. observe the empty bot file

## Expected behavior
Not empty bot file.

## Additional context

[bug]

**Comment by vishwacsena** [comment]
Tracked via #590
