### ISSUE TITLE
Disptacher: An application version with the same version ID (Dispatch.1) already exists

### ISSUE THREAD

**Issue by gabog** [Microsoft/botbuilder-tools#672]
I am using dispatcher to process several LUIS models and it is very unstable, sometimes it works and sometimes it fails with a 400 error (bad request) say that either: 
An application version with the same version ID (Dispatch.1) already exists

or 
An application version with the same version ID (Dispatch) already exists

I then need to go and cleanup the versions, I try again and it sometimes works and sometimes it doesn't.

Is this known issue? What should I do to recover?

Thanks

FYI @darrenj

**Comment by gabog** [comment]
FYI, I looked at the models I am trying to use with the tool and I think the problem is that the generated dispatch model is too big for LUIS and the import fails.
I manually tried to import the generated json into LUIS and I get a similar problem.

The error message changes based on the state of the dispatch versions but I think it is definitely a size problem and I can share the set of models we are trying to use offline so you can improve the tool.
Ideally:
1. If the tool is hitting some LUIS limite, I would like a better error message that tells me what the problem is rather than having to blindly remove and add models to narrow it down.
2. LUIS should probably show better error messages when an import fails (I think dispatch is just showing the error that LUIS returns) so this may need to be looked at by the LUIS team.

Thanks

Gabo

**Comment by tsuwandy** [comment]
This is on the LUIS server side, import returned an error but app is actually created.  I have put in a workaround in Dispatch to handle this.  Will make sure LUIS server side has permanent fix.
