### ISSUE TITLE
Dispatch tool is dropping labeled utteranaces

### ISSUE THREAD

**Issue by gabog** [Microsoft/botbuilder-tools#673]
I am trying to create a dispatch model out of 8 luis models, I have a model with a single intent that has 8 labeled utterance. 
But in the generated model, seven of those eight utterances got dropped and the dispatch intent for the model has only 1 utterance.
I tried some of the dropped utterances against the dispatch model and they get resolved to another model with 0.0x confidence.
Why would the dispatch decide to drop these utterance that have been explicitly labeled in a model and rule to have them handled but a completely different model with such a low score?
Thanks

+ @darrenj FYI

**Comment by darrenj** [comment]
Testing a theory - can you attach the LUIS model that's showing this behaviour? Wondering if it uses patterns

**Comment by gabog** [comment]
Hi, there are no patterns on the model that is getting things dropped from but there is one phrase list and a couple of entities defined. 
There are patterns in some of the other models involved in the process. I can share the set offline if you guys need to take a closer look.
In general, I think the dispatch should do a better job reporting and validating issues, for example:
1. In addition to reporting duplicates, I would like to know if any utterance have been dropped and why so I can address any collisions.
2. It would be good if the generated summary page would show a comp between the number of utterance for each dispatch intent and the number of utterance in the child model so I can see if anything got dropped.
3. It would also be nice if the dispatch could validate that all the labeled utterance in a model map to the proper dispatch intent, in other words, if I explicitly label something in a submodel, this should work on the dispatch model unless it was dropped for being duplicated (and if it did, we would like to know that).
Thanks

Gabo

**Comment by tsuwandy** [comment]
Latest dispatch deployed to npmjs.
