### ISSUE TITLE
Add --ouput json to Azure CLI calls in MSBot

### ISSUE THREAD

**Issue by joseques** [Microsoft/botbuilder-tools#675]
## Tool
Name: [Msbot]

## Describe the problem 
As seen in #671 MSBot when running `az account show` during a `msbot clone services` operation, has trouble parsing the subscription data if the output format of the Azure CLI is set to any other type that isn't `json`, resulting in the error `ERROR: Resource group 'undefined' could not be found.`. This could possibly apply to any other operation involving fetching data from the Azure CLI output.

## To Reproduce
1. Set the default output format as `table` as it's instructed [here](https://docs.microsoft.com/en-us/cli/azure/format-output-azure-cli?view=azure-cli-latest#set-the-default-output-format)
2. Perform an `msbot clone services` operation
3. Error `ERROR: Resource group 'undefined' could not be found.` gets thrown, ending the current cloning operation.

## Expected behavior
The operation should be successful with no interference of the default output format of the Azure CLI

## Proposed solution
The Azure CLI commands should be run with the `--output json` option, in order to avoid problems with the current default output format set in the tool
As seen in the `msbot-clone-services.ts` in [line 257](https://github.com/Microsoft/botbuilder-tools/blob/1845cca8fab44f3054bad3f868791ecd575d002c/packages/MSBot/src/msbot-clone-services.ts#L257) all the commands that are getting executed, should have the `--output json` option resulting in something like
```typescript
command = `az account show --output json `;
```
[enhancement]

**Comment by stevengum** [comment]
Going to close this as a no repro; this I believe has already been fixed, and we're also not receiving additional reports about this problem. If it's still a problem, please @mention me or create a new issue.
