### ISSUE TITLE
Travis build successful with failed publish task

### ISSUE THREAD

**Issue by dfavretto** [Microsoft/botbuilder-tools#678]
## Tool
Name: LuisGen
Platform: Travis - Linux - bash
Build Failing: [# 1575.1](https://travis-ci.org/Microsoft/botbuilder-tools/jobs/440256241#L1061)
 
## Describe the bug
When the CRON job fails in at least one of the tools, the build doesn't fail (which is fine), and neither does it show a message adverting about the failure in the publishing.
 
 
## To Reproduce
1. Go to the Travis Build [# 1575.1](https://travis-ci.org/Microsoft/botbuilder-tools/jobs/440256241#L1061)
2. Read the log where the LUISGen tool fails
 
## Expected behavior
It would be great if the Travis Build had a message warning if any of the tools failed when publishing, although the other tools publish correctly.
 
## Screenshots
![image](https://user-images.githubusercontent.com/23645105/47233028-db79ec80-d3a7-11e8-9525-5476e899688d.png)
 
[bug]

**Comment by sgellock** [comment]
agree we could do something about this, but we won't so closing for now
