### ISSUE TITLE
[Dispatch] Needs more informative error messages

### ISSUE THREAD

**Issue by stevengum97** [Microsoft/botbuilder-tools#68]
@vishwacsena, @justinwilaby 

When attempting to use the dispatch tools to create a new application I received either one or two 404s. The output doesn't make it clear if two requests or only one request failed. Additionally, it's not clear which specific requests failed, so I don't know if something failed when trying to use LUIS or when trying to use QnAMaker.

 ![dispatch_errors](https://user-images.githubusercontent.com/14935595/39011040-3ef228a4-43c5-11e8-9993-d9fd687217b2.PNG)

**Comment by vishwacsena** [comment]
@tsuwandy can you please take a look and close?

**Comment by tsuwandy** [comment]
This is fixed now.
