### ISSUE TITLE
LUISGenTestJS dependencies not installed automatically

### ISSUE THREAD

**Issue by dfavretto** [Microsoft/botbuilder-tools#681]
## Tool
Name: LuisGen
Version: 2.0.0
OS: Windows 10 Pro
 
## Describe the bug
When trying to execute the tests in LUISGen, there's an error due to dependencies not installed inside the test folder.
 
## To Reproduce
1. Run `npm install && npm run build && npm run test` in BotBuilder-Tools folder
2. An error shows up saying `Cannot find type definition file for 'node'`
 
## Expected behavior
After installing dependencies and building the tools, the tests should be run successfully.
 
## Describe the solution you'd like
The command `npm install` should be executed inside the LUISGenTestJS folder. For this, a new script `postinstall` could be added to the `package.json` in LUISGen, which would execute the following command:
`"postinstall": "cd tests/LUISGenTestJS/ && npm install"`
 
## Screenshots
Error when trying to run the tests:
![image](https://user-images.githubusercontent.com/23645105/47233727-ff3e3200-d3a9-11e8-8abf-3d7a4048ccbc.png)

[bug]

**Comment by sgellock** [comment]
we're pushing out new bits that fix this.
