### ISSUE TITLE
msbot clone services fails when appSecret has a "|" (pipe) 

### ISSUE THREAD

**Issue by danielvi1787** [Microsoft/botbuilder-tools#694]
## Information:
* Tools Libraries: msbot clone services
* Libraries' Versions: 4
* OS: Windows

## Issue Description:
When using msbot clone services with --appSecret option and the password has a "|" (pipe) the command fails with message: The syntax of the command is incorrect. 

## Commands Example:
msbot clone services --name "xxx" --luisAuthoringKey "xxx" --folder "C:\Users\xxx\Source\repos\Sanfer-Bot\Sanfer-Bot\DeploymentScripts\msbotClone" --location "westus" --appId "xxx" --appSecret 
"xxx|"

```bash

```
## Workaround:
Generate a new password

**Comment by joseques** [comment]
I'll add to the issue that having `!` in a password using a Linux based CLI, makes the console throw the error `“-bash: !”: event not found`

**Comment by vishwacsena** [comment]
Updated doc via #804 

> **NOTE:** If you are explicitly passing in appSecret as an argument you need to escape any special characters in the password that might be interpreted by the shell to be a command. 
- For *Windows command prompt*, enclose the appSecret in double quotes. e.g. 
msbot clone services --name xxxx --luisAuthoringKey xxxx --location xxxx --folder bot.recipt ***--appSecret "!|%gr%"***
- For *Windows PowerShell, try passing in appSecret after the --% argument. e.g. 
msbot clone services --name xxxx --luisAuthoringKey xxxx --location xxxx --folder bot.recipt ***--% --appSecret "!|%gr%"***
- For *MacOS or Linux*, enclose the appSecret in single quotes. e.g. 
msbot clone services --name xxxx --luisAuthoringKey xxxx --location xxxx --folder bot.recipt ***--appSecret '!|%gr%'***

**Comment by hansmbakker** [comment]
This is not sufficient for some use cases in PowerShell.

Imagine you're writing a script where you want to capture the output (e.g. the generated secret) of msbot. Then you can't pipe the output into something else anymore.

`$output = msbot init [someotherparameters] --quiet --secret --% --appPassword | ConvertFrom-Json` 
does not work

`$outputJson = msbot init [someotherparameters] --quiet --secret --% --appPassword` 
`$output =  $outputJson | ConvertFrom-Json` works a bot

Working with these encoding issues is very unpleasant especially when trying to run these scripts in Azure DevOps.
