### ISSUE TITLE
[MSBot] Error when using Git Bash

### ISSUE THREAD

**Issue by joseques** [Microsoft/botbuilder-tools#700]
## Tool
Name: [Msbot]
Version: *4.0.7-92*
OS: *Windows 10 Pro*
NPM: *6.4.1*
Node: *v10.10.0*
GIT: *2.18.0.windows.1*

## Describe the bug
Using the Git Bash (MinGW), after running some operations like `msbot init` or `msbot clone services` the tool throws the error
```
npm[17156]: src\node_file.cc:1442: Assertion `args[1]->IsInt32()' failed.
1: 00007FF70799DC55
2: 00007FF7079775C6
3: 00007FF707977691
4: 00007FF70793D0E7
5: 00007FF707D5DD22
6: 00007FF707D5F24D
7: 00007FF707D5E2A9
8: 00007FF707D5E18B
9: 0000017D811DC6C1
```
Note that not all parameters are affected. The `help`, `-v` and `secret` parameters seems to be unaffected but an in-depth analysis should be made in order to see how many parameters are affected by this error.

## To Reproduce
1. Open Git Bash in any location
2. Run `msbot init`
3. The following error gets thrown
```
npm[17156]: src\node_file.cc:1442: Assertion `args[1]->IsInt32()' failed.
```

## Expected behavior
After running any `msbot` operation, the process should finish without errors.

[bug]

**Comment by sgellock** [comment]
Probably the same issue as #703

**Comment by Zerryth** [comment]
Using JJ (2.18.0) & I (2.19.1) were able to repro'd in #703, where

> Tried to create a new .bot file using the command 'msbot init', but it hangs forever without giving a clue what is happening

![image](https://user-images.githubusercontent.com/35248895/47590544-649da000-d921-11e8-8f1b-dd674d7713ea.png)

Dana, using a VM, used 2 older versions of git and got the following errors:
_git version 2.15.0.windows.1_
![image](https://user-images.githubusercontent.com/35248895/47591397-4d13e680-d924-11e8-88e6-03ec0b10079e.png)


_git version 2.16.2.windows.1_
![image](https://user-images.githubusercontent.com/35248895/47591436-75034a00-d924-11e8-8a7d-3088834dba05.png)

Note the last one listed is the version @sgellock reported in #703 that worked for him though

**Comment by dmvtech** [comment]
I also tried 2.17.1 on Ubuntu and it was successful
![unix_msbot_git](https://user-images.githubusercontent.com/43397658/47591734-8c8f0280-d925-11e8-92d4-689a5367f4b0.PNG)

**Comment by dmvtech** [comment]
Windows 10 'installed' Git for Windows Bash
====================================
MSBot version: 4.0.7
git version: 2.19.1.windows.1
npm version: 6.4.1
node version: v10.12.0
result: **success**


Windows 10 'installed' Git for Windows CMD
====================================
MSBot version: 4.0.7
git version: 2.19.1.windows.1
npm version: 6.4.1
node version: v10.12.0
result: **success**


Windows 10 - Older version of Git for Windows Bash
====================================
MSBot version: 4.0.7
git version 2.16.2.windows.1
npm version: 6.4.1
node version: v10.12.0
result: **error**

Windows 10 Old version of Git for Windows CMD
====================================
MSBot version: 4.0.7
git version 2.16.2.windows.1
npm version: 6.4.1
node version: v10.12.0
result: **success**


VS PowerShell window
====================================
Running command: node msbot-init.js
git version: 2.19.1.windows.1
npm version: 6.4.1
node version: v10.12.0
result: **error**


PowerShell window
====================================
Running command: node msbot-init.js
git version: 2.19.1.windows.1
npm version: 6.4.1
node version: v10.12.0
result: no **error**

**Comment by mplwork** [comment]
FYI this also doesn't work in a cygwin shell. Powershell tries to get the answers from a console but cygwin only has ptys. I guess the same is true for gitbash.

**Comment by sgellock** [comment]
The above coverage of OS's and shells is sufficient for our usage scenarios.
