### ISSUE TITLE
Cannot show transcript by Bot Framework Emulator(V4 PREVIEW)

### ISSUE THREAD

**Issue by ShawnXiao105** [Microsoft/botbuilder-tools#702]
## Tool
Name: [Chatdown]
Version: *1.0.11*
OS: *win10 pro*

## Describe the bug
I follow the tutorial to generate scripts by chatdown, but I cannot open it in Bot Framework Emulator

## To Reproduce
1. CD to examples folder
2. `chatdown  WhoAreYou.chat>WhoAreYou.transcript`
3. double click to open it by Bot Framework Emulator (V4 PREVIEW)

## Expected behavior
The Chat Dialog will display

## Screenshots
The Emulator Notification pop up error say `Error creating a new conversation in transcript mode: Error: Error while feeding deep-linked transcript to conversation: Cannot read property 'role' of undefined`

## Additional context
Chat file is download from repo and I also reference [this tutorial](https://www.youtube.com/watch?v=hitgZwRphdM)

```
user=vishwac
bot=cafebot

user: Who are you?
bot: Hi, I'm the Contoso Cafe bot. What's your name?
user: I'm vishwac
bot: [Typing][Delay=3000]
Hello Vishwac. Nice to meet you!
```

transcript is as follows:
```json
[
  {
    "conversation": {
      "id": "qdlEmACpCdrL5CAM8blTtzOwC4Y="
    },
    "id": "1",
    "timestamp": "2018-10-24T12:32:51.100Z",
    "type": "conversationUpdate",
    "channelId": "chatdown",
    "membersAdded": [
      {
        "id": "jopVZjYqyE3A5EnA8dYrlA+Mubw=",
        "name": "cafebot",
        "role": "bot"
      }
    ],
    "membersRemoved": []
  },
  {
    "conversation": {
      "id": "qdlEmACpCdrL5CAM8blTtzOwC4Y="
    },
    "id": "2",
    "recipient": {
      "id": "jopVZjYqyE3A5EnA8dYrlA+Mubw=",
      "name": "cafebot",
      "role": "bot"
    },
    "from": {
      "id": "aqMkJoc/DqiL+cgiJhoUJCxSZ+U=",
      "name": "vishwac",
      "role": "user"
    },
    "text": "Who are you?",
    "timestamp": "2018-10-24T12:32:53.100Z",
    "type": "message",
    "channelId": "chatdown"
  },
  {
    "conversation": {
      "id": "qdlEmACpCdrL5CAM8blTtzOwC4Y="
    },
    "id": "3",
    "recipient": {
      "id": "aqMkJoc/DqiL+cgiJhoUJCxSZ+U=",
      "name": "vishwac",
      "role": "user"
    },
    "from": {
      "id": "jopVZjYqyE3A5EnA8dYrlA+Mubw=",
      "name": "cafebot",
      "role": "bot"
    },
    "text": "Hi, I'm the Contoso Cafe bot. What's your name?",
    "timestamp": "2018-10-24T12:32:55.100Z",
    "type": "message",
    "channelId": "chatdown"
  },
  {
    "conversation": {
      "id": "qdlEmACpCdrL5CAM8blTtzOwC4Y="
    },
    "id": "4",
    "recipient": {
      "id": "jopVZjYqyE3A5EnA8dYrlA+Mubw=",
      "name": "cafebot",
      "role": "bot"
    },
    "from": {
      "id": "aqMkJoc/DqiL+cgiJhoUJCxSZ+U=",
      "name": "vishwac",
      "role": "user"
    },
    "text": "I'm vishwac",
    "timestamp": "2018-10-24T12:32:57.100Z",
    "type": "message",
    "channelId": "chatdown"
  },
  {
    "conversation": {
      "id": "qdlEmACpCdrL5CAM8blTtzOwC4Y="
    },
    "id": "6",
    "recipient": {
      "id": "aqMkJoc/DqiL+cgiJhoUJCxSZ+U=",
      "name": "vishwac",
      "role": "user"
    },
    "from": {
      "id": "jopVZjYqyE3A5EnA8dYrlA+Mubw=",
      "name": "cafebot",
      "role": "bot"
    },
    "timestamp": "2018-10-24T12:32:57.200Z",
    "type": "typing",
    "channelId": "chatdown"
  },
  {
    "conversation": {
      "id": "qdlEmACpCdrL5CAM8blTtzOwC4Y="
    },
    "id": "5",
    "recipient": {
      "id": "aqMkJoc/DqiL+cgiJhoUJCxSZ+U=",
      "name": "vishwac",
      "role": "user"
    },
    "from": {
      "id": "jopVZjYqyE3A5EnA8dYrlA+Mubw=",
      "name": "cafebot",
      "role": "bot"
    },
    "text": "Hello Vishwac. Nice to meet you!",
    "timestamp": "2018-10-24T12:33:00.200Z",
    "type": "message",
    "channelId": "chatdown"
  }
]
```

[bug]

(Edited by @compulim for code formatting)

**Comment by ShawnXiao105** [comment]
@tonyanziano Thanks you very much! I DO NOT solve it through the method posted [here](https://github.com/Microsoft/BotFramework-Emulator/issues/931)

**Comment by mburleigh** [comment]
I ran into the same thing this morning. As a workaround I'm just pasting in those values from an old transcript and fixing the values appropriately.

**Comment by justinwilaby** [comment]
The Emulator support chat files natively. Converting them beforehand using the chatdown cli is not necessary if all you plan to do with them is replay them in the Emulator.

**Comment by mburleigh** [comment]
@justinwilaby I see that it should but the emulator will not let me assign folders in the resource pane (I've tried several different versions including the latest nightly 4.0.42335) so transcripts are my only option. When I get some time I will see if it's a known issue in the emulator.

**Comment by danuw** [comment]
Everything seems to point at the fact that 1.0.11 has an issue so I downgraded to 1.0.10 until I have a reason to upgrade if that is useful to anyone 
```
npm i -g chatdown@1.0.10
```

**Comment by vishwacsena** [comment]
@danuw - yes. that's the appropriate temporary workaround while we can address this E2E.

**Comment by compulim** [comment]
@corinagum I am unassigning myself. If I am right, we have fixed it in Web Chat and waiting for a bump. Please correct me if I am wrong. Thanks!
