### ISSUE TITLE
msbot init doesn't work

### ISSUE THREAD

**Issue by samirshaik** [Microsoft/botbuilder-tools#703]
## Tool
Name: Msbot
Version: 4.0.7
OS: Windows 10 Professional

## Describe the bug
Tried to create a new .bot file using the command 'msbot init', but it hangs forever without giving a clue what is happening

## To Reproduce
1. clone https://github.com/Microsoft/BotBuilder-Samples.git
2. cd BotBuilder-Samples\samples\javascript_nodejs\12.nlp-with-luis
3. msbot init

## Expected behavior
Expectation is the cli tool should ask for the name and endpoint.

## Screenshots
NA

## Additional context
NA

[bug]

**Comment by joseques** [comment]
This could be potentially related to #700

**Comment by samirshaik** [comment]
You are right joseques. Behavior described above is very specific to gitbash. Tried with command prompt and the msbot cli worked as expected.

**Comment by sgellock** [comment]
support, can we get a consistent repo as we have some on the team who are able to run msbot init from git bash.  maybe git bash version issue?

**Comment by sgellock** [comment]
going to track this issue with #700
