### ISSUE TITLE
bot created with v4 sdk vsix fails with internal server error when published to azure  - Need better endpoints

### ISSUE THREAD

**Issue by swagatmishra2007** [Microsoft/botbuilder-tools#706]
## Tool
Name: v4 vsix

## Describe the bug
If i create a local bot from v4 vsix , and then publish to an appservice, i get an internal server error on start up. This is because, the .bot file does not contain a "production" endpoint.
Please update the vsix to have a more clear indication to the user that the endpoint is missing , instead of an internal server error. This is because, it's hard to debug startup errors in dot net core without additional configuration.
## To Reproduce
Here are the repro steps:
1. Create a C# Echo Bot using the VSIX (V4) template in VS2017.
2. In Solution Explorer in VS, right-click the project, and select Publish
3. On the Pick a publish target page, select App Service, and then select Create New.
4. Click the Create Profile button at the bottom of the screen.
5. Enter App Name, Subscription, Resource Group, Hosting Plan etc.
6. Click the Create button.

At this point, the deployment process will begin. When the deployment completes, the error message appears in the web browser. 

## Expected behavior
I should get a clear error saying that the production endpoint is missing instead of a 500 server error.

## Additional context

[bug]

**Comment by cleemullins** [comment]
I'll iterate on the VSIX just after the 4.1 packages go live and do the following:

1. Update the package references to 4.1.
2. Provide a better error message. Note that @daveta believes this code is already done and just needs to be packaged and deployed. 

Until then, leaving the VSIX "as-is".

**Comment by sgellock** [comment]
also tracked with #753

**Comment by sgellock** [comment]
dup, using #753 to track the Issue
