### ISSUE TITLE
Dispatch create fails with BadFileName if LUIS files don't have .json extension

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#708]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Version: 1.1.5-53
OS: Windows

## Describe the bug

When creating a dispatch file using the CLI, I add a number of LUIS models that have a .luis extension
```
{
  "authoringRegion": "westus",
  "hierarchical": true,
  "services": [
    {
      "path": "C:\\Users\\darrenj\\source\\repos\\ai\\solutions\\Virtual-Assistant\\src\\csharp\\assistant\\DeploymentScripts\\zh-hans\\general.luis",
      "type": "file",
      "name": "General",
      "id": "1"
    },
```

When executing `dispatch create` I get this error:

```
ERROR
BadFileName
Bad file name: C:\Users\darrenj\source\repos\ai\solutions\Virtual-Assistant\src\csharp\assistant\DeploymentScripts\zh-hans\general.luis
```

Trial and error revealed that renaming my files to a .json extension enabled dispatch to find the files.

## To Reproduce
1. ... See above dispatch file excerpt
2. ... Run dispatch create

## Expected behaviour

We should accept whatever extension the user provides (.luis makes more sense for clarity than JSON). If we are really opinionated on filename we should provide that guidance. Right now we have agreed .json as per the sample spec.

[bug]

**Comment by tsuwandy** [comment]
This has been fixed and will be deployed to npmjs today or tomorrow at the latest.

**Comment by tsuwandy** [comment]
Forgot to add that file extension will no longer matter, it could be .json or .luis or .qna (or anything really).  We'll just try to deserialize it to the right type.  Thanks!
