### ISSUE TITLE
[Dispatch/All Tools] Passing in Arguments should be the same across tools

### ISSUE THREAD

**Issue by stevengum97** [Microsoft/botbuilder-tools#71]
Per the [README.md](https://github.com/Microsoft/botbuilder-tools/blob/34216cf1b73cceb0644ad1701845a4e83f08ca55/Dispatch/readme.md#creating-a-dispatchrc) in **Dispatch/** users are expected to pass in arguments using one `"-"`, e.g.:

```bash
dispatch init -name SomeName
```

However in **LUIS/** the [README](https://github.com/Microsoft/botbuilder-tools/tree/34216cf1b73cceb0644ad1701845a4e83f08ca55/LUIS#cli-usage) specifies that users use `"--"` when passing in configuration arguments and overrides:

```bash
luis list applications --authoringKey luisAuthoringKey
```

This formatting extends to QnAMaker, and other tools, except some tools like **MSBot/** also include [shortcuts (`"-"`)](https://github.com/Microsoft/botbuilder-tools/tree/34216cf1b73cceb0644ad1701845a4e83f08ca55/MSBot#connecting-to-a-localhost-service) like so:

```bash
msbot connect localhost -a appId -p appPassword -e endpointUrl
```

is the same as

```bash
msbot connect localhost --appId appId -appPassword appPassword --endpoint endpointUrl
```

This formatting should be the same so users don't need to remember multiple ways to pass in cli arguments.

**Comment by vishwacsena** [comment]
@tsuwandy - low pri for //BUILD. The standard we should stick to (which is also similar to AZ CLI) is offer both shorthand (-p) as well as extended (--path) across all our CLI tools. At the moment, Chatdown, LUDown, MSBot offer this while luis, QnAMaker and dispatch do not.
