### ISSUE TITLE
Ludown does not de-dupe patterns

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#710]
## Tool
Name: Ludown
Version: 1.0.36
OS: Windows 10

## Describe the bug
Duplicate patterns in .lu files are not de-duped by ludown

## To Reproduce
1. Create a .lu file with duplicate patterns
2. Run ludown parse

## Expected behavior
Ludown automatically de-dupes patterns

[bug]

**Comment by darrenj** [comment]
Ran into this today :)
