### ISSUE TITLE
qnamaker ignores proxy settings

### ISSUE THREAD

**Issue by mplwork** [Microsoft/botbuilder-tools#712]
## Tool
Name: QnAMaker
Version: 1.0.33
OS: Windows 10

## Describe the bug
qnamaker doesn't use any of the node/npm proxy settings:

```
NODE_TLS_REJECT_UNAUTHORIZED=0
HTTP_PROXY=http://localhost:8888
HTTPS_PROXY=http://localhost:8888
 pc> qnamaker create kb --in cognitiveModels/dispatch.qna --subscriptionKey aXXXXXXX95 --msbot

FetchError: request to https://westus.api.cognitive.microsoft.com/qnamaker/v4.0/knowledgebases/createasync failed, reason: connect ECONNREFUSED 40.112.254.71:443
```
```
 pc> npm config list
; cli configs
metrics-registry = "http://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.4.1 node/v8.12.0 win32 x64"

; userconfig C:\Users\mplwork\.npmrc
https-proxy = "http://localhost:8888/"
proxy = "http://localhost:8888/"
registry = "http://registry.npmjs.org/"
strict-ssl = false
```
Any valid ECONNREFUSED would list 127.0.0.1:8888 as the address.

## To Reproduce
See above, set the environment variables and run the qnamaker command.

## Expected behavior
It should connect using the proxy.

## Additional context
Settings in `.npmrc` aren't used either.

[bug]

**Comment by dmvtech** [comment]
I noticed your SSL proxy was not https. If you change that, does it work?

https-proxy = "http://localhost:8888/"

To:

https-proxy = "https://localhost:8888/"

**Comment by stevengum** [comment]
I set the environment variables:
```bash
NODE_TLS_REJECT_UNAUTHORIZED=0
HTTP_PROXY=http://localhost:8888
HTTPS_PROXY=http://localhost:8888
```
And used the following command in the Node.js dispatch sample:
```bash
qnamaker create kb --in cognitiveModels/dispatch.qna --subscriptionKey aXXXXXXX95 --msbot
```

Which succeeded with no problems...

I couldn't get a repro; @Zerryth, @stevkan or @nyxsys can any of you get a repro on this?

**Comment by CoHealer** [comment]
@dmvtech set his https-proxy config to "**https**://localhost:8888/". @stevengum, it looks like you didn't:

`HTTPS_PROXY=http://localhost:8888`

Does this repro with that configuration set to https?

**Comment by dmvtech** [comment]
I've ran a few more tests, just to make sure I had all my own ducks in a row.

I configured:
NODE_TLS_REJECT_UNAUTHORIZED=0
HTTP_PROXY=http://localhost:8888
HTTPS_PROXY=http://localhost:8888

Tested, no Fiddler running. Success.
Tested, with Fiddler running/capturing (port 8888). Success. But do not see traffic in Fiddler.

Changed configuration:
NODE_TLS_REJECT_UNAUTHORIZED=0
HTTP_PROXY=http://localhost:8888
HTTPS_PROXY=http**s**://localhost:8888

Tested, no Fiddler running. Success.
Tested, with Fiddler running/capturing (port 8888). Success. But do not see traffic in Fiddler.

**Comment by stevkan** [comment]
@dmvtech, I noticed your using Node v8.12.0. I just tried to repro and it succeeded in creating the kb with no errors. I am using Node v10.3.0. Could you update and try again?

**Comment by mplwork** [comment]
I'd want to maybe clarify my report a little. If you don't see traffic in Fiddler then Fiddler isn't used and if you don't have a corporate proxy to block Internet access `qnamaker` will always succeed. So not seeing traffic in Fiddler proves my point.

**Comment by tomlm** [comment]
https://github.com/Azure/ms-rest-js/issues/169

**Comment by justinwilaby** [comment]
Careful here! QnAMaker does not use auto-rest and implementing Node specific proxy settings will break the library used on Web clients. 

The approach here should take into account that both web and node compatibility should be preserved.
