### ISSUE TITLE
Powershell not able to connect authentication connection to Bot FIle using msbot

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#713]
## Tool
Name: Msbot
OS: Windows

## Describe the bug

Developers cannot use `msbot connect generic` to set Authentication properties when using PowerShell.

We provided this command which works fine in CMD
```shell
msbot connect generic --name "Authentication" --keys "{\"Azure Active Directory v2\":\"YOUR_AUTH_CONNECTION_NAME\"}" --bot YOURBOTFILE.bot --secret "YOUR_BOT_SECRET" --url "portal.azure.net"
```

First issue is around quotes, adding single quotes around the JSON helps

```shell
msbot connect generic --name "Authentication" --keys '{\"Azure Active Directory v2\":\"YOUR_AUTH_CONNECTION_NAME\"}' --bot YOURBOTFILE.bot --secret "YOUR_BOT_SECRET" --url "portal.azure.net"
```

But then you get a `SyntaxError: Unexpected end of JSON input`

After trial and error it's the spaces in the key (Azure Active Directory v2) causing the issue. Tried a few things but not able to workaround. See [AI Repo Bug](https://github.com/Microsoft/AI/issues/191)

## To Reproduce

```shell
msbot connect generic --name "Authentication" --keys '{\"Azure Active Directory v2\":\"YOUR_AUTH_CONNECTION_NAME\"}' --bot YOURBOTFILE.bot --secret "YOUR_BOT_SECRET" --url "portal.azure.net"
```

## Expected behavior
A command line example that works in PowerShell (and ideally CMD)

[bug]

**Comment by dmvtech** [comment]
Hi Darren,

I have found that the workaround needs some tweaking. It apparently needs to have some some linefeeds/carriage returns to the string. The easiest way in script is to convert it to a PSCustomObject and back to a string. That does work. Additionally, the escape character \ is not needed. Here's what I tried:

```
$keysstring = '{"Azure Active Directory v2":"YOUR_AUTH_CONNECTION_NAME"}'
$keysobject = ConvertFrom-Json $keysstring
$keys = ConvertTo-Json -InputObject $keysobject
```

At this point $keys will output:

```
{
    "Azure Active Directory v2":  "YOUR_AUTH_CONNECTION_NAME"
}
```

Then you can run:
`msbot connect generic --name "Authentication" --keys $keys --bot BotConfiguration.bot --secret "YOUR_BOT_SECRET" --url "portal.azure.net"`

Alternatively, you can construct the $keys variable string on multiple lines beforehand (not good for scripting of course)

```
$keys = '{
>> "Azure Active Directory v2":"YOUR_AUTH_CONNECTION_NAME"
>> }'
```

**Comment by dmvtech** [comment]
The above workaround should be your solution. Unfortunately there are no more elegant ways of doing this at this time. I am closing the issue since this should unblock you. Feel free to reopen if this does not quite solve your scenario.
