### ISSUE TITLE
[MSBOT] --key parameter is ignored for CosmosDb

### ISSUE THREAD

**Issue by digitaldias** [Microsoft/botbuilder-tools#715]
## Tool
Name: Msbot
Version: 4.0.7
OS: Microsoft Windows [Version 10.0.17134.345]

## Describe the bug
Using MSBot to connect to CosmosDB, does not recognize -k or --key parameter. 

## To Reproduce
1. Create a CosmosDB in the Azure Portal
2. Ensure you have an existing .Bot file to add CosmosDB Config to
3. Start by adding MSBot connect cosmosdb -n "MyCosmosDB", then fill out each requested field until you get to the "--key" parameter
4. Observe how MSBot does not accept any kind of value for -k or --key. Tried without quotes around the key, with single quotes around the key, and double quotes around the key, both -k and --key

## Expected behavior
Expected MSBot to accept my key and create a configuration in the .bot file

## Screenshots
![msbot cosmosdb bug](https://user-images.githubusercontent.com/929421/47598553-c52ceb80-d9ba-11e8-8d97-18b976dc7f38.png)

## Additional context

[bug]

**Comment by carlosscastro** [comment]
@digitaldias I just tried this with the latest sources and works for me with a real cosmos db key. Did your key include any special characters that needed to be escaped?

**Comment by carlosscastro** [comment]
Closing this as I could not repro. @digitaldias Feel free to asnwer my question above and reopen if you want to keep discussing. I gave this a try and worked without issues for me.
