### ISSUE TITLE
Cannot view MSA app password for a bot created through az cli

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#721]
## Tool
Name: AZ BOT
Version: AZ CLI: 2.0.46, botservice: 0.4.1
OS: Windows 10

## Describe the bug
Cannot view MSA app when I click on 'manage' in Ibiza bot settings page for a bot created using az bot create

## To Reproduce
1. Install the latest AZ CLI and bot extension
2. create a v4, nodejs bot - e.g. az bot create -k webapp -n cafebottest -g testCafeBot --lang Node --version v4
3. Go to Ibiza portal and open the bot that was created
4. Go to settings -> click on manage to bring up the MSA app settings -> error that says this application ID does not exist

![image](https://user-images.githubusercontent.com/20918136/47622166-fd1d5700-dabe-11e8-961d-55469af2253b.png)

## Expected behavior
Should be able to view the MSA application created by az bot create

[bug]

**Comment by carlosscastro** [comment]
@vishwacsena We just tried this and got no repro. There was a recent server side issue for which a fix was deployed to production. Could you please verify again?

Closing, but feel free to reopen if you still see the error.

**Comment by carlosscastro** [comment]
This is fixed in the next release 0.4.2 of the extension and / or spring 50 of the CLI
