### ISSUE TITLE
No bot file created for v4 node bot - az bot create

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#722]
## Tool
Name: az bot create
Version: Az cli 2.0.46, botservice: 0.4.1
OS: Wind10

## Describe the bug
Created a new v4 bot using az bot create. The new bot created does not run and does not include a .bot file (confirmed through online code editor as well as via az bot download).

## To Reproduce
1. Install the latest az CLI and botservice extension
2. az login
3. az bot create -k webapp -n cafebottest -g testCafeBot --lang Node --version v4
4. Try and talk to the bot in webchat - fails

## Expected behavior
Created bot should work. Upon investigation, I see that there is no .bot file created. Unclear if this is the only issue why the bot does not work. 

![image](https://user-images.githubusercontent.com/20918136/47622243-08bd4d80-dac0-11e8-8799-55909d929143.png)

[bug]

**Comment by carlosscastro** [comment]
Fixed with server side change on intercom.
