### ISSUE TITLE
[DCR] - make --lang flag mandatory and not optional with C# as default

### ISSUE THREAD

**Issue by yochay** [Microsoft/botbuilder-tools#723]
## Tool
Name: [AZ bot create]
Version: Az cli 2.0.46
Win10

## Describe the problem
Az bot create defaults to Csharp (V4?). When creating a new bot it deploys C# webapp, which is a when deploying node.js code. 

az bot create --verbose --resource-group YKtestRG --name testAZcliCreatebot --kind webapp

## Describe the solution you'd like
Make --lang flag as mandatory and not optional 'forcing' developers to set it. 

[enhancement]

**Comment by yochay** [comment]
Only for Web App bots

**Comment by ryanvolum** [comment]
FYI: this DCR should hopefully fix the downstream doc issue here: https://github.com/MicrosoftDocs/bot-docs/issues/466

**Comment by carlosscastro** [comment]
Without breaking changes, we can only improve docs and help. The docs MicrosoftDocs/bot-docs#466 should help limit the confusion for now.
