### ISSUE TITLE
msbot clone services should check for bot name collision ahead of deployment

### ISSUE THREAD

**Issue by darrenj** [Microsoft/botbuilder-tools#727]
## Tool
Name: MsBot
OS: Windows

## Describe the bug

The msbot CLI doesn't check to see if the provided Name for a bot already exists before attempting deployment. When it hits the error it reports the following confusing message, not clearly saying that the name already existed:

```
WARNING: obtained msa app id and password. Provisioning bot now.
ERROR: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.
```

Running `az group deployment operation list --name MyBot -g MyBot --query "[*].properties.statusMessage"` returns this additional information:

```
  {
    "error": {
      "code": "InvalidBotData",
      "message": "Version: Bot Version has an invalid value. "
    }
```
We are seeing numerous developers running into issues where the provided names are not unique enough for the Bot Name. [e.g](https://github.com/MicrosoftDocs/bot-docs/issues/298#issuecomment-433796079). Resources created for the Bot are randomised so don't run into the issue.  

## To Reproduce

Run:
```shell
msbot clone services --name "MyBot" --luisAuthoringKey MY_KEY --folder "DeploymentScripts\en\msbotClone" --location westus
```
## Expected behavior
We should warn that a name isn't unique as part of validation steps. Guide the user on how to resolve.

[bug]

**Comment by sgellock** [comment]
Since we are deprecating msbot as a provisioning and deployment option, replaced with ARM template support, I'm going to resolve this issue as "won't fix"
