### ISSUE TITLE
Chatdown for all the supported channels

### ISSUE THREAD

**Issue by arafattehsin** [Microsoft/botbuilder-tools#732]
## Tool
Chatdown

It has been a great tool for prototyping but it lacks a cool (attractive) graphical look and feel to the clients. Not every client is in favor of WebChat control which is currently somewhat similar to our SDK 4 Emulator. 

## Suggestion
Within the emulator, we should be able to switch to different channels (like Channel Inspector) and the respective UI for that channel will be displayed.

**Comment by vishwacsena** [comment]
Tracked via Microsoft/botframework-emulator#599
