### ISSUE TITLE
Chatdown Designer

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/botbuilder-tools#733]
## Tool
Chatdown

Currently, we have to write down all the chatdown scripts manually. 

## Suggestion
I think it would enhance the tool if we can have ChatDown Designer similar to what we have in AdaptiveCards now.

**Comment by sgellock** [comment]
We are working on design tooling that will aid in visually designing conversations and bots.  There will be some functionality in that tool that will start to address this feature request.
