### ISSUE TITLE
[MSBOT] Dependent on latest AZ CLI. 

### ISSUE THREAD

**Issue by Joll59** [Microsoft/botbuilder-tools#738]
## Tool
Name: [Msbot]
Version: 4.0.7
OS: Win 10

## Describe the bug
Msbot is dependant on the latest version of Azure CLI (AZ CLI), no mention in the documentation of this requirement, it is the cause of multiple errors/issues. 

## Solution:
Document & Msbot checks and throws an error.

## To Reproduce
1. Have an outdated azure CLI, ( azure classic CLI)
2. run `msbot clone services --name "AwesomeBotName" --luisAuthoringKey "YOUR_AUTHORING_KEY" --folder "DeploymentScripts\msbotClone" --location "westus" `
3.  msbot produces 
```
[msbot] Checking az botservice version
[msbot] [msbot] You need to upgrade your az botservice version to >= 0.4.0.
To do this run:
az extension remove -n botservice
az extension add -n botservice
```
## Expected behavior
1. Msbot throws an Error about utilizing an outdated az cli. (az classic cli)
2. Msbot directs user to acquire latest CLI and provides direct Link to CLI download
3. after completing the above. 
4. Running the nicely provided commands should then fix the issue. 

### Actual behavior.
Nothing changes, the error persists and there is no way to address it via Msbot. 

## Screenshots
Screenshots from closed issue here: #511 

[documentation needed]
[feature request]
[bug]

**Comment by Kaiqb** [comment]
@carlosscastro - I've updated the readme, but the bug has additional items that need to be addressed. Assigning it to you per Scott.

**Comment by carlosscastro** [comment]
Perfect @Kaiqb @sgellock I'll put a fix for this before EOW :)

**Comment by sgellock** [comment]
@carlosscastro if we have a fix that needs to go into master, are we tracking that work with a different Issue?  I guess I'm just trying to understand why we closed this ticket if there is remaining work

**Comment by Joll59** [comment]
Hey @carlosscastro, Is there an open issue that addresses the other aspect of this issue ? 
Or was it closed by this PR Azure/azure-cli#7924 ?

**Comment by ryanvolum** [comment]
@carlosscastro, @sgellock It's still unclear whether or not this bug has been fixed/if there's another issue that illustrates it. Should this bug be reopened?

**Comment by carlosscastro** [comment]
@ryanvolum apologizes for missing this one! I added some documentation in msbot, however now we have a much better az version check, including the core cli check and extension version check. The changes for this are in msbot, they just got merged by @vishwacsena in his recent [PR](https://github.com/Microsoft/botbuilder-tools/pull/808) so they will be part of the 4.2 msbot release.

**Comment by AllanXu49** [comment]
@carlosscastro I've just installed version 4.3.1 with the default npm command: 

```
npm install -g ludown luis-apis qnamaker botdispatch msbot chatdown

msbot -v
4.3.1
```

Also I have the latest version of az CLI:

```
az --version

azure-cli (2.0.54)

acr (2.1.11)
acs (2.3.13)
advisor (2.0.0)
ams (0.3.1)
appservice (0.2.10)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.5)
billing (0.2.0)
botservice (0.1.3)   <==========
```



However the problem still persissts

```
>msbot clone services --name "EnterpriseBot1" --luisAuthoringKey "XXXYYYZZZ" --folder "DeploymentScripts\en" --location "westus"
Checking az botservice version
You need to upgrade your az botservice version to >= 0.4.3.
To do this run:
   az extension remove -n botservice
   az extension add -n botservice

```


You should be able to easily reproduce this.

**Comment by sgellock** [comment]
We are testing a fix for this.  Hope to get it published today

**Comment by sgellock** [comment]
Msbot.  Working on getting 4.3.2 out

**Comment by chasemwilliams** [comment]
@sgellock Any update on 4.3.2? I having the same issue as Allan

**Comment by armstrong-charles** [comment]
@vasavenk, Is nightly build fix the problem?

**Comment by armstrong-charles** [comment]
Yes, nightly build fix the problem, thanks
