### ISSUE TITLE
Error when using dispatch refresh

### ISSUE THREAD

**Issue by fbeauchemin** [Microsoft/botbuilder-tools#739]
## Tool
Name: [Dispatch]
Version: *1.1.6*
OS: *Windows 10 Pro*

## Describe the bug
When trying to refresh my dispatch, I get the following:

```bash
Exporting services for dispatch...
Exporting ... LUIS application...
Exporting ... LUIS application...
Exporting ... QnA kb...
Creating dispatch LUIS model json...
Creating training data...
Updating ... model...
Importing ... model...

ERROR
Failed importing ... app
```
Note: Actual services / app name were replaced by `...`

## To Reproduce
1. dispatch refresh -b .\my.bot --dataFolder .\.tmp

## Expected behavior
My dispatch LUIS app is refreshed correctly.

## Additional context
Is there any to output more details of the error? There seem to be no log file ...

*EDITED*: When I use version 1.0.7, everything works perfectly. I guess something is wrong with the handling of the `.bot` file.

[bug]

**Comment by tsuwandy** [comment]
@fbeauchemin, would you mind sharing your .bot/.dispatch file to tiens@microsoft.com so I could try to repro?  i'm guessing the child LUIS app(s) make use of patterns and there's something there causing issues.  thank you!

**Comment by tsuwandy** [comment]
Dispatch 1.1.8 is published with this fix.  Please let me know if you are still seeing the import error.  Thanks!
