### ISSUE TITLE
Luisgen ERR! Exit status 2147516561- luisgen@2.0.2 install: `dotnet tool install -g LUISGen`

### ISSUE THREAD

**Issue by dawwa** [Microsoft/botbuilder-tools#746]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Version: 2.0.2
OS: Windows 10
NPM: 6.4.1

## To Reproduce
1. prepare a package.json and include luisgen
2. run npm install
3. remove luisgen from the package.json
4. run npm install luisgen -g

## Expected behavior
properly install luisgen at step 2.

## Actual behavior
step4 can proceed successfully 
step2 failed with the error shown in the screenshot.
The log has the following details.
`91 verbose stack Error: luisgen@2.0.2 install: `dotnet tool install -g LUISGen`
91 verbose stack Exit status 2147516561
91 verbose stack     at EventEmitter.<anonymous> (C:\Users\dawwa\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
91 verbose stack     at EventEmitter.emit (events.js:182:13)
91 verbose stack     at ChildProcess.<anonymous> (C:\Users\dawwa\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
91 verbose stack     at ChildProcess.emit (events.js:182:13)
91 verbose stack     at maybeClose (internal/child_process.js:962:16)
91 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
92 verbose pkgid luisgen@2.0.2`

## Screenshots
![image](https://user-images.githubusercontent.com/44714043/48179747-7db93000-e2d5-11e8-8b0f-94f8244c1d53.png)

## Additional context

[bug]

**Comment by justinwilaby** [comment]
related to #643

**Comment by dawwa** [comment]
Hi, @ahmedlhanafy , is there any workaround for this? this is breaking our CI/CD pipeline.

**Comment by ahmedlhanafy** [comment]
I'm working on this today. Hopefully, I have a fix or a work around later today.

**Comment by ahmedlhanafy** [comment]
@dawwa I couldn't replicate your issue on a fresh Windows and Ubuntu installations with Node version 6.4.0. Have you tried installing [.NET Core](https://www.microsoft.com/net/download), run `npm install -g luisgen@2.0.2`, restart the computer (or logout from the current session) and run $ `luisgen` again.

There is a quirk in the installation process; if the tool is already installed on your computer and you try to install it again it fails. But I think that's not the issue you're facing.

**Comment by dawwa** [comment]
@ahmedlhanafy , isn't the .NET Core installed already with vs 2017?

**Comment by ahmedlhanafy** [comment]
> isn't the .NET Core installed already with vs 2017?

Not quite sure if it comes by default or you have to pick an option to install it. 

> I first tried the session install by just put luisgen 2.0.2 in package.json file, and do nmp install,

LUISGen is a CLI tool and it should be installed globally not from a `package.json` file.

**Comment by ahmedlhanafy** [comment]
@dawwa Can you confirm that your issue is resolved? And if so, please, close the issue.

**Comment by tomlm** [comment]
The NPM package is a simple script for running **dotnet tools install -g LUISGen** 
You can do a local install of LUIS tools by using **dotnet tool install  LUISGen --tool-path tools**

This should unblock you.
