### ISSUE TITLE
VSIX bots created with space in assembly name fail to deploy

### ISSUE THREAD

**Issue by sgellock** [Microsoft/botbuilder-tools#754]
## Tool
Name: VSIX
Version: 4.0.6.6
OS: Windows

## Describe the bug
Deployed bot created via File -> New project -> VSIX template fails to run when published to AppService due to space in assembly name

## Additional context
If a developer simply creates a new bot using File -> New Project and selects the VSIX templates and does not change the name of the project it will ultimately fail to run when deployed to Azure App AppService.

[bug]

**Comment by cleemullins** [comment]
We've improved this (somewhat) with the latest VSIX. Those no longer default to having a space in the name. A richer set of validations is coming in the 4.3 time frame. 

Closing this out as a Dupe, as the master bug is here:
https://github.com/Microsoft/BotBuilder-Samples/issues/955
