### ISSUE TITLE
msbot clone does not provide a way to deploy code

### ISSUE THREAD

**Issue by sgellock** [Microsoft/botbuilder-tools#755]
## Tool
Name: Msbot
Version: all versions
OS: all supported OS's

## Describe the bug
Using the msbot tools or the Azure CLI, nothing is actually deployed. Resources are "cloned", but code is not pushed.

## Additional context
If developers manage to make their way through scattered deployment documentation, they will then discover that the deployment process is actually not working. Using the msbot tools or the Azure CLI, nothing is actually deployed. Resources are "cloned", but code is not pushed. Instead a C# echobot is configured (even when deploying a Node project).

[bug]

**Comment by vishwacsena** [comment]
Any work in msbot clone is this is dependent on #756 which covers the work on az cli side. 

Moving this to 4.3. For 4.2, we will fix #799 which should document the commands the user needs to run to push code up. 

@carlosscastro; @sgellock FYI

**Comment by stevengum** [comment]
Adding Tom to this as well; @tomlm it sounds like most of the work here was fixed via #816, can we close this?

**Comment by vishwacsena** [comment]
This is fixed in 4.2 via #816 and related work.
