### ISSUE TITLE
Incorrect error thrown when we don't have the az botservice

### ISSUE THREAD

**Issue by sgellock** [Microsoft/botbuilder-tools#759]
## Tool
Name: Msbot az botservice
OS: all supported OS's

## Describe the bug
When running msbot clone, users get an error that says "You need to upgrade your az botservice version". When you try to upgrade, you then learn that you don't have the az botservice, and have to download it. 

## Additional context
I think we also need to make sure our docs are very clear on what the min-version of .net core is and that it's properly documented in the pre-req's section of the samples README.md files

[bug]

**Comment by carlosscastro** [comment]
Other work took over my time. Discussing a new ETA for this one with Vishwac

**Comment by carlosscastro** [comment]
@vishwacsena removing myself from this one to avoid double counting in bug count, since you are already adding it to your ongoing PR. Add me back if you need help from me.
