### ISSUE TITLE
msbot connect bot fails when appPassword contains special characters

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-tools#762]
## Tool
Name: MSBot
Version: 4.0.7
OS: Windows 10 (PowerShell Core CLI)

## Describe the bug
I received an appPassword of "`>;RANDOMWHATEVER`" when I created my bot and whenever I would run `msbot connect bot` with the `--appPassword ">;RANDOMWHATEVER" it would error out with:

```cli
error: option `-p, --appPassword  <appPassword>' argument missing
```

## To Reproduce
Run `msbot connect bot` with an `--appPassword` that starts with an `>` character:

```cli
msbot connect bot  …other params elided for brevity... --appPassword ">;ABC123NYCSEA"
```

## Expected behavior
Should work like any other password. I'm not choosing it, so I have no control over what characters are in there.

## Workaround
_Partial_ work around:

Remove the `>` from the password when calling `msbot connect bot` and then go put it back in manually once the endpoint is added to the `.bot` file. 

**NOTE:** this obviously only works if you're not using a secret to encrypt your settings

**Comment by sgellock** [comment]
@drub0y I think this is a dup of #694

**Comment by drub0y** [comment]
Seems that way.
