### ISSUE TITLE
Unable to install luis-cli: error TS5057: Cannot find a tsconfig.json file at the specified directory: '.'.

### ISSUE THREAD

**Issue by damadei** [Microsoft/botbuilder-tools#766]
## Tool
Name: LUIS
Version: ?
OS: windows 10

## Describe the bug
Unable to install LUIS-Cli, it results in the error attached.

## To Reproduce
Not sure

## Expected behavior
Install without error
[error_luis_cli.txt](https://github.com/Microsoft/botbuilder-tools/files/2581742/error_luis_cli.txt)
[bug]

**Comment by omarsourour** [comment]
@carlosscastro I did in fact. From the error log attached, the `luis-cli` version that is being run is the first version to be created, which is `v1.0.1`. The build process has widely changed since then. I advise using a more recent version?

**Comment by damadei** [comment]
Correct, Omar, it worked fine. Not sure where I took luis-cli from but with luis-apis it works.

**Comment by omarsourour** [comment]
Excellent! Closing issue.
