### ISSUE TITLE
Ludown: Remove duplicate utterances/patterns on ludown translate

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#772]
## Tool
Name: LuDown

## Describe the problem
When running ludown translate on a file without duplicates, sometimes the result will contain duplicate utterances/patterns due to the translation. This causes issues when trying to publish the translated file. `--msbotInput paterns cannot contain duplicates.`
## Describe alternatives you've considered
Manually removing duplicates - long and complicated process prone to errors

[enhancement]

**Comment by omarsourour** [comment]
@lauren-mills When you say "publish" the translated file, do you mean using the LuDown tool to parse the file to JSON?

**Comment by omarsourour** [comment]
Funnily enough, after investigations, the bug has already been solved, but has never been pushed to the public NPM repo. @vishwacsena The npm package version needs to be bumped and pushed. What is the process that we follow? Will this happen with the release?

**Comment by sgellock** [comment]
Close the issue. We’ll push out new bits with the 4.2 release.  @cleemullins fyi

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
