### ISSUE TITLE
msbot connect abs should not enforce optional creation of endpoint

### ISSUE THREAD

**Issue by robert4os** [Microsoft/botbuilder-tools#777]
## Tool
Name:  Msbot
Version: *4.0.7*
OS: *windows 10*

## Describe the bug

The help command of msbot connect bot states that endpoint is optional.
  -e, --endpoint <endpoint>              (OPTIONAL) Registered endpoint url for the Azure Bot Service
  -p, --appPassword  <appPassword>       (OPTIONAL) Microsoft AppPassword for the Azure Bot Service

But the parameter is enforced AND and an endoint is created too. 

## To Reproduce

Check help for msbot connect abs. Then try to omit the enddpoint or the password. It will not accept the omission. 

## Expected behavior

msbot abs connect should not enforce endpoint creation. It should be optional as in the help.

[bug]

**Comment by carlosscastro** [comment]
Thanks for reporting this. In this case, the right behavior is to make the endpoint mandatory which was the original intention. Updating the docs to reflect that.
