### ISSUE TITLE
az bot sms create HTTP 500

### ISSUE THREAD

**Issue by thegoo** [Microsoft/botbuilder-tools#779]
## Tool
Name: az bot sms create
Version: Latest

## Describe the bug
Receiving a HTTP 500 error when attempting to create and enable the SMS channel within my Web App Bot via the Azure CLI.  It cycles thru the max retries and then advises to log a bug.

This issue occurs via Azure DevOps build pipeline with Azure CLI task or thru the Azure Cloud Shell within the Portal.

I've redacted my account details where it indicates <<…>>.

See below:

**Request:**
msrest.http_logger : {"location": "global", "properties": {"channelName": "SmsChannel", "properties": {"phone": "1115551212", "accountSID": "<< MY SID >>", "authToken": "<< MY TOKEN >>", "isEnabled": true}}}

**Response:** 
urllib3.connectionpool : https://management.azure.com:443 "PUT /subscriptions/<< MY SUB >>/resourceGroups/<< MY RG >>/providers/Microsoft.BotService/botServices/<< BOT NAME >>/channels/SmsChannel?api-version=2018-07-12 HTTP/1.1" **500 105**

## To Reproduce
1. Obtain a Twilio SMS phone number
2. Create a Web App Bot in Azure
3. Execute the command in the Cloud Shell; updating with your phone number, SID, and token values: ***az bot sms create -g "<< YOUR RG>>" -n "<< YOUR BOT NAME >>" --auth-token "<< YOUR AUTH TOKEN >>" --account-sid "<< YOUR SID >>" --phone "<< YOUR NUMBER >>"***

## Expected behavior
SMS Channel is created and enabled within my Web App Bot.

## Actual behavior
msrest.exceptions : Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/<< MY SUB >>/resourceGroups/<< MY RG >>/providers/Microsoft.BotService/botServices/<< MY BOT >>/channels/SmsChannel?api-version=2018-07-12 (Caused by ResponseError('too many 500 error responses',))
Error occurred in sending request. Please file an issue on https://github.com/Microsoft/botbuilder-tools/issues

[bug]

**Comment by damaca** [comment]
Same error here with Facebook. I used the same http request that makes this addon and the error says:
```
{"error":{"code":"UnknownError","message":"An unexpected error occurred. Exception: 'System.ArgumentNullException: Value cannot be null.\r\nParameter name: source\r\n   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)\r\n   at Intercom.ResourceProvider.ServiceModel.FacebookChannelResource.RemoveSecrets()\r\n   at Intercom.ResourceProvider.Channels.ArmChannelManager.<GetChannelAsync>d__6`2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at Intercom.ResourceProvider.DataProviders.ChannelResourceDataProvider.<FindResourceAsync>d__16.MoveNext()'."}}
```

**Comment by anusharavindrar** [comment]
I recreated the behavior and it successfully created the SMS Channel and it was enabled within the Web App Bot . I used the current version of Azure CLI i.e., 2.0.63

**Comment by CoHealer** [comment]
Closing, repaired in subsequent CLI build.
