### ISSUE TITLE
MSBot clone can only be run once

### ISSUE THREAD

**Issue by ryanlengel** [Microsoft/botbuilder-tools#780]
## Tool
Name: MsBot
Version: n/a
OS: n/a

## Describe the bug
Transferred from:
Microsoft/AI#231
Author: @digitaldias
> **Description**
> To continue working with Virtual Assistant on a different laptop, the new laptop should be able to obtain all configuration by running the assistant again. What happens instead is the deployment script fails on "resource already exists".
> 
> It would be nice to know if the script, when run a second time, should
> Fail?
> Reset current resources to their default/scripted values
> Ignore the existing resources and continue to the next step

Microsoft/AI#322
Author: @gabog

> **Is your feature request related to a problem? Please describe.**
> msbot clone can not run twice, it ends up duplicating resources and also fails when attempting to create cosmosDB.
> Right now, the only alternative is to delete, recreate and reconfigure the entire resource group.
> **Describe the solution you'd like**
> It is time consuming to assign keys and tune pricing tiers for deployed assistants, we may also lose data that we want to keep.
> It will be good to have an msbot update option that:
> skips the creation of resources if they are already there (app plan, bot registration, cosmos, storage, etc.)
> updates resources that need to be updated: .bot file, LUIS model and QnAMaker.

## To Reproduce
Run the deployment script successfully. Then run it again.

## Expected behavior
The deployment script should not re-create any azure resource, but instead leverage them.

**Comment by lauren-mills** [comment]
Also, https://github.com/Microsoft/AI/issues/322

**Comment by benbrown** [comment]
We're not going to fix this, sorry!
