### ISSUE TITLE
msbot clone: Ability to specify Search Service tier as parameter

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#782]
## Tool
Name: Msbot

## Describe the problem
From [Microsoft/AI/issues/323](https://github.com/Microsoft/AI/issues/323)
Author: @gabog 

> Is your feature request related to a problem? Please describe.
By default, msbot create a Standard Search Service which is kind of expensive for dev and local tests.
If I understand this correctly (https://docs.microsoft.com/en-us/azure/search/search-sku-tier) the search pricing tier can not be changed after its been created.
QnAMaker allows you to select a pricing tier when creating the service but this parameter is not exposed by msbot

Describe the solution you'd like

> I would like to have a parameter where I can specify the pricing tier to be used by the Search Service used by QnAMaker.

Describe alternatives you've considered

> I've considered manually recreating QnAMaker and then update the bot files and the dispatcher, but this is time consuming and I will need to do it again if I need to update my environment from a new drop (msbot doesn't support update, you are forced to delete and recreate if you want to get the latest).

## Additional context

[enhancement]

**Comment by vishwacsena** [comment]
Tracked via #584
