### ISSUE TITLE
msbot clone: Mismatched appId after deployment

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#784]
## Tool
Name: Msbot

## Describe the bug

Raised here: https://github.com/Microsoft/AI/issues/300
Author: @ivlaevski 

After providing the --appId and --appSecret arguments, the created bot has a different appId that does not exist when the "manage" link is clicked.

## To Reproduce
Difficult to repro, but here are the steps:
1. Run msbot clone
2. Deployment fails due to appId provisioning issue
3. Delete resource group using the `az delete group command`
4. Run msbot clone again using the same name and providing the --appId and --appSecret
5. Cloning completes, but bot is created with different appId (unsure if it is the same one created from first clone)

## Expected behavior
The new bot should have the appId that was specified as an argument. 

[bug]

**Comment by vishwacsena** [comment]
Tracked via #721
