### ISSUE TITLE
AZ bot create/ msbot clone: Fails in Southeast Asia

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#785]
## Tool
Name: Msbot
Version: 4.0.7

## Describe the bug
Original issue: https://github.com/Microsoft/AI/issues/309
Author: @NobinJoseRad

> msbot clone command fails when the region selected in "southeastasia". I managed to create it using eastasia however i wish to have southeastasia support.

## To Reproduce
> run msbot clone services with location "southeastasia"

## Expected behavior
> Should be able to create all azure services needed for bot without error

## Screenshots
![](https://user-images.githubusercontent.com/29299856/48529957-8232a980-e8d0-11e8-9116-6d1fe0705a10.png)

[bug]

**Comment by vishwacsena** [comment]
I can repro this with the latest az cli + bot service extension. The az bot create command is failing. Updating  labels. 

@carlosscastro ; @stevengum

**Comment by vishwacsena** [comment]
That makes sense to me. Thanks.

**Comment by stevengum** [comment]
Moved to 4.3 per conversation with Scott

**Comment by stevengum** [comment]
Fixed via stevengum/Azure-cli@8bc1bba49955bbdbe69d2ec8ecad89c7f9b71d49, leaving open until PR is cut and merged against [Azure/Azure-cli](https://github.com/Azure/azure-cli/).

**Comment by stevengum** [comment]
Closed via Azure/Azure-cli#8035.
