### ISSUE TITLE
Chatdown: output transcript text in cards is lowercase

### ISSUE THREAD

**Issue by danuw** [Microsoft/botbuilder-tools#787]
## Tool
Name: Chatdown
Version: 1.10 (went back down from 1.11 not working with transcript conversion)
OS: Mac OS (both before after Mojave update)

## Describe the bug
When writing markdown scenario (.chat), the converted output (.transcript) is all lowercase in cards

## To Reproduce
1. Start a new test.chat file with text (see below)
2. convert it using `chatdown test.chat > test.transcript`
3. Open in Bot Framework emulator or simply look at the test.transcript json
4. Text in cards is lower case

## Expected behaviour
I suppose the case should be stay unchanged

## Screenshots
<img width="769" alt="screenshot 2018-11-21 at 09 39 34" src="https://user-images.githubusercontent.com/8134789/48832883-1b027280-ed72-11e8-9c73-e20b8c08b947.png">

## Additional context

contents of the test.chat file (note card buttons different casing)
```
user=User
bot=Bot

bot: Ask me for help

bot:[Typing][Delay=3000]
[AttachmentLayout=carousel]
[Herocard   
    title=Am I still capitalized?
    subtitle=Let's try without text field
    images=https://memegenerator.net/img/instances/500x/73055378/cheese-gromit.jpg
    buttons=Option 1|OPTION 2| opTION 3]
[Herocard   
    title=Am I still capitalized too?
    subtitle=Let's try without text field
    text=Here is the text...
    images=https://memegenerator.net/img/instances/500x/73055378/cheese-gromit.jpg
    buttons=Option 1|OPTION 2| opTION 3]
```

[bug]

**Comment by vishwacsena** [comment]
@danuw I have a fix for this in #805. For now, since you are snapping to 1.0.10 and given you are on macos, you can take the fix by updating line 404 in /usr/local/lib/node_modules/chatdown to read like this - 

```js
let value = line.substr(start + 1).trim();
```
