### ISSUE TITLE
msbot clone does not release shell input when run on macOS

### ISSUE THREAD

**Issue by sgellock** [Microsoft/botbuilder-tools#789]
## Tool
Name: Msbot
Version: 4.0.7
OS: macOS (Mojave 10.14.1)

## Describe the bug
When msbot clone finishing, it displays a "Done cloning." message but does not display the shell prompt

## To Reproduce
1. open a terminal window on macOS
2. nav to a node project, echo bot from the samples will work
3. msbot clone services -n my-chat-bot --subscriptionId <subscription-id> -l westus --sdkLanguage "Node" -f deploymentScripts/msbotClone

## Expected behavior
Once the CLI tool finishes running, input is returned back to the shell, so the command prompt is active again.

[bug]

**Comment by justinwilaby** [comment]
This likely can be fixed by adding a \n to the end of the output.

**Comment by sgellock** [comment]
Given we're moving away from msbot-cli, I'm closing as won't fix.
