### ISSUE TITLE
Crear lu files from LUIS files

### ISSUE THREAD

**Issue by gabog** [Microsoft/botbuilder-tools#794]
## Information:
* Tools Libraries: ludown
* OS: All

## Issue Description:
As a developer, I would like to be able to create lu files out of an exported LUIS app json so I can develop and tune my apps on the LUIS portal first and then incorporate them as lu files in my source later.

This will also allow me to import other pre-existing Luis apps developed by others without having to rewrite them as lu files.

**Comment by vishwacsena** [comment]
@gabog - you can generate lu files from both LUIS application and or QnA maker KB using the refresh command. See [here](https://github.com/Microsoft/botbuilder-tools/blob/master/packages/Ludown/docs/refresh-command.md) for additional information. 

Note that the .lu file format and ludown tool does not support hierarchical, composite and RegEx entities. refresh will fail if your source LUIS model had these features.

**Comment by gabog** [comment]
thanks Vishwac, I didn't know about this option.
