### ISSUE TITLE
Bot Configuration file format could benefit from a JSON schema to light up intellisense and other tooling

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-tools#795]
## Tool
Name: Msbot

## Describe the problem
While there is some light documentation/samples of the `.bot` file format, you still are pretty much editing raw JSON when it comes down to it unless you stick to using the `msbot` CLI.

## Describe the solution you'd like
Create a JSON schema for the .bot configuration file format to help developers who may prefer to hand edit the files in development environments that understand JSON Schema such as VS Code or VS full.

## Describe alternatives you've considered
Just edit raw JSON and refer to docs/samples for schema.

[enhancement]

**Comment by sgellock** [comment]
with the de-emphasis of .bot files, I don't see us addressing this.
