### ISSUE TITLE
When creating a bot via the Azure CLI, related resource names are randomized

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-tools#796]
## Tool
Name: Azure CLI Extension

## Describe the problem
There does not seem to be any way to control exactly what name is used for some related resources (Web App, App Insights, etc) that is created to host the bot and a random name is chosen based on the first _N_ characters of your bot name. I believe this leads to confusion because, for some steps, you need to actually know the name of the other resources itself (e.g. deploying) and this requires you to figure it out through relationship to the bot service. You can infer this if you happened to have created an entirely new Resource Group that everything ends up in, but the only concrete way to know is to check, for example, which Web App is associated with the Bot Service as the "Messaging Endpoint".

## Describe the solution you'd like
I would love to see the name of the web app simply match the name of the Bot Service by default and, if that approach doesn't work and errors out for some reason, just support additional arguments via the CLI extension that allow me to specify names for each of the ancillary resources explicitly.

## Describe alternatives you've considered
Manually create all of the resources myself so I can control the names of everything explicitly.

[enhancement]

**Comment by stevengum** [comment]
Closing via Azure/Azure-cli#8384
