### ISSUE TITLE
No way to opt out of creating an Application Insights resource (or point to an existing one) from the Azure CLI

### ISSUE THREAD

**Issue by drub0y** [Microsoft/botbuilder-tools#797]
## Tool
Name: Azure CLI Extension

## Describe the problem
An Application Insights resource is always created when using the Azure CLI Extension and, AFAICT, there's no way to opt-out of this or tell the CLI to use a specific existing AI instance that I might have.

## Describe the solution you'd like
Some people might not want to utilize AI at all or they might already have an AI instance they want the Bot telemetry to go into. It would be nice to both have a way to opt-out of using AI altogether as well   have the ability to point to an existing AI instance if I don't want a new one created for me (much like you can for storage).

**Comment by stevengum** [comment]
We're going to stop provisoning/accepting App Insights by default when creating an WebApp Bot. Instead we're going to have documentation and ARM templates that have App Insights.

A simple ARM template would like this:

New resources provisioned through ARM:
- App Service Plan (optional)
- Web App
- Registration Bot
- Application Insights

**Comment by gabog** [comment]
Closing as per @stevengum comment above (won't be relevant in the future).
