### ISSUE TITLE
Luis: better error message for incorrect entity start, end

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botbuilder-tools#798]
## Tool
Name: LUIS

## Describe the problem
When there is an issue with the entity label in a .luis file, the error doesn't tell you which utterance/line the error occurs on so you have to search by the start and end pos of the entity
Example:
```
 {
      "text": "controllare il mio Mammaprogramma del",
      "intent": "FindCalendarEntry",
      "entities": [
        {
          "entity": "RelationshipName",
          "startPos": 19,
          "endPos": 23
        }
      ]
    }
```

Error:
Indices 19,23 are not the start and end of a token

## Describe the solution you'd like
I'd like to know the line and/or utterance that caused the issue so I can fix the problem more easily. 

[enhancement]

**Comment by cahann** [comment]
Backend work in-progress for more descriptive error messages in-case of file import

**Comment by cahann** [comment]
the backend work was done blocked on the frontend, will move it to 4.7
