### ISSUE TITLE
MsBotClone to clarify that bot is empty and provide command to publish

### ISSUE THREAD

**Issue by carlosscastro** [Microsoft/botbuilder-tools#799]
As a temporary doc-only fix for #756, when we complete a bot clone we want to present a clear message that the bot code has NOT been cloned and the bot has a default template. We should also provide the users with the az command that they need to run in order to publish their source. Given that in clone we have the resource group and resource name, we can show them the full command except for --code-dir.

**Comment by carlosscastro** [comment]
@tomlm you had a command documentation fix for this, right?

**Comment by carlosscastro** [comment]
We are waiting for the AZ extension release to put a change here, ETA 12/6

**Comment by vishwacsena** [comment]
Leaving this assigned to @tomlm. the right fix here is to push #816 through with all the other AZ bot service extension fixes.
