### ISSUE TITLE
Luis api- create application which is public by default

### ISSUE THREAD

**Issue by DeepakDonde** [Microsoft/botbuilder-tools#800]
I am trying to create app on Luis which is accessible by non-contributors so that they can

 query this app with a valid key. I am able to create app with the following request body

`{
	"name": "MyFirstDummyApp",
	"description": "This is my first dummy application",
	"culture": "en-us",
	"usageScenario": "IoT",
	"domain": "Comics",
	"initialVersionId": "1.0"
}`

But i don't find any flag or key in request body which can be use to make app public or non-public.

Below is the screenshot from Luis app information under manage tab:
![luis_public](https://user-images.githubusercontent.com/14233168/48930052-c139ae00-ef13-11e8-82aa-cbc606b1b541.PNG)

**Comment by tomlm** [comment]
You can do this via the Update Appication Settings API:
https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/58aeface39e2bb03dcd5909e

From the LUIS command line:
**luis update settings**
