### ISSUE TITLE
Validation support for LUIS|Ludown|Dispatch tools

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botbuilder-tools#803]
## Tool
Name: [Ludown|LUIS|Dispatch]

## Describe the problem
When we import a luis model from .luis file, sometimes there's errors. ideally there should be tooling support to tell us the .luis file is problematic with the detailed information to fix the issues. This goes for .lu file as well as Dispatch tool.

## Describe the solution you'd like
Ludown|LUIS|Dispatch tool support with option for validation

[enhancement]

**Comment by lzc850612** [comment]
This is very useful when it comes to a team working on a bot with language models as part of the code. We need this support to put into the PR step to block the PR from being merged if there's some changes in the .lu file that'll break it.

**Comment by vishwacsena** [comment]
@cahann it would be awesome if we can have a version of the LUIS validations as a library we can include in the CLI so users can validate a model definition without having to post it to the service through a create operation. Alternately we could expose a validate API call that can just validate a model definition file.

**Comment by cleemullins** [comment]
I don't think this is something we're going to take with this iteration of the tool. As we migrate ludown (assuming we do, which is somewhat in flux) we could do it then. 

@vishwacsena Can you confirm, and if so we'll close this out?

**Comment by vishwacsena** [comment]
@cleemullins - yes agreed. There already are layers of validations at the LU level. The service of course does additional validation at model creation/ train/ publish time which cannot be brought down to CLI level. 

I'll go ahead and close this. @lzc850612 - could you please file individual tickets for any missing validations in particular that you would like to see added? We will need to make a per case determination of if we can catch that prior to hitting the service or not.
