### ISSUE TITLE
Not able to deploy to Azure web app 

### ISSUE THREAD

**Issue by Jagan-rajan** [Microsoft/botbuilder-tools#809]
> .net framework version used - 4.6

I am not able to deploy my code to Azure web apps linked to my account eventhough my framework points to .net 4.6

Recieving the below error : 

**Your hosting provider does not yet support ASP.NET 4.6, which your application is configured to use. To learn more about this please visit: http://go.microsoft.com/fwlink/?LinkID=615797&clcid=0x409**

My web app points to .Net framework 4.7 version. 

Please help me with this as we struck with deployments.

**Comment by dmvtech** [comment]
@Jagan-rajan I'm not sure if you are still experiencing this issue or not. Please let me know if the above steps helped remedied or if you still have the problem.

**Comment by dmvtech** [comment]
I am closing this as I do not know if this issue is still happening for you. If this is something that can be consistently reproduced and is a blocking issue, please reopen.
