### ISSUE TITLE
MSBot Clone command fails

### ISSUE THREAD

**Issue by Kaiqb** [Microsoft/botbuilder-tools#814]
## Tool
Name: **MSBot**
Version: *4.0.7*
OS: *Windows 10*

## Describe the bug
MSBot clone command fails with the following error:
ERROR: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.

## To Reproduce
1. Use sample: [12.nlp-with-luis](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/12.nlp-with-luis) 
2. Run the following command:
msbot clone services -f "c:\temp\nlp-with-luis\deploymentScripts\msbotClone" -n nlp-with-luis -l westus --subscriptionId xxxx --appId xxxx --appSecret xxxxx--luisAuthoringKey xxxx --verbose

The following services will be created by this operation:
- Azure App Site Plan                     westus              S1                  nlp-with-luis
 - Azure AppInsights Service               West US 2           F0                  nlp-with-luis
- Azure Blob Storage Service              westus              Standard_LRS        nlp-with-luis
- Azure Bot Service Registration          Global                                  nlp-with-luis
- Azure LUIS Cognitive Service            westus              S0                  nlp-with-luis
- Azure WebApp Service (Bot)              westus                                  nlp-with-luis

Would you like to perform this operation? [y/n]y

Checking az botservice version
az -v
Fetching subscription account
az account show --subscription xxxxxxx
Creating resources in subscription: Bot Framework Team xxxxx
Creating Azure group [nlp-with-luis]
az group create -g nlp-with-luis -l westus
Using the provided ApplicationId and Secret rather than auto-provisioning
Creating Azure Bot Service [nlp-with-luis]
az bot create -g nlp-with-luis --name nlp-with-luis --kind webapp --location westus --insights-location "West US 2"  --version v4 --appid xxxxx -p "xxxxx"

az bot create -g nlp-with-luis --name nlp-with-luis --kind webapp --location westus --insights-location "West US 2"  --version v4 --appid xxxxx -p "xxxxx" exit code: 1
**WARNING**: The behavior of this command has been altered by the following extension: botservice
**ERROR**: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.

I also tried another variation of the `clone` command:
`msbot clone services -f "c:\temp\nlp-with-luis\deploymentScripts\msbotClone" -n nlp-with-luis -l westus --luisAuthoringKey xxxxxxxxxxx --verbose`

It failed with the following message:

[az bot] obtained msa app id and password. Provisioning bot now.
 (Please be patient, this may take several minutes)
az bot create -g nlp-with-luis --name nlp-with-luis --kind webapp --location westus --insights-location "West US 2"  --version v4 exit code: 1
WARNING: The behavior of this command has been altered by the following extension: botservice
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code xxxx to authenticate.
WARNING: obtained msa app id and password. Provisioning bot now.
**ERROR:** At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.

## Expected behavior
Services should be created.
Error messages should be helpful.

[bug]

**Comment by stevengum** [comment]
@Kaiqb have you tried "West US" for location? Looking at az cli, we expect location args in the format of "Central US"

**Comment by stevengum** [comment]
Disregard, sat through a repro with Vishwac. Will investigate

**Comment by stevengum** [comment]
@Kaiqb I'm going to close this as it should be fixed with the latest bits; additionally, the warning:

>az bot create -g nlp-with-luis --name nlp-with-luis --kind webapp --location westus --insights-location "West US 2" --version v4 exit code: 1
> WARNING: The behavior of this command has been altered by the following extension: botservice

Should not be occurring as `create` is not modified by the latest extension.
