### ISSUE TITLE
msbot connect qna command fails if .bot file already contains a qna service with empty strings

### ISSUE THREAD

**Issue by jwiley84** [microsoft/botbuilder-tools#815]
[EDIT: editted to reflect this only happening with qna command. LUIS, appinsights and dispatch work as expected]

Discovered using the nodejs sample from botbuilder-samples, #11. QnAMaker

## Describe the bug
I'm attempting to build one of the samples programmatically, without having to manually add in keys. This sample comes with an 'empty' qna maker service connection in the botfile, ready to be filled out manually (see screenshot below). Attempting to add a qnamaker service via 'msbot connect qna [options]' results in 'invalid URL' error until that whole section is deleted from the bot file. Attempting to use 'msbot disconnect ' with the service's pre-set ID (34) results in the same 'invalid URL' error. Once it's been removed through VSC or VS2017 manually, 'msbot connect qna [options]' works as expected.

## To Reproduce
1. Using command prompt, use the command 'git clone https://github.com/Microsoft/BotBuilder-Samples' to clone repo. 
2. Still in CP, navigate to NodeJS sample 11. 
3. enter 'msbot connect qna' along with correct options
4. Receive error 'TypeError [ERR_INVALID_URL]: Invalid URL:'
5. enter 'msbot disconnect 34' (since the qna service has no associated 'name').
6. Receive error 'TypeError [ERR_INVALID_URL]: Invalid URL:'
7. Open VSC, navigate to bot file, delete entire qna section.
8. enter 'msbot connect qna' along with correct options
9. no error. 

## Expected behavior
msbot has no problem duplicating an already existing qna service or adding a second qna service, it should not hiccup about this 'empty' service. 

## Screenshots
![emptyfile](https://user-images.githubusercontent.com/17333688/49409196-573fb680-f714-11e8-87ed-fc75ef76639b.png)

![error](https://user-images.githubusercontent.com/17333688/49409027-c10b9080-f713-11e8-89a5-278d0dc12647.png)

[bug]

**Comment by Kaiqb** [comment]
We are no longer using .bot file. Please use ARM templates that ship with the samples.
