### ISSUE TITLE
AZ CLI [Extension 0.4.2] Vsix publish error in C#

### ISSUE THREAD

**Issue by carlosscastro** [Microsoft/botbuilder-tools#818]
Tom ran `az bot publish --resource-group CloneBot106 -n CloneBot106 --subscription 9ad09adf-c85f-43a0-96fe-18b146d1f90e -v v4 --verbose --proj-file "Bot Builder Echo Bot V4.csproj"`

Using C#, the publish succeeds but the code changes are not reflected in the bot behavior. The project he published is an echobot from vsix template, except that he edited the text.

He didn't do any manual changes to the bot file. 

When he talks to the bot, the bot still has the old template behavior.

**Comment by stevengum** [comment]
This turned out to be the same problem we encountered with the old VSIX templates, which means that Azure doesn't like `.csproj` files with spaces in their name. Once the `.csproj` name was changed to something without spaces, the bot deployed bot worked as expected.
