### ISSUE TITLE
AZ CLI [Extension 0.4.2] Publish fails with trailing spaces for code dir

### ISSUE THREAD

**Issue by carlosscastro** [Microsoft/botbuilder-tools#820]
Repro steps: run any publish command with --code-dir and add a trailing space at the end, such as ". ". Result: the command fails. 

Reported by @tomlm, I didn't try repro.

**Comment by stevengum** [comment]
Reproduced, already have a fix in mind.

**Comment by stevengum** [comment]
That commit does have the fix for it, reopening issue until a PR is merged against Azure/azure-cli.

**Comment by stevengum** [comment]
Closed via Azure/Azure-cli#8035.
