### ISSUE TITLE
LUIS Dispatch binary is checked in and source code built elsewhere

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botbuilder-tools#822]
## Tool
Name: Dispatch
Version: 4.1.2
OS: windows

## Describe the bug
LUIS Dispatch binary is checked in and source code built elsewhere.

See @tsuwandy for details.

## Expected behavior
- Add source code to github
- Add build and packaging process around source code

**Comment by cleemullins** [comment]
Assigning to @tsuwandy

**Comment by tsuwandy** [comment]
We have stopped checking in binaries to GitHub (@cleemullins we still need to delete existing ones) and unfortunately we can't open source it due to CLI using private LUIS APIs.
