### ISSUE TITLE
msbot clone: Add new qna maker kb to existing qna service

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botbuilder-tools#826]
## Tool
Name: Msbot

## Describe the problem
I'm using msbot clone in an unconventional way to enable multiple language configurations for Dispatch, LUIS, and QnA. I run msbot clone against the same resource group for each language I want to add to my bot. Each time I run the command, it creates a new QnA Maker service with Azure Search, etc. in the resource group. This results in a lot of azure search services and quickly exhausts the quota for a single subscription. 

## Describe the solution you'd like
I'd like to be able to run msbot clone services against an existing resource group, and if there is an existing QnA Maker service in the resource group, add the kb to that service instead of making a new one. This might also be a good idea for the LUIS services, but less critical.

## Describe alternatives you've considered
Having multiple QnA services doesn't break anything, it's just inconvenient. I'm aware there could be situations when you might want multiple QnA services in a single resource group, so maybe it is a flag that could be added or something.

[enhancement]

**Comment by sgellock** [comment]
msbot is deprecated.  we won't add any new features and will on fix Pri0 bugs
