### ISSUE TITLE
[Regression] luis import application fails (latest build off myget feed)

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/botbuilder-tools#830]
## Tool
Name: LUIS
Version: 2.0.7 (myget feed)
OS: Win10

## Describe the bug
luis import application fails with the following - 
```bash
this.addUserAgentInfo is not a function
```

## To Reproduce
1. uninstall luis cli
2. point to the botbuilder myget feed
3. install the luis cli
4. try luis import application command and pass in valid arguments

## Expected behavior
luis import application works. The version that is published to npm works but we have a regression in what's available in the nightly builds.

[bug]

**Comment by stevengum** [comment]
@vishwacsena the ms-rest-js dependency needs to be pinned to [1.0.455](https://github.com/Microsoft/botbuilder-tools/blob/master/packages/LUIS/package.json#L52) (see https://github.com/Azure/ms-rest-js/issues/276 for more info)
