### ISSUE TITLE
[AZ CLI] Errors in Converged app creation should get info from the http response 

### ISSUE THREAD

**Issue by carlosscastro** [Microsoft/botbuilder-tools#833]
We are printing a hardcoded error message when the converged app provisioning fails. We should extract error info from the http response of the app creation request.

**Comment by stevengum** [comment]
Closing via [stevengum/Azure-Cli#f9469d8287d8c4e32c11c7e8cbe9b4a5d0831b4e](https://github.com/Azure/azure-cli/commit/f9469d8287d8c4e32c11c7e8cbe9b4a5d0831b4e).

`--appId` and `-p/--password` are now required for `az bot create` and can be provisioned via Azure CLI (`az ad app create`).

This code will be removed.
