### ISSUE TITLE
msbot clone: --quiet does not suppress LUIS model training output

### ISSUE THREAD

**Issue by lauren-mills** [microsoft/botbuilder-tools#836]
## Tool
Name: Msbot

## Describe the problem
When running msbot clone with --quiet, there is a lot of output from the LUIS training that defeats the purpose. 

## Describe the solution you'd like
When running in quiet mode, I would like to only see prompts that require input and errors.

[enhancement]

**Comment by sgellock** [comment]
msbot is deprecated.  we won't make any new fixes or changes to this tool unless they are Pro-0 (data lose or security related).
