### ISSUE TITLE
Dispatch tool should allow publishing to staging

### ISSUE THREAD

**Issue by genbod** [Microsoft/botbuilder-tools#837]
## Tool
Name: Dispatch

## Describe the problem
Other tools like LUIS have support for publishing to staging. Dispatch refresh does not. This makes CI/CD with LUIS models and Dispatch difficult

## Describe the solution you'd like
A flag for dispatch refresh that lets you set staging status.

## Additional context

[enhancement]

**Comment by tsuwandy** [comment]
Add an optional param to create and refresh commands called "publishSlot".

**Comment by tsuwandy** [comment]
this should be available sometime today with version 1.2.2.
