### ISSUE TITLE
Add better HTTP tests for QnAMaker and LUIS CLI tools

### ISSUE THREAD

**Issue by stevengum** [microsoft/botbuilder-tools#838]
## Tool
Name: LUIS & QnAMaker

## Describe the bug
No tests for #829 and #828

Additionally, it's been brought to my attention that there is poor test coverage for these two modules, so more tests need to be written.

[bug]

**Comment by Zerryth** [comment]
note: test runs leaves files in folders--certainly in the QnAMaker

**Comment by Zerryth** [comment]
### Note #2
* holding off writing tests for these now myself
* as per Steven G., there's a discussion regarding which team should take ownership of which CLI tool

**Comment by stevengum** [comment]
Closing this as the code now lives in https://github.com/microsoft/botframework-cli/
