### ISSUE TITLE
AZ CLI: Using hotmail account, the newly created bot fails to launch.

### ISSUE THREAD

**Issue by Kaiqb** [Microsoft/botbuilder-tools#841]
## Tool
Name: azure-cli (v 2.0.52)
Name: botservice (v 0.4.3)
OS: Windows 10

## Describe the bug
AZ CLI: Using Hotmail account, the newly created bot fails to launch when I am trying to test it in WebChat. The first message that shows up is, "waiting for the bot to ready" followed by "Something went wrong. Contact the administrator". 

## To Reproduce
1. Login to Azure using your personal Hotmail account.
2. Run the following command:
`C:\Temp\WorkingBots\MyBot\MyBot>az bot create  --name "AZBOT" --kind webapp --version v4 --lang "CSharp" --appid "db09d" --password "WU351"`
3. The command returns with the following message. Not error is reported here.
{
  "appId": "0dd4ec82f0",
  "appPassword": "U351",
  "endpoint": "https://vybd.azurewebsites.net/api/messages",
  "id": "Azbot",
  "name": "AZBOT",
  "resourceGroup": "azclibotresourcegroup",
  "serviceName": "AZBOT",
  "subscriptionId": "6362418c9482",
  "tenantId": "931a3711",
  "type": "abs"
}
3. In the Azure portal, use WebChat to test the bot, and I get the error that is mentioned above.

## Expected behavior
Bot should work. 

##Additional info:
Because I was using my personal Hotmail account, I had to do the following before running the `az bot create` command:
Manually provision a Microsoft Application, using the Application Registration Portal at https://apps.dev.microsoft.com/. Once I manually created my application, I passed the application Id and password as parameters for bot creation in the `az bot create` command.
[bug]

**Comment by stevengum** [comment]
Closing via [stevengum/Azure-Cli#f9469d8287d8c4e32c11c7e8cbe9b4a5d0831b4e](https://github.com/Azure/azure-cli/commit/f9469d8287d8c4e32c11c7e8cbe9b4a5d0831b4e).

`--appId` and `-p/--password` are now required for `az bot create` and can be provisioned via Azure CLI (`az ad app create`).
