### ISSUE TITLE
Dispatch refresh fails without any helpful output when using a new version id

### ISSUE THREAD

**Issue by genbod** [Microsoft/botbuilder-tools#845]
## Tool
Name: Dispatch
Version: 1.1.9
OS: Windows 10

## Describe the bug
I am running dispatch refresh with a versionId that already exists.  I get an error that says it failed but no helpful info: 

Exporting services for dispatch...
Exporting artconDispatchModel LUIS application...
Exporting artconEventGridModel LUIS application...
Exporting artconFaqChitChat QnA kb...
Creating dispatch LUIS model json...
Creating training data...
Updating artconDispatch model...
Importing artconDispatch model...

ERROR
Failed importing latest version of artconDispatch app

## To Reproduce
1. Create two other dispatch versions on deployed to prod the other to staging
2. Try and refresh with a different versionId.  It looks like it showed up but I get an error nonetheless

## Expected behavior
No error, or info. on why it failed

## Additional context

[bug]

**Comment by tsuwandy** [comment]
@genbod, did you use the command "dispatch refresh -v {new version}"?  thanks!

**Comment by genbod** [comment]
yes.

**Comment by tsuwandy** [comment]
update published to npmjs
