### ISSUE TITLE
MSBot: Fails to deploy a C# bot with LUIS

### ISSUE THREAD

**Issue by Kaiqb** [Microsoft/botbuilder-tools#848]
## Tool
Name: Msbot
Version: *4.2.0-108*
OS: *Windows 10*

## Describe the bug
A bot with LUIS service fails to deploy with the following error message:

`Command failed: dotnet user-secrets set botFileSecret 56h0q38LxMrNYOII=No executable found matching command "dotnet-user-secrets"`

The bot works fine locally. LUIS service reference is in the .bofile. Here is the bot file has:
{
    "name": "LuisBot",
    "services": [
        {
            "type": "endpoint",
            "name": "development",
            "endpoint": "http://localhost:3978/api/messages",
            "appId": "",
            "appPassword": "",
            "id": "166"
        },
       {
        "type": "luis",
        "name": "LuisBot",
        "appId": "xxxxxxxxx",
        "version": "0.1",
        "authoringKey": "xxxxxxxxx",
        "region": "westus",
        "id": "158"
        }
    ],
    "padlock": "",
    "version": "2.0"
}

## To Reproduce
1. Run the following command to deploy a bot that uses LUIS. 

`msbot clone services --folder deploymentScripts\msbotClone --location "westus" --proj-file "LuisBot.csproj" --name "AzLuisBotKI" --groupName azclibotresourcegroup --luisAuthoringKey "xxxxxxxxxxxxxxxxxxx" --verbose`

Here is the complete output:

Checking az botservice version
az -v

Fetching subscription account
az account show

The following services will be created by this operation:
 Service                                 Location            SKU                 Resource Group
 Azure App Site Plan                     westus              S1                  azclibotresourceg…
 Azure Bot Service Registration          Global                                  azclibotresourceg…
 Azure WebApp Service (Bot)              westus                                  azclibotresourceg…

Resources will be created in subscription: FUSE Temporary (xxxxxxxxxx)
Would you like to perform this operation? [y/n]y

Creating Azure group [azclibotresourcegroup]
az group create -g azclibotresourcegroup -l westus --subscription xxxxxxxxx
Creating Azure Bot Service [AzLuisBotKI]
az bot create -g azclibotresourcegroup --name AzLuisBotKI --kind webapp --location westus --insights-location "West US 2" --subscription xxxxxxx --version v4 --lang CSharp --verbose
[az bot] INFO: Microsoft application id not passed as a parameter. Provisioning a new Microsoft application.
 (Please be patient, this may take several minutes)
[az bot] To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code BUSBSNWQZ to authenticate.

Fetching bot extended information [AzLuisBotKI]
az bot show -g azclibotresourcegroup -n AzLuisBotKI --subscription xxxxxxxx
Fetching co-created resources [AzLuisBotKI]
az resource list -g azclibotresourcegroup --subscription xxxxxxx
Fetching bot website appsettings [AzLuisBotKI]
az webapp config appsettings list -g azclibotresourcegroup -n zuisota4dl --subscription xxxxxxxx
Fetching Azure AppInsights information [AzLuisBotKIy6n77v]
az resource show -g azclibotresourcegroup -n AzLuisBotKIy6n77v  --resource-type microsoft.insights/components --subscription xxxxxxxx
Fetching storage connection string [zuisotrve0]
az storage account show-connection-string -g azclibotresourcegroup -n "zuisotrve0" --subscription xxxxxxx
AzLuisBotKI.bot created.

The secret used to decrypt AzLuisBotKI.bot is: MrNYOII=

NOTE: This secret is not recoverable and you should save it in a safe place according to best security practices.
      Copy this secret and use it to open the AzLuisBotKI.bot the first time.
Updating appsettings.json with botFilePath=AzLuisBotKI.bot
Saving the botFileSecret with dotnet user-secrets
dotnet user-secrets set botFileSecret xxxxxxxxxxxxxxxx
Command failed: dotnet user-secrets set botFileSecret xxxxxxxxxxxxx No executable found matching command "dotnet-user-secrets"

## Expected behavior
Bot should deploy.

[bug]

**Comment by sgellock** [comment]
I think this is a dup of https://github.com/Microsoft/BotBuilder-Samples/issues/1010

**Comment by tomlm** [comment]
Do you have dotnet installed?  I will add dotnet to prerequisties

**Comment by Kaiqb** [comment]
@tomlm - I have VS 2017 installed. What other piece is needed? Can you provide a download/install link? Thx

**Comment by Kaiqb** [comment]
dotnet --version 
2.1.104

**Comment by tomlm** [comment]
Really really old version, and pre-release to boot. 

```
This operation requires Dotnet Core SDK 2.1.500 or newer to be installed.
Go to https://www.microsoft.com/net/download to install on your system.

```

**Comment by Kaiqb** [comment]
Reinstalling a new version now...

**Comment by Kaiqb** [comment]
The error went away after installing the new version. Closing the issue.
