### ISSUE TITLE
MSBot: Deploying C# sample 12.nlp-with-luis fails

### ISSUE THREAD

**Issue by Kaiqb** [Microsoft/botbuilder-tools#849]
## Tool
Name: MSBot
Version: *4.0.2.-108*
OS: *Windows 10*

## To Reproduce
1. Download the sample. 
2. Run the following command:
`msbot clone services --folder deploymentScripts\msbotClone --location "westus" --proj-file "LuisBot.csproj" --name "AzLuisBotKI02"  --verbose`

3. The following error message appears:
`missing --luisAuthoringKey argument` 

## Expected behavior
The service should be provisioned using the bot.recipe file. 
`msbot clone services` command should provision a new LUIS service on behalf of the user. 

This was working a couple of days ago and now that `luisAuthoringKey` is required, it fails.

[bug]

**Comment by sgellock** [comment]
this is by design, no?  you can't provision LUIS resources unless you specify an authoring key

**Comment by tomlm** [comment]
This is by design, you have to provide the luisAuthoringKey to create luis resources. 

I could clean up the error, and say "This recipe requires a luisAuthoringKey to provision LUIS resources"

**Comment by Kaiqb** [comment]
So, if I am deploying a sample with LUIS, I have to provide luisAuhtoringKey, which means that I have to have a LUIS app in the luis.ai portal? Is that the behavior we want for samples? The behavior earlier was much simplers as I didn't have to do anything and the sample got deployed. It was much simlper, IMHO.

**Comment by tomlm** [comment]
I have no idea what you are talking about.  You have ALWAYS needed to provide a LuisAuthoringKey, this has not changed since we first created the tools.

**Comment by sgellock** [comment]
You don’t need a LUIS app. But like azure where you need an account and a subscription you need a LUIS account and an authoring key.

This has always been the case.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Kaiqb** [comment]
Closing the issue.
