### ISSUE TITLE
msbot: no longer appends bot name to luis models

### ISSUE THREAD

**Issue by lauren-mills** [Microsoft/botbuilder-tools#857]
## Tool
Name: Msbot
Version: 4.3.0
OS: Windows

## Describe the bug
Msbot clone no longer appends the bot name to the LUIS models which causes issues when running multiple deployments. If you deploy multiple bots from the same source, you will get errors for having multiple LUIS models with the same name. There used to be a "no-decorate" flag to allow you to control this behavior, but it looks like its no longer there.

## Expected behavior
I want the option to append something to the LUIS model name to create a unique name.

[bug]

**Comment by sgellock** [comment]
My understanding is as follows.  When we clone LUIS requires unique names.  That said, the model names are a combination of "id" + "name".  Using a .bot file or a recipe file that looks like:

  {
      "type": "luis",
      "id": "31",
      "name": "cafeDispatchModel"
    },
    {
      "type": "luis",
      "id": "86",
      "name": "cafeBotBookTableTurnN"
    },
the models for Dispatch would be named "31_ cafeDispatchModel" and "86_ cafeBotBookTableTurnN" respectfully.  To make the prefix more user friendly, you could change the "id" attributes to be something more readable, e.g.
"id": "Booking"

"Booking_cafeBotBookTableTurnN"

**Comment by lauren-mills** [comment]
In practice, it uses the "name" field from the .luis file as the name of the LUIS model instead of prepending the id. This name is automated to the same name as the .lu file it is based on.

![image](https://user-images.githubusercontent.com/27976702/50017492-d42f2380-ff91-11e8-981c-fd7f902b91f6.png)

Even if it did prepend the id, that would not ensure that the name would be unique, since the same bot.recipe file is being used for each deployment. In our case we would get something like "general_General" which would still not be helpful.

I think I can find a workaround for our deployments, but this could still be an issue for customers in the future if they try to deploy more than one bot using the Enterprise Template for instance.
