### ISSUE TITLE
Name: Azure CLI's Bot Extension fails in publishing SDK V4 Bot

### ISSUE THREAD

**Issue by JasonXuMSCSS** [Microsoft/botbuilder-tools#861]
## Tool
Name: Azure CLI's Bot Extension fails in publishing SDK V4 Bot
Version: 
{
  "extensionType": "whl",
  "name": "botservice",
  "version": "0.4.3"
}
OS: Client ran this command is Windows 2012 R2 server.

## Describe the bug
followed the doc at : https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0#deploy-to-azure

But that command in the doc above gave us error:

PS C:\Tools\MyProjects\JasonBotV4Test> az bot publish -g JasonBotV4Test -n JasonBotV4Test --proj-file BasicBot.csproj --sdk-version v4
az: error: unrecognized arguments: --proj-file BasicBot.csproj --sdk-version v4

## To Reproduce
1. Install the latest version of the Azure cli tool.
2. az extension add -n botservice
3. az login
4. PS C:\Tools\MyProjects\JasonBotV4Test> az bot publish -g JasonBotV4Test -n JasonBotV4Test --proj-file BasicBot.csproj --sdk-version v4

## Expected behavior
Publish should be successful

[bug]
The command above returned error below:
az: error: unrecognized arguments: --proj-file BasicBot.csproj --sdk-version v4

**Comment by stevengum** [comment]
@JasonXuMSCSS have you tried using `--proj-name` and `--version`?

**Comment by JasonXuMSCSS** [comment]
Thanks –version worked. It also requires --resource-group too.

az bot publish -g JasonBotV4Test --resource-group ASPNetCoreJasonTestRG -n JasonBotV4Test --proj-file BasicBot.csproj --version v4

The document at https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-enterprise-template-deployment?view=azure-bot-service-4.0#deploy-to-azure is wrong then.

Thanks,
Jason

**Comment by sgellock** [comment]
az cli version 2.0.54 or above addresses this issue, as the extension is no longer a requirement
