### ISSUE TITLE
Running msbot clone services results in "You need to upgrade your AZ CLI version to >= 2.0.52." but my version already is 2.0.52

### ISSUE THREAD

**Issue by damadei** [Microsoft/botbuilder-tools#863]
## Tool
Name: MsBot
Version: 4.3.0
OS: Windows 10

## Describe the bug
Running the following command   

msbot clone services --name "NlpWithDispatch" --luisAuthoringKey "<Authoring key>" --folder "DeploymentScripts/MsbotClone" --location "westus" --appId "<app id>" --appSecret "<appSecret>"

Always results in 
        You need to upgrade your AZ CLI version to >= 2.0.52.
        You can install the latest AZ CLI from https://aka.ms/az-cli-download

However my Azure CLI is already 2.0.52

az --version
azure-cli (2.0.52)

acr (2.1.10)
acs (2.3.12)
advisor (2.0.0)
ams (0.3.1)
appservice (0.2.8)
backup (1.2.1)
batch (3.4.1)
batchai (0.4.5)
billing (0.2.0)
botservice (0.1.2)

## To Reproduce
1. Just run the command

[bug]

**Comment by damadei** [comment]
> Hi @damadei, can you try the daily build ([4.3.2-125](https://botbuilder.myget.org/feed/botbuilder-tools-daily/package/npm/msbot/4.3.2-125)) which can be found on MyGet?
> 
> To download it, you'll first need to change your npm registry to point to our MyGet gallery via this command
> 
> ```shell
> npm config set registry https://botbuilder.myget.org/F/botbuilder-tools-daily/npm/
> ```
> 
> Then install msbot via `npm i msbot` for a local install or `npm i -g msbot`. To reset your registry back to npmjs.org, you'll need to use the following command
> 
> ```shell
> npm config set registry https://registry.npmjs.org/
> ```

Hi @stevengum,

It worked with 4.3.2-129 and using Azure CLI 2.0.54

Thanks,
Daniel

**Comment by stevengum** [comment]
Closing as this has been addressed with the latest public release of msbot, version [**4.3.2**](https://www.npmjs.com/package/msbot/v/4.3.2). This version of msbot does not use the botservice extension, so you are not required to call az extension add -n botservice. 

If you still run into this issue, please **@mention** me in this issue or open up a new issue.
