### ISSUE TITLE
LUIS: clone version using LUIS CLI gives error

### ISSUE THREAD

**Issue by tmsteem82dev** [Microsoft/botbuilder-tools#882]
## Tool
Name: LUIS
Version: 2.2.0
OS: Windows 10

## Describe the bug
The luis clone command appears to be broken. I get an error `versionCloneObject cannot be null or undefined.` trying to calls `luis clone version...`. see steps to reproduce.

## To Reproduce
1. Have a luis app on luis.ai
2. Have a model version named 0.t
3. Have a .luisrc file containing relevant information (appId, authoringKey, region)
4. Call the following command: `luis clone version --versionId 0.t --newVersionId 0.2`

The following error will be displayed
```
versionCloneObject cannot be null or undefined.

LUIS Command Line Interface - © 2018 Microsoft Corporation

Creates a new version using the current snapshot of the selected application version.

Usage:
luis clone version --appId <string> --versionId <string> --newVersionId <string>
```

Note: The `appId` should be unecessary since it is supplied in my `.luisrc` file.

## Expected behavior
I expect the 0.t version to be cloned and a 0.2 version to appear in my LUIS portal.

[bug]

**Comment by CoHealer** [comment]
removing support as triage'd for 4.3

**Comment by stevengum** [comment]
Spoke with @dmvtech today, and I _think_ I got him unblocked. He's going to manually test and then do a PR for the code-fix with a recorded test.
