### ISSUE TITLE
msbot clone services failed with period in bot name with no explanation

### ISSUE THREAD

**Issue by garypretty** [Microsoft/botbuilder-tools#887]
## Tool
Name: msbot
Version: 4.3.2
OS: Windows 10

## Describe the bug
When calling msbot clone services with a name that contains full stops / periods, the command fails after some time, but without a helpful error message.  This will fail for certain services that do not allow periods in the name, such as storage.

When the command eventually fails the error message is "ERROR: At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.".

## To Reproduce
Use msbot clone services with a name with full stops. e.g.

msbot clone services --name "My.Customer.Bot" --luisAuthoringKey "XXXXX" --folder "DeploymentScripts\en" --location "westeurope"

## Expected behavior
It would be helpful if the bot name is checked for potentially problematic chars before executing and prompting the user to alter the name - or try to automatically strip out the illegal chars for services where they are not allowed.  I would imagine the former would be the simplest approach.

## Additional context

[bug]

**Comment by stevengum** [comment]
We're going to strip the periods in `az bot create` and log a warning to the user indicating the name change. Unfortunately for us the testing framework for Azure CLI doesn't support mid-command prompts, so this is our best testable option at this time.

**Comment by stevengum** [comment]
Closing via Azure/Azure-cli#8384
