### ISSUE TITLE
Msbot connect luis --region should be required --> KeyNotFoundException

### ISSUE THREAD

**Issue by luiscantero** [Microsoft/botbuilder-tools#888]
## Tool
Name: Msbot

## Describe the problem
When using msbot to add a LUIS connection, not specifying the --region argument defaults it to "westus". If the model is on eu.luis.ai a KeyNotFoundException is thrown, which is not very helpful.

## Describe the solution you'd like
--region should be required and ideally (this is for another team), the error should be more helpful.

[enhancement]

**Comment by stevengum** [comment]
Unfortunately we cannot change the behavior without it being a breaking change. I agree that this is not great behavior on the part of the CLI and SDK, but in regards to the SDK that information (the invalid key for the region) is all that's returned from LUIS when the error is thrown.

 We are currently evaluating moving towards a more developer-familiar runtime configuration system so it is very likely in the future that this problem will taken care of.

Closing issue as won't fix.
