### ISSUE TITLE
Not Able to Update Bot Tags using AZ cli

### ISSUE THREAD

**Issue by nitinpokharna** [Microsoft/botbuilder-tools#889]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Version: *tool version*
OS: *os version*

## To Reproduce
1. ...
2. ...
3. ...
4. ...

## Additional context

[bug]

**Comment by stevengum** [comment]
@nitinpokharna can you provide the commands you used to try and update the bot tags?

**Comment by stevengum** [comment]
Currently investigating, I've reached out to the Azure CLI team for assistance.

**Comment by gabog** [comment]
This is tentativelly fixed and we are testing it today.

**Comment by stevengum** [comment]
Closing as bugbash was successful and the PR with the fix has been approved.

https://github.com/Azure/azure-cli/pull/9152
