### ISSUE TITLE
TypeScript Error 2345: Argument of Type TurnContext is not assignable to paramater of type TurnContext

### ISSUE THREAD

**Issue by AskYous** [Microsoft/botbuilder-tools#890]
## Tool
Name: Msbot
Version: 4.1.5
OS: Windows 10

## Describe the bug
I hope I'm submitting this in the right place. While creating a bot in TypeScript, I receive multiple TypeScript errors saying:

> Argument of type 'import("c:/Users/to_ys/Documents/my-project/node_modules/botbuilder-core/lib/botStatePropertyAccessor").StatePropertyAccessor<import("c:/Users/to_ys/Documents/my-project/node_modules/botbuilder-dialogs/lib/dialogContext").DialogState>' is not assignable to parameter of type 'import("c:/Users/to_ys/Documents/my-project/node_modules/botbuilder-ai/node_modules/botbuilder-core/lib/botStatePropertyAccessor").StatePropertyAccessor<import("c:/Users/to_ys/Documents/my-project/node_modules/botbuilder-dialogs/lib/dialogContext").DialogState>'.

>   Types of property 'delete' are incompatible.
>     Type '(context: import("c:/Users/to_ys/Documents/my-project/node_modules/botbuilder-core/lib/turnContext").TurnContext) => Promise<void>' is not assignable to type '(context: import("c:/Users/to_ys/Documents/my-project/node_modules/botbuilder-ai/node_modules/botbuilder-core/lib/turnContext").TurnContext) => Promise<void>'.
>       Types of parameters 'context' and 'context' are incompatible.
>         Type 'import("c:/Users/to_ys/Documents/my-project/node_modules/botbuilder-ai/node_modules/botbuilder-core/lib/turnContext").TurnContext' is not assignable to type 'import("c:/Users/to_ys/Documents/my-project/node_modules/botbuilder-core/lib/turnContext").TurnContext'.
>           Types have separate declarations of a private property '_adapter'.

## To Reproduce
1. Create a TS function that accepts a waterfall step context as the argument
2. Define its type using TS (`private someFunction(step: WaterfallStepContext) { ... }`)
3. Pass that argument's context to a commandState's get function (`this.commandState.get(step.context);`)
4. Experience TS complaining that it's not the correct type

## Expected behavior
TypeScript to not complain.

## Screenshots
![image](https://user-images.githubusercontent.com/791996/50699234-2812b280-0ffc-11e9-8119-f91be3b376be.png)

## Additional context

[bug]

**Comment by tdurnford** [comment]
It looks like you have a `node_modules` directory nested inside of the `botbuilder-ai` package. Typically the compiler looks for dependencies in each of the package's directories and then works its way up. With your current dependency structure, the `botbuilder-ai` package is referencing the `botbuilder-core` dependency in its `node_modules` directory while the rest of the project is referencing the  `botbuilder-core` in the top level `node_modules` directory. Consequently, the compiler views the `TurnContext` in the `botbuilder-core`  and the `botbuilder-ai` as different object types. Try flattening your dependencies and see if that fixes your issue. 

Hope that helps!

**Comment by AskYous** [comment]
That makes sense. Thanks @tdurnford . Unfortunately, I ran `npm dedupe` and I still received the same error.

**Comment by stevengum** [comment]
Can you post your `"dependencies"` in the package.json?

**Comment by AskYous** [comment]
"dependencies": {
        "@microsoft/microsoft-graph-client": "^1.3.0",
        "botbuilder": "^4.1.5",
        "botbuilder-ai": "^4.2.0",
        "botbuilder-azure": "^4.1.5",
        "botbuilder-dialogs": "^4.2.0",
        "botframework-config": "^4.1.5",
        "dotenv": "^6.1.0",
        "restify": "^7.2.2"
    },
    "devDependencies": {
        "@types/node": "^10.12.18",
        "eslint": "^5.10.0",
        "eslint-config-standard": "^12.0.0",
        "eslint-plugin-import": "^2.14.0",
        "eslint-plugin-node": "^8.0.0",
        "eslint-plugin-promise": "^4.0.1",
        "eslint-plugin-standard": "^4.0.0",
        "nodemon": "^1.18.8"
    }

**Comment by stevengum** [comment]
Try updating your dependencies to `"~4.2.0"` for the botbuilder/botframework packages. There were a couple of breaking changes between 4.1.0 and 4.2.0. From 4.2.0 forward we use `~` instead of `^` to lock packages to patch versions, not minor.

**Comment by AskYous** [comment]
Wow! I changed all the packages to ~4.2.0 and the errors went away! Thank you! But I have 1 problem left that I'm not sure if it's related. Is this something similar?

![image](https://user-images.githubusercontent.com/791996/50799830-98d2fc80-1292-11e9-84f1-759c30ccc033.png)

**Comment by stevengum** [comment]
Can you try casting the `context.adapter` to a `BotFrameworkAdapter`? I believe the following lines should work:

```ts
import { BotFrameworkAdapter } from 'botbuilder'; // Or add it to your preexisting import

await (context.adapter as BotFrameworkAdapter).signOutUser(context, CONNECTION_SETTINGS_NAME);
```

This isn't similar to the above fix regarding the versions, it's rather that `TurnContext.adapter` is a getter for the type `BotAdapter`, so casting it should fix the issue. ([BotFrameworkAdapter extends BotAdapter](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder/src/botFrameworkAdapter.ts#L108))

**Comment by drub0y** [comment]
The `adapter` property off of a `TurnContext` instance is of type `BotAdapter` and `signOutUser` is an API specific to `BotFrameworkAdapter` so you'd need to downcast to be able to access that more specific adapter implementation's API.

**Comment by AskYous** [comment]
That solved it thanks.

**Comment by Akhila9** [comment]
Argument of type 'import("C:/Users/Downloads/BotFramework-WeChat-master-new/BotFramework-WeChat-master/libraries/typescript/Microsoft.Bot.Builder.Adapters.WeChat/node_modules/botbuilder-core/lib/turnContext").TurnContext' is not assignable to parameter of type 'import("C:/Users/Downloads/BotFramework-WeChat-master-new/BotFramework-WeChat-master/samples/typescript/Microsoft.Bot.Builder.Adapters.WeChat.TestBot/node_modules/botbuilder-core/lib/turnContext").TurnContext'.
  Types have separate declarations of a private property '_adapter'.

Can you please help to resolve this.
