### ISSUE TITLE
msbot clone services doesn't update botFileSecret in app settings when appId and appSecrets are passed on CLI

### ISSUE THREAD

**Issue by hailiu2586** [Microsoft/botbuilder-tools#891]
## Tool
Name: Msbot
Version: msbot@4.3.2
OS: Win10

## Describe the bug
when using msbot clone service to create an Azure Bot  Service, if I pass in the appId and appSecret on the CLI, then the newly generated botFileSecret is outputed to the stdout, but not updated to the web app's appsettings

## To Reproduce

```
msbot clone services -n devondemo-5 --luisAuthoringKey {key} --location westus --folder ./deploymentScripts/msbotClone --subscriptionId {subId} --force --groupName {groupName} --sdkLanguage Node --appId {appId} --appSecret {appSecret}
```

**Comment by stevengum** [comment]
@hailiu2586 I tried to repro and compared the output secret from the CLI and the botFileSecret entry in Azure, but everything looks to be in order, and the bot works as expected. 

#### CLI output secret:
![cli-output](https://user-images.githubusercontent.com/14935595/51210274-3350c280-18c7-11e9-89eb-3295908b79a7.jpg)

#### Blade settings:
![blade-settings](https://user-images.githubusercontent.com/14935595/51210284-38157680-18c7-11e9-8a79-91a4a23e0eca.jpg)

Was the diff located in some other step of the `msbot clone services` process?

___

**Comment by stevengum** [comment]
Closing as a no repro on my end. If you run into the issue again please reopen the issue and post the output from your CLI.
