### ISSUE TITLE
Chatdown: Wouldn't that be great to allow conversation playback like botsociety?

### ISSUE THREAD

**Issue by dawwa** [Microsoft/botbuilder-tools#900]
## Tool
Name: Chatdown/Bot Emulator
I was assuming an animated playback is allowed after open the transcript with Emulator, but it turns to be just static view.

I wish Chatdown would work with Emulator team to animate the conversation rather than static view.
Some playback like the https://botsociety.io would be nice. Thoughts?

**Comment by mdrichardson** [comment]
Thank you for your interest in the Bot Framework Emulator. All emulator feature requests go in the the [Botframework Emulator Repo](https://github.com/Microsoft/BotFramework-Emulator/issues).
