### ISSUE TITLE
Inconsistent ordering of exported patterns

### ISSUE THREAD

**Issue by joetossell29** [Microsoft/botbuilder-tools#901]
## Tool
Name: [LUIS]
Version: 2.0.13
OS: Windows 10

## Describe the bug
Patterns associated with an entity are exported in a random ordered making source control of patterns difficult

## To Reproduce
1. Create a bot using the template in azure
2. Export the default language model
3. Note the order of the patterns in the luis file associated with the greetings intent
4. Export again and compare files
```
luis export version --versionId 0.1 --stdin | Out-File DeploymentScripts/en/luis-general.luis
```

## Expected behavior
Consistent ordering of patterns when exported using LUIS

[bug]

**Comment by ahmedaashour** [comment]
This is not a LUIS issue. A single LUIS app will keep the same ordering of exported patterns no matter how many times the user exports it. However, if the user re-imports the same app and re-exports it, the order of the exported patterns of the new app is not guaranteed to match that of the old app. 
Adding logic to order the patterns and pattern entities by name in the exported app.
