### ISSUE TITLE
[MSBOT] Clone services documentation outdated

### ISSUE THREAD

**Issue by dfavretto** [Microsoft/botbuilder-tools#906]
## Tool
Name: [Msbot]
Version: \-
OS: \-

## Describe the bug
The documentation for using `MSBOT` is outdated, there's no description on how to use the parameters `code-dir` or `proj-file`

## To Reproduce
1. Go to [msbot clone services' documentation](https://github.com/Microsoft/botbuilder-tools/blob/master/packages/MSBot/docs/export-clone.md#cloning-services)
1. Look for the explanation on the said parameters

## Expected behavior
The documentation should be updated with the explanation on how the new parameters work and when to use them.

[bug]

**Comment by Kaiqb** [comment]
Fix is in this [PR](https://github.com/Microsoft/botbuilder-tools/pull/916).
