### ISSUE TITLE
Failure in tsc build script

### ISSUE THREAD

**Issue by patlewis-MSFT** [Microsoft/botbuilder-tools#911]
## Tool
Name: Msbot
Version: Downloaded Jan 22, 2019
OS: Windows 10 : Build 1809 17763.253

## Describe the bug
Failure when running npm run build

## To Reproduce
1. Copied the botbuilder-tools locally and change to the root of the folder
2. npm install -g chatdown msbot ludown luis-apis qnamaker botdispatch luisgen
3. npm install
4. npm run build

## Expected behavior
Following the readme.md file step by step and encountered the error.

## Screenshots
lerna ERR! npm run build exited 1 in 'msbot'
lerna ERR! npm run build stdout:

> msbot@4.3.2 build C:\Development\botbuilder-tools-master\packages\MSBot
> tsc

src/msbot-connect-dispatch.ts(122,44): error TS2345: Argument of type '{ name: string; appId: string; authoringKey: string; subscriptionKey: string; version: string; region: string; serviceIds: string[]; }' is not assignable to parameter of type 'IDispatchService'.
  Property 'getEndpoint' is missing in type '{ name: string; appId: string; authoringKey: string; subscriptionKey: string; version: string; region: string; serviceIds: string[]; }' but required in type 'IDispatchService'.
src/msbot-connect-dispatch.ts(149,5): error TS2411: Property 'getEndpoint' of type '() => string' is not assignable to string index type 'string | boolean | string[] | IConnectedService[] | undefined'.
src/msbot-connect-luis.ts(108,53): error TS2345: Argument of type '{ name: string; appId: string; version: string; authoringKey: string; subscriptionKey: string; region: string; }' is not assignable to parameter of type 'ILuisService'.
  Property 'getEndpoint' is missing in type '{ name: string; appId: string; version: string; authoringKey: string; subscriptionKey: string; region: string; }' but required in type 'ILuisService'.

## Additional context

[bug]

See the following npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\ProgramData\\Microsoft\\VisualStudio\\MDA\\0d22feab\\taco-toolset-6.3.1\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.15.10
3 info using node@v11.7.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild msbot@4.3.2
6 info build msbot@4.3.2
7 verbose unsafe-perm in lifecycle true
8 info msbot@4.3.2 Failed to exec build script
9 verbose stack Error: msbot@4.3.2 build: `tsc`
9 verbose stack Exit status 2
9 verbose stack     at EventEmitter.<anonymous> (C:\ProgramData\Microsoft\VisualStudio\MDA\0d22feab\taco-toolset-6.3.1\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at EventEmitter.emit (events.js:188:13)
9 verbose stack     at ChildProcess.<anonymous> (C:\ProgramData\Microsoft\VisualStudio\MDA\0d22feab\taco-toolset-6.3.1\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:188:13)
9 verbose stack     at maybeClose (internal/child_process.js:978:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
10 verbose pkgid msbot@4.3.2
11 verbose cwd C:\Development\botbuilder-tools-master\packages\MSBot
12 error Windows_NT 10.0.17763
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\Microsoft\\VisualStudio\\MDA\\0d22feab\\taco-toolset-6.3.1\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v11.7.0
15 error npm  v2.15.10
16 error code ELIFECYCLE
17 error msbot@4.3.2 build: `tsc`
17 error Exit status 2
18 error Failed at the msbot@4.3.2 build script 'tsc'.
18 error This is most likely a problem with the msbot package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     tsc
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs msbot
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls msbot
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by tsuwandy** [comment]
Error is actually coming from msbot.

src/msbot-connect-dispatch.ts(122,44

**Comment by sgellock** [comment]
@patlewis-MSFT are you trying to clone and build the repo?  if so, you'll need to make sure you have TypeScript installed, and you'll also need .NET Core SDK installed.

@mdrichardson if this is the case, the a PR to update https://github.com/Microsoft/botbuilder-tools/blob/master/README.md to include the full list of dependencies would be awesome.

**Comment by mdrichardson** [comment]
@sgellock 	On it. Pat hasn't responded in awhile, but I can update the dependencies, regardless.

**Comment by patlewis-MSFT** [comment]
I’ll send update later today after I test.

**Comment by mdrichardson** [comment]
I was able to successfully build. I even uninstalled *all* of my global npm packages.

@patlewis-MSFT 	Maybe there's been a change in the `botbuilder-tools` repo that makes this work. Additionally, you may need to update your npm packages. Use:

`npm install -g npm lerna chatdown msbot ludown luis-apis qnamaker botdispatch`

Success screenshot:

![image](https://user-images.githubusercontent.com/40401643/52664363-b1e85200-2ebd-11e9-8c1d-4cee0eb35c9e.png)

**Comment by patlewis-MSFT** [comment]
I completely uninstalled node.js, visual studio, npm, etc. After reinstalling everything appears to work now. tThanks!

**Comment by mdrichardson** [comment]
Weird. Glad it works, though!
