### ISSUE TITLE
create/refresh should not fail when LUIS intent has no utterance (only use pattern)

### ISSUE THREAD

**Issue by tsuwandy** [Microsoft/botbuilder-tools#913]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]
Version: *tool version*
OS: *os version*

## To Reproduce
1. ...
2. ...
3. ...
4. ...

## Additional context

[bug]

**Comment by sgellock** [comment]
@cahann triage as you see fit

**Comment by tsuwandy** [comment]
Fix is ready.  BMW folks are not blocked so will wait to batch this up with other fixes.
