### ISSUE TITLE
`msbot clone services` verbose need to be more verbose

### ISSUE THREAD

**Issue by mydiemho** [Microsoft/botbuilder-tools#920]
## Tool
Name: Msbot

## Describe the problem
When I run `msbot clone services` with verbose flag, it is not clear to me whether the command is still running or hanged.

## Describe the solution you'd like
constant feedback to user that process is running, something like `...` every 5 seconds to show it's running.

## Additional context

[enhancement]

**Comment by sgellock** [comment]
We have some enhancements coming to our CLI tooling in our upcoming 4.3 release which I believe will address your concerns.
