### ISSUE TITLE
msbot "clone" command should be renamed to msbot "new" as cloning seems like a publish operation rather than new

### ISSUE THREAD

**Issue by sanjeevdwivedi** [Microsoft/botbuilder-tools#921]
## Tool
Name: [Msbot|Ludown|LUIS|QnAMaker|Chatdown|Dispatch|LuisGen]

## Describe the problem
the command msbot clone ... creates a new deployment but the word "clone" is confusing. It should instead be called msbot "new" to make it explicit.

## Additional context

[enhancement]

**Comment by sgellock** [comment]
@sanjeevdwivedi thank you for the feedback and suggestion for a clarifying name for the action.  We agree.  We will be rolling out updates to our command line tools over the 4.3 and 4.4 releases.  It's our expectation that these updates will clarify the confusion you've highlighted.
