### ISSUE TITLE
Please update docs/export-clone.md with explicit details on what will be executed.

### ISSUE THREAD

**Issue by hattan** [Microsoft/botbuilder-tools#923]
## Tool
msbot

## Describe the problem
The readme docs for clone services does not describe in detail which az commands will be executed. 

## Describe the solution you'd like
Please update the file docs/export-clone.md to list out all the steps and az commands that will be executed as part of clone services.

## Describe alternatives you've considered
The msbot tool would list out all the commands it will execute in the confirmation step before starting the process.

[enhancement]

**Comment by sgellock** [comment]
@Kaiqb let's make sure the new CLI changes we will be releasing in 4.3 address this issue.

**Comment by yochay** [comment]
@hattan if you use the --verbose flag on msbot clone services, it prints our all AZ CLI command that take place during the clone process.

**Comment by hattan** [comment]
@yochay - thanks, I was more interested in knowing what it will do before I run the az cli command. Via the docs/readme.  With --verbose will the cli print out statements and confirm before starting? or simply list the commands as they are executing.

Even if no changes were made to cli, simply listing the steps in the docs would be useful to know what clone services actually does without running it.

**Comment by sgellock** [comment]
--verbose does not cause prompt validation before every command.  It simply outputs every command it’s executing.

**Comment by hattan** [comment]
Thanks @sgellock . That's what I had assumed. 

The thinking behind this issue is to document which az cli commands will be executed so when researching msbot clone services. This way users would have a clear understanding of what resources it will created for them.

**Comment by sgellock** [comment]
That’s good feedback.  Our intention is to provide the Az CLI commands as part of our 4.3 and 4.4 work.  You should start to see us using Az CLI commands as our main recommendation for CLI interactions for things msbot clone services has done for us in the past

**Comment by Kaiqb** [comment]
We are moving away  from the msbot clone command. Updates to the deployment scenario will either use  az cli specific command or ARM templates. As these updates are made to the tooling, the docs will be updated.
