### ISSUE TITLE
[Ludown] Using a list entity in an utterance is not documented

### ISSUE THREAD

**Issue by dkisselev** [Microsoft/botbuilder-tools#929]
## Tool
Name: Ludown

## Describe the problem
The ludown file format documentation (https://github.com/Microsoft/botbuilder-tools/blob/master/packages/Ludown/docs/lu-file-format.md) does not demonstrate how List entities should be included in Utterances.

The correct format is to write an utterance that just uses one of the list entries directly in plain text (no curly braces or other syntax:
```
# Bands
- Show all rock bands

$genre:Rock=
 - Rock

$genre:Electronic=
 - Electronic
```

However, this is not explicitly documented. As a user, I was trying utterances such as:
```
- Show all {genre=Rock} bands
- Show all {genre} bands
```

## Describe the solution you'd like
Please expand the Lists documentation to show some usage examples and explicitly state that developers should include a value from the list directly in the utterance, not an entity label or any other value.

## Additional context
One example is in an example ludown file: https://github.com/Microsoft/botbuilder-tools/blob/master/packages/Ludown/examples/9.lu#L40

[enhancement]

**Comment by Kaiqb** [comment]
Add info in the file format document. PR is [here](https://github.com/Microsoft/botbuilder-tools/pull/957).
