### ISSUE TITLE
LuisGen NuGet package failing install

### ISSUE THREAD

**Issue by jackiebecker** [Microsoft/botbuilder-tools#930]
## Tool
Name: LuisGen
Version: 2.0.2
OS: Windows 10 Ent., Version 1809, Build 17763.253

## Describe the bug
When installing LuisGen as nuget package, received this error in PM console: 
```
NU1202: Package LUISGen 2.0.2 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package LUISGen 2.0.2 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
NU1212: Invalid project-package combination for LUISGen 2.0.2. DotnetToolReference project style can only contain references of the DotnetTool type 
Package 'LUISGen 2.0.2' has a package type 'DotnetTool' that is not supported by project '<MY PROJECT>'
```
Where <MY PROJECT> is of course replaced with the name of my project. Working on latest Visual Studio build (VS 2017, build 15.9.6). 

## Expected behavior
Correct installation of LuisGen NuGet package in project of type netcoreapp2.1

[bug]

**Comment by jackiebecker** [comment]
**Update:**  was able to successfully install from the command line; learned that I was unable to install in project from package console because LuisGen is a tool, not library.

**Ask:** would have been helpful to have an error message indicating this. The error message 

`Package LUISGen 2.0.2 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Package LUISGen 2.0.2 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any`

made me run down a rabbit hole of checking dotnet versions that was not relevant to the solution. Knowing the solution, I see that the third error message indicates the problem--however, the other two were red herrings. An error message simply saying: 

`Package 'LUISGen 2.0.2' has a package type 'DotnetTool' that can not be installed into project '<MY PROJECT> as it is not a library: DotnetTool types must be installed at the command line using 'dotnet tool install'.`

would have made the solution instantly obvious.

**Comment by tsuwandy** [comment]
Unfortunately, we can't control the first error message.  The package is marked as 'DotnetTool' and thus it won't allow it to be installed via package manager console.
