### ISSUE TITLE
MSBot fails to Encrypt (missing --id parameter)

### ISSUE THREAD

**Issue by cleemullins** [Microsoft/botbuilder-tools#934]
## Tool
MSBot version 4.3.2-151
dotnet version 4.2.100

## Describe the bug
At the end of a clone operation for a C# project, MSBot errors out with encryption failure(s). 

```
NOTE: This secret is not recoverable and you should save it in a safe place according to best security practices.
      Copy this secret and use it to open the zbot.bot the first time.
Updating appsettings.json with botFilePath=zbot.bot
Saving the botFileSecret with dotnet user-secrets
dotnet user-secrets set botFileSecret [Kilroy's secret was here]
Command failed: dotnet user-secrets set botFileSecret [Kilroy's secret was here] Could not find the global property 'UserSecretsId' in MSBuild project 'C:\Users\chris\source\repos\ZBot\ZBot.csproj'. Ensure this property is set in the project or use the '--id' command line option.
Usage: msbot clone services [options]
```

The "--id" parameter should be used, but was not specified. 
`Ensure this property is set in the project or use the '--id' command line option.`

The alternative, is adding this element to the .csproj file:
```
<PropertyGroup>
    <UserSecretsId>USER_SECRETS_GUID</UserSecretsId>
</PropertyGroup>
```
... but doing that would require creating a new GUID as well. 

Better to let the tool do the work.

**Comment by tomlm** [comment]
The code already detects this condition and adds the UserSecretsId.  I was not able to repo this
