### ISSUE TITLE
Unable to run dispatch refresh against multiple bot files from same directory

### ISSUE THREAD

**Issue by jcoenen** [Microsoft/botbuilder-tools#938]
## Tool
Name: Dispatch
Version: *1.2.2*
OS: *Windows 10 Version 1803 (Build 17314.472*

## Describe the bug
If I run a dispatch refresh command against a bot file everything works great.   If I from that same directory call a dispatch refresh against a different bot file the dispatch model does not get updated.   I believe the reason for this is the first run creates some files (data folder, summary.html, json file and a dispatch file).   When you run it a second time it does not create a new dispatch file and I believe uses the dispatch file from the previous (1st run) as its connection for importing, training, and publishing the dispatch file at the end of the operation.   So it will do the export process against the correct bot file, but then when it does the import process it uses the existing dispatch file which was for a previous run.

## To Reproduce

1.   Have two different bot files connecting to two different environments in a folder (C:\DispatchError).
2.  Run this command  dispatch refresh --bot C:\DispatchError\Botfile1.bot --secret BOTFIle1_SECRET
3.  Don't remove any of the files or folders that were created in that directory
3.  Run this command dispatch refresh --bot C:\DispatchError\Botfile2.bot --secret BOTFILE2_SECRET
4.  Notice that the dispatch in BotFile2 doesnt get updated and that when the command was running it looked something like this

> Exporting services for dispatch...
> Exporting **BOT2_General** LUIS application...
> Exporting FAQ QnA kb...
> Exporting ChitChat QnA kb...
> Creating dispatch LUIS model json...
> Creating training data...
> Updating **BOT1_Dispatch** model...
> Importing **BOT1_Dispatch** model...
> Training **BOT1_Dispatch** model...

## Expected behavior
I would expect that when I ran the refresh command for Bot2 that it would update the dispatch in the Bot2.bot file.

## Additional context

[bug]

**Comment by tsuwandy** [comment]
update published to npmjs.org.
