### ISSUE TITLE
Exclude LUIS / QnA models when calling Dispatch create / update with bot file

### ISSUE THREAD

**Issue by garypretty** [microsoft/botbuilder-tools#944]
## Tool
Dispatch

## Describe the problem
It would be good to be able to specifically exclude or include LUIS / QnA apps when using 'dispatch create' or 'dispatch refresh' pointing to a bot file.  I have an extra LUIS model which I am going to require within my bot, but not one that should be evaluated at the top level when an activity comes in.

## Describe the solution you'd like
Additional parameters to exclude LUIS / QnA models within a bot file by Id.

## Describe alternatives you've considered
I am assuming I can use the 'dispatch remove' command after I have ran the command to create / refresh my file, but this feels like an unnecessary step.  Happy to be told there is already a way of doing this that I am missing :)

[enhancement]

**Comment by tsuwandy** [comment]
We need to add a flag to the ConnectedService item to specify whether or not a bot service will participate in Dispatch.

**Comment by tsuwandy** [comment]
@garypretty, closing this as bot file/msbot is deprecated and we are working on the next gen dispatch solution.  "dispatch remove" would be the right mitigation. :-)
