### ISSUE TITLE
msbot clone services with a sample results in 2 .bot files

### ISSUE THREAD

**Issue by navzam** [Microsoft/botbuilder-tools#945]
## Tool
Name: Msbot
Version: 4.3.2
OS: Windows 10

## Describe the bug
According to [this doc for deploying sample bots](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-samples?view=azure-bot-service-4.0&tabs=js#deploy-javascript-and-c-bots-using-az-cli), the `--name` parameter can be the same name as your local bot. But if you have an existing bot and you use the same name, `msbot` gives this error:

```
echobot.bot already exists. Please choose a different name or delete echobot.bot and try again.
```

If you use a different name, the command runs but creates a second .bot file with the new name. Now you have two .bot files which is confusing.

## To Reproduce
1. Download the [02.a.echobot](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/02.a.echobot) sample
2. Follow the documentation for [deploying a sample bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-samples?view=azure-bot-service-4.0&tabs=js#deploy-javascript-and-c-bots-using-az-cli). When running `msbot clone services`, use `--name "echobot"`
3. Error!
4. Run `msbot clone services` again but with a different name
5. Two .bot files!

## Expected behavior
I expect to be able to use my existing .bot file instead of ending up with two separate ones.

[bug]

**Comment by sgellock** [comment]
We agree, though we won't fix this.  we will be investing in ARM templates and Az CLI as our recommended approach to provisioning and deployment
