### ISSUE TITLE
Azure deployments unreliable

### ISSUE THREAD

**Issue by ikivanc** [Microsoft/botbuilder-tools#946]
Multiple times while trying to deploy a Bot Registration, App Service, or Web App Bot in Azure I ran in to "failed to get deployment status" resulting in an incomplete deployment of resources, or times when deployment would seemingly complete but not everything would be there.

**Comment by sgellock** [comment]
@ikivanc, what command line tool(s) are you running that exhibit this behavior?  are you running `msbot clone services` or are you running `az bot create`?  In either case, we are working on a couple of things that will help hear.  First off, we will be moving to using ARM templates to provision resources.  This will give us transactional support (no partial deployments).  Secondly, we have started to make additional investments in our az bot CLI tooling.  Our focus on using Az CLI as our tool chain of choice will allow us to provide detailed commands such that it becomes more clear what is required to provision and deploy, and it will also allow us to focus on making this portion of our CLI offering more robust.
