### ISSUE TITLE
ChatDown [Typing] not recognized when compiling .transcript

### ISSUE THREAD

**Issue by matthewshim-ms** [Microsoft/botbuilder-tools#95]
When attempting to compile .transcript file from BookTable-happyPath.chat in the Chatdown/Examples folder, CLI outputs this error: 

**skipping unknown tag [Typing]**

Similarly produces the same error when manually trying to use the [Typing] tag elsewhere.

**Comment by vishwacsena** [comment]
Fixed in latest update
