### ISSUE TITLE
Tool fails to convert to Luis model when using colons in entities

### ISSUE THREAD

**Issue by pawett** [Microsoft/botbuilder-tools#950]
## Tool
Name: LUDown
Version: *1.1.0*
OS: *Windows 10*

## Describe the bug
It is not possible to use colons as part of the Entity name or value since this character is used in the definition of the markdown to separate the type/value. It seems that the tool is not able to separate correctly the values for the entity and therefore they are not recovered.

## To Reproduce
1. ... Use colon(:) to define an entity ($Country:Office:Argentina:Córdoba)
2. ... Use the tool to convert to json
3. ... Definition for the entity does not appear in the json file

## Expected behavior
This perhaps might not  be considered as a bug, but in that case should be a reference in the documentation to the reserved characters that can't be used in the entities definitions. 
Other option is to use a diferent character to separate the entity name from the entity value in the .lu file definition.

[bug]

**Comment by omarsourour** [comment]
@pawett Since changing the syntax is a breaking change, we want to avoid that unless extremely necessary. So the other option you are mentioning is to add the reserved characters as an entry in the documentation, am I correct?

**Comment by omarsourour** [comment]
@pawett Kind reminder :)

**Comment by pawett** [comment]
Sorry to not answer earlier, I was on vacation.. You are right, I am aware that a syntax change would be a major change, so a mention of the "reserved" characters in the documentation should be good enough to avoid the problems I have experienced for future users.
