### ISSUE TITLE
Force flag does not work to force removal of LUIS application.

### ISSUE THREAD

**Issue by seank-com** [Microsoft/botbuilder-tools#951]
## Tool
Name: LUIS
Version: 2.2.0
OS: Debian stretch

## Describe the bug
Trying to delete my LUIS applications and restart the ```botbuilder-samples/samples/csharp_dotnetcore/14.nlp-with-dispatch``` sample from scratch. I delete the Dispatch application from [luis.ai/applications](https://www.luis.ai/applications) without problems. When I try to delete Weather or Home Automation application from the website I get the helpful "BadArgument: The application Weather is referenced by a Dispatch application. Please, ask the application owner to remove the referenece, your use the flag force=true to force delete the relation." of course there is no way to set the force flag from the web UI so I try using the LUIS command line.

## To Reproduce
1. run the following command to find you appId
```bash
$ luis list applications --authoringKey <luisAuthoringKey>
```
2. run the command to delete the application
```bash
$ luis delete application --appId <appId>  --authoringKey <luisAuthoringKey>
```
see error "The application Weather is referenced by a Dispatch application. Please, ask the application owner to remove the referenece, your use the flag force=true to force delete the relation."

3. add force parameter
```bash
$ luis delete application --appId <appId>  --authoringKey <luisAuthoringKey> --force
```

## Expected behavior
Success

## Actual behavior
The application Weather is referenced by a Dispatch application. Please, ask the application owner to remove the referenece, your use the flag force=true to force delete the relation.

**Comment by seank-com** [comment]
FYI, looking at the code in `/usr/local/lib/node_modules/luis-apis/bin/luis.js`

It appears that all the `--force` flag does is bypass the 

```javascript
    let answer = readlineSync.question(`Are you sure you want to delete the application...
```
    
I tried also setting `args.force=true` since the `client.apps.deleteMethod` labels this as the options parameter but that didn't work either.

**Comment by hansmbakker** [comment]
I'm experiencing this bug too. I also reported it on https://stackoverflow.com/questions/54551571/how-to-delete-luis-application-that-was-referenced-by-dispatch-application since the LUIS team seems to prefer that channel, but they didn't reply yet. Anyway it should be fixed in the web UI as well.

**Comment by hansmbakker** [comment]
Workaround is to use the [`DELETE` REST request](requesthttps://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/5890b47c39e2bb052c5b9c39) manually.

**Comment by kayousef** [comment]
Hello @seank-com 

Thank you for using Bot builder tools and LUIS. We have noticed the reported issue earlier, and already have a permanent fix in the pipeline. This fix handles the case when you can't delete a dispatch child app, when the parent app is already deleted. That should be available within the week.

Unfortunately, for the **force** flag, you will need to use the DELETE REST request manually as @hansmbakker  suggested. That flag is still not supported in the SDK and LUIS Command line yet. We are already working on that, and will try to make it available ASAP.

@hansmbakker Thank you for the suggestion. I have just seen your post on stackoverflow, and replied to that as well.

**Comment by seank-com** [comment]
Thanks it appears they have fixed the https://luis.ai web ui and I can now delete those applications.
