### ISSUE TITLE
You need to upgrade your AZ CLI version to >= 2.0.53

### ISSUE THREAD

**Issue by JasonPGiordano** [Microsoft/botbuilder-tools#962]
## Information:
* Tools Libraries: msbot
* Libraries' Versions: 4.3.2 and daily build 4.3.2-152
* OS: Windows

## Issue Description:
Error incorrectly states AZ CLI version is the issue when a newer version is installed

## Commands Example:
msbot clone services --name "[NAME]" --luisAuthoringKey "[KEY]" --folder ".\DeploymentScripts\en" --location "westus"

## Reproduction Steps:
1. Install AZ CLI 2.0.58
2. Install latest MSBot
3. Run msbot clone services

## Expected Behavior:
Actually runs

## Actual Results:
Checking az botservice version
You need to upgrade your AZ CLI version to >= 2.0.53.
        You can install the latest AZ CLI from https://aka.ms/az-cli-download

**Comment by JasonPGiordano** [comment]
As I suspected, the expected behavior occurs when 2.0.53 is installed.  The "greater than" version check is not working but the "equal to" 2.0.53 check is working.

**Comment by nurih** [comment]
Encountering same issue.

**Comment by nurih** [comment]
Looks like the extension for **AZ** listed under [current extensions](https://azurecliextensionsync.blob.core.windows.net/index1/index.json) is stated as being _exactly_ 2.0.52,  not allowing the extension for the latest revision AZ cli.
```
        "botservice": [
            {
                "downloadUrl": "https://github.com/Microsoft/botbuilder-tools/releases/download/az-cli-extension/botservice-0.4.3-py2.py3-none-any.whl",
                "filename": "botservice-0.4.3-py2.py3-none-any.whl",
                "metadata": {
                    "azext.isPreview": true,
                    "azext.maxCliCoreVersion": "2.0.52",
                    "azext.minCliCoreVersion": "2.0.52",
```
Does this extension require such strict version matching that a patch-level increment is not allowed?

**Comment by v-kydela** [comment]
I just had a look at the source code, and my guess is that MSBot isn't able to correctly parse the currently-installed version of the Azure CLI. It determines the currently-installed version by running [`az -v `](https://github.com/Microsoft/botbuilder-tools/blob/master/packages/MSBot/src/msbot-clone-services.ts#L1074) and then detecting a version number in the output with the regex [`/([0-9]+)\.([0-9]+)\.([0-9]+)\)/`](https://github.com/Microsoft/botbuilder-tools/blob/master/packages/MSBot/src/msbot-clone-services.ts#L1222). We can see that it expects the version number to end with a `)` which it does not. Perhaps `az -v` displayed the version number differently in previous versions.

**Comment by nurih** [comment]
@v-kydela see [PR](https://github.com/Microsoft/botbuilder-tools/pull/963). I think there's also a version comparison glitch.
