### ISSUE TITLE
bugbash - az bot create does not open browser window

### ISSUE THREAD

**Issue by v-kydela** [Microsoft/botbuilder-tools#979]
## Tool
Name: az bot
Version: 2.0.58
OS: Windows 10

## Describe the bug

Running this command:

`C:\Users\v-kydela>az bot create --kind webapp --name KyleEchoBotCSharp --location westus --version v4 --lang Csharp --verbose --resource-group KyleEchoBot`

I saw this in the output:

```
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code *****5MAL to authenticate.
```

## Expected behavior

I expect the tool to open a browser window automatically

[bug]

**Comment by stevengum** [comment]
Closed, this is a feature of msbot, not az bot
