### ISSUE TITLE
bugbash - Kudu resources not being deleted before zip deployment

### ISSUE THREAD

**Issue by mdrichardson** [Microsoft/botbuilder-tools#980]
## Information:
* Tools Libraries: AZ CLI
* Libraries' Versions: Latest everything. AZ CLI from bug bash
* OS: Win 10

## Issue Description:
Resources in Kudu (wwwroot) are not deleted before zip deployment. If everything else works, this isn't a big deal. But if something else breaks and the default echo bot stays in there, it will confuse users.

## Reproduction Steps:
1. From bug bash, run scenario 1 with yeoman/Typescript
2. Run the `az bot publish...` command towards the end

## Expected Behavior:
All files under wwwroot are deleted before zip deployment.

## Actual Results:
I added a DELETEME.txt and then zip deployed:

![image](https://user-images.githubusercontent.com/40401643/53131433-a8946080-3521-11e9-9adc-120a52c025a1.png)

**Comment by stevengum** [comment]
Closing this as we've added a deprecation message for `az bot publish -v v4` which tells users to use `az webapp` to publish their bot and points to our docs that illustrate how to do this.
