### ISSUE TITLE
bugbash - Post deployment script not firing

### ISSUE THREAD

**Issue by mdrichardson** [Microsoft/botbuilder-tools#982]
## Information:
* Tools Libraries: AZ CLI
* Libraries' Versions: Latest everything. AZ CLI from bug bash
* OS: Win 10

## Issue Description:
The post-install script `webConfigPrep.js` is not being fired after zip deployment. I believe `npm run build` isn't being executed, in general. You can verify this because `web.config` still points to `index.js` and not `lib/index.js`.

This may be related to: https://github.com/Microsoft/botbuilder-tools/issues/981

## Reproduction Steps:
1. From bug bash, run scenario 1 with yeoman/Typescript
2. Run the `az bot publish...` command towards the end

## Expected Behavior:
`webConfigPrep.js` to fire after deployment.

## Actual Results:
`webConfigPrep.js` does not fire and `web.config` remains unchanged, pointing to `index.js` instead of `lib/index.js`

**Comment by stevengum** [comment]
@mdrichardson do you have the publish command you were using to publish your local bot? Were you using the flag --keep-node-modules?

**Comment by mdrichardson** [comment]
@stevengum 	I used [the BugBash instructions](https://microsoft-my.sharepoint.com/:w:/p/kamrani/Eb_grxvMTdJCgp7hr5Az734BHPUFX0mZU3-XzrpKYBtRpw?rtime=o1DlLE6u1kg), which had:

```
az bot publish --name <bot-resource-name> --proj-file-path "<csproj-file>" --resource-group <resource-group-name> --code-dir <directory-path> --verbose --version v4
```

So no, no `--keep-node-modules` flag. I could try again with it (I still have the files for that bot), if you want. Let me know.

**Comment by stevengum** [comment]
I'm going to close this as we want users to use `az webapp` for their deployments. If they are using zipdeploy which is what we use in `az bot publish`, they should build their code before deploying, and therefore not use the webConfigPrep.js script. 

(My goal is to eventually remove that or document how users should configure their Web App for deployment if they for some reason want to use it.)
