### ISSUE TITLE
bugbash - az bot create says it's using the default resource group

### ISSUE THREAD

**Issue by v-kydela** [Microsoft/botbuilder-tools#983]
## Tool
Name: az bot
Version: 2.0.58
OS: Windows 10

## Describe the bug

Running this command:

`C:\Users\v-kydela>az bot create --kind webapp --name KyleEchoBotCSharp --location westus --version v4 --lang Csharp --verbose --resource-group KyleEchoBot`

I saw this in the output:

`Configured default 'v-kydela_ResourceGroup' for arg resource_group_name`

However, I also saw 

  "resourceGroup": "KyleEchoBot",

In the final JSON and confirmed in Azure that my resources were created in the group KyleEchoBot and not v-kydela_ResourceGroup.

## Expected behavior

The tool should not mislead the user by saying it's using the default resource group when it's actually using the resource group provided as an argument.

[bug]

**Comment by stevengum** [comment]
I'm pretty sure this is in the underlying azure cli or one of its dependencies; we don't explicitly log these default argument messages. I'll dig into it and see what I find.

**Comment by stevengum** [comment]
This message isn't logged by `az bot` but by a lower-level piece of code. Closing as won't fix.
