### ISSUE TITLE
bugbash - az bot publish is not overwriting the code in Azure

### ISSUE THREAD

**Issue by EricDahlvang** [Microsoft/botbuilder-tools#984]
## Tool
Name: AZ CLI
Version: 2.0
OS: windows

## Describe the bug
Deployment succeeded, but the old code is still in the App Service Editor.

## To Reproduce
az bot publish a v4 Echo bot

## Expected behavior
Successful deployment should change the executing code in the web app

## Screenshots
![image](https://user-images.githubusercontent.com/11055362/53132998-79342280-3526-11e9-9657-0c4ea96e0424.png)

az bot publish --name ericwebappbashtest --proj-file-path "echobot1.csproj" --resource-group bugbashresources --code-dir "c:\work\bash\echobot1\echobot1" --verbose --version v4
Detected SDK version v4. Running prepare publish in code directory c:\work\bash\echobot1\echobot1 and for project file echobot1.csproj
Preparing Bot Builder SDK v4 bot for publish, with code directory c:\work\bash\echobot1\echobot1 and project file echobot1.csproj.
Detected bot language C#, Bot Builder version v4.
Creating upload zip file, code directory c:\work\bash\echobot1\echobot1.
Adding node_modules to folders to exclude from zip file.
Compressing bot source into c:\work\bash\EchoBot1\upload.zip.
Zip file path created, at c:\work\bash\EchoBot1\upload.zip.
Detected SCM_DO_BUILD_DURING_DEPLOYMENT with value of "true" in App Service's Application Settings. Build will commence during deployment. For more information, see https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file
Source code read, uploading to Kudu.
Retrieving current deployment info.
Bot source published. Preparing bot application to run the new source.
Deployment successful!
{
  "active": true,
  "author": "N/A",
  "author_email": "N/A",
  "complete": true,
  "deployer": "Push-Deployer",
  "end_time": "2019-02-20T23:37:00.0089473Z",
  "id": "55a243bceff3484e81dd0963c18f18fa",
  "is_readonly": true,
  "is_temp": false,
  "last_success_end_time": "2019-02-20T23:37:00.0089473Z",
  "log_url": "https://ericwebappbashtest.scm.azurewebsites.net/api/deployments/latest/log",
  "message": "Created via a push deployment",
  "progress": "",
  "provisioningState": null,
 "received_time": "2019-02-20T23:36:26.2762935Z",
  "site_name": "ericwebappbashtest",
  "start_time": "2019-02-20T23:36:26.3700515Z",
  "status": 4,
  "status_text": "",
  "url": "https://ericwebappbashtest.scm.azurewebsites.net/api/deployments/latest"
}

## Additional context
bug bash

[bug]

**Comment by sgellock** [comment]
Since we are deprecating msbot as a provisioning and deployment option, replaced with ARM template support, I'm going to resolve this issue as "won't fix"
