### ISSUE TITLE
bugbash - az bot publish should not require --proj-file-path AND --code-dir

### ISSUE THREAD

**Issue by EricDahlvang** [Microsoft/botbuilder-tools#985]
## Tool
Name: AZ CLI
Version: 2.0
OS: windows

## Describe the bug
When publishing a .net bot, providing the .csproj should be enough.  I don't see why --code-dir is necessary

## Expected behavior
only the .csproj should be required for c# deployments

[bug]

**Comment by sgellock** [comment]
Since we are deprecating msbot as a provisioning and deployment option, replaced with ARM template support, I'm going to resolve this issue as "won't fix"

**Comment by hansmbakker** [comment]
@sgellock I believe this is related to `az bot` (AZ CLI), not to `msbot`.

> we are deprecating msbot as a provisioning and deployment option, replaced with ARM template support

Does this have impact on people who are currently deploying using `az bot publish`?

**Comment by sgellock** [comment]
@hansmbakker we're suggesting customer use Zip deploy to deploy their bots to Azure.  So for C# bots it would look like the following:
for C#

1. `az bot prepare-deploy --lang Csharp --code-dir "." --proj-file-path "MyBot.csproj"`
2. `zip your bot (next cli command assumes a zip named code.zip):  it is the folder that has the .csproj file`
3. `az webapp deployment source config-zip --resource-group "<new-group-name>" --name "<name-of-web-app>" --src "code.zip"` 


we've got updated documentation queued up which will document this much better than what we currently have.  Should land on or about May 1.

**Comment by hansmbakker** [comment]
@sgellock thank you for the clarification!

Besides whether this works, could you explain how the bot builder team see this fit into a CI/CD pipeline where one deployment package (artifact) is created that is deployed to multiple environments?

Currently that does not work because of different bot files being needed for different environments.

**Comment by hansmbakker** [comment]
@sgellock if you use `--code-dir "."` and zip the folder that has the `.csproj` file, does that still work if there is a project in `..\DependencyProject`?

E.g. if you have
- the head project in `BotSolutionFolder\WebAppBot\WebAppBot.csproj`
- business logic in `BotSolutionFolder\BusinessLogic\BusinessLogic.csproj`

And you make `BotSolutionFolder\WebAppBot` your working folder and only supply `--code-dir "."`, then you miss your `BusinessLogic` project I assume?

**Comment by sgellock** [comment]
@hansmbakker I haven't tried the dependency project scenario you've raised.  should be easy to test.  basically zip deployment is simply taking a compiled structure, packaging it up, and then unzipping it on the azure server.  if you want help here, I can ask our support team to work the issue with you.

**Comment by stevengum** [comment]
@hansmbakker, when you use the zipdeploy api via [`az webapp deployment source config-zip`][zipdeploy], the API is designed to take a ready-to-go website/app/bot. The code should already be built and working. 

This is scenario is applicable if you have not configured your App Service to build on deployment; meaning you haven't set `SCM_DO_BUILD_DURING_DEPLOYMENT` to true on your App Service's Application Settings.

Note: You don't need to manually configure this environment variable to be false for zipdeploy to do its thing.


  [zipdeploy]: https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/source?view=azure-cli-latest#az-webapp-deployment-source-config-zip

**Comment by hansmbakker** [comment]
@sgellock Thank you for thinking along! I'll try it next Tuesday as the Easter weekend already started here :)
