### ISSUE TITLE
Zip deployment failed using "az bot publish" command for MVCTestBot project

### ISSUE THREAD

**Issue by Zerryth** [Microsoft/botbuilder-tools#987]
## Tool
- az cli 2.0.58
- Windows 10

## Describe the bug
Following the steps in Scenario 2 of the az cli bug bash, results in "`Zip deployment failed`" when attempting to deploy the downloaded code of `MVCTestBot`.

## To Reproduce
Following 
1. Download MVCTestBot code
2. Added `SimpleCredentialIProvider` to bot adapter
```csharp
   public void ConfigureServices(IServiceCollection services)
        {
            
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

            var credential = new SimpleCredentialProvider(Configuration["AppId"], Configuration["AppPassword"]);

            // Add the Adapter as a singleton and our Bot as transient.
            services.AddSingleton<IBotFrameworkHttpAdapter>(sp => new BotFrameworkHttpAdapter(credential));
            services.AddTransient<IBot>(sp => new MyBot());
        }
```

and `appsettings.json`:

```js
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    }
  },
  "AllowedHosts": "*",
  "AppId": "",
  "AppPassword":  ""
}
```

Leaving setting `AppId` and `AppPassword` to just empty strings.

3. Ran `az group create` and `az bot create`
4. `az bot publish --name ashleybugbash2 --proj-file-path Microsoft.Bot.Builder.TestBot.csproj --resource-group ashleybugbash2 --code-dir "." --verbose --version v4`

## Expected behavior
for local bot to deploy to Azure

## Screenshots
![image](https://user-images.githubusercontent.com/35248895/53134841-9ae4d800-352d-11e9-9d9a-558ae04eb2f5.png)

[bug]

**Comment by stevengum** [comment]
@zerryth, can you share your source code? (zip your entire code directory if possible and send it to me)

**Comment by Zerryth** [comment]
@stevengum Done. Emailed to you

**Comment by mdrichardson** [comment]
After digging into this due to my related, closed issue above, I think it [might have something to do with this](https://docs.microsoft.com/en-us/azure/app-service/deploy-zip#what-happens-to-my-app-during-deployment). If I specify `--keep-node-modules`, the CLI reports that everything except `node_modules` was deleted, but if I check, *nothing* is deleted. Easy to verify since it creates a C# echo bot by default and I'm trying to publish a Node one.

**Comment by sgellock** [comment]
Since we are deprecating msbot as a provisioning and deployment option, replaced with ARM template support, I'm going to resolve this issue as "won't fix"
