### ISSUE TITLE
msbot clone services multi-language support

### ISSUE THREAD

**Issue by brisebois** [Microsoft/botbuilder-tools#989]
## Tool
Name: Msbot

## Describe the problem
When deploying **Enterprise Bot Template** in scenarios where we need to support multiple languages we can't use **msbot clone services** since we must provide a language specific folder.

Deploying more or more language for a single bot is not uncommon in countries that have more than one official language.

## Describe the solution you'd like
I would like to be able to specify an array of languages that would leverage the DeploymentScripts folder and handle deploying the language specific resources (Search, LUIS, QnA Maker) & use the Dispatch to identify which language specific services to use based on detected language or client culture.

## Describe alternatives you've considered
I've considered deploying one language and adding others by hand. This seems to defeat the goal of using msbot to scaffold and deploy a bot.

[enhancement]

**Comment by Zerryth** [comment]
@brisebois have you taken a look at the Virtual Assistant template that our team is working on?
* [Template Overview](https://github.com/Microsoft/AI/tree/master/solutions/Virtual-Assistant)
* [Actual Code](https://github.com/Microsoft/AI/tree/master/solutions/Virtual-Assistant/src/csharp/assistant)

Essentially the idea is that you build two different LUIS models that can expertly handle each language, and under `DeploymentScripts` there's a powershell script that essentially runs `msbot clone` twice to provision 1. the services needed by any bot and 2. the specific LUIS models that the user would like to implement.

I'd recommend taking a look at that on-going project to see a robust solution for a multi-lingual bot that you can model your own after.

**Comment by artemvalmus** [comment]
@Zerryth thanks for the links. I had the same problem and your solution is really helpful. Could you please tell me how you generated dispatch.lu file? Is there a command or PS script generating this file taking other .lu files as an argument?

**Comment by Zerryth** [comment]
@artemvalmus you can find more information regarding .lu files in the botbuilder-tools repo here:
* [ludown package](https://github.com/Microsoft/botbuilder-tools/tree/master/packages/Ludown)

**Comment by sgellock** [comment]
Since we are deprecating msbot as a provisioning and deployment option, replaced with ARM template support, I'm going to resolve this issue as "won't fix"
