### ISSUE TITLE
environment names end up in Dispatch when using dispatch refresh

### ISSUE THREAD

**Issue by hansmbakker** [Microsoft/botbuilder-tools#990]
## Tool
Name: Dispatch

## Describe the problem
I would like to create several environments of the same solution (say dev and test). LUIS does not allow having apps with the same name in different Azure resource groups as QnA Maker does. Therefore, to create separate LUIS apps per environment one would need to e.g. suffix the LUIS app names with the environment (e.g. `general_dev`, `general_test`).

In `dispatch add` you can override the generated Intent names with `--intentName`, but by default it will result in the environment name ending up in the generated intent (e.g. `l_general_dev`)

This becomes a problem when you generate a class from the Dispatch file using [`LUISGen`](https://github.com/Microsoft/botbuilder-tools/tree/master/packages/LUISGen) because then you end up with environment names in the generated `Enum`.

Furthermore, I believe `dispatch refresh` creates Dispatch Intents based on the names of the LUIS apps / QnA Maker without a way to override the generated Intent names.

## Describe the solution you'd like
- A clean way to separate LUIS apps by environment, in the way that QnA Maker does it (by using Azure resource groups)
- An easy way to generate or update Dispatch from a bot file without getting environment names in generated code.

[enhancement]

**Comment by hansmbakker** [comment]
I understand you can use a generated `.dispatch` file to keep the correct Intent names, but that is not a file that should be checked in to version control since it contains all secrets in plaintext.

**Comment by tsuwandy** [comment]
@hansmbakker, Dispatch CLI has no way of knowing if env name is in the app name.  Did you try using --intentName parameter and control the intent names that way?  ie --intentName l_general

dispatch refresh uses the configuration in .dispatch file to generated the intent names.  If --intentName command was previously set, then it should be honored.

**Comment by hansmbakker** [comment]
@tsuwandy yes I did that, so it did get stored in .dispatch, but how can I share that in a proper way with other developers?

I do not want plaintext secrets in my git repository.

This is similar to the feedback Microsoft got in https://github.com/Microsoft/BotBuilder/issues/5273#issuecomment-459134879

**Comment by tsuwandy** [comment]
Ah, I see.   We actually had similar issue for enterprise bot scenario, and since there is no property intentName in msbot schema, we came up with the workaround using the "id" property of the bot connected service.   Take the your example, name of the LUIS source could be "general_dev", but set the id property to "general".  Dispatch CLI will detect this and use the id field and create the intent "l_general" instead.  Try this out and let me know if it works out.

**Comment by hansmbakker** [comment]
Yes, setting the id manually in the bot file works.

It just does not work when creating a luis app and piping that to `msbot connect luis --stdin` I believe; by default msbot generates a number id.

**Comment by tsuwandy** [comment]
This is correct, there is no option to set the id from msbot parameter.  Regardless, you could control the intent name in Dispatch via the optional "--intentName" parameter, or if you are using msbot, you could use update the "id" field.   Closing this.  Let me know if you need anything else.  Thank you!
