### ISSUE TITLE
The generated class does not contain the detected pattern information (but only the matched entities).

### ISSUE THREAD

**Issue by hansmbakker** [Microsoft/botbuilder-tools#992]
## Tool
Name: LuisGen

## Describe the problem
The generated class does not contain the detected pattern information (but only the matched entities). 

## Describe the solution you'd like
- Have the `LuisRecognizer.RecognizeAsync` method in `Microsoft.Bot.Builder.AI.Luis` return the Pattern property
- Deserialize the detected pattern information in the generated class

## Describe alternatives you've considered
Calling the REST API directly (which defeats the purpose of the LUISgen app and the nuget package)

## Additional context
I have a LUIS app that can detect question types (e.g. that a question is a definition question). The DefinitionQuestion intent is completely modeled as pattern utterances.

The content for the definitions is in a QnA Knowledge Base, together with other questions.

The generated dispatch app does not properly recognize the correct intent (it tries to refer to the QnA KB instead of the question types LUIS app. It does, however, return the correctly detected pattern in the API response JSON along with the detected entity.

[enhancement]

**Comment by cahann** [comment]
LUISgen parses the endpoint response which doesnt include patterns only the top scoring intent and entities cause patterns are only signals to the ML model

**Comment by hansmbakker** [comment]
I see this output in the `test -> inspect` view in the Luis portal so I expect it should be in the endpoint response.

This is needed because LUIS Dispatch shows strange behavior sometimes where a certain intent (of QnA maker) is returned even when a pattern is 100% matched from another LUIS app (which has no utterances, but only patterns).
In this case I need to know the information about that matched pattern.

**Comment by cahann** [comment]
You see this output while testing the trained model as we should it for debugging reasons but at runtime this information is not surfaced. We can extend the LUIS response to include this info but it will be a feature request for LUIS :)

**Comment by hansmbakker** [comment]
Ok, where can I file such a feature request? Or can you convert this issue into a feature request?

**Comment by cahann** [comment]
I added it to the LUIS backlog and it will get priotrized with our next release cycle.

**Comment by hansmbakker** [comment]
Thank you!
