### ISSUE TITLE
Open source Dispatch

### ISSUE THREAD

**Issue by hansmbakker** [Microsoft/botbuilder-tools#994]
## Tool
Name: [Dispatch]

## Describe the problem
Currently the binaries of Dispatch CLI are checked in to this repository, but I cannot find the sources

## Describe the solution you'd like
Put the sources in the repository.

[enhancement]

**Comment by tsuwandy** [comment]
@hansmbakker, this is in the plan.

**Comment by hcyang** [comment]
Dispatch uses some LUIS internal features, so it's not proper to open source it unless LUIS becomes open source itself.
