### ISSUE TITLE
Distribute Dispatch CLI as dotnet tool instead of npm package

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/botbuilder-tools#995]
## Tool
Name: [Dispatch]

## Describe the problem
I see Dispatch CLI is a .net core application. Could you please distribute it as a `dotnet tool` just like LUISGen?

## Describe the solution you'd like
Let us download Dispatch CLI as `dotnet tool`

## Describe alternatives you've considered
Let us build something ourselves using a Nuget package (see #345) or https://github.com/Azure/azure-sdk-for-net/issues/5278

[enhancement]

**Comment by tsuwandy** [comment]
@hansmbakker , there's work going on to consolidate all the tools one or two tools so stay tuned.

**Comment by tsuwandy** [comment]
@hansmbakker, checking on this at the moment.  Will update as soon as we decide on the solution. Thanks!

**Comment by hansmbakker** [comment]
@tsuwandy thank you for checking!

If we could get a nuget package (with a .net library) then we could use this in azure functions or build our own tools - this is also requested in #345. This is a solution that would be flexible to all of us.

**Comment by tsuwandy** [comment]
@hansmbakker, we are working on this.  Will update this issue when package is ready, should be in a few days. Thanks!

**Comment by hansmbakker** [comment]
Thank you!

**Comment by tsuwandy** [comment]
Hello, private package is here:
https://botbuilder.myget.org/feed/botbuilder-tools-daily/package/nuget/Dispatch

We are working to publish it to nuget.org.  Thanks for your patience!

**Comment by tsuwandy** [comment]
@hansmbakker, thanks so much for your patience!  Unfortunately, after further discussion with the rest of the team, we have decided that we won't be releasing dispatch as a nuget package.   The rest of our tooling is NodeJS based and the next version of Dispatch (targeted for BUILD 2020) will also be in NodeJS.  The nuget package won't be maintained/supported post BUILD 2020 so it doesn't seem worthwhile to use it for a short time only.

**Comment by hansmbakker** [comment]
Ok, that's clear. Thank you for your efforts, though!
