### ISSUE TITLE
MSBot CLI documentation lacks examples for adding AppInsights and Blob storage

### ISSUE THREAD

**Issue by n01d** [Microsoft/botbuilder-tools#996]
## Tool
Name: MSBot documentation

https://github.com/Microsoft/botbuilder-tools/blob/master/packages/MSBot/docs/add-services.md

## Describe the problem
MSBot CLI documentation lacks examples for adding AppInsights and Blob storage which makes it hard to understand which options to use.

## Describe the solution you'd like
Add examples for the CLI commands similar to the example for "Connecting to Azure Bot Service"

**Comment by Kaiqb** [comment]
We are moving away from msbot cli. The approach to is to use appsettings.json or .env file for service references.
