### ISSUE TITLE
LUDown Refresh Doesn't Support Regex Entities

### ISSUE THREAD

**Issue by daden-ms** [Microsoft/botbuilder-tools#998]
## Tool
Name: Ludown
Version: 1.1.0
OS: Windows 10 Enterprise Version 1809, OS build 17763.316

## Describe the bug
When LUIS Model JSON file contains regex entity, LUDown tool gives error message as 
"Sorry, input LUIS JSON file has references to regular expression entities. Cannot convert to .lu file.
Stopping further processing."

## To Reproduce
1. add this to any valid LUIS JSON model file
"regex_entities": [
       {
      "name": "builtin.phonenumber",
      "regexPattern": "hrf-[0-9]{6}",
      "roles": []
    }
  ],
2. run LUIS refresh command like this:
ludown refresh -i  C:\source\JSON\test-prebuilt.json -o C:\source\LU --verbose

## Expected behavior
The LUDown tool should be able to process the json file and a .lu file with content $HRF-number:/hrf-[0-9]{6}/  should be generated

## Screenshots
N/A

## Additional context
N/A

[bug]

**Comment by omarsourour** [comment]
After investigations, this issue has already been resolved, and should be available with the next release.

@sgellock Do we have any patch deployments (bug fix releases) planned before 4.4?

**Comment by sgellock** [comment]
@omarsourour we can push something out whenever you're ready.

**Comment by vishwacsena** [comment]
This is fixed and available in the latest ludown CLI available on npmjs. 
Verified with Ludown tool version 1.2.0. 
You can get to the latest ludown tool via 
```bash
> npm i -g ludown
```
