### ISSUE TITLE
Support of Custom Translate and Transliteration in LUDown Translate 

### ISSUE THREAD

**Issue by daden-ms** [microsoft/botbuilder-tools#999]
## Tool
Name: Ludown
## Describe the problem
Currently, LUDown translate uses the standard Microsoft Translator API.  There are scenarios where a custom translator performs better and needed. The same applies to custom transliteration. 

## Describe the solution you'd like
Provide in the "ludown translate" an option where a custom translator and transliteration web endpoint 
can be used for translation and transliteration.

## Describe alternatives you've considered
N/A.

## Additional context
N/A.

**Comment by vishwacsena** [comment]
@daden-ms this can be very tricky in that utterances with labelled entity values need to translated and mapped back correctly. E.g. There is explicit dependency on [word alignment](https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-translate?tabs=curl#obtain-alignment-information) available as part of the translate service call that needs to be mapped back. 

Do not have any plans to add this kind of capability into the core of Ludown CLI itself. That said, Ludown is available as a [library](https://github.com/microsoft/botbuilder-tools/blob/master/packages/Ludown/docs/ludown-library.md) and so it should be possible for you to wrap the parse and refresh command groups with appropriate translate/ transliterate modules.
